import { LessonLayout } from '@/components/layout/LessonLayout';
import { Callout } from '@/components/common/Callout';
import { MathBlock, InlineMath } from '@/components/common/MathBlock';

export default function Section125() {
  return (
    <LessonLayout sectionId={125}>
      <h2>Two Theorems of Pappus</h2>

      <p>
        Pappus of Alexandria, who lived around 300 A.D., was one of the last geometers
        of the Alexandrian school of Greek mathematics. He discovered a number of
        interesting properties of centroids, two of which are described in this section.
      </p>

      <h3>First Theorem: Volume of Revolution</h3>

      <p>
        Consider a plane region <InlineMath>Q</InlineMath> lying between the graphs of
        two continuous functions <InlineMath>f</InlineMath> and <InlineMath>g</InlineMath>{' '}
        over an interval <InlineMath>[a, b]</InlineMath>, where{' '}
        <InlineMath>{'0 < g < f'}</InlineMath>. Let <InlineMath>S</InlineMath> be the
        solid of revolution generated by rotating <InlineMath>Q</InlineMath> about
        the x-axis.
      </p>

      <p>
        Let <InlineMath>{'a(Q)'}</InlineMath> denote the area of{' '}
        <InlineMath>Q</InlineMath>, <InlineMath>{'v(S)'}</InlineMath> the volume of{' '}
        <InlineMath>S</InlineMath>, and <InlineMath>{'\\bar{y}'}</InlineMath> the
        y-coordinate of the centroid of <InlineMath>Q</InlineMath>.
      </p>

      <Callout type="info">
        <strong>Pappus's First Theorem:</strong> The volume of the solid of revolution
        <InlineMath>S</InlineMath> is equal to the circumference of the circle traced
        by the centroid multiplied by the area of <InlineMath>Q</InlineMath>:
        <MathBlock>
          {`v(S) = 2\\pi \\bar{y} \\cdot a(Q)`}
        </MathBlock>
      </Callout>

      <h3>Proof</h3>

      <p>
        The volume is given by the integral:
      </p>
      <MathBlock>
        {`v(S) = \\pi \\int_a^b [f^2(x) - g^2(x)] \\, dx`}
      </MathBlock>

      <p>
        The y-coordinate of the centroid is given by:
      </p>
      <MathBlock>
        {`\\bar{y} \\cdot a(Q) = \\iint_Q y \\, dy \\, dx = \\int_a^b \\left[ \\int_{g(x)}^{f(x)} y \\, dy \\right] dx = \\int_a^b \\frac{1}{2}[f^2(x) - g^2(x)] \\, dx`}
      </MathBlock>

      <p>
        Comparing these two formulas immediately gives{' '}
        <InlineMath>{'v(S) = 2\\pi\\bar{y} \\cdot a(Q)'}</InlineMath>.
      </p>

      <h3>Example: Volume of a Torus</h3>

      <p>
        Let <InlineMath>S</InlineMath> be the torus generated by rotating a circular
        disk <InlineMath>Q</InlineMath> of radius <InlineMath>R</InlineMath> about an
        axis at a distance <InlineMath>{'b > R'}</InlineMath> from the center of{' '}
        <InlineMath>Q</InlineMath>.
      </p>

      <p>
        We have <InlineMath>{'\\bar{y} = b'}</InlineMath> and{' '}
        <InlineMath>{'a(Q) = \\pi R^2'}</InlineMath>, so by Pappus's theorem:
      </p>
      <MathBlock>
        {`v(S) = 2\\pi \\bar{y} \\cdot a(Q) = 2\\pi^2 R^2 b`}
      </MathBlock>

      <h3>Using Pappus to Find Centroids</h3>

      <p>
        Pappus's theorem can also be used to calculate centroids when the volume is
        known.
      </p>

      <p>
        <strong>Example:</strong> Find the y-coordinate of the centroid of the
        semicircular disk <InlineMath>{'Q = \\{(x, y) \\mid x^2 + y^2 \\leq R^2, y \\geq 0\\}'}</InlineMath>.
      </p>

      <p>
        The area of <InlineMath>Q</InlineMath> is{' '}
        <InlineMath>{'\\frac{1}{2}\\pi R^2'}</InlineMath>. When <InlineMath>Q</InlineMath>{' '}
        is rotated about the x-axis, it generates a solid sphere of volume{' '}
        <InlineMath>{'\\frac{4}{3}\\pi R^3'}</InlineMath>. By Pappus's formula:
      </p>
      <MathBlock>
        {`\\frac{4}{3}\\pi R^3 = 2\\pi \\bar{y} \\left( \\frac{1}{2}\\pi R^2 \\right), \\quad \\text{so} \\quad \\bar{y} = \\frac{4R}{3\\pi}`}
      </MathBlock>

      <h3>Second Theorem: Center of Mass of a Union</h3>

      <Callout type="info">
        <strong>Pappus's Second Theorem:</strong> Let <InlineMath>A</InlineMath> and{' '}
        <InlineMath>B</InlineMath> be two thin plates that are either disjoint or
        intersect in a set of content zero. Let <InlineMath>{'m(A)'}</InlineMath> and{' '}
        <InlineMath>{'m(B)'}</InlineMath> denote their masses and let{' '}
        <InlineMath>C_A</InlineMath> and <InlineMath>C_B</InlineMath> denote vectors
        from an origin to their respective centers of mass. Then the union{' '}
        <InlineMath>{'A \\cup B'}</InlineMath> has mass{' '}
        <InlineMath>{'m(A) + m(B)'}</InlineMath> and its center of mass is determined
        by:
        <MathBlock>
          {`C = \\frac{m(A)C_A + m(B)C_B}{m(A) + m(B)}`}
        </MathBlock>
      </Callout>

      <p>
        The quotient for <InlineMath>C</InlineMath> is a linear combination of the
        form <InlineMath>{'aC_A + bC_B'}</InlineMath>, where <InlineMath>a</InlineMath>{' '}
        and <InlineMath>b</InlineMath> are nonnegative scalars with sum 1. Such a
        linear combination is called a <strong>convex combination</strong>. The
        endpoint of <InlineMath>C</InlineMath> lies on the line segment joining the
        endpoints of <InlineMath>C_A</InlineMath> and <InlineMath>C_B</InlineMath>.
      </p>

      <Callout type="success">
        <strong>Key Insight:</strong> Pappus's theorems provide elegant shortcuts
        for computing volumes and centroids. The first theorem relates the volume
        of a solid of revolution to the path traced by the centroid of the generating
        region. The second theorem shows that the center of mass of a union lies on
        the line segment joining the individual centers of mass—a weighted average.
      </Callout>
    </LessonLayout>
  );
}
