import type { QuizQuestion } from './types';

/**
 * Quiz questions for Section 68: Integer Points on Conics
 */
export const section68Questions: QuizQuestion[] = [
  {
    id: 1,
    type: 'multiple-choice',
    question: 'What is the norm of x + y√d?',
    options: ['x + y', 'x² + dy²', 'x² - dy²', 'xy'],
    correctIndex: 2,
    difficulty: 'easy',
    explanation:
      'The norm is defined as N(x + y√d) = x² - dy², which measures distance from the hyperbola.',
  },
  {
    id: 2,
    type: 'multiple-choice',
    question: 'Why is the norm multiplicative useful?',
    options: [
      'It makes calculations easier',
      'It means products of norm-1 elements have norm 1',
      'It proves the equation has no solutions',
      'It relates to areas',
    ],
    correctIndex: 1,
    difficulty: 'medium',
    explanation:
      'If N(α) = 1 and N(β) = 1, then N(αβ) = N(α)N(β) = 1, so products of solutions give solutions.',
  },
  {
    id: 3,
    type: 'multiple-choice',
    question: 'What is the fundamental solution to x² - 2y² = 1?',
    options: ['(1, 0)', '(3, 2)', '(17, 12)', '(2, 1)'],
    correctIndex: 1,
    difficulty: 'medium',
    explanation:
      '(3, 2) is the smallest positive solution since 9 - 8 = 1, and (1,0) is trivial.',
  },
  {
    id: 4,
    type: 'multiple-choice',
    question: 'How do you generate (17, 12) from (3, 2)?',
    options: [
      'Add 14 and 10',
      'Square (3 + 2√2)',
      'Multiply by 5',
      'Use the discriminant',
    ],
    correctIndex: 1,
    difficulty: 'medium',
    explanation:
      '(3 + 2√2)² = 17 + 12√2, so squaring the fundamental solution gives the next solution.',
  },
  {
    id: 5,
    type: 'multiple-choice',
    question: 'What structure do the solutions to x² - dy² = 1 form?',
    options: [
      'A finite group',
      'An infinite cyclic group',
      'A vector space',
      'A ring',
    ],
    correctIndex: 1,
    difficulty: 'hard',
    explanation:
      'The positive solutions form an infinite cyclic group generated by the fundamental solution.',
  },
  {
    id: 6,
    type: 'multiple-choice',
    question: 'Check: Does (99, 70) satisfy x² - 2y² = 1?',
    options: [
      'No, 99² - 2(70)² = 0',
      'No, 99² - 2(70)² = 2',
      'Yes, 9801 - 9800 = 1',
      'Yes, 9801 - 4900 = 4901',
    ],
    correctIndex: 2,
    difficulty: 'easy',
    explanation:
      '99² = 9801 and 2×70² = 2×4900 = 9800, so 9801 - 9800 = 1. ✓',
  },
  {
    id: 7,
    type: 'multiple-choice',
    question: 'What is the connection to Pythagorean triples?',
    options: [
      'Both involve circles',
      'Both use multiplicative norms for generation',
      'Both have exactly 4 solutions',
      'There is no connection',
    ],
    correctIndex: 1,
    difficulty: 'medium',
    explanation:
      'Pythagorean triples use i = √(-1) for generation; hyperbola solutions use √d similarly.',
  },
  {
    id: 8,
    type: 'multiple-choice',
    question: 'If (a, b) solves x² - dy² = -1, what does (a + b√d)² solve?',
    options: [
      'x² - dy² = -1',
      'x² - dy² = 1',
      'x² - dy² = -2',
      'x² + dy² = 1',
    ],
    correctIndex: 1,
    difficulty: 'hard',
    explanation:
      'N((a + b√d)²) = N(a + b√d)² = (-1)² = 1, so the square gives a solution to x² - dy² = 1.',
  },
];
