import type { QuizQuestion } from './types';

/**
 * Quiz questions for Section 77: The Pell Equation Revisited
 */
export const section77Questions: QuizQuestion[] = [
  {
    id: 1,
    type: 'multiple-choice',
    question: 'How is x² - dy² = 1 parametrized?',
    options: [
      'x = cos θ, y = sin θ',
      'x = eᶿ, y = e⁻ᶿ',
      'x = θ, y = √(θ² - 1)',
      'x = cosh θ, y = (1/√d) sinh θ',
    ],
    correctIndex: 3,
    difficulty: 'medium',
    explanation:
      'The parametrization x = cosh θ, y = (1/√d) sinh θ satisfies x² - dy² = 1.',
  },
  {
    id: 2,
    type: 'multiple-choice',
    question: 'What is the rule for x_{θ+φ} on x² - dy² = 1?',
    options: [
      'xθ · xφ + d · yθ · yφ',
      'xθ + xφ',
      'xθ · xφ',
      'xθ · yφ + yθ · xφ',
    ],
    correctIndex: 0,
    difficulty: 'medium',
    explanation:
      'x_{θ+φ} = xθ · xφ + d · yθ · yφ, from the hyperbolic addition formulas.',
  },
  {
    id: 3,
    type: 'multiple-choice',
    question: 'What algebraic structure do the integer points on x² - dy² = 1 form?',
    options: [
      'A field',
      'A finite group',
      'An infinite cyclic group',
      'A ring',
    ],
    correctIndex: 2,
    difficulty: 'medium',
    explanation:
      'The integer points form an infinite cyclic group generated by the fundamental solution.',
  },
  {
    id: 4,
    type: 'multiple-choice',
    question: 'What is the identity element for point addition on x² - dy² = 1?',
    options: ['(0, 0)', '(1, 0)', '(1, 1)', '(0, 1)'],
    correctIndex: 1,
    difficulty: 'easy',
    explanation:
      '(1, 0) is the identity, corresponding to θ = 0 since cosh 0 = 1, sinh 0 = 0.',
  },
  {
    id: 5,
    type: 'multiple-choice',
    question: 'The point addition formula is equivalent to multiplying:',
    options: [
      'xθ + yθ by xφ + yφ',
      'cosh θ by cosh φ',
      '(xθ + yθ√d)(xφ + yφ√d)',
      'xθ · yθ by xφ · yφ',
    ],
    correctIndex: 2,
    difficulty: 'medium',
    explanation:
      'x_{θ+φ} + y_{θ+φ}√d = (xθ + yθ√d)(xφ + yφ√d), the same multiplication from Chapter 8.',
  },
  {
    id: 6,
    type: 'multiple-choice',
    question: 'For x² - 2y² = 1, adding (3, 2) to itself gives:',
    options: [
      '(17, 12)',
      '(6, 4)',
      '(9, 4)',
      '(11, 8)',
    ],
    correctIndex: 0,
    difficulty: 'medium',
    explanation:
      'x = 3·3 + 2·2·2 = 17, y = 3·2 + 2·3 = 12, giving (17, 12).',
  },
  {
    id: 7,
    type: 'multiple-choice',
    question: 'What generates all integer solutions to x² - dy² = 1?',
    options: [
      'The point (d, 1)',
      'Any integer point',
      'The point (√d, 1)',
      'The fundamental solution nearest to (1, 0)',
    ],
    correctIndex: 3,
    difficulty: 'easy',
    explanation:
      'All integer solutions come from repeatedly adding the fundamental solution (nearest to (1, 0)).',
  },
  {
    id: 8,
    type: 'multiple-choice',
    question: 'What is the inverse of an integer point (x, y) on x² - dy² = 1?',
    options: [
      '(x, y)',
      '(x, -y)',
      '(-x, -y)',
      '(y, x)',
    ],
    correctIndex: 1,
    difficulty: 'easy',
    explanation:
      'The inverse is (x, -y), corresponding to parameter -θ since sinh(-θ) = -sinh θ.',
  },
];
