import type { QuizQuestion } from './types';

export const section79Questions: QuizQuestion[] = [
  {
    id: 1,
    type: 'multiple-choice',
    question: 'A measure space is a triple $(X, \\mathcal{M}, \\mu)$ where:',
    options: [
      '$X = \\mathbb{R}$, $\\mathcal{M}$ is the Borel sets, $\\mu$ is Lebesgue measure',
      '$X$ is a set, $\\mathcal{M}$ is a $\\sigma$-algebra, and $\\mu$ is a countably additive measure on $\\mathcal{M}
    correctIndex: 1,
    difficulty: 'medium',
    explanation: 'A measure space consists of a set, a $\\sigma$-algebra of measurable sets, and a countably additive non-negative measure. This is the abstract framework for integration.',
  },
      '$X$ is a metric space, $\\mathcal{M}$ is the open sets, $\\mu$ is any function',
      '$X$ is finite, $\\mathcal{M} = 2^X$, $\\mu$ is counting measure',
    ],
    correctIndex: 3,
    difficulty: 'medium',
    explanation: 'A measure space consists of a set, a $\\sigma$-algebra of measurable sets, and a countably additive non-negative measure. This is the abstract framework for integration.',
  },
  {
    id: 2,
    type: 'multiple-choice',
    question: 'A $\\sigma$-algebra $\\mathcal{M}$ on $X$ must satisfy:',
    options: [
      'Closed under finite unions only',
      'Contains only open sets',
      '$X \\in \\mathcal{M}$, closed under complements, and closed under countable unions',
      'Is a finite collection',
    ],
    correctIndex: 2,
    difficulty: 'medium',
    explanation: 'A $\\sigma$-algebra contains the whole space, is closed under complementation, and is closed under countable unions (hence also countable intersections).',
  },
  {
    id: 3,
    type: 'multiple-choice',
    question: 'A measure $\\mu$ is called $\\sigma$-finite if:',
    options: [
      '$\\mu(X) < \\infty
    correctIndex: 2,
    difficulty: 'medium',
    explanation: '$\\sigma$-finiteness means $X$ is a countable union of sets with finite measure. Lebesgue measure on $\\mathbb{R}^n$ is $\\sigma$-finite but not finite.',
  },
      '$\\mu(E) < \\infty$ for all $E \\in \\mathcal{M}
    correctIndex: 1,
    difficulty: 'medium',
    explanation: '$\\sigma$-finiteness means $X$ is a countable union of sets with finite measure. Lebesgue measure on $\\mathbb{R}^n$ is $\\sigma$-finite but not finite.',
  },
      '$X = \\bigcup_{n=1}^\\infty E_n$ with $\\mu(E_n) < \\infty$ for all $n
    correctIndex: 1,
    difficulty: 'medium',
    explanation: '$\\sigma$-finiteness means $X$ is a countable union of sets with finite measure. Lebesgue measure on $\\mathbb{R}^n$ is $\\sigma$-finite but not finite.',
  },
      '$\\mathcal{M}$ is countable',
    ],
    correctIndex: 1,
    difficulty: 'medium',
    explanation: '$\\sigma$-finiteness means $X$ is a countable union of sets with finite measure. Lebesgue measure on $\\mathbb{R}^n$ is $\\sigma$-finite but not finite.',
  },
  {
    id: 4,
    type: 'multiple-choice',
    question: 'A measure is complete if:',
    options: [
      'The measure takes only values 0 and 1',
      'Every subset of a null set is measurable (and has measure zero)',
      'Every set is measurable',
      '$\\mu(X) = 1
    correctIndex: 1,
    difficulty: 'hard',
    explanation: 'Completeness means null sets have all their subsets measurable. Lebesgue measure is complete, but Borel measure is not (there are non-Borel subsets of Borel null sets).',
  },
    ],
    correctIndex: 2,
    difficulty: 'hard',
    explanation: 'Completeness means null sets have all their subsets measurable. Lebesgue measure is complete, but Borel measure is not (there are non-Borel subsets of Borel null sets).',
  },
  {
    id: 5,
    type: 'multiple-choice',
    question: 'The Borel $\\sigma$-algebra on $\\mathbb{R}^n$ is:',
    options: [
      'The Lebesgue measurable sets',
      'The set of all subsets of $\\mathbb{R}^n
    correctIndex: 2,
    difficulty: 'easy',
    explanation: 'The Borel $\\sigma$-algebra is generated by the open sets. It contains all open, closed, $G_\\delta$, $F_\\sigma$ sets, etc., but is smaller than the Lebesgue $\\sigma$-algebra.',
  },
      'The smallest $\\sigma$-algebra containing all open sets',
      'Only the open and closed sets',
    ],
    correctIndex: 3,
    difficulty: 'easy',
    explanation: 'The Borel $\\sigma$-algebra is generated by the open sets. It contains all open, closed, $G_\\delta$, $F_\\sigma$ sets, etc., but is smaller than the Lebesgue $\\sigma$-algebra.',
  },
];
