packages:
  # Main shared library
  - 'shared'

  # Course packages (exclude deploy directories and PDFs)
  - 'abstract-algebra'
  - 'advanced-linalg'
  - 'atlas-shrugged'
  - 'basic-algebra'
  - 'bfi'
  - 'calc_easy'
  - 'calc_lib_art'
  - 'calc1-course'
  - 'coding-theory-course'
  - 'course-template'
  - 'crypto-react'
  - 'df-course'
  - 'euclid'
  - 'euler-intro'
  - 'four-pillars'
  - 'gauss'
  - 'human-action'
  - 'intro-discrete'
  - 'islr'
  - 'koblitz-course'
  - 'lcn'
  - 'linalg'
  - 'man-econ-state'
  - 'math_history'
  - 'men-of-math-course'
  - 'mod-race'
  - 'numbers-geometry-course'
  - 'only-the-strong-survive'
  - 'orange-is-new-green'
  - 'probability'
  - 'real-analysis'
  - 'road-to-serfdom'
  - 'rudin-course'
  - 'tao-analysis-1'
  - 'thales'
  - 'west-graphs'
  - 'why-math'

  # Infrastructure
  - 'firebase/functions'
  - 'e2e'

  # Legacy courses (may need migration)
  - 'aa'
  - 'ba'
  - 'cryptography'
