import type { QuizQuestion } from './types';

export const section13Questions: QuizQuestion[] = [
  {
    id: 1,
    type: 'multiple-choice',
    question: 'What branch of geometry did Gaspard Monge found?',
    options: [
      'Analytic geometry',
      'Differential geometry',
      'Projective geometry',
      'Descriptive geometry'
    ],
    correctIndex: 3,
    difficulty: 'easy',
    explanation: 'Monge founded descriptive geometry, the technique of representing 3D objects in 2D using projections.',
  },
  {
    id: 2,
    type: 'multiple-choice',
    question: 'Descriptive geometry was initially kept as a military secret because:',
    options: [
      'It was used for fortification design',
      'It was used for cryptography',
      'It was used for navigation',
      'It was used for artillery calculations'
    ],
    correctIndex: 0,
    difficulty: 'medium',
    explanation: 'Monge developed descriptive geometry for military fortification design, and it was classified for years.',
  },
  {
    id: 3,
    type: 'multiple-choice',
    question: 'What famous institution did Monge help establish?',
    options: [
      'The Sorbonne',
      'The École Polytechnique',
      'Cambridge University',
      'The Royal Society'
    ],
    correctIndex: 1,
    difficulty: 'easy',
    explanation: 'Monge was instrumental in founding the École Polytechnique, which trained French engineers and scientists.',
  },
  {
    id: 4,
    type: 'multiple-choice',
    question: 'Monge accompanied Napoleon on which military expedition as a scientist?',
    options: [
      'The Russian campaign',
      'The Italian campaign',
      'The Egyptian expedition',
      'The Spanish campaign'
    ],
    correctIndex: 2,
    difficulty: 'medium',
    explanation: 'Monge joined Napoleon\'s Egyptian expedition (1798-1801) as part of the scientific team.',
  },
  {
    id: 5,
    type: 'text',
    question: 'What type of surfaces did Monge study that are generated by moving lines?',
    correctAnswer: 'ruled',
    difficulty: 'hard',
    explanation: 'Monge studied ruled surfaces, which can be generated by a moving straight line.',
  },
];
