import { LessonLayout } from '../../components/layout/LessonLayout';
import { Math as MathInline, MathBlock } from '../../components/common/MathBlock';
import { Callout } from '../../components/common/Callout';

export default function Section77() {
  return (
    <LessonLayout sectionId={77}>
      <h1>Linear Span</h1>

      <p>
        Given a set of vectors, we can form new vectors by taking linear combinations. The
        collection of all vectors that can be obtained this way is called the <strong>span</strong>.
        Understanding spans is fundamental to linear algebra and reveals the geometric
        structure generated by a set of vectors.
      </p>

      <h2>Definition of Span</h2>

      <Callout type="definition" title="Linear Span">
        <p>
          Let <MathInline>{`\\mathbf{v}_1, \\mathbf{v}_2, \\ldots, \\mathbf{v}_k`}</MathInline> be vectors
          in <MathInline>{`\\mathbb{R}^n`}</MathInline>. The <strong>span</strong> (or <strong>linear span</strong>)
          of these vectors is the set of all linear combinations:
        </p>
        <MathBlock>{`\\text{span}\\{\\mathbf{v}_1, \\ldots, \\mathbf{v}_k\\} = \\{c_1\\mathbf{v}_1 + c_2\\mathbf{v}_2 + \\cdots + c_k\\mathbf{v}_k : c_1, \\ldots, c_k \\in \\mathbb{R}\\}`}</MathBlock>
      </Callout>

      <p>
        A vector <MathInline>{`\\mathbf{w}`}</MathInline> is in the span if and only if there exist
        scalars <MathInline>{`c_1, \\ldots, c_k`}</MathInline> such
        that <MathInline>{`\\mathbf{w} = c_1\\mathbf{v}_1 + \\cdots + c_k\\mathbf{v}_k`}</MathInline>.
      </p>

      <h2>Examples in ℝ²</h2>

      <Callout type="example" title="Span of One Vector">
        <p>Let <MathInline>{`\\mathbf{v} = (1, 2)`}</MathInline>. Then:</p>
        <MathBlock>{`\\text{span}\\{(1, 2)\\} = \\{c(1, 2) : c \\in \\mathbb{R}\\} = \\{(c, 2c) : c \\in \\mathbb{R}\\}`}</MathBlock>
        <p>
          This is the line through the origin with slope 2. Geometrically, the span of a single
          nonzero vector is the line through the origin in the direction of that vector.
        </p>
      </Callout>

      <Callout type="example" title="Span of Two Vectors">
        <p>Let <MathInline>{`\\mathbf{v}_1 = (1, 0)`}</MathInline> and <MathInline>{`\\mathbf{v}_2 = (0, 1)`}</MathInline>.</p>
        <MathBlock>{`\\text{span}\\{(1, 0), (0, 1)\\} = \\{c_1(1, 0) + c_2(0, 1) : c_1, c_2 \\in \\mathbb{R}\\} = \\{(c_1, c_2) : c_1, c_2 \\in \\mathbb{R}\\}`}</MathBlock>
        <p>This equals all of <MathInline>{`\\mathbb{R}^2`}</MathInline>. We say these vectors <strong>span</strong> <MathInline>{`\\mathbb{R}^2`}</MathInline>.</p>
      </Callout>

      <Callout type="example" title="Two Vectors That Don't Span ℝ²">
        <p>Let <MathInline>{`\\mathbf{v}_1 = (1, 2)`}</MathInline> and <MathInline>{`\\mathbf{v}_2 = (2, 4)`}</MathInline>.</p>
        <p>
          Note that <MathInline>{`\\mathbf{v}_2 = 2\\mathbf{v}_1`}</MathInline>. Any linear combination is:
        </p>
        <MathBlock>{`c_1(1, 2) + c_2(2, 4) = (c_1 + 2c_2)(1, 2)`}</MathBlock>
        <p>
          This is still just a scalar multiple of <MathInline>{`(1, 2)`}</MathInline>, so the span is
          the same line as before—not all of <MathInline>{`\\mathbb{R}^2`}</MathInline>.
        </p>
      </Callout>

      <h2>Geometric Interpretation</h2>

      <Callout type="info" title="Spans in ℝ³">
        <p>In <MathInline>{`\\mathbb{R}^3`}</MathInline>, the span of vectors can be:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li><strong>One nonzero vector:</strong> A line through the origin</li>
          <li><strong>Two non-parallel vectors:</strong> A plane through the origin</li>
          <li><strong>Three vectors (not all in one plane):</strong> All of <MathInline>{`\\mathbb{R}^3`}</MathInline></li>
        </ul>
        <p>
          Adding more vectors beyond what's needed to span the space doesn't increase the span.
        </p>
      </Callout>

      <Callout type="example" title="A Plane in ℝ³">
        <p>Let <MathInline>{`\\mathbf{v}_1 = (1, 0, 1)`}</MathInline> and <MathInline>{`\\mathbf{v}_2 = (0, 1, 1)`}</MathInline>.</p>
        <MathBlock>{`\\text{span}\\{\\mathbf{v}_1, \\mathbf{v}_2\\} = \\{(c_1, c_2, c_1 + c_2) : c_1, c_2 \\in \\mathbb{R}\\}`}</MathBlock>
        <p>
          This is the plane <MathInline>{`z = x + y`}</MathInline> (passing through the origin).
          Any point <MathInline>{`(a, b, c)`}</MathInline> is in this span iff <MathInline>{`c = a + b`}</MathInline>.
        </p>
      </Callout>

      <h2>Testing if a Vector is in a Span</h2>

      <p>
        To determine if <MathInline>{`\\mathbf{w}`}</MathInline> is in <MathInline>{`\\text{span}\\{\\mathbf{v}_1, \\ldots, \\mathbf{v}_k\\}`}</MathInline>,
        we solve the equation <MathInline>{`c_1\\mathbf{v}_1 + \\cdots + c_k\\mathbf{v}_k = \\mathbf{w}`}</MathInline> for
        the scalars <MathInline>{`c_i`}</MathInline>.
      </p>

      <Callout type="example" title="Is (5, 7) in the Span?">
        <p>
          Is <MathInline>{`(5, 7)`}</MathInline> in <MathInline>{`\\text{span}\\{(1, 2), (3, 1)\\}`}</MathInline>?
        </p>
        <p><strong>Solution:</strong> We need <MathInline>{`c_1`}</MathInline> and <MathInline>{`c_2`}</MathInline> such that:</p>
        <MathBlock>{`c_1(1, 2) + c_2(3, 1) = (5, 7)`}</MathBlock>
        <p>This gives the system:</p>
        <MathBlock>{`c_1 + 3c_2 = 5`}</MathBlock>
        <MathBlock>{`2c_1 + c_2 = 7`}</MathBlock>
        <p>From the first equation: <MathInline>{`c_1 = 5 - 3c_2`}</MathInline>. Substituting:</p>
        <MathBlock>{`2(5 - 3c_2) + c_2 = 7 \\implies 10 - 5c_2 = 7 \\implies c_2 = \\frac{3}{5}`}</MathBlock>
        <MathBlock>{`c_1 = 5 - 3 \\cdot \\frac{3}{5} = 5 - \\frac{9}{5} = \\frac{16}{5}`}</MathBlock>
        <p>
          Yes, <MathInline>{`(5, 7) = \\frac{16}{5}(1, 2) + \\frac{3}{5}(3, 1)`}</MathInline> is in the span.
        </p>
      </Callout>

      <Callout type="example" title="A Vector Not in the Span">
        <p>
          Is <MathInline>{`(1, 2, 3)`}</MathInline> in <MathInline>{`\\text{span}\\{(1, 0, 1), (0, 1, 1)\\}`}</MathInline>?
        </p>
        <p><strong>Solution:</strong> We need:</p>
        <MathBlock>{`c_1(1, 0, 1) + c_2(0, 1, 1) = (1, 2, 3)`}</MathBlock>
        <p>This gives:</p>
        <MathBlock>{`c_1 = 1, \\quad c_2 = 2, \\quad c_1 + c_2 = 3`}</MathBlock>
        <p>Check: <MathInline>{`c_1 + c_2 = 1 + 2 = 3`}</MathInline> ✓</p>
        <p>
          Yes! <MathInline>{`(1, 2, 3) = 1 \\cdot (1, 0, 1) + 2 \\cdot (0, 1, 1)`}</MathInline>.
        </p>
      </Callout>

      <h2>Properties of Span</h2>

      <Callout type="theorem" title="Properties of the Span">
        <p>For vectors in <MathInline>{`\\mathbb{R}^n`}</MathInline>:</p>
        <ol className="list-decimal pl-6 space-y-2">
          <li>The span always contains the zero vector (take all <MathInline>{`c_i = 0`}</MathInline>)</li>
          <li>Each <MathInline>{`\\mathbf{v}_i`}</MathInline> is in its own span (take <MathInline>{`c_i = 1`}</MathInline>, others 0)</li>
          <li>The span is <strong>closed under addition</strong>: if <MathInline>{`\\mathbf{u}, \\mathbf{w} \\in \\text{span}`}</MathInline>, then <MathInline>{`\\mathbf{u} + \\mathbf{w} \\in \\text{span}`}</MathInline></li>
          <li>The span is <strong>closed under scalar multiplication</strong>: if <MathInline>{`\\mathbf{u} \\in \\text{span}`}</MathInline>, then <MathInline>{`c\\mathbf{u} \\in \\text{span}`}</MathInline></li>
          <li><MathInline>{`\\text{span}\\{\\mathbf{0}\\} = \\{\\mathbf{0}\\}`}</MathInline></li>
        </ol>
      </Callout>

      <p>
        Properties 3 and 4 say that the span is a <strong>subspace</strong> of <MathInline>{`\\mathbb{R}^n`}</MathInline>—a
        subset that is itself a vector space under the same operations.
      </p>

      <h2>Spanning Sets</h2>

      <Callout type="definition" title="Spanning Set">
        <p>
          A set of vectors <MathInline>{`\\{\\mathbf{v}_1, \\ldots, \\mathbf{v}_k\\}`}</MathInline> is a <strong>spanning
          set</strong> for <MathInline>{`\\mathbb{R}^n`}</MathInline> if <MathInline>{`\\text{span}\\{\\mathbf{v}_1, \\ldots, \\mathbf{v}_k\\} = \\mathbb{R}^n`}</MathInline>.
        </p>
        <p>
          Equivalently, every vector in <MathInline>{`\\mathbb{R}^n`}</MathInline> can be written as a linear
          combination of <MathInline>{`\\mathbf{v}_1, \\ldots, \\mathbf{v}_k`}</MathInline>.
        </p>
      </Callout>

      <Callout type="example" title="Standard Basis Spans ℝⁿ">
        <p>
          The standard basis vectors <MathInline>{`\\{\\mathbf{e}_1, \\ldots, \\mathbf{e}_n\\}`}</MathInline> span <MathInline>{`\\mathbb{R}^n`}</MathInline>:
        </p>
        <MathBlock>{`(x_1, \\ldots, x_n) = x_1\\mathbf{e}_1 + \\cdots + x_n\\mathbf{e}_n`}</MathBlock>
        <p>Every vector is uniquely expressible as a linear combination of standard basis vectors.</p>
      </Callout>

      <Callout type="example" title="Another Spanning Set for ℝ²">
        <p>
          The vectors <MathInline>{`(1, 1)`}</MathInline> and <MathInline>{`(1, -1)`}</MathInline> also span <MathInline>{`\\mathbb{R}^2`}</MathInline>.
        </p>
        <p>To express <MathInline>{`(a, b)`}</MathInline>:</p>
        <MathBlock>{`c_1(1, 1) + c_2(1, -1) = (a, b)`}</MathBlock>
        <MathBlock>{`c_1 + c_2 = a, \\quad c_1 - c_2 = b`}</MathBlock>
        <p>Solving: <MathInline>{`c_1 = (a+b)/2`}</MathInline>, <MathInline>{`c_2 = (a-b)/2`}</MathInline>.</p>
        <p>
          For any <MathInline>{`(a, b)`}</MathInline>, we can find such <MathInline>{`c_1, c_2`}</MathInline>,
          so the span is all of <MathInline>{`\\mathbb{R}^2`}</MathInline>.
        </p>
      </Callout>

      <h2>When Do Vectors Span ℝⁿ?</h2>

      <Callout type="theorem" title="Spanning ℝⁿ">
        <p>To span <MathInline>{`\\mathbb{R}^n`}</MathInline>, you need:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li>At least <MathInline>{`n`}</MathInline> vectors</li>
          <li>The vectors must be "independent enough" (no redundancy)</li>
        </ul>
        <p>
          Specifically, <MathInline>{`k`}</MathInline> vectors span <MathInline>{`\\mathbb{R}^n`}</MathInline> iff <MathInline>{`k \\geq n`}</MathInline> and
          the vectors are not all contained in a proper subspace.
        </p>
      </Callout>

      <Callout type="example" title="Minimum Spanning Sets">
        <ul className="list-disc pl-6 space-y-2">
          <li><MathInline>{`\\mathbb{R}^2`}</MathInline> requires at least 2 non-parallel vectors</li>
          <li><MathInline>{`\\mathbb{R}^3`}</MathInline> requires at least 3 vectors not all in a plane</li>
          <li><MathInline>{`\\mathbb{R}^n`}</MathInline> requires at least <MathInline>{`n`}</MathInline> vectors in "general position"</li>
        </ul>
      </Callout>

      <h2>Redundant Vectors</h2>

      <p>
        If a vector is already in the span of others, adding it doesn't enlarge the span.
      </p>

      <Callout type="theorem" title="Removing Redundant Vectors">
        <p>
          If <MathInline>{`\\mathbf{v}_k \\in \\text{span}\\{\\mathbf{v}_1, \\ldots, \\mathbf{v}_{k-1}\\}`}</MathInline>, then:
        </p>
        <MathBlock>{`\\text{span}\\{\\mathbf{v}_1, \\ldots, \\mathbf{v}_k\\} = \\text{span}\\{\\mathbf{v}_1, \\ldots, \\mathbf{v}_{k-1}\\}`}</MathBlock>
      </Callout>

      <Callout type="example" title="A Redundant Vector">
        <p>Consider <MathInline>{`\\{(1, 0), (0, 1), (1, 1)\\}`}</MathInline> in <MathInline>{`\\mathbb{R}^2`}</MathInline>.</p>
        <p>
          Since <MathInline>{`(1, 1) = (1, 0) + (0, 1)`}</MathInline>, the third vector is redundant:
        </p>
        <MathBlock>{`\\text{span}\\{(1, 0), (0, 1), (1, 1)\\} = \\text{span}\\{(1, 0), (0, 1)\\} = \\mathbb{R}^2`}</MathBlock>
      </Callout>

      <h2>Summary</h2>

      <Callout type="info" title="Key Concepts">
        <p><strong>Span:</strong> <MathInline>{`\\text{span}\\{\\mathbf{v}_1, \\ldots, \\mathbf{v}_k\\} = \\{c_1\\mathbf{v}_1 + \\cdots + c_k\\mathbf{v}_k\\}`}</MathInline></p>
        <p><strong>Geometric meaning:</strong></p>
        <ul className="list-disc pl-6 space-y-1">
          <li>One nonzero vector spans a line</li>
          <li>Two non-parallel vectors span a plane</li>
          <li><MathInline>{`n`}</MathInline> "independent" vectors span <MathInline>{`\\mathbb{R}^n`}</MathInline></li>
        </ul>
        <p><strong>Testing membership:</strong> Solve <MathInline>{`c_1\\mathbf{v}_1 + \\cdots + c_k\\mathbf{v}_k = \\mathbf{w}`}</MathInline> for scalars</p>
        <p><strong>Properties:</strong> Span contains <MathInline>{`\\mathbf{0}`}</MathInline>, closed under + and scalar ×</p>
        <p><strong>Spanning set:</strong> Vectors whose span equals the entire space</p>
      </Callout>
    </LessonLayout>
  );
}
