import type { QuizQuestion } from './types';

export const section15Questions: QuizQuestion[] = [
  {
    id: 1,
    type: 'multiple-choice',
    question: 'Which of the following is NOT a group axiom?',
    options: [
      'Commutativity',
      'Closure',
      'Associativity',
      'Existence of inverses',
    ],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: 'Commutativity is not required for a group. Groups with commutativity are called abelian groups.',
  },
  {
    id: 2,
    type: 'multiple-choice',
    question: 'The identity element in $(\\mathbb{Z}, +)$ is:',
    options: [
      '1',
      '0',
      '-1',
      'There is none',
    ],
    correctIndex: 1,
    difficulty: 'easy',
    explanation: 'Under addition, $0 + a = a + 0 = a$ for all $a$, so $0$ is the identity.',
  },
  {
    id: 3,
    type: 'multiple-choice',
    question: 'In a group, $(ab)^{-1}$ equals:',
    options: [
      '$a^{-1}b^{-1}
    correctIndex: 3,
    difficulty: 'medium',
    explanation: 'The inverse of a product reverses order: $(ab)^{-1} = b^{-1}a^{-1}$.',
  },
      '$ab
    correctIndex: 1,
    difficulty: 'medium',
    explanation: 'The inverse of a product reverses order: $(ab)^{-1} = b^{-1}a^{-1}$.',
  },
      '$(ba)^{-1}
    correctIndex: 1,
    difficulty: 'medium',
    explanation: 'The inverse of a product reverses order: $(ab)^{-1} = b^{-1}a^{-1}$.',
  },
      '$b^{-1}a^{-1}
    correctIndex: 1,
    difficulty: 'medium',
    explanation: 'The inverse of a product reverses order: $(ab)^{-1} = b^{-1}a^{-1}$.',
  },
    ],
    correctIndex: 1,
    difficulty: 'medium',
    explanation: 'The inverse of a product reverses order: $(ab)^{-1} = b^{-1}a^{-1}$.',
  },
  {
    id: 4,
    type: 'multiple-choice',
    question: 'The order of $[2]$ in $(\\mathbb{Z}_6, +)$ is:',
    options: [
      '2',
      '6',
      '3',
      '1',
    ],
    correctIndex: 2,
    difficulty: 'medium',
    explanation: '$[2] + [2] + [2] = [6] = [0]$, so the smallest $n$ with $n \\cdot [2] = [0]$ is $n = 3$.',
  },
  {
    id: 5,
    type: 'multiple-choice',
    question: 'A group is cyclic if:',
    options: [
      'It has no identity',
      'Every element has finite order',
      'It is abelian',
      'It is generated by a single element',
    ],
    correctIndex: 3,
    difficulty: 'easy',
    explanation: 'A cyclic group has the form $G = \\langle g \\rangle = \\{g^n : n \\in \\mathbb{Z}\\}$ for some generator $g$.',
  },
  {
    id: 6,
    type: 'multiple-choice',
    question: 'Which group is NOT abelian?',
    options: [
      '$(\\mathbb{Z}, +)
    correctIndex: 2,
    difficulty: 'medium',
    explanation: '$S_3$ is not abelian: $(1 \\, 2)(1 \\, 3) \\neq (1 \\, 3)(1 \\, 2)$.',
  },
      '$(\\mathbb{Z}_n, +)
    correctIndex: 0,
    difficulty: 'medium',
    explanation: '$S_3$ is not abelian: $(1 \\, 2)(1 \\, 3) \\neq (1 \\, 3)(1 \\, 2)$.',
  },
      '$(S_3, \\circ)
    correctIndex: 0,
    difficulty: 'medium',
    explanation: '$S_3$ is not abelian: $(1 \\, 2)(1 \\, 3) \\neq (1 \\, 3)(1 \\, 2)$.',
  },
      '$(\\mathbb{R}^*, \\cdot)
    correctIndex: 0,
    difficulty: 'medium',
    explanation: '$S_3$ is not abelian: $(1 \\, 2)(1 \\, 3) \\neq (1 \\, 3)(1 \\, 2)$.',
  },
    ],
    correctIndex: 0,
    difficulty: 'medium',
    explanation: '$S_3$ is not abelian: $(1 \\, 2)(1 \\, 3) \\neq (1 \\, 3)(1 \\, 2)$.',
  },
];
