import type { QuizQuestion } from './types';

export const section25Questions: QuizQuestion[] = [
  {
    id: 1,
    type: 'multiple-choice',
    question: 'A cyclic code is a linear code where:',
    options: [
      'All codewords are zero',
      'The code has exactly one codeword',
      'Every cyclic shift of a codeword is also a codeword',
      'The generator polynomial has degree 0',
    ],
    correctIndex: 2,
    difficulty: 'easy',
    explanation: 'Cyclic codes are closed under cyclic shifts (rotating the bits).',
  },
  {
    id: 2,
    type: 'multiple-choice',
    question: 'Every cyclic code of length $n$ is generated by a polynomial $g(x)$ that:',
    options: [
      'Has degree $n
    correctIndex: 3,
    difficulty: 'medium',
    explanation: 'The generator polynomial $g(x)$ must divide $x^n - 1$.',
  },
      'Is irreducible',
      'Equals $x^n - 1
    correctIndex: 0,
    difficulty: 'medium',
    explanation: 'The generator polynomial $g(x)$ must divide $x^n - 1$.',
  },
      'Divides $x^n - 1
    correctIndex: 0,
    difficulty: 'medium',
    explanation: 'The generator polynomial $g(x)$ must divide $x^n - 1$.',
  },
    ],
    correctIndex: 0,
    difficulty: 'medium',
    explanation: 'The generator polynomial $g(x)$ must divide $x^n - 1$.',
  },
  {
    id: 3,
    type: 'multiple-choice',
    question: 'If $g(x)$ has degree $r$ and the code has length $n$, the dimension is:',
    options: [
      '$r
    correctIndex: 3,
    difficulty: 'medium',
    explanation: 'Dimension $k = n - \\deg(g) = n - r$.',
  },
      '$n
    correctIndex: 1,
    difficulty: 'medium',
    explanation: 'Dimension $k = n - \\deg(g) = n - r$.',
  },
      '$n + r
    correctIndex: 1,
    difficulty: 'medium',
    explanation: 'Dimension $k = n - \\deg(g) = n - r$.',
  },
      '$n - r
    correctIndex: 1,
    difficulty: 'medium',
    explanation: 'Dimension $k = n - \\deg(g) = n - r$.',
  },
    ],
    correctIndex: 1,
    difficulty: 'medium',
    explanation: 'Dimension $k = n - \\deg(g) = n - r$.',
  },
  {
    id: 4,
    type: 'multiple-choice',
    question: 'The check polynomial $h(x)$ satisfies:',
    options: [
      '$g(x) + h(x) = x^n - 1
    correctIndex: 1,
    difficulty: 'medium',
    explanation: 'The check polynomial is $h(x) = (x^n - 1)/g(x)$, so $g(x) h(x) = x^n - 1$.',
  },
      '$g(x) \\cdot h(x) = x^n - 1
    correctIndex: 2,
    difficulty: 'medium',
    explanation: 'The check polynomial is $h(x) = (x^n - 1)/g(x)$, so $g(x) h(x) = x^n - 1$.',
  },
      '$g(x) = h(x)
    correctIndex: 2,
    difficulty: 'medium',
    explanation: 'The check polynomial is $h(x) = (x^n - 1)/g(x)$, so $g(x) h(x) = x^n - 1$.',
  },
      '$h(x) = 1
    correctIndex: 2,
    difficulty: 'medium',
    explanation: 'The check polynomial is $h(x) = (x^n - 1)/g(x)$, so $g(x) h(x) = x^n - 1$.',
  },
    ],
    correctIndex: 2,
    difficulty: 'medium',
    explanation: 'The check polynomial is $h(x) = (x^n - 1)/g(x)$, so $g(x) h(x) = x^n - 1$.',
  },
  {
    id: 5,
    type: 'multiple-choice',
    question: 'The syndrome of received word $r(x)$ is computed as:',
    options: [
      '$r(x) \\mod g(x)
    correctIndex: 0,
    difficulty: 'medium',
    explanation: 'The syndrome is $s(x) = r(x) \\mod g(x)$. If $s(x) = 0$, then $r(x)$ is a codeword.',
  },
      '$r(x) + g(x)
    correctIndex: 3,
    difficulty: 'medium',
    explanation: 'The syndrome is $s(x) = r(x) \\mod g(x)$. If $s(x) = 0$, then $r(x)$ is a codeword.',
  },
      '$r(x) \\cdot g(x)
    correctIndex: 3,
    difficulty: 'medium',
    explanation: 'The syndrome is $s(x) = r(x) \\mod g(x)$. If $s(x) = 0$, then $r(x)$ is a codeword.',
  },
      '$r(x) / g(x)
    correctIndex: 3,
    difficulty: 'medium',
    explanation: 'The syndrome is $s(x) = r(x) \\mod g(x)$. If $s(x) = 0$, then $r(x)$ is a codeword.',
  },
    ],
    correctIndex: 3,
    difficulty: 'medium',
    explanation: 'The syndrome is $s(x) = r(x) \\mod g(x)$. If $s(x) = 0$, then $r(x)$ is a codeword.',
  },
  {
    id: 6,
    type: 'multiple-choice',
    question: 'CRC (Cyclic Redundancy Check) is used primarily for:',
    options: [
      'Error detection',
      'Encryption',
      'Data compression',
      'Sorting',
    ],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: 'CRC uses cyclic codes to detect transmission errors in networking, storage, etc.',
  },
];
