import { LessonLayout } from '@/components/layout/LessonLayout';
import { Definition, Theorem, Example } from '@/components/common/ContentBlocks';
import { InlineMath, MathBlock } from '@/components/common/MathBlock';
import { MatchingExplorer } from '@/components/visualizations';

export default function Section08() {
  return (
    <LessonLayout sectionId={8}>
      <p>
        Within a set of people, some pairs are compatible as roommates; under what
        conditions can we pair them all up? Many applications of graphs involve such
        pairings. In the job assignment problem, we want to pair jobs with qualified
        applicants. Bipartite graphs have a natural vertex partition, and we want to know
        whether the two sets can be paired using edges.
      </p>

      <h2>Interactive Matching Explorer</h2>

      <p>
        Explore bipartite matchings interactively. Click edges to build a matching, find
        maximum matchings, and verify Hall's condition for perfect matchings.
      </p>

      <MatchingExplorer className="my-8" />

      <h2>Matchings</h2>

      <Definition title="Matching">
        <p>
          A <strong>matching</strong> in a graph <InlineMath math="G" /> is a set of
          non-loop edges with no shared endpoints. The vertices incident to the edges of
          a matching <InlineMath math="M" /> are <strong>saturated</strong> by{' '}
          <InlineMath math="M" />; the others are <strong>unsaturated</strong> (we say{' '}
          <InlineMath math="M" />-saturated and <InlineMath math="M" />-unsaturated).
        </p>
        <p className="mt-2">
          A <strong>perfect matching</strong> in a graph is a matching that saturates
          every vertex.
        </p>
      </Definition>

      <Example title="Perfect Matchings in Complete Bipartite Graphs">
        <p>
          Consider <InlineMath math="K_{n,n}" /> with partite sets{' '}
          <InlineMath math="X = \{x_1, \ldots, x_n\}" /> and{' '}
          <InlineMath math="Y = \{y_1, \ldots, y_n\}" />. A perfect matching defines a
          bijection from <InlineMath math="X" /> to <InlineMath math="Y" />.
          Successively finding mates for{' '}
          <InlineMath math="x_1, x_2, \ldots" /> yields <InlineMath math="n!" /> perfect
          matchings.
        </p>
        <p className="mt-2">
          Each matching is represented by a permutation of <InlineMath math="[n]" />,
          mapping <InlineMath math="i" /> to <InlineMath math="j" /> when{' '}
          <InlineMath math="x_i" /> is matched to <InlineMath math="y_j" />.
        </p>
      </Example>

      <Example title="Perfect Matchings in Complete Graphs">
        <p>
          Since it has odd order, <InlineMath math="K_{2n+1}" /> has no perfect matching.
          The number <InlineMath math="f_n" /> of perfect matchings in{' '}
          <InlineMath math="K_{2n}" /> is the number of ways to pair up{' '}
          <InlineMath math="2n" /> distinct people.
        </p>
        <p className="mt-2">
          There are <InlineMath math="2n - 1" /> choices for the partner of{' '}
          <InlineMath math="v_{2n}" />, and for each such choice there are{' '}
          <InlineMath math="f_{n-1}" /> ways to complete the matching. Hence:
        </p>
        <MathBlock math="f_n = (2n-1) \cdot f_{n-1} = (2n-1) \cdot (2n-3) \cdots (1) = (2n-1)!!" />
        <p>
          Equivalently, <InlineMath math="f_n = \frac{(2n)!}{2^n n!}" /> (each matching
          is generated by <InlineMath math="2^n n!" /> orderings).
        </p>
      </Example>

      <h2>Maximum Matchings</h2>

      <p>
        A matching is a set of edges, so its <strong>size</strong> is the number of
        edges. We can seek a large matching by iteratively selecting edges whose
        endpoints are not used by the edges already selected. This yields a{' '}
        <em>maximal</em> matching but maybe not a <em>maximum</em> matching.
      </p>

      <Definition title="Maximal vs. Maximum Matching">
        <p>
          A <strong>maximal matching</strong> in a graph is a matching that cannot be
          enlarged by adding an edge.
        </p>
        <p className="mt-2">
          A <strong>maximum matching</strong> is a matching of maximum size among all
          matchings in the graph.
        </p>
        <p className="mt-2 text-dark-300">
          Every maximum matching is maximal, but the converse need not hold.
        </p>
      </Definition>

      <Example title="Maximal ≠ Maximum">
        <p>
          The smallest graph having a maximal matching that is not a maximum matching is{' '}
          <InlineMath math="P_4" />. If we take the middle edge, we can add no other, but
          the two end edges form a larger matching.
        </p>
        <p className="mt-2">
          This illustrates that greedy selection doesn't always find the optimum.
        </p>
      </Example>

      <h3>Augmenting Paths</h3>

      <Definition title="Alternating and Augmenting Paths">
        <p>
          Given a matching <InlineMath math="M" />, an{' '}
          <strong>
            <InlineMath math="M" />-alternating path
          </strong>{' '}
          is a path that alternates between edges in <InlineMath math="M" /> and edges
          not in <InlineMath math="M" />.
        </p>
        <p className="mt-2">
          An{' '}
          <strong>
            <InlineMath math="M" />-augmenting path
          </strong>{' '}
          is an <InlineMath math="M" />-alternating path whose endpoints are both
          unsaturated by <InlineMath math="M" />.
        </p>
      </Definition>

      <p>
        Given an <InlineMath math="M" />-augmenting path <InlineMath math="P" />, we can
        replace the edges of <InlineMath math="M" /> in <InlineMath math="P" /> with the
        other edges of <InlineMath math="P" /> to obtain a new matching{' '}
        <InlineMath math="M'" /> with one more edge. This operation is called{' '}
        <strong>augmentation</strong>.
      </p>

      <Definition title="Symmetric Difference">
        <p>
          If <InlineMath math="G" /> and <InlineMath math="H" /> are graphs with vertex
          set <InlineMath math="V" />, then the <strong>symmetric difference</strong>{' '}
          <InlineMath math="G \triangle H" /> is the graph with vertex set{' '}
          <InlineMath math="V" /> whose edges are all those appearing in exactly one of{' '}
          <InlineMath math="G" /> and <InlineMath math="H" />.
        </p>
        <p className="mt-2">
          For matchings: <InlineMath math="M \triangle M' = (M - M') \cup (M' - M)" />.
        </p>
      </Definition>

      <Theorem title="Lemma 3.1.9">
        <p>
          Every component of the symmetric difference of two matchings is a path or an
          even cycle.
        </p>
        <details className="mt-3">
          <summary className="cursor-pointer text-blue-400 hover:text-blue-300">
            Proof
          </summary>
          <div className="mt-2 pl-4 border-l-2 border-dark-700">
            <p>
              Let <InlineMath math="M" /> and <InlineMath math="M'" /> be matchings, and
              let <InlineMath math="F = M \triangle M'" />. Since{' '}
              <InlineMath math="M" /> and <InlineMath math="M'" /> are matchings, every
              vertex has at most one incident edge from each. Thus{' '}
              <InlineMath math="F" /> has at most two edges at each vertex.
            </p>
            <p className="mt-2">
              Since <InlineMath math="\Delta(F) \leq 2" />, every component of{' '}
              <InlineMath math="F" /> is a path or a cycle. Furthermore, every path or
              cycle alternates between edges of <InlineMath math="M - M'" /> and edges of{' '}
              <InlineMath math="M' - M" />. Thus each cycle has even length.
            </p>
          </div>
        </details>
      </Theorem>

      <Theorem title="Berge's Theorem (Theorem 3.1.10)">
        <p>
          A matching <InlineMath math="M" /> in a graph <InlineMath math="G" /> is a
          maximum matching in <InlineMath math="G" /> if and only if{' '}
          <InlineMath math="G" /> has no <InlineMath math="M" />-augmenting path.
        </p>
        <details className="mt-3">
          <summary className="cursor-pointer text-blue-400 hover:text-blue-300">
            Proof
          </summary>
          <div className="mt-2 pl-4 border-l-2 border-dark-700">
            <p>
              We prove the contrapositive of each direction: <InlineMath math="G" /> has
              a matching larger than <InlineMath math="M" /> if and only if{' '}
              <InlineMath math="G" /> has an <InlineMath math="M" />-augmenting path.
            </p>
            <p className="mt-2">
              <strong>(⇐)</strong> An <InlineMath math="M" />-augmenting path can be used
              to produce a matching larger than <InlineMath math="M" />.
            </p>
            <p className="mt-2">
              <strong>(⇒)</strong> Let <InlineMath math="M'" /> be a matching larger than{' '}
              <InlineMath math="M" />. Let <InlineMath math="F = M \triangle M'" />. By
              Lemma 3.1.9, <InlineMath math="F" /> consists of paths and even cycles. The
              cycles have the same number of edges from <InlineMath math="M" /> and{' '}
              <InlineMath math="M'" />.
            </p>
            <p className="mt-2">
              Since <InlineMath math="|M'| > |M|" />, <InlineMath math="F" /> must have a
              component with more edges of <InlineMath math="M'" /> than of{' '}
              <InlineMath math="M" />. Such a component can only be a path that starts
              and ends with an edge of <InlineMath math="M'" />; thus it is an{' '}
              <InlineMath math="M" />-augmenting path.
            </p>
          </div>
        </details>
      </Theorem>

      <h2>Hall's Matching Condition</h2>

      <p>
        When filling jobs with applicants, there may be many more applicants than jobs.
        We model this with an <InlineMath math="X, Y" />-bigraph and seek a matching that
        saturates <InlineMath math="X" />.
      </p>

      <Definition title="Hall's Condition">
        <p>
          For a bipartite graph with bipartition <InlineMath math="X, Y" />, let{' '}
          <InlineMath math="N(S)" /> denote the set of vertices having a neighbor in{' '}
          <InlineMath math="S" />.
        </p>
        <p className="mt-2">
          <strong>Hall's Condition:</strong> For all{' '}
          <InlineMath math="S \subseteq X" />,{' '}
          <InlineMath math="|N(S)| \geq |S|" />.
        </p>
        <p className="mt-2 text-dark-300">
          This is obviously necessary: if a matching saturates <InlineMath math="X" />,
          then for every <InlineMath math="S \subseteq X" />, there must be at least{' '}
          <InlineMath math="|S|" /> vertices to match to <InlineMath math="S" />.
        </p>
      </Definition>

      <Theorem title="Hall's Theorem (Theorem 3.1.11)">
        <p>
          An <InlineMath math="X, Y" />-bigraph <InlineMath math="G" /> has a matching
          that saturates <InlineMath math="X" /> if and only if{' '}
          <InlineMath math="|N(S)| \geq |S|" /> for all{' '}
          <InlineMath math="S \subseteq X" />.
        </p>
        <details className="mt-3">
          <summary className="cursor-pointer text-blue-400 hover:text-blue-300">
            Proof
          </summary>
          <div className="mt-2 pl-4 border-l-2 border-dark-700">
            <p>
              <strong>Necessity:</strong> The <InlineMath math="|S|" /> vertices matched
              to <InlineMath math="S" /> must lie in <InlineMath math="N(S)" />.
            </p>
            <p className="mt-2">
              <strong>Sufficiency:</strong> We prove the contrapositive. If{' '}
              <InlineMath math="M" /> is a maximum matching that doesn't saturate{' '}
              <InlineMath math="X" />, we find <InlineMath math="S \subseteq X" /> with{' '}
              <InlineMath math="|N(S)| < |S|" />.
            </p>
            <p className="mt-2">
              Let <InlineMath math="u \in X" /> be unsaturated. Among vertices reachable
              from <InlineMath math="u" /> by <InlineMath math="M" />-alternating paths,
              let <InlineMath math="S" /> be those in <InlineMath math="X" /> and{' '}
              <InlineMath math="T" /> be those in <InlineMath math="Y" />.
            </p>
            <p className="mt-2">
              The <InlineMath math="M" />-alternating paths from{' '}
              <InlineMath math="u" /> reach <InlineMath math="Y" /> along edges not in{' '}
              <InlineMath math="M" /> and return to <InlineMath math="X" /> along edges
              in <InlineMath math="M" />. Hence <InlineMath math="M" /> matches{' '}
              <InlineMath math="T" /> with <InlineMath math="S - \{u\}" />. Since there's
              no augmenting path, every vertex of <InlineMath math="T" /> is saturated,
              so <InlineMath math="T = N(S)" />.
            </p>
            <p className="mt-2">
              Thus{' '}
              <InlineMath math="|N(S)| = |T| = |S - \{u\}| = |S| - 1 < |S|" />.
            </p>
          </div>
        </details>
      </Theorem>

      <h2>Vertex Covers</h2>

      <p>
        We now connect matchings to another graph parameter.
      </p>

      <Definition title="Vertex Cover">
        <p>
          A <strong>vertex cover</strong> of a graph <InlineMath math="G" /> is a set{' '}
          <InlineMath math="Q \subseteq V(G)" /> such that every edge of{' '}
          <InlineMath math="G" /> has at least one endpoint in <InlineMath math="Q" />.
        </p>
        <p className="mt-2">
          The <strong>vertex cover number</strong> <InlineMath math="\beta(G)" /> is the
          minimum size of a vertex cover.
        </p>
      </Definition>

      <p>
        Matchings and vertex covers are related: every vertex cover must contain at least
        one endpoint of each edge in a matching. Thus{' '}
        <InlineMath math="\beta(G) \geq |M|" /> for every matching{' '}
        <InlineMath math="M" />.
      </p>

      <Theorem title="König-Egerváry Theorem (Theorem 3.1.16)">
        <p>
          If <InlineMath math="G" /> is a bipartite graph, then the maximum size of a
          matching in <InlineMath math="G" /> equals the minimum size of a vertex cover.
        </p>
        <MathBlock math="\alpha'(G) = \beta(G)" />
        <p className="mt-2 text-dark-300">
          Here <InlineMath math="\alpha'(G)" /> denotes the maximum matching size (the{' '}
          <strong>matching number</strong>).
        </p>
        <details className="mt-3">
          <summary className="cursor-pointer text-blue-400 hover:text-blue-300">
            Proof Sketch
          </summary>
          <div className="mt-2 pl-4 border-l-2 border-dark-700">
            <p>
              We always have <InlineMath math="\alpha'(G) \leq \beta(G)" />. For
              bipartite graphs, equality is achieved by constructing a vertex cover from a
              maximum matching using alternating paths, similar to the proof of Hall's
              Theorem.
            </p>
          </div>
        </details>
      </Theorem>

      <Example title="König-Egerváry in Practice">
        <p>
          Consider <InlineMath math="K_{3,3}" />. A maximum matching has size 3 (a
          perfect matching exists). A minimum vertex cover also has size 3 (we can take
          all vertices from one partite set).
        </p>
        <p className="mt-2">
          For non-bipartite graphs, equality may fail. In a triangle{' '}
          <InlineMath math="K_3" />, the maximum matching has size 1, but the minimum
          vertex cover has size 2.
        </p>
      </Example>

      <h2>Independent Sets</h2>

      <Definition title="Independent Set">
        <p>
          An <strong>independent set</strong> in a graph <InlineMath math="G" /> is a set
          of pairwise non-adjacent vertices.
        </p>
        <p className="mt-2">
          The <strong>independence number</strong> <InlineMath math="\alpha(G)" /> is the
          maximum size of an independent set.
        </p>
      </Definition>

      <Theorem title="Gallai's Theorem">
        <p>
          For any graph <InlineMath math="G" /> without isolated vertices:
        </p>
        <MathBlock math="\alpha(G) + \beta(G) = n(G)" />
        <details className="mt-3">
          <summary className="cursor-pointer text-blue-400 hover:text-blue-300">
            Proof
          </summary>
          <div className="mt-2 pl-4 border-l-2 border-dark-700">
            <p>
              A set <InlineMath math="S" /> is independent if and only if its complement{' '}
              <InlineMath math="\overline{S} = V(G) - S" /> is a vertex cover. Thus{' '}
              <InlineMath math="S" /> is a maximum independent set iff{' '}
              <InlineMath math="\overline{S}" /> is a minimum vertex cover, and:
            </p>
            <MathBlock math="\alpha(G) = n(G) - \beta(G)" />
          </div>
        </details>
      </Theorem>

      <h2>Key Takeaways</h2>

      <ul className="list-disc list-inside space-y-2 mt-4">
        <li>
          <strong>Matching:</strong> A set of edges with no shared endpoints. Perfect
          matchings saturate all vertices.
        </li>
        <li>
          <strong>Maximal vs. Maximum:</strong> Maximal matchings can't be extended;
          maximum matchings have the most edges. They're not the same!
        </li>
        <li>
          <strong>Berge's Theorem:</strong> A matching is maximum iff there is no
          augmenting path.
        </li>
        <li>
          <strong>Hall's Theorem:</strong> An <InlineMath math="X, Y" />-bigraph has a
          matching saturating <InlineMath math="X" /> iff{' '}
          <InlineMath math="|N(S)| \geq |S|" /> for all{' '}
          <InlineMath math="S \subseteq X" />.
        </li>
        <li>
          <strong>König-Egerváry:</strong> In bipartite graphs, maximum matching size =
          minimum vertex cover size.
        </li>
        <li>
          <strong>Gallai's Theorem:</strong>{' '}
          <InlineMath math="\alpha(G) + \beta(G) = n(G)" /> for graphs without isolated
          vertices.
        </li>
      </ul>
    </LessonLayout>
  );
}
