import type { QuizQuestion } from './types';

export const section10Questions: QuizQuestion[] = [
  {
    id: 1,
    type: 'multiple-choice',
    question: 'The Pythagorean theorem states: in a right triangle with legs a, b and hypotenuse c:',
    options: [
      '$a + b = c$',
      '$a^2 + b^2 = c^2$',
      '$ab = c$',
      '$a^2 - b^2 = c^2$'
    ],
    correctIndex: 1,
    difficulty: 'easy',
    explanation: 'The sum of the squares on the legs equals the square on the hypotenuse.',
  },
  {
    id: 2,
    type: 'multiple-choice',
    question: 'A Pythagorean triple is a set of three positive integers (a, b, c) such that:',
    options: [
      '$a + b + c = 0$',
      '$a \\cdot b \\cdot c = 1$',
      '$a^2 + b^2 = c^2$',
      '$a/b = b/c$'
    ],
    correctIndex: 2,
    difficulty: 'easy',
    explanation: 'Pythagorean triples like (3, 4, 5) satisfy the Pythagorean equation with integers.',
  },
  {
    id: 3,
    type: 'multiple-choice',
    question: 'The triple (5, 12, 13) is Pythagorean because:',
    options: [
      '$5 + 12 = 13$',
      '$5 \\times 12 = 13$',
      '$5^{12} = 13$',
      '$25 + 144 = 169$'
    ],
    correctIndex: 3,
    difficulty: 'medium',
    explanation: '$5^2 + 12^2 = 25 + 144 = 169 = 13^2$.',
  },
  {
    id: 4,
    type: 'multiple-choice',
    question: 'Euclid\'s proof of the Pythagorean theorem (I.47) uses:',
    options: [
      'Area arguments with squares on the sides',
      'Similar triangles',
      'Trigonometry',
      'Coordinate geometry'
    ],
    correctIndex: 0,
    difficulty: 'medium',
    explanation: 'Euclid shows the square on the hypotenuse equals the sum of squares on the legs by area comparison.',
  },
  {
    id: 5,
    type: 'multiple-choice',
    question: 'There are infinitely many Pythagorean triples, generated by formulas like:',
    options: [
      '$(n, n+1, n+2)$',
      '$(m^2 - n^2, 2mn, m^2 + n^2)$ for $m > n > 0$',
      '$(2^n, 3^n, 5^n)$',
      '$(n, 2n, 3n)$'
    ],
    correctIndex: 1,
    difficulty: 'hard',
    explanation: 'This parametric formula generates all primitive Pythagorean triples when m, n are coprime and have opposite parity.',
  },
  {
    id: 6,
    type: 'multiple-choice',
    question: 'The converse of the Pythagorean theorem says: if $a^2 + b^2 = c^2$, then:',
    options: [
      'The triangle is equilateral',
      'The triangle is isosceles',
      'The triangle has a right angle between sides a and b',
      'The triangle cannot exist'
    ],
    correctIndex: 2,
    difficulty: 'hard',
    explanation: 'If the side lengths satisfy $a^2 + b^2 = c^2$, the angle opposite c must be a right angle.',
  },
];
