import { LessonLayout } from '@/components/layout';
import { Definition, Example } from '@/components/common';
import { InlineMath, MathBlock } from '@/components/common/MathBlock';
import { Callout } from '@/components/common/Callout';
import { ParameterCard } from '@/components/visualizations';

export default function Section03() {
  return (
    <LessonLayout sectionId={3}>
      <h2 className="text-2xl font-bold text-dark-100 mb-6">secp256k1 Parameters</h2>

      <p className="mb-4">
        secp256k1 is fully specified by six parameters: <InlineMath>(p, a, b, G, n, h)</InlineMath>.
        Each serves a specific purpose, and together they define the curve that secures Bitcoin.
      </p>

      <h3 className="text-xl font-semibold text-dark-100 mt-8 mb-4">The Six Parameters</h3>

      <ParameterCard className="my-8" />

      <div className="bg-dark-800 rounded-lg p-6 mb-6">
        <div className="grid grid-cols-3 md:grid-cols-6 gap-4 text-center">
          <div>
            <span className="text-2xl font-bold text-amber-400">p</span>
            <p className="text-xs text-dark-400 mt-1">Field prime</p>
          </div>
          <div>
            <span className="text-2xl font-bold text-emerald-400">a</span>
            <p className="text-xs text-dark-400 mt-1">Curve coeff.</p>
          </div>
          <div>
            <span className="text-2xl font-bold text-purple-400">b</span>
            <p className="text-xs text-dark-400 mt-1">Curve coeff.</p>
          </div>
          <div>
            <span className="text-2xl font-bold text-rose-400">G</span>
            <p className="text-xs text-dark-400 mt-1">Generator</p>
          </div>
          <div>
            <span className="text-2xl font-bold text-cyan-400">n</span>
            <p className="text-xs text-dark-400 mt-1">Order</p>
          </div>
          <div>
            <span className="text-2xl font-bold text-indigo-400">h</span>
            <p className="text-xs text-dark-400 mt-1">Cofactor</p>
          </div>
        </div>
      </div>

      <h3 className="text-xl font-semibold text-dark-100 mt-8 mb-4">
        1. The Prime <InlineMath>p</InlineMath>
      </h3>

      <Definition title="secp256k1 Prime">
        <MathBlock>
          {`p = 2^{256} - 2^{32} - 977`}
        </MathBlock>
        <p className="mt-2">
          In hexadecimal:
        </p>
        <p className="font-mono text-xs mt-2 break-all text-amber-400">
          FFFFFFFF FFFFFFFF FFFFFFFF FFFFFFFF FFFFFFFF FFFFFFFF FFFFFFFE FFFFFC2F
        </p>
      </Definition>

      <p className="mb-4">
        This is a <strong>pseudo-Mersenne prime</strong>—very close to a power of 2. This
        special form allows for fast modular reduction, making operations ~30% faster.
      </p>

      <Callout type="info" title="Why 256 Bits?">
        <p>
          A 256-bit prime provides approximately <strong>128-bit security</strong>.
          Breaking ECDLP requires roughly <InlineMath>2^{'{128}'}</InlineMath> operations—more
          than all the atoms in the observable universe.
        </p>
      </Callout>

      <h3 className="text-xl font-semibold text-dark-100 mt-8 mb-4">
        2. The Curve Coefficients <InlineMath>a</InlineMath> and <InlineMath>b</InlineMath>
      </h3>

      <Definition title="secp256k1 Equation">
        <MathBlock>
          {`y^2 = x^3 + 0 \\cdot x + 7`}
        </MathBlock>
        <p className="mt-2">
          Simplified: <InlineMath>y^2 = x^3 + 7</InlineMath>
        </p>
        <p className="mt-2">
          So <InlineMath>a = 0</InlineMath> and <InlineMath>b = 7</InlineMath>.
        </p>
      </Definition>

      <p className="mb-4">
        Why these values?
      </p>

      <ul className="list-disc list-inside space-y-2 mb-6">
        <li>
          <strong><InlineMath>a = 0</InlineMath>:</strong> Simplifies point doubling formula,
          enabling optimizations. This makes it a "Koblitz curve."
        </li>
        <li>
          <strong><InlineMath>b = 7</InlineMath>:</strong> Smallest value that produces a valid
          curve with the required properties. No room for hidden backdoors.
        </li>
      </ul>

      <Example title="Contrast with NIST P-256">
        <p>NIST P-256 uses coefficients derived from the hash of a "random" seed:</p>
        <p className="font-mono text-xs mt-2 text-rose-400">
          b = 5ac635d8 aa3a93e7 b3ebbd55 769886bc 651d06b0 cc53b0f6 3bce3c3e 27d2604b
        </p>
        <p className="mt-2 text-dark-400">
          This "nothing up my sleeve" number was generated by the NSA. Some cryptographers
          questioned whether it could hide a weakness.
        </p>
      </Example>

      <h3 className="text-xl font-semibold text-dark-100 mt-8 mb-4">
        3. The Generator Point <InlineMath>G</InlineMath>
      </h3>

      <Definition title="secp256k1 Generator">
        <p>
          <InlineMath>G</InlineMath> is a specific point on the curve that generates all other
          points through scalar multiplication:
        </p>
        <div className="mt-3 space-y-2">
          <p className="text-sm">
            <strong>x-coordinate:</strong>
          </p>
          <p className="font-mono text-xs break-all text-rose-400">
            79BE667E F9DCBBAC 55A06295 CE870B07 029BFCDB 2DCE28D9 59F2815B 16F81798
          </p>
          <p className="text-sm mt-2">
            <strong>y-coordinate:</strong>
          </p>
          <p className="font-mono text-xs break-all text-rose-400">
            483ADA77 26A3C465 5DA4FBFC 0E1108A8 FD17B448 A6855419 9C47D08F FB10D4B8
          </p>
        </div>
      </Definition>

      <p className="mb-4">
        <InlineMath>G</InlineMath> was chosen deterministically (not randomly) to be the point
        with the smallest x-coordinate that generates a group of the correct order.
      </p>

      <h3 className="text-xl font-semibold text-dark-100 mt-8 mb-4">
        4. The Order <InlineMath>n</InlineMath>
      </h3>

      <Definition title="secp256k1 Order">
        <p>
          The order <InlineMath>n</InlineMath> is the number of points on the curve (including
          the point at infinity):
        </p>
        <p className="font-mono text-xs mt-2 break-all text-cyan-400">
          n = FFFFFFFF FFFFFFFF FFFFFFFF FFFFFFFE BAAEDCE6 AF48A03B BFD25E8C D0364141
        </p>
        <p className="mt-2">
          This is a 256-bit prime slightly less than <InlineMath>p</InlineMath>.
        </p>
      </Definition>

      <p className="mb-4">
        <InlineMath>n</InlineMath> being prime is crucial—it means:
      </p>

      <ul className="list-disc list-inside space-y-2 mb-6">
        <li>Every non-identity point generates the entire group</li>
        <li>No subgroup attacks possible</li>
        <li><InlineMath>nG = \mathcal{'{O}'}</InlineMath> (the point at infinity)</li>
      </ul>

      <h3 className="text-xl font-semibold text-dark-100 mt-8 mb-4">
        5. The Cofactor <InlineMath>h</InlineMath>
      </h3>

      <Definition title="secp256k1 Cofactor">
        <MathBlock>
          {`h = 1`}
        </MathBlock>
        <p className="mt-2">
          The cofactor is <InlineMath>h = \#E(\mathbb{'{F}'}_p) / n</InlineMath>, where{' '}
          <InlineMath>\#E(\mathbb{'{F}'}_p)</InlineMath> is the total number of points.
        </p>
      </Definition>

      <p className="mb-4">
        <InlineMath>h = 1</InlineMath> is the simplest and most secure case:
      </p>

      <ul className="list-disc list-inside space-y-2 mb-6">
        <li>All points (except <InlineMath>\mathcal{'{O}'}</InlineMath>) have prime order</li>
        <li>No need for cofactor multiplication in protocols</li>
        <li>No small-subgroup attacks</li>
      </ul>

      <Callout type="warning" title="Curves with h {'>'} 1">
        <p>
          Curve25519 has <InlineMath>h = 8</InlineMath>, requiring careful protocol design
          to avoid small-subgroup attacks. secp256k1's <InlineMath>h = 1</InlineMath> avoids
          this complexity.
        </p>
      </Callout>

      <h3 className="text-xl font-semibold text-dark-100 mt-8 mb-4">Parameter Summary</h3>

      <div className="overflow-x-auto">
        <table className="w-full text-sm">
          <thead>
            <tr className="text-left">
              <th className="pb-2">Parameter</th>
              <th className="pb-2">Value</th>
              <th className="pb-2">Purpose</th>
            </tr>
          </thead>
          <tbody className="text-dark-300">
            <tr>
              <td className="py-2 text-amber-400">p</td>
              <td className="font-mono">2²⁵⁶ - 2³² - 977</td>
              <td>Defines the field</td>
            </tr>
            <tr>
              <td className="py-2 text-emerald-400">a</td>
              <td className="font-mono">0</td>
              <td>Simplifies arithmetic</td>
            </tr>
            <tr>
              <td className="py-2 text-purple-400">b</td>
              <td className="font-mono">7</td>
              <td>Defines curve shape</td>
            </tr>
            <tr>
              <td className="py-2 text-rose-400">G</td>
              <td className="font-mono">(0x79BE..., 0x483A...)</td>
              <td>Starting point</td>
            </tr>
            <tr>
              <td className="py-2 text-cyan-400">n</td>
              <td className="font-mono">~2²⁵⁶ (prime)</td>
              <td>Group order</td>
            </tr>
            <tr>
              <td className="py-2 text-indigo-400">h</td>
              <td className="font-mono">1</td>
              <td>Simplifies protocols</td>
            </tr>
          </tbody>
        </table>
      </div>
    </LessonLayout>
  );
}
