import type { QuizQuestion } from './types';

export const section125Questions: QuizQuestion[] = [
  {
    id: 1,
    type: 'multiple-choice',
    question: 'Pappus\'s first theorem states that the volume of a solid of revolution equals:',
    options: [
      '$\\pi r^2 h
    correctIndex: 2,
    difficulty: 'easy',
    explanation: 'Pappus\'s first theorem: $v(S) = 2\\pi \\bar{y} \\cdot a(Q)$, where $\\bar{y}$ is the distance from the centroid to the axis. The centroid travels a circle of circumference $2\\pi\\bar{y}$.',
  },
      'The surface area times the thickness',
      'The area of the generating region times the distance traveled by its centroid',
      'The integral of the cross-sectional area',
    ],
    correctIndex: 1,
    difficulty: 'easy',
    explanation: 'Pappus\'s first theorem: $v(S) = 2\\pi \\bar{y} \\cdot a(Q)$, where $\\bar{y}$ is the distance from the centroid to the axis. The centroid travels a circle of circumference $2\\pi\\bar{y}$.',
  },
  {
    id: 2,
    type: 'multiple-choice',
    question: 'A torus is generated by rotating a disk of radius $R$ about an axis at distance $b > R$ from its center. Its volume is:',
    options: [
      '$\\frac{4}{3}\\pi R^3
    correctIndex: 3,
    difficulty: 'medium',
    explanation: 'Using Pappus: $\\bar{y} = b$ (distance to axis) and $a(Q) = \\pi R^2$ (disk area). So $v = 2\\pi b \\cdot \\pi R^2 = 2\\pi^2 R^2 b$.',
  },
      '$\\pi R^2 b
    correctIndex: 2,
    difficulty: 'medium',
    explanation: 'Using Pappus: $\\bar{y} = b$ (distance to axis) and $a(Q) = \\pi R^2$ (disk area). So $v = 2\\pi b \\cdot \\pi R^2 = 2\\pi^2 R^2 b$.',
  },
      '$4\\pi R^2 b
    correctIndex: 2,
    difficulty: 'medium',
    explanation: 'Using Pappus: $\\bar{y} = b$ (distance to axis) and $a(Q) = \\pi R^2$ (disk area). So $v = 2\\pi b \\cdot \\pi R^2 = 2\\pi^2 R^2 b$.',
  },
      '$2\\pi^2 R^2 b
    correctIndex: 2,
    difficulty: 'medium',
    explanation: 'Using Pappus: $\\bar{y} = b$ (distance to axis) and $a(Q) = \\pi R^2$ (disk area). So $v = 2\\pi b \\cdot \\pi R^2 = 2\\pi^2 R^2 b$.',
  },
    ],
    correctIndex: 2,
    difficulty: 'medium',
    explanation: 'Using Pappus: $\\bar{y} = b$ (distance to axis) and $a(Q) = \\pi R^2$ (disk area). So $v = 2\\pi b \\cdot \\pi R^2 = 2\\pi^2 R^2 b$.',
  },
  {
    id: 3,
    type: 'multiple-choice',
    question: 'To find the centroid of a semicircular disk of radius $R$, we can use Pappus\'s theorem by noting that rotating it about the diameter generates a:',
    options: [
      'Hemisphere',
      'Sphere',
      'Cone',
      'Cylinder',
    ],
    correctIndex: 1,
    difficulty: 'medium',
    explanation: 'Rotating a semicircular disk about its diameter generates a full sphere. Using the known sphere volume $\\frac{4}{3}\\pi R^3$ and Pappus\'s theorem, we can solve for $\\bar{y} = \\frac{4R}{3\\pi}$.',
  },
  {
    id: 4,
    type: 'multiple-choice',
    question: 'Pappus\'s second theorem states that the center of mass of the union of two plates is:',
    options: [
      'A convex combination of their individual centers of mass, weighted by mass',
      'The midpoint of the line joining their centers of mass',
      'The geometric center of the combined region',
      'Always equidistant from both original centers of mass'
    ],
    correctIndex: 0,
    difficulty: 'medium',
    explanation: 'The combined center of mass is $C = \\frac{m(A)C_A + m(B)C_B}{m(A) + m(B)}$, a weighted average (convex combination) of the individual centers of mass.',
  },
  {
    id: 5,
    type: 'numeric',
    question: 'A semicircular disk of radius $R = 3$ has centroid at distance $\\bar{y} = \\frac{4R}{3\\pi}$ from its diameter. What is $\\bar{y}$ rounded to two decimal places?',
    correctAnswer: 1.27,
    numericRange: { min: 0, max: 5, precision: 2 },
    difficulty: 'medium',
    explanation: 'With $R = 3$: $\\bar{y} = \\frac{4 \\cdot 3}{3\\pi} = \\frac{4}{\\pi} \\approx 1.27$.',
  },
];
