import type { QuizQuestion } from './types';

export const section06Questions: QuizQuestion[] = [
  {
    id: 1,
    type: 'multiple-choice',
    question: 'What determines the price of a factor of production?',
    options: [
      'Its cost of production',
      'Government regulation',
      'Its discounted marginal revenue product',
      'Historical tradition',
    ],
    correctIndex: 2,
    difficulty: 'medium',
    explanation: 'Factors are paid according to their marginal contribution to revenue, discounted by the interest rate to account for time.',
  },
  {
    id: 2,
    type: 'multiple-choice',
    question: 'What is the marginal revenue product (MRP) of a factor?',
    options: [
      'The total revenue from selling all output',
      'The cost of producing one more unit',
      'The profit per unit of output',
      'The additional revenue from employing one more unit of the factor',
    ],
    correctIndex: 3,
    difficulty: 'medium',
    explanation: 'MRP is the additional revenue generated by employing one more unit of a factor, holding other inputs constant.',
  },
  {
    id: 3,
    type: 'multiple-choice',
    question: 'Why does the law of diminishing returns apply to factor employment?',
    options: [
      'Adding more of one factor while holding others fixed yields smaller increments',
      'Workers get tired over time',
      'Prices always rise',
      'Technology becomes obsolete',
    ],
    correctIndex: 0,
    difficulty: 'medium',
    explanation: 'With other factors fixed, adding more of one factor eventually yields diminishing marginal returns as the factor ratio becomes less optimal.',
  },
  {
    id: 4,
    type: 'multiple-choice',
    question: 'According to Rothbard, what happens when factor prices are set above market levels?',
    options: [
      'Unemployment or surplus of that factor results',
      'Employment increases',
      'Nothing changes',
      'Quality improves',
    ],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: 'If factor prices exceed MRP, employers will hire less of that factor, creating unemployment or surplus.',
  },
  {
    id: 5,
    type: 'multiple-choice',
    question: 'What is the imputation problem in economics?',
    options: [
      'How to accuse people of economic crimes',
      'How to calculate taxes',
      'How to measure GDP',
      'How to attribute value to individual factors when they work jointly',
    ],
    correctIndex: 3,
    difficulty: 'hard',
    explanation: 'The imputation problem asks how to determine each factor\'s individual contribution when factors produce jointly.',
  },
  {
    id: 6,
    type: 'multiple-choice',
    question: 'Why do factor prices tend toward their marginal revenue product?',
    options: [
      'Government mandates it',
      'Competition among employers bids prices up to MRP',
      'Workers demand it',
      'It is a mathematical identity'
    ],
    correctIndex: 1,
    difficulty: 'medium',
    explanation: 'Competition among employers for factors drives prices up toward MRP; if prices exceeded MRP, losses would occur.',
  },
];
