import { LessonLayout } from '@/components/layout/LessonLayout';
import { Callout } from '@/components/common/Callout';
import { MathBlock, InlineMath } from '@/components/common/MathBlock';

export default function Section19() {
  return (
    <LessonLayout sectionId={19}>
      <h2>The Alternating Group</h2>
      <p>
        The <strong>alternating group</strong> <InlineMath>A_n</InlineMath> consists of all even permutations in <InlineMath>S_n</InlineMath>.
        It is one of the most important infinite families of finite groups, being simple for <InlineMath>n \geq 5</InlineMath>.
      </p>

      <h3>Even and Odd Permutations</h3>
      <Callout type="info">
        <strong>Theorem:</strong> Every permutation can be written as a product of transpositions.
        Moreover, the <strong>parity</strong> (even or odd number of transpositions) is well-defined:
        if <InlineMath>\sigma = \tau_1 \cdots \tau_k = \rho_1 \cdots \rho_m</InlineMath> (products of transpositions),
        then <InlineMath>k \equiv m \pmod{'{'}2{'}'}</InlineMath>.
      </Callout>

      <Callout type="info">
        <strong>Definition:</strong> A permutation is <strong>even</strong> if it can be written as a product of
        an even number of transpositions, and <strong>odd</strong> otherwise.
        The <strong>sign</strong> (or <strong>signature</strong>) of <InlineMath>\sigma</InlineMath> is:
        <MathBlock>\text{'{'}sgn{'}'}(\sigma) = \begin{'{'}cases{'}'} +1 & \text{'{'}if {'}'} \sigma \text{'{'} is even{'}'} \\ -1 & \text{'{'}if {'}'} \sigma \text{'{'} is odd{'}'} \end{'{'}cases{'}'}</MathBlock>
      </Callout>

      <h3>The Alternating Group</h3>
      <Callout type="info">
        <strong>Definition:</strong> The <strong>alternating group</strong> <InlineMath>A_n</InlineMath> is:
        <MathBlock>A_n = \ker(\text{'{'}sgn{'}'}) = \{'{'}\sigma \in S_n : \text{'{'}sgn{'}'}(\sigma) = 1\{'}'}</MathBlock>
      </Callout>

      <p>Since <InlineMath>{`\\text{sgn}: S_n \\to \\{\\pm 1\\}`}</InlineMath> is a surjective homomorphism:</p>
      <ul className="list-disc list-inside text-dark-300 mb-6 space-y-2">
        <li><InlineMath>A_n \unlhd S_n</InlineMath></li>
        <li><InlineMath>[S_n : A_n] = 2</InlineMath></li>
        <li><InlineMath>|A_n| = n!/2</InlineMath></li>
      </ul>

      <h3>Cycle Structure and Parity</h3>
      <Callout type="info">
        <strong>Proposition:</strong> A <InlineMath>k</InlineMath>-cycle is even if and only if <InlineMath>k</InlineMath> is odd.
      </Callout>

      <p>
        <strong>Proof:</strong> <InlineMath>(a_1 \, a_2 \, \cdots \, a_k) = (a_1 \, a_k)(a_1 \, a_{'{'}k-1{'}'}) \cdots (a_1 \, a_2)</InlineMath>,
        which is a product of <InlineMath>k - 1</InlineMath> transpositions.
      </p>

      <p>Examples:</p>
      <ul className="list-disc list-inside text-dark-300 mb-4 space-y-1">
        <li>2-cycles (transpositions) are odd</li>
        <li>3-cycles are even: <InlineMath>(1\,2\,3) = (1\,3)(1\,2)</InlineMath></li>
        <li>4-cycles are odd: <InlineMath>(1\,2\,3\,4) = (1\,4)(1\,3)(1\,2)</InlineMath></li>
      </ul>

      <h3>Generators for A_n</h3>
      <Callout type="info">
        <strong>Theorem:</strong> <InlineMath>A_n</InlineMath> is generated by the 3-cycles.
      </Callout>

      <p>
        <strong>Proof:</strong> Any even permutation is a product of an even number of transpositions.
        We can pair them: <InlineMath>(a\,b)(c\,d)</InlineMath>. If they share an element, say <InlineMath>(a\,b)(a\,c) = (a\,c\,b)</InlineMath>.
        If disjoint: <InlineMath>(a\,b)(c\,d) = (a\,b)(a\,c)(a\,c)(c\,d) = (a\,c\,b)(a\,d\,c)</InlineMath>.
      </p>

      <h3>Conjugacy in A_n</h3>
      <p>
        In <InlineMath>S_n</InlineMath>, two permutations are conjugate iff they have the same cycle type.
        In <InlineMath>A_n</InlineMath>, a conjugacy class from <InlineMath>S_n</InlineMath> either:
      </p>
      <ul className="list-disc list-inside text-dark-300 mb-6 space-y-2">
        <li>Remains a single conjugacy class in <InlineMath>A_n</InlineMath>, or</li>
        <li>Splits into two conjugacy classes of equal size</li>
      </ul>

      <p>
        A class splits iff the cycle type consists of distinct odd integers.
        For example, in <InlineMath>A_5</InlineMath>, the 5-cycles split into two conjugacy classes.
      </p>

      <h3>Small Alternating Groups</h3>
      <ul className="list-disc list-inside text-dark-300 mb-6 space-y-2">
        <li><InlineMath>A_2 = \{'{'}e\{'}'}</InlineMath> — trivial</li>
        <li><InlineMath>A_3 = \{'{'}e, (1\,2\,3), (1\,3\,2)\{'}'} \cong \mathbb{'{'}Z{'}'}/3\mathbb{'{'}Z{'}'}</InlineMath> — cyclic</li>
        <li><InlineMath>A_4</InlineMath> — has 12 elements, contains the Klein four-group <InlineMath>V_4</InlineMath> as a normal subgroup</li>
        <li><InlineMath>A_5</InlineMath> — has 60 elements, is the smallest non-abelian simple group</li>
      </ul>

      <h3>A_4 Has No Subgroup of Order 6</h3>
      <Callout type="info">
        <strong>Proposition:</strong> <InlineMath>A_4</InlineMath> has no subgroup of order 6.
      </Callout>

      <p>
        <strong>Proof:</strong> If <InlineMath>H \le A_4</InlineMath> with <InlineMath>|H| = 6</InlineMath>, then <InlineMath>[A_4 : H] = 2</InlineMath>, so <InlineMath>H \unlhd A_4</InlineMath>.
        Since <InlineMath>H</InlineMath> would have index 2, it must contain all 3-cycles (there are 8 of them).
        But <InlineMath>|H| = 6 {'<'} 8</InlineMath>, contradiction.
      </p>

      <p>This shows the converse of Lagrange's Theorem fails.</p>

      <Callout type="success">
        <strong>Summary:</strong> The alternating group <InlineMath>A_n</InlineMath> consists of even permutations and has order <InlineMath>n!/2</InlineMath>.
        It is a normal subgroup of index 2 in <InlineMath>S_n</InlineMath>. A <InlineMath>k</InlineMath>-cycle is even iff <InlineMath>k</InlineMath> is odd.
        <InlineMath>A_n</InlineMath> is generated by 3-cycles. <InlineMath>A_5</InlineMath> is the smallest non-abelian simple group.
      </Callout>
    </LessonLayout>
  );
}
