import { LessonLayout } from '@/components/layout/LessonLayout';
import { Callout } from '@/components/common/Callout';
import { MathBlock, InlineMath } from '@/components/common/MathBlock';

export default function Section14() {
  return (
    <LessonLayout sectionId={14}>
      <h2>The Lattice of Subgroups</h2>
      <p>
        The collection of all subgroups of a group forms a mathematical structure called a <strong>lattice</strong>.
        Visualizing this lattice helps understand the group's internal structure.
      </p>

      <h3>Lattice Structure</h3>
      <Callout type="info">
        <strong>Definition:</strong> The <strong>lattice of subgroups</strong> of a group <InlineMath>G</InlineMath> is the partially ordered set
        <InlineMath>(\mathcal{'{'}L{'}'}(G), \subseteq)</InlineMath> where <InlineMath>\mathcal{'{'}L{'}'}(G)</InlineMath> is the set of all subgroups of <InlineMath>G</InlineMath>,
        ordered by inclusion.
      </Callout>

      <p>This is a lattice in the algebraic sense because:</p>
      <ul className="list-disc list-inside text-dark-300 mb-6 space-y-2">
        <li><strong>Meet:</strong> <InlineMath>H \wedge K = H \cap K</InlineMath> (intersection is a subgroup)</li>
        <li><strong>Join:</strong> <InlineMath>H \vee K = \langle H, K \rangle</InlineMath> (subgroup generated by <InlineMath>H \cup K</InlineMath>)</li>
      </ul>

      <h3>Drawing Lattice Diagrams</h3>
      <p>
        In a <strong>Hasse diagram</strong>, subgroups are represented as nodes, with an edge from <InlineMath>H</InlineMath> to <InlineMath>K</InlineMath>
        (drawn upward) if <InlineMath>H \le K</InlineMath> and there is no subgroup strictly between them.
      </p>

      <h3>Example: Lattice of Z/12Z</h3>
      <p>
        The subgroups of <InlineMath>\mathbb{'{'}Z{'}'}/12\mathbb{'{'}Z{'}'}</InlineMath> correspond to divisors of 12:
      </p>
      <MathBlock>
        {`\\begin{array}{c}
\\langle \\bar{1} \\rangle \\\\[1ex]
\\langle \\bar{2} \\rangle \\quad \\langle \\bar{3} \\rangle \\\\[1ex]
\\langle \\bar{4} \\rangle \\quad \\langle \\bar{6} \\rangle \\\\[1ex]
\\langle \\bar{0} \\rangle
\\end{array}`}
      </MathBlock>
      <p>
        With <InlineMath>H \le K</InlineMath> if and only if the generator of <InlineMath>H</InlineMath> divides the generator of <InlineMath>K</InlineMath> (as divisors of 12).
      </p>

      <h3>Example: Lattice of S_3</h3>
      <p>The subgroups of <InlineMath>S_3</InlineMath>:</p>
      <ul className="list-disc list-inside text-dark-300 mb-4 space-y-1">
        <li><InlineMath>\{'{'}e\{'}'}</InlineMath> — order 1</li>
        <li><InlineMath>\langle (1\,2) \rangle, \langle (1\,3) \rangle, \langle (2\,3) \rangle</InlineMath> — order 2</li>
        <li><InlineMath>A_3 = \langle (1\,2\,3) \rangle</InlineMath> — order 3</li>
        <li><InlineMath>S_3</InlineMath> — order 6</li>
      </ul>

      <p>
        The three subgroups of order 2 are incomparable (none contains another).
        <InlineMath>A_3</InlineMath> is comparable only with <InlineMath>\{'{'}e\{'}'}</InlineMath> and <InlineMath>S_3</InlineMath>.
      </p>

      <h3>Example: Lattice of D_8</h3>
      <p>The dihedral group <InlineMath>D_8</InlineMath> has a rich subgroup structure:</p>
      <ul className="list-disc list-inside text-dark-300 mb-4 space-y-1">
        <li>1 subgroup of order 1: <InlineMath>\{'{'}1\{'}'}</InlineMath></li>
        <li>1 subgroup of order 2 in the center: <InlineMath>\{'{'}1, r^2\{'}'}</InlineMath></li>
        <li>4 other subgroups of order 2: <InlineMath>\langle s \rangle, \langle sr \rangle, \langle sr^2 \rangle, \langle sr^3 \rangle</InlineMath></li>
        <li>1 cyclic subgroup of order 4: <InlineMath>\langle r \rangle</InlineMath></li>
        <li>2 Klein four-subgroups: <InlineMath>\{'{'}1, r^2, s, sr^2\{'}'}</InlineMath> and <InlineMath>\{'{'}1, r^2, sr, sr^3\{'}'}</InlineMath></li>
        <li>1 subgroup of order 8: <InlineMath>D_8</InlineMath></li>
      </ul>

      <h3>Properties of Lattices</h3>
      <Callout type="info">
        <strong>Theorem:</strong> In a finite group:
        <ul className="list-disc list-inside mt-2 space-y-1">
          <li>The lattice has a minimum (<InlineMath>\{'{'}e\{'}'}</InlineMath>) and maximum (<InlineMath>G</InlineMath>)</li>
          <li>For any <InlineMath>H, K</InlineMath>: <InlineMath>|H \cap K|</InlineMath> divides <InlineMath>\gcd(|H|, |K|)</InlineMath></li>
          <li>If <InlineMath>H \le K</InlineMath>, then <InlineMath>|H|</InlineMath> divides <InlineMath>|K|</InlineMath> (by Lagrange)</li>
        </ul>
      </Callout>

      <h3>Modular Lattices</h3>
      <p>
        The subgroup lattice of any group is a <strong>modular lattice</strong>, meaning it satisfies the modular law:
      </p>
      <MathBlock>\text{'{'}If {'}'} H \le K, \text{'{'} then {'}'} H \vee (K \cap L) = K \cap (H \vee L)</MathBlock>

      <h3>Using Lattices</h3>
      <p>Lattice diagrams help visualize:</p>
      <ul className="list-disc list-inside text-dark-300 mb-6 space-y-2">
        <li>Which subgroups contain which others</li>
        <li>Maximal and minimal subgroups</li>
        <li>Normal subgroups (they have special properties in the lattice)</li>
        <li>Index relations between subgroups</li>
      </ul>

      <Callout type="warning">
        <strong>Note:</strong> Not every lattice is the subgroup lattice of some group.
        Characterizing which lattices arise from groups is a difficult problem.
      </Callout>

      <Callout type="success">
        <strong>Summary:</strong> The subgroups of a group form a lattice under inclusion, with meet given by intersection
        and join by the generated subgroup. Lattice diagrams provide visual representations of subgroup structure.
        The lattice is always modular and can reveal important structural information about the group.
      </Callout>
    </LessonLayout>
  );
}
