import { LessonLayout } from '@/components/layout/LessonLayout';
import { Callout } from '@/components/common/Callout';
import { MathBlock, InlineMath } from '@/components/common/MathBlock';

export default function Section72() {
  return (
    <LessonLayout sectionId={72}>
      <h2>Cyclotomic Extensions</h2>
      <p>
        <strong>Cyclotomic extensions</strong> <InlineMath>\mathbb{"{Q}"}(\zeta_n)/\mathbb{"{Q}"}</InlineMath>
        are the field extensions generated by roots of unity. They are the prototypical
        examples of abelian Galois extensions and play a central role in algebraic number
        theory and the proof of the Kronecker-Weber theorem.
      </p>

      <Callout type="info">
        <strong>Central Role:</strong> Cyclotomic fields are the "building blocks" of
        all abelian extensions of <InlineMath>\mathbb{"{Q}"}</InlineMath>. Every finite
        abelian extension of <InlineMath>\mathbb{"{Q}"}</InlineMath> is contained in some
        cyclotomic field (Kronecker-Weber theorem).
      </Callout>

      <h3>Basic Properties</h3>

      <div className="bg-dark-800/50 rounded-xl p-6 border border-dark-700 my-6">
        <h4 className="text-primary-400 mb-4">Definition</h4>
        <p>
          The <InlineMath>n</InlineMath>-th <strong>cyclotomic field</strong>
          is <InlineMath>\mathbb{"{Q}"}(\zeta_n)</InlineMath>,
          where <InlineMath>\zeta_n = e^{"{2\\pi i/n}"}</InlineMath> is a primitive
          <InlineMath>n</InlineMath>-th root of unity.
        </p>
      </div>

      <div className="bg-dark-800/50 rounded-xl p-6 border border-dark-700 my-6">
        <h4 className="text-primary-400 mb-4">Theorem: Basic Properties</h4>
        <ol className="list-decimal list-inside space-y-3 text-dark-300">
          <li><InlineMath>\mathbb{"{Q}"}(\zeta_n)</InlineMath> is the splitting field
            of <InlineMath>x^n - 1</InlineMath> over <InlineMath>\mathbb{"{Q}"}</InlineMath></li>
          <li><InlineMath>[\mathbb{"{Q}"}(\zeta_n):\mathbb{"{Q}"}] = \varphi(n)</InlineMath>
            where <InlineMath>\varphi</InlineMath> is Euler's totient</li>
          <li><InlineMath>\mathbb{"{Q}"}(\zeta_n)/\mathbb{"{Q}"}</InlineMath> is Galois (normal and separable)</li>
        </ol>
      </div>

      <h3>The Galois Group</h3>

      <div className="bg-dark-800/50 rounded-xl p-6 border border-dark-700 my-6">
        <h4 className="text-primary-400 mb-4">Theorem</h4>
        <MathBlock>{`\\text{Gal}(\\mathbb{Q}(\\zeta_n)/\\mathbb{Q}) \\cong (\\mathbb{Z}/n\\mathbb{Z})^*`}</MathBlock>
        <p className="mt-3">
          The isomorphism is given by: for each <InlineMath>a \in (\mathbb{"{Z}"}/n\mathbb{"{Z}"})^*</InlineMath>,
          there is a unique automorphism <InlineMath>\sigma_a</InlineMath> defined by
        </p>
        <MathBlock>{`\\sigma_a(\\zeta_n) = \\zeta_n^a`}</MathBlock>
      </div>

      <p>
        <strong>Why this works:</strong> Any automorphism must send <InlineMath>\zeta_n</InlineMath>
        to another primitive <InlineMath>n</InlineMath>-th root, i.e., to <InlineMath>\zeta_n^a</InlineMath>
        for some <InlineMath>a</InlineMath> with <InlineMath>\gcd(a, n) = 1</InlineMath>.
      </p>

      <div className="bg-dark-800 p-4 rounded-lg my-4 border-l-4 border-amber-500">
        <p className="font-semibold text-amber-400">Example: <InlineMath>\mathbb{"{Q}"}(\zeta_7)</InlineMath></p>
        <p className="mt-2">
          <InlineMath>\text{"{Gal}"}(\mathbb{"{Q}"}(\zeta_7)/\mathbb{"{Q}"}) \cong (\mathbb{"{Z}"}/7\mathbb{"{Z}"})^* \cong \mathbb{"{Z}"}/6\mathbb{"{Z}"}</InlineMath>
        </p>
        <p className="mt-2">
          This is cyclic of order 6, generated by <InlineMath>\sigma_3: \zeta_7 \mapsto \zeta_7^3</InlineMath>.
        </p>
        <p className="mt-2">
          The subgroups of <InlineMath>\mathbb{"{Z}"}/6\mathbb{"{Z}"}</InlineMath> have orders 1, 2, 3, 6,
          corresponding to intermediate fields of degrees 6, 3, 2, 1 over <InlineMath>\mathbb{"{Q}"}</InlineMath>.
        </p>
      </div>

      <h3>Subfields of Cyclotomic Fields</h3>

      <div className="bg-dark-800/50 rounded-xl p-6 border border-dark-700 my-6">
        <h4 className="text-primary-400 mb-4">Theorem: Containment</h4>
        <p>
          <InlineMath>\mathbb{"{Q}"}(\zeta_m) \subseteq \mathbb{"{Q}"}(\zeta_n)</InlineMath>
          if and only if <InlineMath>m \mid n</InlineMath>.
        </p>
      </div>

      <div className="bg-dark-800 p-4 rounded-lg my-4 border-l-4 border-blue-500">
        <p className="font-semibold text-blue-400">Important Special Case</p>
        <p className="mt-2">
          For odd prime <InlineMath>p</InlineMath>, <InlineMath>\mathbb{"{Q}"}(\zeta_p)</InlineMath>
          contains a unique quadratic subfield:
        </p>
        <MathBlock>{`\\mathbb{Q}\\left(\\sqrt{p^*}\\right) \\quad \\text{where } p^* = (-1)^{(p-1)/2} p`}</MathBlock>
        <p className="mt-2">
          So: <InlineMath>\mathbb{"{Q}"}(\sqrt{"{5}"}) \subset \mathbb{"{Q}"}(\zeta_5)</InlineMath>,
          <InlineMath>\mathbb{"{Q}"}(\sqrt{"{-3}"}) \subset \mathbb{"{Q}"}(\zeta_3)</InlineMath>,
          <InlineMath>\mathbb{"{Q}"}(\sqrt{"{-7}"}) \subset \mathbb{"{Q}"}(\zeta_7)</InlineMath>.
        </p>
      </div>

      <h3>The Conductor</h3>

      <div className="bg-dark-800/50 rounded-xl p-6 border border-dark-700 my-6">
        <h4 className="text-primary-400 mb-4">Definition</h4>
        <p>
          For a subfield <InlineMath>K \subseteq \mathbb{"{Q}"}(\zeta_n)</InlineMath>, the
          <strong> conductor</strong> of <InlineMath>K</InlineMath> is the smallest <InlineMath>m</InlineMath>
          such that <InlineMath>K \subseteq \mathbb{"{Q}"}(\zeta_m)</InlineMath>.
        </p>
      </div>

      <h3>Quadratic Subfields</h3>

      <div className="bg-dark-800/50 rounded-xl p-6 border border-dark-700 my-6">
        <h4 className="text-primary-400 mb-4">Theorem: Quadratic Fields in Cyclotomic Fields</h4>
        <p>
          Every quadratic field <InlineMath>\mathbb{"{Q}"}(\sqrt{"{d}"})</InlineMath> is contained
          in some cyclotomic field. Specifically, if <InlineMath>d</InlineMath> is the discriminant:
        </p>
        <MathBlock>{`\\mathbb{Q}(\\sqrt{d}) \\subseteq \\mathbb{Q}(\\zeta_{|d|})`}</MathBlock>
      </div>

      <h3>Gauss Sums</h3>

      <p>
        The quadratic subfield can be expressed using <strong>Gauss sums</strong>:
      </p>

      <div className="bg-dark-800/50 rounded-xl p-6 border border-dark-700 my-6">
        <h4 className="text-primary-400 mb-4">Definition: Gauss Sum</h4>
        <p>
          For prime <InlineMath>p</InlineMath>, the quadratic Gauss sum is:
        </p>
        <MathBlock>{`g = \\sum_{a=1}^{p-1} \\left(\\frac{a}{p}\\right) \\zeta_p^a`}</MathBlock>
        <p className="mt-3">
          where <InlineMath>\left(\frac{"{a}"}{"{p}"}\right)</InlineMath> is the Legendre symbol.
        </p>
      </div>

      <div className="bg-dark-800/50 rounded-xl p-6 border border-dark-700 my-6">
        <h4 className="text-primary-400 mb-4">Theorem</h4>
        <MathBlock>{`g^2 = \\left(\\frac{-1}{p}\\right) p = (-1)^{(p-1)/2} p = p^*`}</MathBlock>
        <p className="mt-3">
          Thus <InlineMath>g = \pm\sqrt{"{p^*}"}</InlineMath>, giving the quadratic subfield explicitly.
        </p>
      </div>

      <h3>Kronecker-Weber Theorem</h3>

      <div className="bg-dark-800/50 rounded-xl p-6 border border-dark-700 my-6">
        <h4 className="text-primary-400 mb-4">Theorem (Kronecker-Weber)</h4>
        <p>
          Every finite abelian extension of <InlineMath>\mathbb{"{Q}"}</InlineMath> is contained
          in a cyclotomic field <InlineMath>\mathbb{"{Q}"}(\zeta_n)</InlineMath> for some <InlineMath>n</InlineMath>.
        </p>
      </div>

      <Callout type="warning">
        <strong>Deep Result:</strong> The Kronecker-Weber theorem is a cornerstone of algebraic
        number theory. Its proof requires substantial machinery (local fields, ramification theory).
        The generalization to other base fields is Hilbert's 12th problem, still open in general.
      </Callout>

      <h3>Example: The Fifth Cyclotomic Field</h3>

      <div className="bg-dark-800 p-4 rounded-lg my-4 border-l-4 border-purple-500">
        <p className="font-semibold text-purple-400">Complete Analysis of <InlineMath>\mathbb{"{Q}"}(\zeta_5)</InlineMath></p>
        <p className="mt-2">
          <InlineMath>\zeta_5 = e^{"{2\\pi i/5}"}</InlineMath>, so <InlineMath>[\mathbb{"{Q}"}(\zeta_5):\mathbb{"{Q}"}] = \varphi(5) = 4</InlineMath>.
        </p>
        <p className="mt-2">
          <InlineMath>\text{"{Gal}"}(\mathbb{"{Q}"}(\zeta_5)/\mathbb{"{Q}"}) \cong (\mathbb{"{Z}"}/5\mathbb{"{Z}"})^* \cong \mathbb{"{Z}"}/4\mathbb{"{Z}"}</InlineMath>.
        </p>
        <p className="mt-2"><strong>Subgroups and subfields:</strong></p>
        <ul className="list-disc list-inside space-y-1 mt-2 text-dark-300">
          <li>Whole group <InlineMath>\leftrightarrow \mathbb{"{Q}"}</InlineMath></li>
          <li>Subgroup of index 2 <InlineMath>\leftrightarrow \mathbb{"{Q}"}(\sqrt{"{5}"})</InlineMath> (unique quadratic subfield)</li>
          <li>Trivial subgroup <InlineMath>\leftrightarrow \mathbb{"{Q}"}(\zeta_5)</InlineMath></li>
        </ul>
        <p className="mt-2">
          We can write <InlineMath>\zeta_5 + \zeta_5^4 = \frac{"{-1 + \\sqrt{5}}"}{"{2}"} = \varphi - 1</InlineMath>
          (related to the golden ratio!).
        </p>
      </div>

      <Callout type="success">
        <strong>Summary:</strong> Cyclotomic fields <InlineMath>\mathbb{"{Q}"}(\zeta_n)</InlineMath>
        have degree <InlineMath>\varphi(n)</InlineMath> and Galois
        group <InlineMath>(\mathbb{"{Z}"}/n\mathbb{"{Z}"})^*</InlineMath>. Their subfields
        correspond to subgroups of this abelian group. Every quadratic field lies in some
        cyclotomic field, and the Kronecker-Weber theorem says the same for ALL abelian
        extensions of <InlineMath>\mathbb{"{Q}"}</InlineMath>. Cyclotomic fields are thus
        the universal objects for studying abelian extensions.
      </Callout>
    </LessonLayout>
  );
}
