import { LessonLayout } from '@/components/layout/LessonLayout';
import { Callout } from '@/components/common/Callout';
import { MathBlock, InlineMath } from '@/components/common/MathBlock';

export default function Section71() {
  return (
    <LessonLayout sectionId={71}>
      <h2>Composite and Simple Extensions</h2>
      <p>
        Given multiple field extensions, how do they combine? <strong>Composite extensions</strong>
        are the smallest fields containing multiple given extensions, while <strong>simple extensions</strong>
        are generated by a single element. The Primitive Element Theorem shows that separable
        finite extensions are surprisingly simple.
      </p>

      <Callout type="info">
        <strong>Key Question:</strong> When is <InlineMath>F(\alpha, \beta)</InlineMath>
        actually equal to <InlineMath>F(\gamma)</InlineMath> for some single
        element <InlineMath>\gamma</InlineMath>?
      </Callout>

      <h3>Composite Fields</h3>

      <div className="bg-dark-800/50 rounded-xl p-6 border border-dark-700 my-6">
        <h4 className="text-primary-400 mb-4">Definition: Composite (Compositum)</h4>
        <p>
          Let <InlineMath>K_1</InlineMath> and <InlineMath>K_2</InlineMath> be subfields of
          a common field <InlineMath>L</InlineMath>. The <strong>composite</strong>
          (or <strong>compositum</strong>) <InlineMath>K_1 K_2</InlineMath> is the smallest
          subfield of <InlineMath>L</InlineMath> containing both <InlineMath>K_1</InlineMath>
          and <InlineMath>K_2</InlineMath>.
        </p>
      </div>

      <p>
        Equivalently, <InlineMath>K_1 K_2</InlineMath> is the field generated by <InlineMath>K_1 \cup K_2</InlineMath>.
        If <InlineMath>K_1 = F(\alpha_1, \ldots, \alpha_m)</InlineMath>
        and <InlineMath>K_2 = F(\beta_1, \ldots, \beta_n)</InlineMath>,
        then <InlineMath>K_1 K_2 = F(\alpha_1, \ldots, \alpha_m, \beta_1, \ldots, \beta_n)</InlineMath>.
      </p>

      <div className="bg-dark-800 p-4 rounded-lg my-4 border-l-4 border-amber-500">
        <p className="font-semibold text-amber-400">Example</p>
        <p className="mt-2">
          <InlineMath>\mathbb{"{Q}"}(\sqrt{"{2}"})\mathbb{"{Q}"}(\sqrt{"{3}"}) = \mathbb{"{Q}"}(\sqrt{"{2}"}, \sqrt{"{3}"})</InlineMath>
        </p>
        <p className="mt-2">
          Both <InlineMath>\mathbb{"{Q}"}(\sqrt{"{2}"})</InlineMath>
          and <InlineMath>\mathbb{"{Q}"}(\sqrt{"{3}"})</InlineMath> have degree 2
          over <InlineMath>\mathbb{"{Q}"}</InlineMath>, but their composite has degree 4.
        </p>
      </div>

      <h3>Degree of Composites</h3>

      <div className="bg-dark-800/50 rounded-xl p-6 border border-dark-700 my-6">
        <h4 className="text-primary-400 mb-4">Theorem: Degree Bounds</h4>
        <p>
          For finite extensions <InlineMath>K_1/F</InlineMath> and <InlineMath>K_2/F</InlineMath>:
        </p>
        <MathBlock>{`[K_1 K_2 : F] \\leq [K_1:F] \\cdot [K_2:F]`}</MathBlock>
        <p className="mt-3">
          Equality holds if <InlineMath>\gcd([K_1:F], [K_2:F]) = 1</InlineMath>.
        </p>
      </div>

      <div className="bg-dark-800/50 rounded-xl p-6 border border-dark-700 my-6">
        <h4 className="text-primary-400 mb-4">Theorem: Linearly Disjoint Extensions</h4>
        <p>
          Extensions <InlineMath>K_1/F</InlineMath> and <InlineMath>K_2/F</InlineMath>
          (inside a common overfield) are <strong>linearly disjoint</strong>
          if <InlineMath>K_1 \cap K_2 = F</InlineMath> and <InlineMath>[K_1 K_2 : F] = [K_1:F][K_2:F]</InlineMath>.
        </p>
      </div>

      <h3>Simple Extensions</h3>

      <div className="bg-dark-800/50 rounded-xl p-6 border border-dark-700 my-6">
        <h4 className="text-primary-400 mb-4">Definition</h4>
        <p>
          A field extension <InlineMath>K/F</InlineMath> is <strong>simple</strong> if
          <InlineMath>K = F(\alpha)</InlineMath> for some single element <InlineMath>\alpha</InlineMath>.
          Such an <InlineMath>\alpha</InlineMath> is called a <strong>primitive element</strong>
          for the extension.
        </p>
      </div>

      <div className="bg-dark-800 p-4 rounded-lg my-4 border-l-4 border-amber-500">
        <p className="font-semibold text-amber-400">Not All Extensions Are Simple</p>
        <p className="mt-2">
          Consider <InlineMath>K = \mathbb{"{F}"}_p(s, t)</InlineMath>, the rational function field
          in two variables over <InlineMath>\mathbb{"{F}"}_p</InlineMath>.
        </p>
        <p className="mt-2">
          Let <InlineMath>F = \mathbb{"{F}"}_p(s^p, t^p)</InlineMath>. Then <InlineMath>K/F</InlineMath>
          has degree <InlineMath>p^2</InlineMath> but is NOT simple.
        </p>
        <p className="mt-2 text-dark-300">
          (This is an inseparable extension where the Primitive Element Theorem fails.)
        </p>
      </div>

      <h3>The Primitive Element Theorem</h3>

      <div className="bg-dark-800/50 rounded-xl p-6 border border-dark-700 my-6">
        <h4 className="text-primary-400 mb-4">Theorem (Primitive Element)</h4>
        <p>
          Let <InlineMath>K/F</InlineMath> be a finite separable extension. Then <InlineMath>K/F</InlineMath>
          is simple: there exists <InlineMath>\alpha \in K</InlineMath> with <InlineMath>K = F(\alpha)</InlineMath>.
        </p>
      </div>

      <Callout type="info">
        <strong>In particular:</strong> Every finite extension in characteristic 0 is simple.
        Every finite extension of a finite field is simple.
      </Callout>

      <h3>Finding Primitive Elements</h3>

      <div className="bg-dark-800/50 rounded-xl p-6 border border-dark-700 my-6">
        <h4 className="text-primary-400 mb-4">Theorem: Explicit Construction</h4>
        <p>
          Let <InlineMath>K = F(\alpha, \beta)</InlineMath> be a finite separable extension.
          If <InlineMath>F</InlineMath> is infinite, then for all but finitely
          many <InlineMath>c \in F</InlineMath>:
        </p>
        <MathBlock>{`K = F(\\alpha + c\\beta)`}</MathBlock>
      </div>

      <div className="bg-dark-800 p-4 rounded-lg my-4 border-l-4 border-blue-500">
        <p className="font-semibold text-blue-400">Example: <InlineMath>\mathbb{"{Q}"}(\sqrt{"{2}"}, \sqrt{"{3}"})</InlineMath></p>
        <p className="mt-2">
          We claim <InlineMath>\mathbb{"{Q}"}(\sqrt{"{2}"}, \sqrt{"{3}"}) = \mathbb{"{Q}"}(\sqrt{"{2}"} + \sqrt{"{3}"})</InlineMath>.
        </p>
        <p className="mt-2">
          Let <InlineMath>\gamma = \sqrt{"{2}"} + \sqrt{"{3}"}</InlineMath>. Then:
        </p>
        <MathBlock>{`\\gamma^2 = 5 + 2\\sqrt{6}`}</MathBlock>
        <p className="mt-2">
          So <InlineMath>\sqrt{"{6}"} = (\gamma^2 - 5)/2 \in \mathbb{"{Q}"}(\gamma)</InlineMath>.
        </p>
        <p className="mt-2">
          Also <InlineMath>\gamma \cdot \sqrt{"{6}"} = \sqrt{"{12}"} + \sqrt{"{18}"} = 2\sqrt{"{3}"} + 3\sqrt{"{2}"}</InlineMath>.
        </p>
        <p className="mt-2">
          From <InlineMath>\gamma = \sqrt{"{2}"} + \sqrt{"{3}"}</InlineMath>
          and <InlineMath>2\sqrt{"{3}"} + 3\sqrt{"{2}"}</InlineMath>, we can
          solve for <InlineMath>\sqrt{"{2}"}</InlineMath> and <InlineMath>\sqrt{"{3}"}</InlineMath> individually.
        </p>
      </div>

      <h3>Proof Idea of Primitive Element Theorem</h3>

      <p>
        The key insight is to count <InlineMath>F</InlineMath>-embeddings:
      </p>

      <ol className="list-decimal list-inside space-y-2 my-4 text-dark-300">
        <li>
          For <InlineMath>K = F(\alpha, \beta)</InlineMath> separable of degree <InlineMath>n</InlineMath>,
          there are exactly <InlineMath>n</InlineMath> embeddings <InlineMath>K \hookrightarrow \overline{"{F}"}</InlineMath>.
        </li>
        <li>
          Let <InlineMath>\alpha_1, \ldots, \alpha_r</InlineMath> be the conjugates of <InlineMath>\alpha</InlineMath>
          and <InlineMath>\beta_1, \ldots, \beta_s</InlineMath> the conjugates of <InlineMath>\beta</InlineMath>.
        </li>
        <li>
          For <InlineMath>c \in F</InlineMath>, consider <InlineMath>\gamma = \alpha + c\beta</InlineMath>.
          We need <InlineMath>[F(\gamma):F] = n</InlineMath>.
        </li>
        <li>
          This fails only if <InlineMath>\alpha_i + c\beta_j = \alpha_k + c\beta_l</InlineMath>
          for some distinct pairs, which gives only finitely many "bad" values of <InlineMath>c</InlineMath>.
        </li>
      </ol>

      <h3>Galois Groups and Composites</h3>

      <div className="bg-dark-800/50 rounded-xl p-6 border border-dark-700 my-6">
        <h4 className="text-primary-400 mb-4">Theorem</h4>
        <p>
          Let <InlineMath>K_1/F</InlineMath> and <InlineMath>K_2/F</InlineMath> be Galois extensions
          inside a common overfield. Then <InlineMath>K_1 K_2/F</InlineMath> is Galois, and:
        </p>
        <MathBlock>{`\\text{Gal}(K_1 K_2/F) \\hookrightarrow \\text{Gal}(K_1/F) \\times \\text{Gal}(K_2/F)`}</MathBlock>
        <p className="mt-3">
          The embedding is given by <InlineMath>\sigma \mapsto (\sigma|_{"{K_1}"}, \sigma|_{"{K_2}"})</InlineMath>.
        </p>
        <p className="mt-3">
          This is an isomorphism iff <InlineMath>K_1 \cap K_2 = F</InlineMath>.
        </p>
      </div>

      <div className="bg-dark-800 p-4 rounded-lg my-4 border-l-4 border-emerald-500">
        <p className="font-semibold text-emerald-400">Example</p>
        <p className="mt-2">
          <InlineMath>K_1 = \mathbb{"{Q}"}(\sqrt{"{2}"})</InlineMath>, <InlineMath>K_2 = \mathbb{"{Q}"}(\sqrt{"{3}"})</InlineMath>.
        </p>
        <p className="mt-2">
          Since <InlineMath>K_1 \cap K_2 = \mathbb{"{Q}"}</InlineMath>:
        </p>
        <MathBlock>{`\\text{Gal}(\\mathbb{Q}(\\sqrt{2}, \\sqrt{3})/\\mathbb{Q}) \\cong \\mathbb{Z}/2\\mathbb{Z} \\times \\mathbb{Z}/2\\mathbb{Z}`}</MathBlock>
        <p className="mt-2">
          The Klein four-group!
        </p>
      </div>

      <Callout type="success">
        <strong>Summary:</strong> The composite <InlineMath>K_1 K_2</InlineMath> is the smallest
        field containing both <InlineMath>K_1</InlineMath> and <InlineMath>K_2</InlineMath>.
        The Primitive Element Theorem states that every finite separable extension is simple,
        generated by a single element. For infinite base fields, <InlineMath>\alpha + c\beta</InlineMath>
        is a primitive element for almost all <InlineMath>c</InlineMath>. For Galois extensions,
        composites correspond to subgroups of direct products.
      </Callout>
    </LessonLayout>
  );
}
