import { LessonLayout } from '@/components/layout/LessonLayout';
import { Definition, Theorem, Example } from '@/components/common/ContentBlocks';
import { Callout } from '@/components/common/Callout';
import { MathBlock, InlineMath } from '@/components/common/MathBlock';

export default function Section41() {
  return (
    <LessonLayout sectionId={41}>
      <h2>Principal Ideal Domains (PIDs)</h2>

      <p>
        Principal Ideal Domains occupy a central position in the hierarchy of integral domains.
        They generalize the integers while retaining enough structure to guarantee unique
        factorization and other desirable properties. Understanding PIDs provides insight
        into more general rings.
      </p>

      <h3>Definition and First Properties</h3>

      <Definition title="Principal Ideal Domain">
        <p>
          An integral domain <InlineMath>R</InlineMath> is a <strong>Principal Ideal Domain</strong> (PID)
          if every ideal of <InlineMath>R</InlineMath> is principal, i.e., generated by a single element:
        </p>
        <MathBlock>
          {'\\text{For every ideal } I \\subseteq R, \\text{ there exists } a \\in R \\text{ with } I = (a)'}
        </MathBlock>
      </Definition>

      <Example title="Examples of PIDs">
        <p>
          The following are Principal Ideal Domains:
        </p>
        <ul className="list-disc list-inside mt-2">
          <li><InlineMath>{'\\mathbb{Z}'}</InlineMath> — every ideal is <InlineMath>{'(n)'}</InlineMath> for some <InlineMath>n</InlineMath></li>
          <li><InlineMath>F[x]</InlineMath> for any field <InlineMath>F</InlineMath></li>
          <li>Any Euclidean domain (we proved this previously)</li>
          <li>Any field (the only ideals are <InlineMath>{'(0)'}</InlineMath> and <InlineMath>{'(1)'}</InlineMath>)</li>
        </ul>
      </Example>

      <Example title="Non-Examples">
        <p>
          <InlineMath>{'\\mathbb{Z}[x]'}</InlineMath> is NOT a PID. The ideal <InlineMath>{'(2, x)'}</InlineMath>
          (elements of form <InlineMath>{'2f(x) + xg(x)'}</InlineMath>) cannot be generated by a single polynomial.
        </p>
        <p className="mt-2">
          If <InlineMath>{'(2, x) = (d)'}</InlineMath>, then <InlineMath>d</InlineMath> divides both 2 and <InlineMath>x</InlineMath>,
          so <InlineMath>{'d \\in \\{\\pm 1, \\pm 2\\}'}</InlineMath>. But <InlineMath>{'d = \\pm 1'}</InlineMath> gives
          <InlineMath>{'(d) = \\mathbb{Z}[x]'}</InlineMath>, and <InlineMath>{'1 \\notin (2, x)'}</InlineMath>.
          And <InlineMath>{'d = \\pm 2'}</InlineMath> gives <InlineMath>{'x \\notin (2)'}</InlineMath>. Contradiction.
        </p>
      </Example>

      <h3>GCDs in PIDs</h3>

      <Theorem title="GCDs Exist in PIDs"
        proof={
          <>
            <p>
              Consider the ideal <InlineMath>{'(a, b) = \\{ra + sb : r, s \\in R\\}'}</InlineMath>.
              Since <InlineMath>R</InlineMath> is a PID, <InlineMath>{'(a, b) = (d)'}</InlineMath> for some
              <InlineMath>d</InlineMath>.
            </p>
            <p className="mt-2">
              Since <InlineMath>{'a, b \\in (d)'}</InlineMath>, we have <InlineMath>{'d \\mid a'}</InlineMath> and
              <InlineMath>{'d \\mid b'}</InlineMath>, so <InlineMath>d</InlineMath> is a common divisor.
            </p>
            <p className="mt-2">
              If <InlineMath>{'c \\mid a'}</InlineMath> and <InlineMath>{'c \\mid b'}</InlineMath>, then
              <InlineMath>{'c \\mid d'}</InlineMath> since <InlineMath>{'d \\in (a, b)'}</InlineMath>, so
              <InlineMath>{'d = ra + sb'}</InlineMath> for some <InlineMath>{'r, s'}</InlineMath>.
            </p>
          </>
        }
      >
        <p>
          In a PID, any two elements <InlineMath>a, b</InlineMath> have a greatest common divisor
          <InlineMath>d = \\gcd(a, b)</InlineMath>, and it can be expressed as
        </p>
        <MathBlock>
          {'d = ra + sb \\quad \\text{for some } r, s \\in R'}
        </MathBlock>
        <p className="mt-2">
          In fact, <InlineMath>{'\\gcd(a, b)'}</InlineMath> is a generator of the ideal <InlineMath>{'(a, b)'}</InlineMath>.
        </p>
      </Theorem>

      <h3>Primes and Irreducibles</h3>

      <Definition title="Irreducible Element">
        <p>
          A nonzero, non-unit element <InlineMath>{'p \\in R'}</InlineMath> is <strong>irreducible</strong>
          if whenever <InlineMath>{'p = ab'}</InlineMath>, either <InlineMath>a</InlineMath> or <InlineMath>b</InlineMath> is a unit.
        </p>
      </Definition>

      <Definition title="Prime Element">
        <p>
          A nonzero, non-unit element <InlineMath>{'p \\in R'}</InlineMath> is <strong>prime</strong>
          if whenever <InlineMath>{'p \\mid ab'}</InlineMath>, either <InlineMath>{'p \\mid a'}</InlineMath> or
          <InlineMath>{'p \\mid b'}</InlineMath>.
        </p>
        <p className="mt-2">
          Equivalently, <InlineMath>p</InlineMath> is prime iff <InlineMath>{'(p)'}</InlineMath> is a prime ideal.
        </p>
      </Definition>

      <Theorem title="Prime Implies Irreducible"
        proof={
          <>
            <p>
              Suppose <InlineMath>p</InlineMath> is prime and <InlineMath>{'p = ab'}</InlineMath>.
              Then <InlineMath>{'p \\mid ab'}</InlineMath>, so <InlineMath>{'p \\mid a'}</InlineMath> or
              <InlineMath>{'p \\mid b'}</InlineMath>.
            </p>
            <p className="mt-2">
              Say <InlineMath>{'p \\mid a'}</InlineMath>, so <InlineMath>{'a = pc'}</InlineMath>. Then
              <InlineMath>{'p = ab = pcb'}</InlineMath>, giving <InlineMath>{'1 = cb'}</InlineMath>.
              Thus <InlineMath>b</InlineMath> is a unit.
            </p>
          </>
        }
      >
        <p>
          In any integral domain, every prime element is irreducible.
        </p>
      </Theorem>

      <Theorem title="Irreducible Implies Prime in PIDs"
        proof={
          <>
            <p>
              Let <InlineMath>p</InlineMath> be irreducible and suppose <InlineMath>{'p \\mid ab'}</InlineMath>.
              Let <InlineMath>{'d = \\gcd(p, a)'}</InlineMath>. Since <InlineMath>R</InlineMath> is a PID,
              <InlineMath>{'d \\mid p'}</InlineMath>, so <InlineMath>{'d = 1'}</InlineMath> (unit) or
              <InlineMath>{'d = up'}</InlineMath> (associate of <InlineMath>p</InlineMath>).
            </p>
            <p className="mt-2">
              Case 1: <InlineMath>{'d \\sim p'}</InlineMath>. Then <InlineMath>{'p \\mid a'}</InlineMath>.
            </p>
            <p className="mt-2">
              Case 2: <InlineMath>d</InlineMath> is a unit. Write <InlineMath>{'1 = rp + sa'}</InlineMath> (since
              <InlineMath>{'(p, a) = (1)'}</InlineMath>). Then <InlineMath>{'b = rpb + sab'}</InlineMath>.
              Since <InlineMath>{'p \\mid ab'}</InlineMath>, we have <InlineMath>{'p \\mid b'}</InlineMath>.
            </p>
          </>
        }
      >
        <p>
          In a PID, every irreducible element is prime. Thus prime and irreducible are equivalent in PIDs.
        </p>
      </Theorem>

      <Callout type="warning">
        <strong>This Fails in General Domains:</strong> In <InlineMath>{'\\mathbb{Z}[\\sqrt{-5}]'}</InlineMath>,
        the element 2 is irreducible but not prime. We have <InlineMath>{'2 \\mid 6 = (1+\\sqrt{-5})(1-\\sqrt{-5})'}</InlineMath>
        but 2 divides neither factor. This ring is not a PID.
      </Callout>

      <h3>Prime Ideals and Maximal Ideals in PIDs</h3>

      <Theorem title="Nonzero Prime Ideals are Maximal"
        proof={
          <>
            <p>
              Let <InlineMath>P = (p)</InlineMath> be a nonzero prime ideal. Suppose <InlineMath>{'(p) \\subseteq (a) \\subseteq R'}</InlineMath>
              with <InlineMath>{'(a) \\neq R'}</InlineMath>.
            </p>
            <p className="mt-2">
              Then <InlineMath>{'a \\mid p'}</InlineMath>, so <InlineMath>{'p = ab'}</InlineMath> for some <InlineMath>b</InlineMath>.
              Since <InlineMath>p</InlineMath> is prime (hence irreducible), either <InlineMath>a</InlineMath> or
              <InlineMath>b</InlineMath> is a unit.
            </p>
            <p className="mt-2">
              If <InlineMath>a</InlineMath> is a unit, <InlineMath>{'(a) = R'}</InlineMath>, contradiction.
              So <InlineMath>b</InlineMath> is a unit, meaning <InlineMath>{'p \\sim a'}</InlineMath>, so <InlineMath>{'(p) = (a)'}</InlineMath>.
            </p>
          </>
        }
      >
        <p>
          In a PID, every nonzero prime ideal is maximal. The only prime ideals are:
        </p>
        <ul className="list-disc list-inside mt-2">
          <li><InlineMath>{'(0)'}</InlineMath> (prime but not maximal, unless <InlineMath>R</InlineMath> is a field)</li>
          <li><InlineMath>{'(p)'}</InlineMath> for irreducible <InlineMath>p</InlineMath> (both prime and maximal)</li>
        </ul>
      </Theorem>

      <Example title="Prime Ideals in Z and F[x]">
        <p>
          In <InlineMath>{'\\mathbb{Z}'}</InlineMath>: Prime ideals are <InlineMath>{'(0)'}</InlineMath> and
          <InlineMath>{'(p)'}</InlineMath> for primes <InlineMath>p</InlineMath>. The maximal ideals are
          exactly <InlineMath>{'(p)'}</InlineMath>.
        </p>
        <p className="mt-2">
          In <InlineMath>{'\\mathbb{Q}[x]'}</InlineMath>: Prime ideals are <InlineMath>{'(0)'}</InlineMath> and
          <InlineMath>{'(f(x))'}</InlineMath> for irreducible polynomials <InlineMath>f(x)</InlineMath>.
        </p>
      </Example>

      <h3>Ascending Chain Condition</h3>

      <Theorem title="PIDs are Noetherian"
        proof={
          <>
            <p>
              Let <InlineMath>{'I_1 \\subseteq I_2 \\subseteq I_3 \\subseteq \\cdots'}</InlineMath> be an ascending
              chain of ideals. Let <InlineMath>{'I = \\bigcup_{n=1}^{\\infty} I_n'}</InlineMath>.
            </p>
            <p className="mt-2">
              Then <InlineMath>I</InlineMath> is an ideal, so <InlineMath>{'I = (a)'}</InlineMath> for some <InlineMath>a</InlineMath>.
              Since <InlineMath>{'a \\in I'}</InlineMath>, we have <InlineMath>{'a \\in I_N'}</InlineMath> for some <InlineMath>N</InlineMath>.
            </p>
            <p className="mt-2">
              Then <InlineMath>{'I = (a) \\subseteq I_N \\subseteq I'}</InlineMath>, so <InlineMath>{'I = I_N'}</InlineMath>.
              For all <InlineMath>{'n \\geq N'}</InlineMath>: <InlineMath>{'I_n = I_N'}</InlineMath>.
            </p>
          </>
        }
      >
        <p>
          A PID satisfies the <strong>ascending chain condition</strong> (ACC) on ideals: every ascending
          chain of ideals <InlineMath>{'I_1 \\subseteq I_2 \\subseteq \\cdots'}</InlineMath> eventually stabilizes.
        </p>
        <p className="mt-2">
          Equivalently, every non-empty set of ideals has a maximal element.
        </p>
      </Theorem>

      <Callout type="info">
        <strong>Noetherian Rings:</strong> A ring satisfying ACC on ideals is called <em>Noetherian</em>
        (after Emmy Noether). PIDs are Noetherian, but Noetherian rings need not be PIDs. For example,
        <InlineMath>{'\\mathbb{Z}[x]'}</InlineMath> is Noetherian but not a PID.
      </Callout>

      <h3>The Hierarchy of Domains</h3>

      <p>
        We now have a clear hierarchy:
      </p>

      <MathBlock>
        {'\\text{Fields} \\subset \\text{Euclidean Domains} \\subset \\text{PIDs} \\subset \\text{UFDs} \\subset \\text{Integral Domains}'}
      </MathBlock>

      <p>
        Each inclusion is proper:
      </p>
      <ul className="list-disc list-inside mt-2">
        <li><InlineMath>{'\\mathbb{Z}'}</InlineMath> is Euclidean but not a field</li>
        <li><InlineMath>{'\\mathbb{Z}[(1+\\sqrt{-19})/2]'}</InlineMath> is a PID but not Euclidean</li>
        <li><InlineMath>{'\\mathbb{Z}[x]'}</InlineMath> is a UFD but not a PID</li>
        <li><InlineMath>{'\\mathbb{Z}[\\sqrt{-5}]'}</InlineMath> is an integral domain but not a UFD</li>
      </ul>

      <Callout type="success">
        <strong>Summary:</strong> A PID is an integral domain where every ideal is principal. In a PID,
        GCDs exist and can be written as linear combinations; prime and irreducible are equivalent;
        nonzero prime ideals are maximal; and the ACC holds. PIDs include all Euclidean domains and
        are themselves UFDs (as we will see next).
      </Callout>
    </LessonLayout>
  );
}
