import { LessonLayout } from '@/components/layout/LessonLayout';
import { Definition, Theorem, Example } from '@/components/common/ContentBlocks';
import { Callout } from '@/components/common/Callout';
import { MathBlock, InlineMath } from '@/components/common/MathBlock';

export default function Section52() {
  return (
    <LessonLayout sectionId={52}>
      <h2>Tensor Products of Modules</h2>

      <p>
        The tensor product is a fundamental construction that combines two modules to produce a
        third. It provides the algebraic foundation for multilinear algebra and has applications
        throughout mathematics, from differential geometry to representation theory.
      </p>

      <h3>Motivation: Bilinear Maps</h3>

      <Definition title="Bilinear Map">
        <p>
          Let <InlineMath>M, N, P</InlineMath> be <InlineMath>R</InlineMath>-modules. A map
          <InlineMath>{'\\phi: M \\times N \\to P'}</InlineMath> is <strong><InlineMath>R</InlineMath>-bilinear</strong> if:
        </p>
        <ul className="list-disc list-inside mt-2">
          <li><InlineMath>{'\\phi(m_1 + m_2, n) = \\phi(m_1, n) + \\phi(m_2, n)'}</InlineMath></li>
          <li><InlineMath>{'\\phi(m, n_1 + n_2) = \\phi(m, n_1) + \\phi(m, n_2)'}</InlineMath></li>
          <li><InlineMath>{'\\phi(rm, n) = r\\phi(m, n) = \\phi(m, rn)'}</InlineMath></li>
        </ul>
        <p className="mt-2">
          for all <InlineMath>{'m, m_i \\in M'}</InlineMath>, <InlineMath>{'n, n_i \\in N'}</InlineMath>, <InlineMath>{'r \\in R'}</InlineMath>.
        </p>
      </Definition>

      <p>
        The tensor product <InlineMath>{'M \\otimes_R N'}</InlineMath> is designed to convert bilinear maps
        into linear maps.
      </p>

      <h3>Construction of Tensor Product</h3>

      <Definition title="Tensor Product">
        <p>
          For <InlineMath>R</InlineMath>-modules <InlineMath>M</InlineMath> and <InlineMath>N</InlineMath>, the
          <strong>tensor product</strong> <InlineMath>{'M \\otimes_R N'}</InlineMath> is constructed as:
        </p>
        <MathBlock>
          {'M \\otimes_R N = F(M \\times N) / K'}
        </MathBlock>
        <p className="mt-2">
          where <InlineMath>{'F(M \\times N)'}</InlineMath> is the free <InlineMath>R</InlineMath>-module on
          <InlineMath>{'M \\times N'}</InlineMath>, and <InlineMath>K</InlineMath> is the submodule generated by:
        </p>
        <ul className="list-disc list-inside mt-2">
          <li><InlineMath>{'(m_1 + m_2, n) - (m_1, n) - (m_2, n)'}</InlineMath></li>
          <li><InlineMath>{'(m, n_1 + n_2) - (m, n_1) - (m, n_2)'}</InlineMath></li>
          <li><InlineMath>{'(rm, n) - r(m, n)'}</InlineMath></li>
          <li><InlineMath>{'(m, rn) - r(m, n)'}</InlineMath></li>
        </ul>
        <p className="mt-2">
          We write <InlineMath>{'m \\otimes n'}</InlineMath> for the image of <InlineMath>{'(m, n)'}</InlineMath> in
          <InlineMath>{'M \\otimes_R N'}</InlineMath>.
        </p>
      </Definition>

      <Theorem title="Universal Property of Tensor Products"
        proof={
          <>
            <p>
              The map <InlineMath>{'\\iota: M \\times N \\to M \\otimes N'}</InlineMath> given by
              <InlineMath>{'\\iota(m, n) = m \\otimes n'}</InlineMath> is bilinear by construction.
            </p>
            <p className="mt-2">
              Given a bilinear <InlineMath>{'\\phi'}</InlineMath>, define <InlineMath>{'\\tilde{\\phi}'}</InlineMath>
              on generators by <InlineMath>{'\\tilde{\\phi}(m \\otimes n) = \\phi(m, n)'}</InlineMath> and extend
              linearly. The relations in <InlineMath>K</InlineMath> ensure this is well-defined.
            </p>
          </>
        }
      >
        <p>
          For any bilinear map <InlineMath>{'\\phi: M \\times N \\to P'}</InlineMath>, there exists a unique
          <InlineMath>R</InlineMath>-linear map <InlineMath>{'\\tilde{\\phi}: M \\otimes_R N \\to P'}</InlineMath> such that
          <InlineMath>{'\\tilde{\\phi}(m \\otimes n) = \\phi(m, n)'}</InlineMath>.
        </p>
        <p className="mt-2">
          In other words, bilinear maps from <InlineMath>{'M \\times N'}</InlineMath> correspond bijectively
          to linear maps from <InlineMath>{'M \\otimes_R N'}</InlineMath>.
        </p>
      </Theorem>

      <h3>Properties of Tensors</h3>

      <Theorem title="Basic Tensor Identities"
        proof={
          <>
            <p>
              These follow immediately from the defining relations of the tensor product.
            </p>
          </>
        }
      >
        <p>
          In <InlineMath>{'M \\otimes_R N'}</InlineMath>:
        </p>
        <MathBlock>
          {'(m_1 + m_2) \\otimes n = m_1 \\otimes n + m_2 \\otimes n'}
        </MathBlock>
        <MathBlock>
          {'m \\otimes (n_1 + n_2) = m \\otimes n_1 + m \\otimes n_2'}
        </MathBlock>
        <MathBlock>
          {'(rm) \\otimes n = r(m \\otimes n) = m \\otimes (rn)'}
        </MathBlock>
        <MathBlock>
          {'m \\otimes 0 = 0 = 0 \\otimes n'}
        </MathBlock>
      </Theorem>

      <Callout type="warning">
        <strong>Not All Elements Are Simple Tensors:</strong> Not every element of <InlineMath>{'M \\otimes N'}</InlineMath>
        has the form <InlineMath>{'m \\otimes n'}</InlineMath>. In general, elements are sums
        <InlineMath>{'\\sum_i m_i \\otimes n_i'}</InlineMath>. Simple tensors generate <InlineMath>{'M \\otimes N'}</InlineMath>,
        but the representation is not unique.
      </Callout>

      <h3>Examples</h3>

      <Example title="Tensor Product with R">
        <p>
          For any <InlineMath>R</InlineMath>-module <InlineMath>M</InlineMath>:
        </p>
        <MathBlock>
          {'R \\otimes_R M \\cong M'}
        </MathBlock>
        <p className="mt-2">
          The isomorphism sends <InlineMath>{'r \\otimes m \\mapsto rm'}</InlineMath>.
        </p>
      </Example>

      <Example title="Tensor Product of Free Modules">
        <p>
          <InlineMath>{'R^m \\otimes_R R^n \\cong R^{mn}'}</InlineMath>
        </p>
        <p className="mt-2">
          If <InlineMath>{'\\{e_i\\}'}</InlineMath> is a basis for <InlineMath>{'R^m'}</InlineMath> and
          <InlineMath>{'\\{f_j\\}'}</InlineMath> is a basis for <InlineMath>{'R^n'}</InlineMath>, then
          <InlineMath>{'\\{e_i \\otimes f_j\\}'}</InlineMath> is a basis for <InlineMath>{'R^m \\otimes R^n'}</InlineMath>.
        </p>
      </Example>

      <Example title="Tensoring with Quotients">
        <p>
          <InlineMath>{'\\mathbb{Z}/m\\mathbb{Z} \\otimes_\\mathbb{Z} \\mathbb{Z}/n\\mathbb{Z} \\cong \\mathbb{Z}/\\gcd(m,n)\\mathbb{Z}'}</InlineMath>
        </p>
        <p className="mt-2">
          In particular, <InlineMath>{'\\mathbb{Z}/2\\mathbb{Z} \\otimes_\\mathbb{Z} \\mathbb{Z}/3\\mathbb{Z} = 0'}</InlineMath>.
        </p>
      </Example>

      <Example title="Extension of Scalars">
        <p>
          If <InlineMath>{'R \\to S'}</InlineMath> is a ring homomorphism and <InlineMath>M</InlineMath> is an
          <InlineMath>R</InlineMath>-module, then <InlineMath>{'S \\otimes_R M'}</InlineMath> is an <InlineMath>S</InlineMath>-module
          called the <strong>extension of scalars</strong>.
        </p>
        <p className="mt-2">
          For example: <InlineMath>{'\\mathbb{C} \\otimes_\\mathbb{R} V \\cong V \\otimes_\\mathbb{R} \\mathbb{C}'}</InlineMath>
          complexifies a real vector space.
        </p>
      </Example>

      <h3>Properties of the Tensor Functor</h3>

      <Theorem title="Tensor Product Properties"
        proof={
          <>
            <p>
              Commutativity: The map <InlineMath>{'m \\otimes n \\mapsto n \\otimes m'}</InlineMath> extends to an isomorphism.
            </p>
            <p className="mt-2">
              Associativity: Both sides satisfy the same universal property for trilinear maps.
            </p>
            <p className="mt-2">
              Distribution: Direct verification using the universal property.
            </p>
          </>
        }
      >
        <p>
          For <InlineMath>R</InlineMath>-modules:
        </p>
        <ul className="list-disc list-inside mt-2">
          <li><strong>Commutativity:</strong> <InlineMath>{'M \\otimes N \\cong N \\otimes M'}</InlineMath></li>
          <li><strong>Associativity:</strong> <InlineMath>{'(L \\otimes M) \\otimes N \\cong L \\otimes (M \\otimes N)'}</InlineMath></li>
          <li><strong>Distributivity:</strong> <InlineMath>{'L \\otimes (M \\oplus N) \\cong (L \\otimes M) \\oplus (L \\otimes N)'}</InlineMath></li>
          <li><strong>Identity:</strong> <InlineMath>{'R \\otimes M \\cong M'}</InlineMath></li>
        </ul>
      </Theorem>

      <Theorem title="Right Exactness"
        proof={
          <>
            <p>
              Tensoring is right exact: if <InlineMath>{'A \\to B \\to C \\to 0'}</InlineMath> is exact, then
              <InlineMath>{'M \\otimes A \\to M \\otimes B \\to M \\otimes C \\to 0'}</InlineMath> is exact.
            </p>
            <p className="mt-2">
              However, tensoring does not preserve injections in general. Modules for which it does are called <em>flat</em>.
            </p>
          </>
        }
      >
        <p>
          The functor <InlineMath>{'M \\otimes -'}</InlineMath> is right exact. That is, if
          <InlineMath>{'N_1 \\to N_2 \\to N_3 \\to 0'}</InlineMath> is exact, then
        </p>
        <MathBlock>
          {'M \\otimes N_1 \\to M \\otimes N_2 \\to M \\otimes N_3 \\to 0'}
        </MathBlock>
        <p className="mt-2">
          is exact.
        </p>
      </Theorem>

      <Callout type="info">
        <strong>Tensors in Physics:</strong> The tensor product is the mathematical foundation for
        tensors in physics. A tensor of type <InlineMath>{'(r, s)'}</InlineMath> at a point is an element
        of <InlineMath>{'V \\otimes \\cdots \\otimes V \\otimes V^* \\otimes \\cdots \\otimes V^*'}</InlineMath>
        (<InlineMath>r</InlineMath> copies of <InlineMath>V</InlineMath>, <InlineMath>s</InlineMath> copies of <InlineMath>{'V^*'}</InlineMath>).
      </Callout>

      <Callout type="success">
        <strong>Summary:</strong> The tensor product <InlineMath>{'M \\otimes_R N'}</InlineMath> linearizes
        bilinear maps: bilinear maps from <InlineMath>{'M \\times N'}</InlineMath> correspond to linear maps
        from <InlineMath>{'M \\otimes N'}</InlineMath>. Tensor products are commutative, associative, and
        distribute over direct sums. The functor is right exact but not left exact in general.
      </Callout>
    </LessonLayout>
  );
}
