import { LessonLayout } from '@/components/layout/LessonLayout';
import { Callout } from '@/components/common/Callout';
import { InlineMath } from '@/components/common/MathBlock';

export default function Section25() {
  return (
    <LessonLayout sectionId={25}>
      <h2>Simplicity of A_n</h2>
      <p>
        One of the most important results in group theory is that the alternating group <InlineMath>A_n</InlineMath>
        is simple for <InlineMath>n \geq 5</InlineMath>. This section proves this fundamental theorem.
      </p>

      <h3>Simplicity Reminder</h3>
      <Callout type="info">
        <strong>Definition:</strong> A group <InlineMath>G</InlineMath> is <strong>simple</strong> if <InlineMath>G \neq \{'{'}e\{'}'}</InlineMath> and the only
        normal subgroups of <InlineMath>G</InlineMath> are <InlineMath>\{'{'}e\{'}'}</InlineMath> and <InlineMath>G</InlineMath>.
      </Callout>

      <h3>Small Cases</h3>
      <p>First, let's verify simplicity fails for small <InlineMath>n</InlineMath>:</p>
      <ul className="list-disc list-inside text-dark-300 mb-6 space-y-2">
        <li><InlineMath>A_1 = A_2 = \{'{'}e\{'}'}</InlineMath> — trivial, not simple by definition</li>
        <li><InlineMath>A_3 \cong \mathbb{'{'}Z{'}'}/3\mathbb{'{'}Z{'}'}</InlineMath> — simple (cyclic of prime order)</li>
        <li><InlineMath>A_4</InlineMath> has <InlineMath>V_4 \unlhd A_4</InlineMath> — NOT simple</li>
      </ul>

      <h3>Key Lemmas</h3>
      <Callout type="info">
        <strong>Lemma 1:</strong> <InlineMath>A_n</InlineMath> is generated by 3-cycles for <InlineMath>n \geq 3</InlineMath>.
      </Callout>
      <p>
        <em>Proof:</em> Any even permutation is a product of an even number of transpositions.
        Products of two transpositions can be written as 3-cycles (shown earlier).
      </p>

      <Callout type="info">
        <strong>Lemma 2:</strong> For <InlineMath>n \geq 5</InlineMath>, all 3-cycles in <InlineMath>A_n</InlineMath> are conjugate.
      </Callout>
      <p>
        <em>Proof:</em> Given 3-cycles <InlineMath>(a\,b\,c)</InlineMath> and <InlineMath>(d\,e\,f)</InlineMath>, find <InlineMath>\sigma \in A_n</InlineMath> with <InlineMath>\sigma(a) = d, \sigma(b) = e, \sigma(c) = f</InlineMath>.
        Since <InlineMath>n \geq 5</InlineMath>, we can ensure <InlineMath>\sigma</InlineMath> is even.
      </p>

      <Callout type="info">
        <strong>Lemma 3:</strong> For <InlineMath>n \geq 5</InlineMath>, if <InlineMath>N \unlhd A_n</InlineMath> contains any 3-cycle, then <InlineMath>N = A_n</InlineMath>.
      </Callout>
      <p>
        <em>Proof:</em> Normal subgroups are unions of conjugacy classes. By Lemma 2, all 3-cycles are conjugate
        in <InlineMath>A_n</InlineMath>. So if <InlineMath>N</InlineMath> contains one 3-cycle, it contains all 3-cycles. By Lemma 1, <InlineMath>N = A_n</InlineMath>.
      </p>

      <h3>The Main Theorem</h3>
      <Callout type="info">
        <strong>Theorem:</strong> <InlineMath>A_n</InlineMath> is simple for <InlineMath>n \geq 5</InlineMath>.
      </Callout>

      <p>
        <strong>Proof:</strong> Let <InlineMath>N \unlhd A_n</InlineMath> with <InlineMath>N \neq \{'{'}e\{'}'}</InlineMath>. We show <InlineMath>N</InlineMath> contains a 3-cycle.
      </p>

      <p>
        Let <InlineMath>\sigma \in N</InlineMath>, <InlineMath>\sigma \neq e</InlineMath>. Consider the cycle structure of <InlineMath>\sigma</InlineMath>:
      </p>

      <p><strong>Case 1:</strong> <InlineMath>\sigma</InlineMath> contains a cycle of length <InlineMath>\geq 3</InlineMath>.</p>
      <p>
        Say <InlineMath>\sigma</InlineMath> contains <InlineMath>(1\,2\,3\,\ldots)</InlineMath>. Let <InlineMath>\tau = (1\,2\,3)</InlineMath>.
        Then <InlineMath>\tau \sigma \tau^{'{-1}'} \sigma^{'{-1}'}</InlineMath> is a commutator in <InlineMath>N</InlineMath>.
        Calculation shows this is a non-trivial element moving fewer points than <InlineMath>\sigma</InlineMath> (or is a 3-cycle).
        Iterate until we get a 3-cycle.
      </p>

      <p><strong>Case 2:</strong> <InlineMath>\sigma</InlineMath> is a product of disjoint transpositions.</p>
      <p>
        Say <InlineMath>\sigma = (1\,2)(3\,4)\cdots</InlineMath>. Since <InlineMath>n \geq 5</InlineMath>, let <InlineMath>\tau = (1\,2\,3) \in A_n</InlineMath>.
        Then <InlineMath>\tau \sigma \tau^{'{-1}'} = (2\,3)(1\,4)\cdots</InlineMath>.
        So <InlineMath>\sigma(\tau\sigma\tau^{'{-1}'}) = (1\,2)(3\,4)(2\,3)(1\,4)\cdots = (1\,3)(2\,4)\cdots</InlineMath>.
      </p>
      <p>
        The commutator <InlineMath>\sigma(\tau\sigma\tau^{'{-1}'}) \sigma^{'{-1}'} (\tau\sigma\tau^{'{-1}'})^{'{-1}'} \in N</InlineMath> is a 3-cycle.
      </p>

      <p>
        By Lemma 3, <InlineMath>N = A_n</InlineMath>. Thus <InlineMath>A_n</InlineMath> has no proper non-trivial normal subgroups.
      </p>

      <h3>Why Does A_4 Fail?</h3>
      <p>
        In <InlineMath>A_4</InlineMath>, the 3-cycles split into two conjugacy classes (not all 3-cycles are conjugate in <InlineMath>A_4</InlineMath>).
        This allows <InlineMath>V_4 = \{'{'}e, (1\,2)(3\,4), (1\,3)(2\,4), (1\,4)(2\,3)\{'}'}</InlineMath> to be a proper normal subgroup.
      </p>

      <h3>Significance</h3>
      <p>
        The simplicity of <InlineMath>A_n</InlineMath> for <InlineMath>n \geq 5</InlineMath> is crucial because:
      </p>
      <ul className="list-disc list-inside text-dark-300 mb-6 space-y-2">
        <li>It provides an infinite family of simple groups</li>
        <li><InlineMath>A_5</InlineMath> is the smallest non-abelian simple group (order 60)</li>
        <li>It implies that the general quintic equation cannot be solved by radicals (Galois theory)</li>
        <li>The <InlineMath>A_n</InlineMath> appear in the Classification of Finite Simple Groups</li>
      </ul>

      <Callout type="success">
        <strong>Summary:</strong> <InlineMath>A_n</InlineMath> is simple for <InlineMath>n \geq 5</InlineMath>. The proof uses that <InlineMath>A_n</InlineMath> is generated by 3-cycles,
        all 3-cycles are conjugate in <InlineMath>A_n</InlineMath> for <InlineMath>n \geq 5</InlineMath>, and commutator arguments to show any non-trivial
        normal subgroup contains a 3-cycle, hence equals <InlineMath>A_n</InlineMath>. This is a cornerstone result in group theory.
      </Callout>
    </LessonLayout>
  );
}
