import { LessonLayout } from '@/components/layout/LessonLayout';
import { Callout } from '@/components/common/Callout';
import { MathBlock, InlineMath } from '@/components/common/MathBlock';

export default function Section13() {
  return (
    <LessonLayout sectionId={13}>
      <h2>Subgroups Generated by Subsets</h2>
      <p>
        Given any subset of a group, we can construct the smallest subgroup containing it.
        This leads to the concept of <strong>generators</strong> and <strong>generating sets</strong>.
      </p>

      <h3>The Subgroup Generated by a Subset</h3>
      <Callout type="info">
        <strong>Definition:</strong> For a subset <InlineMath>S \subseteq G</InlineMath>, the <strong>subgroup generated by S</strong>,
        denoted <InlineMath>\langle S \rangle</InlineMath>, is the smallest subgroup of <InlineMath>G</InlineMath> containing <InlineMath>S</InlineMath>.
      </Callout>

      <p>Equivalently:</p>
      <MathBlock>\langle S \rangle = \bigcap \{'{'}H \le G : S \subseteq H\{'}'}</MathBlock>

      <h3>Explicit Description</h3>
      <Callout type="info">
        <strong>Theorem:</strong> For a non-empty subset <InlineMath>S \subseteq G</InlineMath>:
        <MathBlock>\langle S \rangle = \{'{'}s_1^{'{'}\epsilon_1{'}'} s_2^{'{'}\epsilon_2{'}'} \cdots s_n^{'{'}\epsilon_n{'}'} : n \geq 0, \, s_i \in S, \, \epsilon_i = \pm 1\{'}'}</MathBlock>
        That is, <InlineMath>\langle S \rangle</InlineMath> consists of all finite products of elements of <InlineMath>S</InlineMath> and their inverses.
      </Callout>

      <p>
        The empty product gives the identity, so <InlineMath>e \in \langle S \rangle</InlineMath>. If <InlineMath>S = \emptyset</InlineMath>, then <InlineMath>\langle \emptyset \rangle = \{'{'}e\{'}'}</InlineMath>.
      </p>

      <h3>Generators</h3>
      <Callout type="info">
        <strong>Definition:</strong> A subset <InlineMath>S</InlineMath> is a <strong>generating set</strong> for <InlineMath>G</InlineMath> if <InlineMath>\langle S \rangle = G</InlineMath>.
        Elements of <InlineMath>S</InlineMath> are called <strong>generators</strong>.
        If <InlineMath>G</InlineMath> has a finite generating set, <InlineMath>G</InlineMath> is <strong>finitely generated</strong>.
      </Callout>

      <h3>Examples</h3>

      <p><strong>Example 1:</strong> <InlineMath>\mathbb{'{'}Z{'}'} = \langle 1 \rangle = \langle -1 \rangle = \langle 2, 3 \rangle</InlineMath></p>
      <p>
        The last equality holds because <InlineMath>\gcd(2, 3) = 1</InlineMath>, so <InlineMath>1 = 3 - 2 \in \langle 2, 3 \rangle</InlineMath>.
      </p>

      <p><strong>Example 2:</strong> <InlineMath>S_n = \langle (1\,2), (1\,2\,3\,\ldots\,n) \rangle</InlineMath></p>
      <p>
        The transposition and the <InlineMath>n</InlineMath>-cycle generate all of <InlineMath>S_n</InlineMath>.
      </p>

      <p><strong>Example 3:</strong> <InlineMath>{`S_n = \\langle (1\\,2), (2\\,3), \\ldots, (n{-}1\\,n) \\rangle`}</InlineMath></p>
      <p>
        Adjacent transpositions also generate <InlineMath>S_n</InlineMath>.
      </p>

      <p><strong>Example 4:</strong> <InlineMath>{`D_{2n} = \\langle r, s \\rangle`}</InlineMath></p>
      <p>
        Where <InlineMath>r</InlineMath> is rotation by <InlineMath>2\pi/n</InlineMath> and <InlineMath>s</InlineMath> is a reflection.
      </p>

      <h3>Properties</h3>
      <ul className="list-disc list-inside text-dark-300 mb-6 space-y-2">
        <li><InlineMath>S \subseteq T \Rightarrow \langle S \rangle \le \langle T \rangle</InlineMath></li>
        <li><InlineMath>\langle \langle S \rangle \rangle = \langle S \rangle</InlineMath></li>
        <li><InlineMath>\langle S \cup T \rangle = \langle \langle S \rangle \cup \langle T \rangle \rangle</InlineMath></li>
        <li>If <InlineMath>G</InlineMath> is abelian, <InlineMath>\langle S \rangle = \{'{'}s_1^{'{'}a_1{'}'} \cdots s_k^{'{'}a_k{'}'} : s_i \in S, a_i \in \mathbb{'{'}Z{'}'}\{'}'}</InlineMath></li>
      </ul>

      <h3>Join of Subgroups</h3>
      <p>
        For subgroups <InlineMath>H, K \le G</InlineMath>, the <strong>join</strong> (or <strong>subgroup generated by H and K</strong>) is:
      </p>
      <MathBlock>\langle H, K \rangle = \langle H \cup K \rangle</MathBlock>

      <p>
        This is generally larger than the set product <InlineMath>HK</InlineMath>, unless <InlineMath>HK = KH</InlineMath>.
      </p>

      <h3>Finitely Generated Groups</h3>
      <Callout type="info">
        <strong>Examples:</strong>
        <ul className="list-disc list-inside mt-2 space-y-1">
          <li>All finite groups are finitely generated</li>
          <li><InlineMath>\mathbb{'{'}Z{'}'}</InlineMath> is finitely generated (by 1)</li>
          <li><InlineMath>\mathbb{'{'}Q{'}'}</InlineMath> is NOT finitely generated</li>
        </ul>
      </Callout>

      <p>
        <strong>Why isn't Q finitely generated?</strong> If <InlineMath>\mathbb{'{'}Q{'}'} = \langle \frac{'{'}a_1{'}'}{'{'}b_1{'}'}, \ldots, \frac{'{'}a_n{'}'}{'{'}b_n{'}'} \rangle</InlineMath>,
        all elements would have denominators dividing <InlineMath>b_1 \cdots b_n</InlineMath>, but <InlineMath>\frac{'{'}1{'}'}{'{'}b_1 \cdots b_n + 1{'}'} \in \mathbb{'{'}Q{'}'}</InlineMath>.
      </p>

      <h3>The Commutator Subgroup</h3>
      <p>
        An important example of a generated subgroup:
      </p>
      <Callout type="info">
        <strong>Definition:</strong> The <strong>commutator subgroup</strong> (or <strong>derived subgroup</strong>) of <InlineMath>G</InlineMath> is:
        <MathBlock>G' = [G, G] = \langle [a, b] : a, b \in G \rangle</MathBlock>
        where <InlineMath>[a, b] = aba^{'{-1}'}b^{'{-1}'}</InlineMath> is the commutator of <InlineMath>a</InlineMath> and <InlineMath>b</InlineMath>.
      </Callout>

      <p>
        <InlineMath>G'</InlineMath> measures how "non-abelian" <InlineMath>G</InlineMath> is: <InlineMath>G</InlineMath> is abelian if and only if <InlineMath>G' = \{'{'}e\{'}'}</InlineMath>.
      </p>

      <Callout type="success">
        <strong>Summary:</strong> The subgroup generated by a subset <InlineMath>S</InlineMath> is the smallest subgroup containing <InlineMath>S</InlineMath>,
        consisting of all finite products of elements of <InlineMath>S</InlineMath> and their inverses.
        Generating sets provide compact descriptions of groups. A group is finitely generated if it has
        a finite generating set.
      </Callout>
    </LessonLayout>
  );
}
