import { LessonLayout } from '@/components/layout/LessonLayout';
import { Definition, Theorem, Example } from '@/components/common/ContentBlocks';
import { Callout } from '@/components/common/Callout';
import { MathBlock, InlineMath } from '@/components/common/MathBlock';

export default function Section58() {
  return (
    <LessonLayout sectionId={58}>
      <h2>Tensor Algebras: Symmetric and Exterior</h2>

      <p>
        The symmetric and exterior algebras are fundamental constructions built from a vector space.
        They generalize the notions of symmetric and antisymmetric functions and provide the
        algebraic framework for differential forms, multilinear algebra, and much of modern geometry.
      </p>

      <h3>The Tensor Algebra</h3>

      <Definition title="Tensor Algebra">
        <p>
          For a vector space <InlineMath>V</InlineMath> over <InlineMath>F</InlineMath>, define the
          <strong>tensor powers</strong>:
        </p>
        <MathBlock>
          {'T^0(V) = F, \\quad T^1(V) = V, \\quad T^k(V) = V \\otimes V \\otimes \\cdots \\otimes V \\text{ (}k\\text{ times)}'}
        </MathBlock>
        <p className="mt-2">
          The <strong>tensor algebra</strong> is the direct sum with multiplication by tensor product:
        </p>
        <MathBlock>
          {'T(V) = \\bigoplus_{k=0}^{\\infty} T^k(V) = F \\oplus V \\oplus (V \\otimes V) \\oplus \\cdots'}
        </MathBlock>
      </Definition>

      <Theorem title="Universal Property of Tensor Algebra"
        proof={
          <>
            <p>
              Given <InlineMath>{'f: V \\to A'}</InlineMath>, extend to <InlineMath>T(V)</InlineMath> by
              <InlineMath>{'\\phi(v_1 \\otimes \\cdots \\otimes v_k) = f(v_1) \\cdots f(v_k)'}</InlineMath>
              and linearity.
            </p>
          </>
        }
      >
        <p>
          For any algebra <InlineMath>A</InlineMath> and linear map <InlineMath>{'f: V \\to A'}</InlineMath>,
          there exists a unique algebra homomorphism <InlineMath>{'\\phi: T(V) \\to A'}</InlineMath> extending <InlineMath>f</InlineMath>.
        </p>
      </Theorem>

      <h3>The Symmetric Algebra</h3>

      <Definition title="Symmetric Algebra">
        <p>
          The <strong>symmetric algebra</strong> <InlineMath>{'S(V)'}</InlineMath> (or <InlineMath>{'\\text{Sym}(V)'}</InlineMath>)
          is the quotient of <InlineMath>{'T(V)'}</InlineMath> by the ideal generated by all
          <InlineMath>{'v \\otimes w - w \\otimes v'}</InlineMath>:
        </p>
        <MathBlock>
          {'S(V) = T(V) / (v \\otimes w - w \\otimes v : v, w \\in V)'}
        </MathBlock>
        <p className="mt-2">
          It is a commutative graded algebra: <InlineMath>{'S(V) = \\bigoplus_{k=0}^{\\infty} S^k(V)'}</InlineMath>.
        </p>
      </Definition>

      <Theorem title="Symmetric Algebra is Polynomial Ring"
        proof={
          <>
            <p>
              If <InlineMath>{'\\{e_1, \\ldots, e_n\\}'}</InlineMath> is a basis for <InlineMath>V</InlineMath>,
              then <InlineMath>{'S(V)'}</InlineMath> is generated by <InlineMath>{'e_1, \\ldots, e_n'}</InlineMath>
              with the commutation relations. This is precisely <InlineMath>{'F[e_1, \\ldots, e_n]'}</InlineMath>.
            </p>
          </>
        }
      >
        <p>
          If <InlineMath>{'\\dim V = n'}</InlineMath>, then
        </p>
        <MathBlock>
          {'S(V) \\cong F[x_1, x_2, \\ldots, x_n]'}
        </MathBlock>
        <p className="mt-2">
          The symmetric power <InlineMath>{'S^k(V)'}</InlineMath> corresponds to homogeneous polynomials of degree <InlineMath>k</InlineMath>.
        </p>
      </Theorem>

      <Example title="Symmetric Tensors">
        <p>
          In <InlineMath>{'S^2(V)'}</InlineMath>, the product of <InlineMath>{'v, w \\in V'}</InlineMath> is written
          <InlineMath>{'v \\cdot w'}</InlineMath> (or just <InlineMath>vw</InlineMath>), and <InlineMath>{'vw = wv'}</InlineMath>.
        </p>
        <p className="mt-2">
          <InlineMath>{'\\dim S^2(\\mathbb{R}^n) = \\binom{n+1}{2}'}</InlineMath> (quadratic forms have this many independent coefficients).
        </p>
      </Example>

      <h3>The Exterior Algebra</h3>

      <Definition title="Exterior Algebra">
        <p>
          The <strong>exterior algebra</strong> (or <strong>Grassmann algebra</strong>)
          <InlineMath>{'\\Lambda(V)'}</InlineMath> (or <InlineMath>{'\\bigwedge V'}</InlineMath>) is the quotient:
        </p>
        <MathBlock>
          {'\\Lambda(V) = T(V) / (v \\otimes v : v \\in V)'}
        </MathBlock>
        <p className="mt-2">
          The product is the <strong>wedge product</strong> <InlineMath>{'\\wedge'}</InlineMath>. It is anticommutative:
        </p>
        <MathBlock>
          {'v \\wedge w = -w \\wedge v'}
        </MathBlock>
      </Definition>

      <Theorem title="Properties of Wedge Product"
        proof={
          <>
            <p>
              From <InlineMath>{'(v + w) \\wedge (v + w) = 0'}</InlineMath>, expand to get
              <InlineMath>{'v \\wedge v + v \\wedge w + w \\wedge v + w \\wedge w = 0'}</InlineMath>.
              Since <InlineMath>{'v \\wedge v = w \\wedge w = 0'}</InlineMath>, we get <InlineMath>{'v \\wedge w = -w \\wedge v'}</InlineMath>.
            </p>
          </>
        }
      >
        <ul className="list-disc list-inside mt-2">
          <li><InlineMath>{'v \\wedge v = 0'}</InlineMath> for all <InlineMath>{'v \\in V'}</InlineMath></li>
          <li><InlineMath>{'v \\wedge w = -w \\wedge v'}</InlineMath> (anticommutativity)</li>
          <li>If <InlineMath>{'\\{v_1, \\ldots, v_k\\}'}</InlineMath> is linearly dependent, then <InlineMath>{'v_1 \\wedge \\cdots \\wedge v_k = 0'}</InlineMath></li>
        </ul>
      </Theorem>

      <Definition title="Exterior Powers">
        <p>
          The <InlineMath>k</InlineMath>-th <strong>exterior power</strong> <InlineMath>{'\\Lambda^k(V)'}</InlineMath>
          is the span of <InlineMath>k</InlineMath>-fold wedge products:
        </p>
        <MathBlock>
          {'\\Lambda^k(V) = \\text{span}\\{v_1 \\wedge v_2 \\wedge \\cdots \\wedge v_k : v_i \\in V\\}'}
        </MathBlock>
      </Definition>

      <Theorem title="Dimension of Exterior Powers"
        proof={
          <>
            <p>
              If <InlineMath>{'\\{e_1, \\ldots, e_n\\}'}</InlineMath> is a basis for <InlineMath>V</InlineMath>,
              then <InlineMath>{'\\{e_{i_1} \\wedge \\cdots \\wedge e_{i_k} : 1 \\leq i_1 < \\cdots < i_k \\leq n\\}'}</InlineMath>
              is a basis for <InlineMath>{'\\Lambda^k(V)'}</InlineMath>.
            </p>
          </>
        }
      >
        <p>
          If <InlineMath>{'\\dim V = n'}</InlineMath>:
        </p>
        <MathBlock>
          {'\\dim \\Lambda^k(V) = \\binom{n}{k}'}
        </MathBlock>
        <p className="mt-2">
          In particular:
        </p>
        <ul className="list-disc list-inside mt-2">
          <li><InlineMath>{'\\Lambda^0(V) = F'}</InlineMath></li>
          <li><InlineMath>{'\\Lambda^1(V) = V'}</InlineMath></li>
          <li><InlineMath>{'\\Lambda^n(V)'}</InlineMath> is 1-dimensional</li>
          <li><InlineMath>{'\\Lambda^k(V) = 0'}</InlineMath> for <InlineMath>{'k > n'}</InlineMath></li>
        </ul>
      </Theorem>

      <Example title="Exterior Algebra of R^3">
        <p>
          For <InlineMath>{'V = \\mathbb{R}^3'}</InlineMath> with basis <InlineMath>{'\\{e_1, e_2, e_3\\}'}</InlineMath>:
        </p>
        <ul className="list-disc list-inside mt-2">
          <li><InlineMath>{'\\Lambda^0(V) = \\mathbb{R}'}</InlineMath>, basis: <InlineMath>{'\\{1\\}'}</InlineMath></li>
          <li><InlineMath>{'\\Lambda^1(V) = V'}</InlineMath>, basis: <InlineMath>{'\\{e_1, e_2, e_3\\}'}</InlineMath></li>
          <li><InlineMath>{'\\Lambda^2(V)'}</InlineMath>, basis: <InlineMath>{'\\{e_1 \\wedge e_2, e_1 \\wedge e_3, e_2 \\wedge e_3\\}'}</InlineMath></li>
          <li><InlineMath>{'\\Lambda^3(V)'}</InlineMath>, basis: <InlineMath>{'\\{e_1 \\wedge e_2 \\wedge e_3\\}'}</InlineMath></li>
        </ul>
        <p className="mt-2">
          Total dimension: <InlineMath>{'1 + 3 + 3 + 1 = 8 = 2^3'}</InlineMath>.
        </p>
      </Example>

      <h3>Connections to Determinants and Geometry</h3>

      <Theorem title="Top Exterior Power and Determinants"
        proof={
          <>
            <p>
              <InlineMath>{'\\Lambda^n(V)'}</InlineMath> is 1-dimensional. A linear map <InlineMath>{'T: V \\to V'}</InlineMath>
              induces <InlineMath>{'\\Lambda^n T: \\Lambda^n V \\to \\Lambda^n V'}</InlineMath>, which is
              multiplication by a scalar—precisely <InlineMath>{'\\det T'}</InlineMath>.
            </p>
          </>
        }
      >
        <p>
          If <InlineMath>{'\\dim V = n'}</InlineMath> and <InlineMath>{'T: V \\to V'}</InlineMath> is linear, then
          for any <InlineMath>{'v_1, \\ldots, v_n \\in V'}</InlineMath>:
        </p>
        <MathBlock>
          {'T(v_1) \\wedge \\cdots \\wedge T(v_n) = (\\det T)(v_1 \\wedge \\cdots \\wedge v_n)'}
        </MathBlock>
      </Theorem>

      <Theorem title="Criterion for Linear Independence"
        proof={
          <>
            <p>
              If linearly dependent, one vector is a combination of others; the wedge product is zero
              by multilinearity and the alternating property.
            </p>
            <p className="mt-2">
              If independent, extend to a basis and compute explicitly.
            </p>
          </>
        }
      >
        <p>
          Vectors <InlineMath>{'v_1, \\ldots, v_k \\in V'}</InlineMath> are linearly independent if and only if
          <InlineMath>{'v_1 \\wedge v_2 \\wedge \\cdots \\wedge v_k \\neq 0'}</InlineMath>.
        </p>
      </Theorem>

      <Callout type="info">
        <strong>Differential Forms:</strong> In differential geometry, the exterior algebra of the
        cotangent space at a point gives differential forms. The wedge product corresponds to the
        exterior product of forms, and <InlineMath>{'\\Lambda^k(T_p^* M)'}</InlineMath> gives <InlineMath>k</InlineMath>-forms.
        The exterior derivative <InlineMath>d</InlineMath> connects to de Rham cohomology.
      </Callout>

      <Callout type="success">
        <strong>Summary:</strong> The tensor algebra <InlineMath>{'T(V)'}</InlineMath> is the universal
        associative algebra containing <InlineMath>V</InlineMath>. The symmetric algebra <InlineMath>{'S(V)'}</InlineMath>
        quotients by commutativity relations and equals the polynomial ring. The exterior algebra
        <InlineMath>{'\\Lambda(V)'}</InlineMath> quotients by <InlineMath>{'v \\wedge v = 0'}</InlineMath>,
        yielding anticommutative products. These algebras encode multilinear data and connect to
        determinants, differential forms, and algebraic topology.
      </Callout>
    </LessonLayout>
  );
}
