import { LessonLayout } from '@/components/layout/LessonLayout';
import { Callout } from '@/components/common/Callout';
import { MathBlock, InlineMath } from '@/components/common/MathBlock';

export default function Section10() {
  return (
    <LessonLayout sectionId={10}>
      <h2>Subgroups: Definition and Examples</h2>
      <p>
        A <strong>subgroup</strong> is a subset of a group that is itself a group under the same operation.
        Understanding subgroups is essential for analyzing the structure of groups.
      </p>

      <h3>Definition</h3>
      <Callout type="info">
        <strong>Definition:</strong> A subset <InlineMath>H</InlineMath> of a group <InlineMath>G</InlineMath> is a <strong>subgroup</strong> of <InlineMath>G</InlineMath>,
        written <InlineMath>H \le G</InlineMath> or <InlineMath>H {'<'} G</InlineMath>, if <InlineMath>H</InlineMath> is a group under the operation of <InlineMath>G</InlineMath>.
        If <InlineMath>H \neq G</InlineMath>, we say <InlineMath>H</InlineMath> is a <strong>proper subgroup</strong>.
      </Callout>

      <h3>The Subgroup Test</h3>
      <Callout type="info">
        <strong>Theorem (Two-Step Subgroup Test):</strong> A non-empty subset <InlineMath>H \subseteq G</InlineMath> is a subgroup if and only if:
        <ol className="list-decimal list-inside mt-2 space-y-1">
          <li><InlineMath>a, b \in H \Rightarrow ab \in H</InlineMath> (closure)</li>
          <li><InlineMath>a \in H \Rightarrow a^{'{-1}'} \in H</InlineMath> (inverses)</li>
        </ol>
      </Callout>

      <Callout type="info">
        <strong>Theorem (One-Step Subgroup Test):</strong> A non-empty subset <InlineMath>H \subseteq G</InlineMath> is a subgroup if and only if:
        <MathBlock>a, b \in H \Rightarrow ab^{'{-1}'} \in H</MathBlock>
      </Callout>

      <h3>Trivial Subgroups</h3>
      <p>Every group <InlineMath>G</InlineMath> has at least two subgroups:</p>
      <ul className="list-disc list-inside text-dark-300 mb-6 space-y-2">
        <li><InlineMath>\{'{'}e\{'}'}</InlineMath> — the <strong>trivial subgroup</strong></li>
        <li><InlineMath>G</InlineMath> itself — the <strong>improper subgroup</strong></li>
      </ul>
      <p>All other subgroups are called <strong>proper non-trivial subgroups</strong>.</p>

      <h3>Examples</h3>

      <p><strong>Example 1:</strong> Subgroups of <InlineMath>(\mathbb{'{'}Z{'}'}, +)</InlineMath></p>
      <p>
        The subgroups of <InlineMath>\mathbb{'{'}Z{'}'}</InlineMath> are exactly <InlineMath>n\mathbb{'{'}Z{'}'} = \{'{'}nk : k \in \mathbb{'{'}Z{'}'}\{'}'}</InlineMath> for <InlineMath>n \geq 0</InlineMath>.
        So the subgroups are <InlineMath>\{'{'}0\{'}'}, \mathbb{'{'}Z{'}'}, 2\mathbb{'{'}Z{'}'}, 3\mathbb{'{'}Z{'}'}, \ldots</InlineMath>
      </p>

      <p><strong>Example 2:</strong> Subgroups of <InlineMath>S_3</InlineMath></p>
      <ul className="list-disc list-inside text-dark-300 mb-4 space-y-1">
        <li><InlineMath>\{'{'}e\{'}'}</InlineMath></li>
        <li><InlineMath>\{'{'}e, (1\,2)\{'}'}, \{'{'}e, (1\,3)\{'}'}, \{'{'}e, (2\,3)\{'}'}</InlineMath> — cyclic subgroups of order 2</li>
        <li><InlineMath>\{'{'}e, (1\,2\,3), (1\,3\,2)\{'}'} = A_3</InlineMath> — cyclic subgroup of order 3</li>
        <li><InlineMath>S_3</InlineMath></li>
      </ul>

      <p><strong>Example 3:</strong> Subgroups of <InlineMath>\mathbb{'{'}Z{'}'}/12\mathbb{'{'}Z{'}'}</InlineMath></p>
      <p>The subgroups are generated by divisors of 12:</p>
      <ul className="list-disc list-inside text-dark-300 mb-4 space-y-1">
        <li><InlineMath>\langle \bar{'{'}0{'}'} \rangle = \{'{'}\bar{'{'}0{'}'}\{'}'}</InlineMath> — order 1</li>
        <li><InlineMath>\langle \bar{'{'}6{'}'} \rangle = \{'{'}\bar{'{'}0{'}'}, \bar{'{'}6{'}'}\{'}'}</InlineMath> — order 2</li>
        <li><InlineMath>\langle \bar{'{'}4{'}'} \rangle = \{'{'}\bar{'{'}0{'}'}, \bar{'{'}4{'}'}, \bar{'{'}8{'}'}\{'}'}</InlineMath> — order 3</li>
        <li><InlineMath>\langle \bar{'{'}3{'}'} \rangle = \{'{'}\bar{'{'}0{'}'}, \bar{'{'}3{'}'}, \bar{'{'}6{'}'}, \bar{'{'}9{'}'}\{'}'}</InlineMath> — order 4</li>
        <li><InlineMath>\langle \bar{'{'}2{'}'} \rangle</InlineMath> — order 6</li>
        <li><InlineMath>\langle \bar{'{'}1{'}'} \rangle = \mathbb{'{'}Z{'}'}/12\mathbb{'{'}Z{'}'}</InlineMath> — order 12</li>
      </ul>

      <h3>Intersection of Subgroups</h3>
      <Callout type="info">
        <strong>Theorem:</strong> The intersection of any collection of subgroups of <InlineMath>G</InlineMath> is a subgroup of <InlineMath>G</InlineMath>.
      </Callout>

      <p>
        <strong>Proof:</strong> Let <InlineMath>\{'{'}H_i\{'}'}</InlineMath> be subgroups and <InlineMath>H = \bigcap H_i</InlineMath>. Then <InlineMath>e \in H</InlineMath> (so <InlineMath>H \neq \emptyset</InlineMath>).
        If <InlineMath>a, b \in H</InlineMath>, then <InlineMath>a, b \in H_i</InlineMath> for all <InlineMath>i</InlineMath>, so <InlineMath>ab^{'{-1}'} \in H_i</InlineMath> for all <InlineMath>i</InlineMath>, hence <InlineMath>ab^{'{-1}'} \in H</InlineMath>.
      </p>

      <Callout type="warning">
        <strong>Warning:</strong> The union of two subgroups is generally NOT a subgroup. For example,
        in <InlineMath>\mathbb{'{'}Z{'}'}</InlineMath>, <InlineMath>2\mathbb{'{'}Z{'}'} \cup 3\mathbb{'{'}Z{'}'}</InlineMath> is not a subgroup since <InlineMath>2 + 3 = 5 \notin 2\mathbb{'{'}Z{'}'} \cup 3\mathbb{'{'}Z{'}'}</InlineMath>.
      </Callout>

      <h3>Products of Subsets</h3>
      <p>
        For subsets <InlineMath>A, B \subseteq G</InlineMath>, define the <strong>product</strong>:
      </p>
      <MathBlock>AB = \{'{'}ab : a \in A, b \in B\{'}'}</MathBlock>

      <Callout type="info">
        <strong>Theorem:</strong> If <InlineMath>H, K \le G</InlineMath>, then <InlineMath>HK</InlineMath> is a subgroup if and only if <InlineMath>HK = KH</InlineMath>.
      </Callout>

      <Callout type="success">
        <strong>Summary:</strong> Subgroups are subsets that are groups under the inherited operation.
        The subgroup test provides efficient criteria for verification. Intersections of subgroups are subgroups,
        but unions generally are not. The subgroups of <InlineMath>\mathbb{'{'}Z{'}'}</InlineMath> are precisely <InlineMath>n\mathbb{'{'}Z{'}'}</InlineMath> for <InlineMath>n \geq 0</InlineMath>.
      </Callout>
    </LessonLayout>
  );
}
