import type { QuizQuestion } from './types';

export const section08Questions: QuizQuestion[] = [
  {
    id: 1,
    type: 'multiple-choice',
    question: 'The order of a finite field must be:',
    options: [
      'A power of 2',
      'Any positive integer',
      'A prime number only',
      '$p^n$ for some prime $p$ and positive integer $n$'
    ],
    correctIndex: 3,
    difficulty: 'medium',
    explanation: 'A finite field has order $p^n$ where $p$ is prime and $n$ is a positive integer. Fields of this order are denoted $GF(p^n)$ or $\\mathbb{F}_{p^n}$.',
  },
  {
    id: 2,
    type: 'multiple-choice',
    question: 'A polynomial $f(X) \\in F[X]$ is irreducible if:',
    options: [
      'It has no roots',
      'Its degree is prime',
      'It cannot be factored into polynomials of lower positive degree',
      'Its coefficients are all 1',
    ],
    correctIndex: 2,
    difficulty: 'medium',
    explanation: 'A polynomial is irreducible if whenever $f(X) = g(X)h(X)$, either $g(X)$ or $h(X)$ has degree 0 (is a constant). It cannot be factored into smaller degree polynomials.',
  },
  {
    id: 3,
    type: 'multiple-choice',
    question: 'If $f(X)$ is irreducible over field $F$, then $F[X]/\\langle f(X) \\rangle$ is:',
    options: [
      'Only a ring',
      'A field',
      'Not a ring',
      'The same as $F$'
    ],
    correctIndex: 1,
    difficulty: 'medium',
    explanation: 'Quotienting a polynomial ring by an ideal generated by an irreducible polynomial produces a field. This is the standard construction for finite field extensions.',
  },
  {
    id: 4,
    type: 'numeric',
    question: 'How many elements does $GF(8)$ have?',
    correctAnswer: 8,
    numericRange: { min: 1, max: 100, precision: 0 },
    difficulty: 'easy',
    explanation: '$GF(8)$ denotes the Galois field of 8 elements. Note that $8 = 2^3$, so this is the finite field of order $2^3$.',
  },
  {
    id: 5,
    type: 'multiple-choice',
    question: 'In any finite field $F = GF(p^n)$, the multiplicative group $F^*$ of non-zero elements is:',
    options: [
      'Cyclic',
      'Always non-cyclic',
      'Not a group',
      'Isomorphic to $\\mathbb{Z}_p
    correctIndex: 0,
    difficulty: 'medium',
    explanation: 'A fundamental theorem states that the multiplicative group of any finite field is cyclic. A generator of this group is called a primitive element.',
  },
    ],
    correctIndex: 2,
    difficulty: 'medium',
    explanation: 'A fundamental theorem states that the multiplicative group of any finite field is cyclic. A generator of this group is called a primitive element.',
  },
  {
    id: 6,
    type: 'numeric',
    question: 'In $GF(p^n)$, how many primitive elements are there?',
    correctAnswer: 8,
    numericRange: { min: 1, max: 100, precision: 0 },
    difficulty: 'hard',
    explanation: 'The number of primitive elements in $GF(p^n)$ is $\\phi(p^n - 1)$ where $\\phi$ is Euler\'s totient function. For $GF(16) = GF(2^4)$, we have $\\phi(15) = \\phi(3 \\cdot 5) = 2 \\cdot 4 = 8$.',
  },
];
