import type { QuizQuestion } from './types';

export const section15Questions: QuizQuestion[] = [
  {
    id: 1,
    type: 'multiple-choice',
    question: 'A code $C$ is called cyclic if for every codeword $(c_0, c_1, \\ldots, c_{n-1}) \\in C$, which of the following is also in $C$?',
    options: [
      '$(c_1, c_0, c_2, \\ldots, c_{n-1})$',
      '$(c_{n-1}, c_0, c_1, \\ldots, c_{n-2})$',
      '$(c_0, c_0, c_1, \\ldots, c_{n-1})$',
      '$(c_{n-1}, c_{n-2}, \\ldots, c_1, c_0)$'
    ],
    correctIndex: 1,
    difficulty: 'easy',
    explanation: 'A cyclic code is closed under cyclic shifts. The cyclic shift of $(c_0, c_1, \\ldots, c_{n-1})$ is $(c_{n-1}, c_0, c_1, \\ldots, c_{n-2})$, where the last coordinate moves to the first position.',
  },
  {
    id: 2,
    type: 'multiple-choice',
    question: 'In the polynomial representation of cyclic codes, codewords are represented as polynomials in which quotient ring?',
    options: [
      '$\\mathbb{F}_q[x]$',
      '$\\mathbb{F}_q[x]/(x^n + 1)$',
      '$\\mathbb{F}_q[x]/(x^n - 1)$',
      '$\\mathbb{F}_q[x]/(x^{n-1} - 1)$'
    ],
    correctIndex: 2,
    difficulty: 'medium',
    explanation: 'Cyclic codes of length $n$ over $\\mathbb{F}_q$ correspond to ideals in the quotient ring $\\mathbb{F}_q[x]/(x^n - 1)$. This ring structure captures the cyclic shift operation perfectly.',
  },
  {
    id: 3,
    type: 'multiple-choice',
    question: 'Every ideal in $\\mathbb{F}_q[x]/(x^n - 1)$ is generated by a unique monic polynomial $g(x)$ that divides $x^n - 1$. This polynomial is called:',
    options: [
      'The check polynomial',
      'The parity polynomial',
      'The generator polynomial',
      'The minimal polynomial'
    ],
    correctIndex: 2,
    difficulty: 'easy',
    explanation: 'The generator polynomial $g(x)$ is the unique monic polynomial of lowest degree that generates the cyclic code as an ideal. It must divide $x^n - 1$.',
  },
  {
    id: 4,
    type: 'numeric',
    question: 'If a cyclic code of length $n = 7$ has generator polynomial $g(x) = x^3 + x + 1$, what is the dimension $k$ of the code?',
    correctAnswer: 4,
    numericRange: { min: 0, max: 7, precision: 0 },
    difficulty: 'medium',
    explanation: 'The dimension of a cyclic code is $k = n - \\deg(g(x))$. Here, $k = 7 - 3 = 4$.',
  },
  {
    id: 5,
    type: 'multiple-choice',
    question: 'If $c(x)$ is a codeword polynomial in a cyclic code, what polynomial operation corresponds to a cyclic shift of the codeword?',
    options: [
      'Multiplying by $x$ in $\\mathbb{F}_q[x]/(x^n - 1)$',
      'Adding $x$ in $\\mathbb{F}_q[x]/(x^n - 1)$',
      'Dividing by $x$ in $\\mathbb{F}_q[x]/(x^n - 1)$',
      'Taking the derivative of $c(x)$'
    ],
    correctIndex: 0,
    difficulty: 'medium',
    explanation: 'Multiplying by $x$ in the quotient ring $\\mathbb{F}_q[x]/(x^n - 1)$ shifts all coefficients up by one position, with $x^n \\equiv 1$ wrapping the leading coefficient to the constant term.',
  },
  {
    id: 6,
    type: 'numeric',
    question: 'How many distinct cyclic codes of length $7$ exist over $\\mathbb{F}_2$, given that $x^7 - 1 = (x+1)(x^3+x+1)(x^3+x^2+1)$ over $\\mathbb{F}_2$?',
    correctAnswer: 8,
    numericRange: { min: 1, max: 100, precision: 0 },
    difficulty: 'hard',
    explanation: 'Each cyclic code corresponds to a divisor of $x^7 - 1$. With three irreducible factors, there are $2^3 = 8$ divisors (including $1$ and $x^7 - 1$ itself), hence $8$ distinct cyclic codes.',
  },
];
