import type { QuizQuestion } from './types';

export const section11Questions: QuizQuestion[] = [
  {
    id: 1,
    type: 'multiple-choice',
    question: 'A linear code is:',
    options: [
      'A subspace of the vector space $V(n, q)$',
      'Any subset of $V(n, q)$',
      'A code with even weight code words only',
      'A code generated by a polynomial'
    ],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: 'A linear code is defined as a subspace of the vector space $V(n, q)$ of all $n$-tuples over the field $GF(q)$. Being a subspace implies closure under addition and scalar multiplication.',
  },
  {
    id: 2,
    type: 'multiple-choice',
    question: 'The Singleton bound states that for a linear $[n, k, d]$ code:',
    options: [
      '$d \\leq n - k + 1$',
      '$d \\geq n - k + 1$',
      '$d = n - k$',
      '$k \\leq d$'
    ],
    correctIndex: 0,
    difficulty: 'medium',
    explanation: 'The Singleton bound gives an upper bound on the minimum distance: $d \\leq n - k + 1$. Codes achieving this bound are called MDS (Maximum Distance Separable) codes.',
  },
  {
    id: 3,
    type: 'multiple-choice',
    question: 'Two codes of length $n$ are equivalent if:',
    options: [
      'One can be obtained from the other by permuting coordinate positions',
      'They have the same number of code words',
      'They have the same minimum distance',
      'Their generator matrices are identical'
    ],
    correctIndex: 0,
    difficulty: 'medium',
    explanation: 'Two codes are equivalent if there exists a permutation of the $n$ coordinate positions that maps one code to the other. Equivalent codes have the same weight distribution and minimum distance.',
  },
  {
    id: 4,
    type: 'multiple-choice',
    question: 'For a linear $[n, k, d]$ code with parity check matrix $\\mathbf{H} = (\\mathbf{A} \\mid \\mathbf{I}_{n-k})$, a generator matrix is:',
    options: [
      '$\\mathbf{G} = (\\mathbf{I}_k \\mid -\\mathbf{A}^t)$',
      '$\\mathbf{G} = (\\mathbf{A} \\mid \\mathbf{I}_k)$',
      '$\\mathbf{G} = \\mathbf{H}^t$',
      '$\\mathbf{G} = \\mathbf{H}$'
    ],
    correctIndex: 0,
    difficulty: 'medium',
    explanation: 'When the parity check matrix is $\\mathbf{H} = (\\mathbf{A} \\mid \\mathbf{I}_{n-k})$, the corresponding generator matrix in systematic form is $\\mathbf{G} = (\\mathbf{I}_k \\mid -\\mathbf{A}^t)$.',
  },
  {
    id: 5,
    type: 'multiple-choice',
    question: 'Which of the following is always a linear code?',
    options: [
      'A polynomial code over a field',
      'A code with exactly 5 code words',
      'Any code with minimum distance 3',
      'A code where all code words have weight 4'
    ],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: 'Polynomial codes over fields are always linear codes. A code with 5 code words cannot be linear (the number of code words must be a power of $q$). The other properties do not guarantee linearity.',
  },
  {
    id: 6,
    type: 'numeric',
    question: 'A linear $[7, 4]$ code over $GF(2)$ has how many code words?',
    correctAnswer: 16,
    numericRange: { min: 1, max: 128, precision: 0 },
    difficulty: 'easy',
    explanation: 'A linear $[n, k]$ code over $GF(q)$ has $q^k$ code words. For $q = 2$ and $k = 4$, there are $2^4 = 16$ code words.',
  },
];
