import type { QuizQuestion } from './types';

export const section04Questions: QuizQuestion[] = [
  {
    id: 1,
    type: 'multiple-choice',
    question: 'In a polynomial code with generator polynomial $g(X)$, the code word corresponding to message polynomial $a(X)$ is:',
    options: [
      '$b(X) = a(X) \\cdot g(X)$',
      '$b(X) = a(X) + g(X)$',
      '$b(X) = a(X) / g(X)$',
      '$b(X) = a(X) - g(X)$'
    ],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: 'In a polynomial code, encoding is done by polynomial multiplication. The code polynomial is $b(X) = a(X) \\cdot g(X)$.',
  },
  {
    id: 2,
    type: 'multiple-choice',
    question: 'A polynomial with coefficients in $\\mathbb{B}$ is divisible by $1 + X$ if and only if:',
    options: [
      'It has an even number of terms',
      'It has an odd number of terms',
      'Its degree is even',
      'Its constant term is 0'
    ],
    correctIndex: 0,
    difficulty: 'medium',
    explanation: 'A binary polynomial $f(X)$ is divisible by $1 + X$ if and only if it has an even number of non-zero terms. This is because $f(1) = 0$ in $\\mathbb{B}$ when the sum of coefficients is 0 (even count).',
  },
  {
    id: 3,
    type: 'multiple-choice',
    question: 'In a polynomial code generated by $g(X) = (1+X)h(X)$, every code word has:',
    options: [
      'Even weight',
      'Odd weight',
      'Weight divisible by 3',
      'Weight equal to $\\deg g(X)$'
    ],
    correctIndex: 0,
    difficulty: 'medium',
    explanation: 'When $(1+X)$ divides the generator polynomial $g(X)$, every code polynomial is divisible by $(1+X)$, which means it has an even number of terms, hence even weight.',
  },
  {
    id: 4,
    type: 'numeric',
    question: 'For a polynomial $(m, n)$-code with generator polynomial of degree $k$, what is $n$?',
    correctAnswer: 6,
    numericRange: { min: 1, max: 20, precision: 0 },
    difficulty: 'medium',
    explanation: 'In a polynomial code, if the message length is $m$ and the generator polynomial has degree $k$, then the code word length is $n = m + k$. For example, $m = 3, k = 3$ gives $n = 6$.',
  },
  {
    id: 5,
    type: 'multiple-choice',
    question: 'An error vector $\\mathbf{e}$ goes undetected in a polynomial code if and only if:',
    options: [
      'The error polynomial $e(X)$ is a multiple of $g(X)$',
      'The error polynomial $e(X)$ has odd weight',
      'The error polynomial has degree less than $\\deg g(X)$',
      'The error is in the first position'
    ],
    correctIndex: 0,
    difficulty: 'medium',
    explanation: 'In a polynomial code, an error is undetected precisely when the error vector is itself a code word. This happens when $e(X)$ is divisible by the generator polynomial $g(X)$.',
  },
  {
    id: 6,
    type: 'multiple-choice',
    question: 'The polynomial code generated by $g(X) = 1 + X + X^3$ with message length 3 has code length:',
    options: [
      '6',
      '3',
      '4',
      '7'
    ],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: 'For a polynomial code, code length $n = m + k$ where $m$ is message length and $k$ is the degree of the generator polynomial. Here $n = 3 + 3 = 6$.',
  },
];
