import type { QuizQuestion } from './types';

export const section36Questions: QuizQuestion[] = [
  {
    id: 1,
    type: 'multiple-choice',
    question: 'The automorphism group $\\text{Aut}(C)$ of a binary code $C$ consists of:',
    options: [
      'All linear transformations of $\\mathbb{F}_2^n
    correctIndex: 2,
    difficulty: 'easy',
    explanation: 'For a binary code, $\\text{Aut}(C)$ is the group of coordinate permutations $\\pi \\in S_n$ such that $\\pi(C) = C$, i.e., permutations that preserve the code.',
  },
      'Only the identity permutation',
      'Permutations of coordinates that map $C$ to itself',
      'All bijections from $C$ to $C
    correctIndex: 1,
    difficulty: 'easy',
    explanation: 'For a binary code, $\\text{Aut}(C)$ is the group of coordinate permutations $\\pi \\in S_n$ such that $\\pi(C) = C$, i.e., permutations that preserve the code.',
  },
    ],
    correctIndex: 1,
    difficulty: 'easy',
    explanation: 'For a binary code, $\\text{Aut}(C)$ is the group of coordinate permutations $\\pi \\in S_n$ such that $\\pi(C) = C$, i.e., permutations that preserve the code.',
  },
  {
    id: 2,
    type: 'multiple-choice',
    question: 'The automorphism group of a cyclic code of length $n$ always contains:',
    options: [
      'Only the trivial group',
      'The cyclic group $\\mathbb{Z}_n
    correctIndex: 1,
    difficulty: 'easy',
    explanation: 'By definition, cyclic codes are invariant under cyclic shifts, so $\\text{Aut}(C)$ contains the cyclic group $\\mathbb{Z}_n$ generated by the cyclic shift $i \\mapsto i+1 \\pmod{n}$.',
  },
      'The symmetric group $S_n
    correctIndex: 2,
    difficulty: 'easy',
    explanation: 'By definition, cyclic codes are invariant under cyclic shifts, so $\\text{Aut}(C)$ contains the cyclic group $\\mathbb{Z}_n$ generated by the cyclic shift $i \\mapsto i+1 \\pmod{n}$.',
  },
      'The alternating group $A_n
    correctIndex: 2,
    difficulty: 'easy',
    explanation: 'By definition, cyclic codes are invariant under cyclic shifts, so $\\text{Aut}(C)$ contains the cyclic group $\\mathbb{Z}_n$ generated by the cyclic shift $i \\mapsto i+1 \\pmod{n}$.',
  },
    ],
    correctIndex: 2,
    difficulty: 'easy',
    explanation: 'By definition, cyclic codes are invariant under cyclic shifts, so $\\text{Aut}(C)$ contains the cyclic group $\\mathbb{Z}_n$ generated by the cyclic shift $i \\mapsto i+1 \\pmod{n}$.',
  },
  {
    id: 3,
    type: 'multiple-choice',
    question: 'The automorphism group of the binary Golay code $\\mathcal{G}_{23}$ is:',
    options: [
      'The trivial group',
      'The symmetric group $S_{23}$',
      'The cyclic group $\\mathbb{Z}_{23}$',
      'The Mathieu group $M_{23}$'
    ],
    correctIndex: 3,
    difficulty: 'medium',
    explanation: 'The automorphism group of $\\mathcal{G}_{23}$ is the Mathieu group $M_{23}$, one of the sporadic simple groups. This is a remarkable connection between coding theory and group theory.',
  },
  {
    id: 4,
    type: 'numeric',
    question: 'The order of the Mathieu group $M_{24}$ (automorphism group of the extended Golay code $\\mathcal{G}_{24}$) is $24 \\cdot 23 \\cdot 22 \\cdot 21 \\cdot 20 \\cdot 48 = 244,823,040$. What is $|M_{24}| / 24!$?',
    correctAnswer: 0,
    numericRange: { min: 0, max: 1, precision: 5 },
    difficulty: 'hard',
    explanation: '$M_{24}$ is a proper subgroup of $S_{24}$. Actually $|M_{24}| = 244,823,040$ while $24! \\approx 6.2 \\times 10^{23}$, so the ratio is extremely small (approximately $3.95 \\times 10^{-16}$).',
  },
  {
    id: 5,
    type: 'multiple-choice',
    question: 'Two codes $C_1$ and $C_2$ are called equivalent if:',
    options: [
      'There exists a coordinate permutation mapping $C_1$ to $C_2$',
      'They have the same weight distribution',
      'They have the same length',
      'They have the same dimension',
    ],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: 'For binary codes, equivalence means there is a permutation $\\pi \\in S_n$ such that $\\pi(C_1) = C_2$. Equivalent codes have the same error-correcting capability.',
  },
  {
    id: 6,
    type: 'multiple-choice',
    question: 'The automorphism group of the $[7, 4, 3]$ Hamming code is:',
    options: [
      'The symmetric group $S_7$',
      '$\\text{GL}_3(\\mathbb{F}_2) \\cong \\text{PSL}_2(7)$ of order 168',
      'The cyclic group $\\mathbb{Z}_7$',
      'The trivial group'
    ],
    correctIndex: 1,
    difficulty: 'hard',
    explanation: 'The automorphism group of the $[7, 4, 3]$ Hamming code is $\\text{GL}_3(\\mathbb{F}_2)$, the general linear group of $3 \\times 3$ invertible matrices over $\\mathbb{F}_2$, which has order $168$.',
  },
];
