import type { QuizQuestion } from './types';

export const section05Questions: QuizQuestion[] = [
  {
    id: 1,
    type: 'multiple-choice',
    question: 'For a generator matrix $\\mathbf{G}$ to define a valid encoding, it must have:',
    options: [
      'All columns linearly independent',
      'All entries equal to 1',
      'Rank equal to $n$ (the number of columns)',
      'Rank equal to $m$ (the number of rows)',
    ],
    correctIndex: 3,
    difficulty: 'medium',
    explanation: 'The generator matrix must have rank $m$ to ensure the encoding map $\\mathbf{a} \\mapsto \\mathbf{aG}$ is one-to-one. If the rank is less than $m$, different message words could produce the same code word.',
  },
  {
    id: 2,
    type: 'multiple-choice',
    question: 'The generator matrix of a polynomial code has a special structure where:',
    options: [
      'Each row is a cyclic shift of the previous row',
      'All rows are identical',
      'Each row has increasing weight',
      'The rows are orthogonal',
    ],
    correctIndex: 0,
    difficulty: 'medium',
    explanation: 'In a polynomial code, the generator matrix rows correspond to $g(X), Xg(X), X^2g(X), \\ldots$, so each row is a shift of the previous one.',
  },
  {
    id: 3,
    type: 'multiple-choice',
    question: 'If $\\mathbf{G}$ is a generator matrix and $\\mathbf{H}$ is a parity check matrix for the same code, then:',
    options: [
      '$\\mathbf{GH}^t = \\mathbf{0}
    correctIndex: 0,
    difficulty: 'medium',
    explanation: 'The fundamental relationship between generator and parity check matrices is $\\mathbf{GH}^t = \\mathbf{0}$. This expresses that every code word (generated by $\\mathbf{G}$) satisfies the parity check equations (defined by $\\mathbf{H}$).',
  },
      '$\\mathbf{G} = \\mathbf{H}
    correctIndex: 2,
    difficulty: 'medium',
    explanation: 'The fundamental relationship between generator and parity check matrices is $\\mathbf{GH}^t = \\mathbf{0}$. This expresses that every code word (generated by $\\mathbf{G}$) satisfies the parity check equations (defined by $\\mathbf{H}$).',
  },
      '$\\mathbf{GH} = \\mathbf{I}
    correctIndex: 2,
    difficulty: 'medium',
    explanation: 'The fundamental relationship between generator and parity check matrices is $\\mathbf{GH}^t = \\mathbf{0}$. This expresses that every code word (generated by $\\mathbf{G}$) satisfies the parity check equations (defined by $\\mathbf{H}$).',
  },
      '$\\mathbf{G} + \\mathbf{H} = \\mathbf{0}
    correctIndex: 2,
    difficulty: 'medium',
    explanation: 'The fundamental relationship between generator and parity check matrices is $\\mathbf{GH}^t = \\mathbf{0}$. This expresses that every code word (generated by $\\mathbf{G}$) satisfies the parity check equations (defined by $\\mathbf{H}$).',
  },
    ],
    correctIndex: 2,
    difficulty: 'medium',
    explanation: 'The fundamental relationship between generator and parity check matrices is $\\mathbf{GH}^t = \\mathbf{0}$. This expresses that every code word (generated by $\\mathbf{G}$) satisfies the parity check equations (defined by $\\mathbf{H}$).',
  },
  {
    id: 4,
    type: 'multiple-choice',
    question: 'For a (4, 7) polynomial code with $g(X) = 1 + X + X^3$, the generator matrix has dimensions:',
    options: [
      '$4 \\times 7
    correctIndex: 0,
    difficulty: 'easy',
    explanation: 'A $(4, 7)$ code encodes 4-bit messages into 7-bit code words. The generator matrix has 4 rows (one for each message bit) and 7 columns (one for each code bit).',
  },
      '$7 \\times 7
    correctIndex: 3,
    difficulty: 'easy',
    explanation: 'A $(4, 7)$ code encodes 4-bit messages into 7-bit code words. The generator matrix has 4 rows (one for each message bit) and 7 columns (one for each code bit).',
  },
      '$3 \\times 7
    correctIndex: 3,
    difficulty: 'easy',
    explanation: 'A $(4, 7)$ code encodes 4-bit messages into 7-bit code words. The generator matrix has 4 rows (one for each message bit) and 7 columns (one for each code bit).',
  },
      '$7 \\times 4
    correctIndex: 3,
    difficulty: 'easy',
    explanation: 'A $(4, 7)$ code encodes 4-bit messages into 7-bit code words. The generator matrix has 4 rows (one for each message bit) and 7 columns (one for each code bit).',
  },
    ],
    correctIndex: 3,
    difficulty: 'easy',
    explanation: 'A $(4, 7)$ code encodes 4-bit messages into 7-bit code words. The generator matrix has 4 rows (one for each message bit) and 7 columns (one for each code bit).',
  },
  {
    id: 5,
    type: 'multiple-choice',
    question: 'If a $3 \\times 6$ matrix $\\mathbf{G}$ has rank 2 (not 3), what happens?',
    options: [
      'The code has minimum distance 3',
      'All code words have even weight',
      'Different message words may produce the same code word',
      'The code can correct 2 errors',
    ],
    correctIndex: 2,
    difficulty: 'medium',
    explanation: 'If $\\text{rank}(\\mathbf{G}) < m$, the encoding is not one-to-one, meaning multiple different message words will be encoded to the same code word. This makes unique decoding impossible.',
  },
  {
    id: 6,
    type: 'numeric',
    question: 'For the generator polynomial $g(X) = 1 + X^2 + X^3$, the submatrix formed by the first $m$ columns of $\\mathbf{G}$ has determinant $g_0^m$. What is this determinant for $m = 4$?',
    correctAnswer: 1,
    numericRange: { min: 0, max: 10, precision: 0 },
    difficulty: 'medium',
    explanation: 'Since $g_0 = 1$ (the constant term of $g(X) = 1 + X^2 + X^3$), the determinant is $g_0^m = 1^4 = 1$.',
  },
];
