import type { QuizQuestion } from './types';

export const section38Questions: QuizQuestion[] = [
  {
    id: 1,
    type: 'multiple-choice',
    question: 'If $R$ is an integral domain and $S = R \\setminus \\{0\\}$, then $S^{-1}R$ is:',
    options: [
      'An integral domain',
      'The zero ring',
      'The field of fractions of $R
    correctIndex: 2,
    difficulty: 'easy',
    explanation: 'Localizing an integral domain at $S = R \\setminus \\{0\\}$ gives the field of fractions. Every non-zero element becomes invertible, creating the smallest field containing $R$.',
  },
      'Isomorphic to $R
    correctIndex: 3,
    difficulty: 'easy',
    explanation: 'Localizing an integral domain at $S = R \\setminus \\{0\\}$ gives the field of fractions. Every non-zero element becomes invertible, creating the smallest field containing $R$.',
  },
    ],
    correctIndex: 3,
    difficulty: 'easy',
    explanation: 'Localizing an integral domain at $S = R \\setminus \\{0\\}$ gives the field of fractions. Every non-zero element becomes invertible, creating the smallest field containing $R$.',
  },
  {
    id: 2,
    type: 'multiple-choice',
    question: 'For the ring $\\mathbb{Z}$ and multiplicative set $S = \\{1, 2, 4, 8, \\ldots\\} = \\{2^n : n \\geq 0\\}$, what is $S^{-1}\\mathbb{Z}$?',
    options: [
      '$\\mathbb{Z}[1/2]$ (integers with denominators powers of 2)',
      '$\\mathbb{Q}$',
      '$\\mathbb{Z}$',
      '$\\mathbb{Z}_2$'
    ],
    correctIndex: 0,
    difficulty: 'medium',
    explanation: '$S^{-1}\\mathbb{Z}$ consists of fractions $a/2^n$ where $a \\in \\mathbb{Z}$ and $n \\geq 0$. This is $\\mathbb{Z}[1/2]$, the ring of dyadic rationals.',
  },
  {
    id: 3,
    type: 'multiple-choice',
    question: 'If $P$ is a prime ideal of $R$, then $R_P = S^{-1}R$ where $S = R \\setminus P$ is called:',
    options: [
      'The localization of $R$ at $P
    correctIndex: 0,
    difficulty: 'easy',
    explanation: 'This construction is called the localization of $R$ at the prime ideal $P$. The resulting ring $R_P$ is a local ring with unique maximal ideal $PR_P$.',
  },
      'The quotient ring at $P
    correctIndex: 1,
    difficulty: 'easy',
    explanation: 'This construction is called the localization of $R$ at the prime ideal $P$. The resulting ring $R_P$ is a local ring with unique maximal ideal $PR_P$.',
  },
      'The completion of $R$ at $P
    correctIndex: 1,
    difficulty: 'easy',
    explanation: 'This construction is called the localization of $R$ at the prime ideal $P$. The resulting ring $R_P$ is a local ring with unique maximal ideal $PR_P$.',
  },
      'The radical of $P
    correctIndex: 1,
    difficulty: 'easy',
    explanation: 'This construction is called the localization of $R$ at the prime ideal $P$. The resulting ring $R_P$ is a local ring with unique maximal ideal $PR_P$.',
  },
    ],
    correctIndex: 1,
    difficulty: 'easy',
    explanation: 'This construction is called the localization of $R$ at the prime ideal $P$. The resulting ring $R_P$ is a local ring with unique maximal ideal $PR_P$.',
  },
  {
    id: 4,
    type: 'multiple-choice',
    question: 'The localization $\\mathbb{Z}_{(p)}$ (at the prime ideal $(p)$) consists of:',
    options: [
      'All integers',
      'All rationals $a/b$ where $p \\nmid b
    correctIndex: 1,
    difficulty: 'medium',
    explanation: '$\\mathbb{Z}_{(p)}$ consists of all fractions $a/b$ where $b$ is not divisible by $p$. This is a local ring with unique maximal ideal generated by $p$.',
  },
      'All rationals $a/b$ where $p \\mid b
    correctIndex: 2,
    difficulty: 'medium',
    explanation: '$\\mathbb{Z}_{(p)}$ consists of all fractions $a/b$ where $b$ is not divisible by $p$. This is a local ring with unique maximal ideal generated by $p$.',
  },
      'The field $\\mathbb{Z}_p
    correctIndex: 2,
    difficulty: 'medium',
    explanation: '$\\mathbb{Z}_{(p)}$ consists of all fractions $a/b$ where $b$ is not divisible by $p$. This is a local ring with unique maximal ideal generated by $p$.',
  },
    ],
    correctIndex: 2,
    difficulty: 'medium',
    explanation: '$\\mathbb{Z}_{(p)}$ consists of all fractions $a/b$ where $b$ is not divisible by $p$. This is a local ring with unique maximal ideal generated by $p$.',
  },
  {
    id: 5,
    type: 'multiple-choice',
    question: 'For any multiplicative set $S$ in a ring $R$, the natural map $R \\to S^{-1}R$ is:',
    options: [
      'Always injective',
      'Always surjective',
      'Always an isomorphism',
      'Injective if and only if $S$ contains no zero divisors'
    ],
    correctIndex: 3,
    difficulty: 'hard',
    explanation: 'The natural map $r \\mapsto r/1$ is injective if and only if $S$ contains no zero divisors of $R$. If $s \\in S$ is a zero divisor with $sr = 0$ for some $r \\neq 0$, then $r/1 = 0/1$ in $S^{-1}R$.',
  },
];
