import type { QuizQuestion } from './types';

export const section33Questions: QuizQuestion[] = [
  {
    id: 1,
    type: 'multiple-choice',
    question: 'The free group $F_2$ on two generators $a$ and $b$ is:',
    options: [
      'Finite',
      'Abelian',
      'Isomorphic to $\\mathbb{Z} \\times \\mathbb{Z}
    correctIndex: 3,
    difficulty: 'easy',
    explanation: 'The free group $F_2$ is non-abelian (since $ab \\neq ba$ in $F_2$) and infinite. It is NOT isomorphic to $\\mathbb{Z} \\times \\mathbb{Z}$, which is the free abelian group on two generators.',
  },
      'Non-abelian and infinite',
    ],
    correctIndex: 2,
    difficulty: 'easy',
    explanation: 'The free group $F_2$ is non-abelian (since $ab \\neq ba$ in $F_2$) and infinite. It is NOT isomorphic to $\\mathbb{Z} \\times \\mathbb{Z}$, which is the free abelian group on two generators.',
  },
  {
    id: 2,
    type: 'multiple-choice',
    question: 'In the free group $F(a, b)$, what is the reduced form of $aba^{-1}b^{-1}ab$?',
    options: [
      '$aba^{-1}b^{-1}ab
    correctIndex: 0,
    difficulty: 'medium',
    explanation: 'The word $aba^{-1}b^{-1}ab$ is already reduced since no adjacent pair consists of an element and its inverse. This is the commutator $[a,b]$ followed by $ab$.',
  },
      '$ab
    correctIndex: 3,
    difficulty: 'medium',
    explanation: 'The word $aba^{-1}b^{-1}ab$ is already reduced since no adjacent pair consists of an element and its inverse. This is the commutator $[a,b]$ followed by $ab$.',
  },
      '$b
    correctIndex: 3,
    difficulty: 'medium',
    explanation: 'The word $aba^{-1}b^{-1}ab$ is already reduced since no adjacent pair consists of an element and its inverse. This is the commutator $[a,b]$ followed by $ab$.',
  },
      '$a^2
    correctIndex: 3,
    difficulty: 'medium',
    explanation: 'The word $aba^{-1}b^{-1}ab$ is already reduced since no adjacent pair consists of an element and its inverse. This is the commutator $[a,b]$ followed by $ab$.',
  },
    ],
    correctIndex: 3,
    difficulty: 'medium',
    explanation: 'The word $aba^{-1}b^{-1}ab$ is already reduced since no adjacent pair consists of an element and its inverse. This is the commutator $[a,b]$ followed by $ab$.',
  },
  {
    id: 3,
    type: 'multiple-choice',
    question: 'The presentation $\\langle a, b \\mid aba^{-1}b^{-1} \\rangle$ defines:',
    options: [
      'The free group $F_2
    correctIndex: 2,
    difficulty: 'medium',
    explanation: 'The relation $aba^{-1}b^{-1} = 1$ means $ab = ba$, so $a$ and $b$ commute. This makes the group the free abelian group on two generators, isomorphic to $\\mathbb{Z}^2$.',
  },
      'The trivial group',
      'The free abelian group $\\mathbb{Z}^2
    correctIndex: 0,
    difficulty: 'medium',
    explanation: 'The relation $aba^{-1}b^{-1} = 1$ means $ab = ba$, so $a$ and $b$ commute. This makes the group the free abelian group on two generators, isomorphic to $\\mathbb{Z}^2$.',
  },
      'The dihedral group $D_4
    correctIndex: 0,
    difficulty: 'medium',
    explanation: 'The relation $aba^{-1}b^{-1} = 1$ means $ab = ba$, so $a$ and $b$ commute. This makes the group the free abelian group on two generators, isomorphic to $\\mathbb{Z}^2$.',
  },
    ],
    correctIndex: 0,
    difficulty: 'medium',
    explanation: 'The relation $aba^{-1}b^{-1} = 1$ means $ab = ba$, so $a$ and $b$ commute. This makes the group the free abelian group on two generators, isomorphic to $\\mathbb{Z}^2$.',
  },
  {
    id: 4,
    type: 'multiple-choice',
    question: 'The group with presentation $\\langle a \\mid a^n \\rangle$ is isomorphic to:',
    options: [
      '$\\mathbb{Z}
    correctIndex: 3,
    difficulty: 'easy',
    explanation: 'This presentation gives a cyclic group generated by $a$ with the relation $a^n = 1$, which is exactly $\\mathbb{Z}_n$, the cyclic group of order $n$.',
  },
      'The trivial group',
      '$\\mathbb{Z} \\times \\mathbb{Z}_n
    correctIndex: 1,
    difficulty: 'easy',
    explanation: 'This presentation gives a cyclic group generated by $a$ with the relation $a^n = 1$, which is exactly $\\mathbb{Z}_n$, the cyclic group of order $n$.',
  },
      '$\\mathbb{Z}_n
    correctIndex: 1,
    difficulty: 'easy',
    explanation: 'This presentation gives a cyclic group generated by $a$ with the relation $a^n = 1$, which is exactly $\\mathbb{Z}_n$, the cyclic group of order $n$.',
  },
    ],
    correctIndex: 1,
    difficulty: 'easy',
    explanation: 'This presentation gives a cyclic group generated by $a$ with the relation $a^n = 1$, which is exactly $\\mathbb{Z}_n$, the cyclic group of order $n$.',
  },
  {
    id: 5,
    type: 'multiple-choice',
    question: 'If $F$ is a free group, which statement is TRUE?',
    options: [
      '$F$ has only finitely many subgroups',
      'Every quotient of $F$ is free',
      'Every subgroup of $F$ is free',
      '$F$ is always abelian',
    ],
    correctIndex: 2,
    difficulty: 'hard',
    explanation: 'The Nielsen-Schreier theorem states that every subgroup of a free group is free. However, quotients of free groups need not be free (any group is a quotient of some free group).',
  },
];
