import type { QuizQuestion } from './types';

export const section25Questions: QuizQuestion[] = [
  {
    id: 1,
    type: 'multiple-choice',
    question: 'For which values of $n$ is $A_n$ simple?',
    options: [
      '$n \\geq 4
    correctIndex: 1,
    difficulty: 'medium',
    explanation: '$A_n$ is simple for $n \\geq 5$. $A_3 \\cong \\mathbb{Z}_3$ is simple but abelian, and $A_4$ has a normal subgroup (the Klein 4-group).',
  },
      '$n \\geq 5
    correctIndex: 0,
    difficulty: 'medium',
    explanation: '$A_n$ is simple for $n \\geq 5$. $A_3 \\cong \\mathbb{Z}_3$ is simple but abelian, and $A_4$ has a normal subgroup (the Klein 4-group).',
  },
      '$n \\geq 3
    correctIndex: 0,
    difficulty: 'medium',
    explanation: '$A_n$ is simple for $n \\geq 5$. $A_3 \\cong \\mathbb{Z}_3$ is simple but abelian, and $A_4$ has a normal subgroup (the Klein 4-group).',
  },
      'All $n \\geq 1
    correctIndex: 0,
    difficulty: 'medium',
    explanation: '$A_n$ is simple for $n \\geq 5$. $A_3 \\cong \\mathbb{Z}_3$ is simple but abelian, and $A_4$ has a normal subgroup (the Klein 4-group).',
  },
    ],
    correctIndex: 0,
    difficulty: 'medium',
    explanation: '$A_n$ is simple for $n \\geq 5$. $A_3 \\cong \\mathbb{Z}_3$ is simple but abelian, and $A_4$ has a normal subgroup (the Klein 4-group).',
  },
  {
    id: 2,
    type: 'multiple-choice',
    question: 'Why is $A_4$ not simple?',
    options: [
      'It is abelian',
      'It has order 12',
      'It contains the Klein four-group $V_4$ as a normal subgroup',
      'It has a Sylow 2-subgroup',
    ],
    correctIndex: 2,
    difficulty: 'medium',
    explanation: '$A_4$ contains $V_4 = \\{e, (12)(34), (13)(24), (14)(23)\\}$ which is normal.',
  },
  {
    id: 3,
    type: 'multiple-choice',
    question: 'The key fact used to prove $A_5$ is simple is that:',
    options: [
      '3-cycles generate $A_n$ for $n \\geq 3
    correctIndex: 0,
    difficulty: 'hard',
    explanation: 'The proof uses that $A_n$ is generated by 3-cycles, and any normal subgroup containing one 3-cycle must contain all 3-cycles (by conjugation).',
  },
      '$A_5$ is abelian',
      '$A_5$ has no subgroups',
      '$A_5$ has order 60',
    ],
    correctIndex: 2,
    difficulty: 'hard',
    explanation: 'The proof uses that $A_n$ is generated by 3-cycles, and any normal subgroup containing one 3-cycle must contain all 3-cycles (by conjugation).',
  },
  {
    id: 4,
    type: 'numeric',
    question: 'What is the order of $A_5$?',
    correctAnswer: 60,
    numericRange: { min: 1, max: 200, precision: 0 },
    difficulty: 'easy',
    explanation: '$|A_n| = n!/2$, so $|A_5| = 120/2 = 60$.',
  },
  {
    id: 5,
    type: 'multiple-choice',
    question: 'Since $A_5$ is simple and non-abelian, $A_5$ is:',
    options: [
      'Solvable',
      'A $p$-group',
      'Cyclic',
      'Not solvable'
    ],
    correctIndex: 3,
    difficulty: 'hard',
    explanation: 'A non-abelian simple group is not solvable (solvable groups have abelian composition factors).',
  },
];
