import type { QuizQuestion } from './types';

export const section12Questions: QuizQuestion[] = [
  {
    id: 1,
    type: 'multiple-choice',
    question: 'A group $G$ is cyclic if:',
    options: [
      '$G$ has a subgroup of every order dividing $|G|
    correctIndex: 3,
    difficulty: 'easy',
    explanation: '$G$ is cyclic if it is generated by a single element: $G = \\langle g \\rangle = \\{g^n : n \\in \\mathbb{Z}\\}$.',
  },
      '$G$ is abelian',
      '$G$ is finite',
      '$G = \\langle g \\rangle$ for some $g \\in G
    correctIndex: 0,
    difficulty: 'easy',
    explanation: '$G$ is cyclic if it is generated by a single element: $G = \\langle g \\rangle = \\{g^n : n \\in \\mathbb{Z}\\}$.',
  },
    ],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: '$G$ is cyclic if it is generated by a single element: $G = \\langle g \\rangle = \\{g^n : n \\in \\mathbb{Z}\\}$.',
  },
  {
    id: 2,
    type: 'numeric',
    question: 'What is the order of $\\overline{3}$ in the cyclic group $\\mathbb{Z}/12\\mathbb{Z}$?',
    correctAnswer: 4,
    numericRange: { min: 1, max: 20, precision: 0 },
    difficulty: 'medium',
    explanation: 'The order of $\\overline{a}$ in $\\mathbb{Z}/n\\mathbb{Z}$ is $n/\\gcd(a, n) = 12/\\gcd(3, 12) = 12/3 = 4$.',
  },
  {
    id: 3,
    type: 'numeric',
    question: 'How many generators does $\\mathbb{Z}/10\\mathbb{Z}$ have?',
    correctAnswer: 4,
    numericRange: { min: 1, max: 20, precision: 0 },
    difficulty: 'medium',
    explanation: 'The generators are elements coprime to 10: $\\overline{1}, \\overline{3}, \\overline{7}, \\overline{9}$. This equals $\\phi(10) = 4$.',
  },
  {
    id: 4,
    type: 'multiple-choice',
    question: 'The subgroups of a cyclic group $\\mathbb{Z}/n\\mathbb{Z}$ are:',
    options: [
      'Only $\\{0\\}$ and $\\mathbb{Z}/n\\mathbb{Z}
    correctIndex: 2,
    difficulty: 'medium',
    explanation: 'For each divisor $d$ of $n$, there is exactly one subgroup of order $d$, namely $\\langle n/d \\rangle$.',
  },
      'In bijection with positive integers',
      'In bijection with divisors of $n
    correctIndex: 1,
    difficulty: 'medium',
    explanation: 'For each divisor $d$ of $n$, there is exactly one subgroup of order $d$, namely $\\langle n/d \\rangle$.',
  },
      'Always cyclic but not in any pattern',
    ],
    correctIndex: 1,
    difficulty: 'medium',
    explanation: 'For each divisor $d$ of $n$, there is exactly one subgroup of order $d$, namely $\\langle n/d \\rangle$.',
  },
  {
    id: 5,
    type: 'multiple-choice',
    question: 'Every cyclic group is:',
    options: [
      'Abelian',
      'Finite',
      'Infinite',
      'Non-abelian',
    ],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: 'Every cyclic group is abelian: $g^m g^n = g^{m+n} = g^{n+m} = g^n g^m$.',
  },
];
