import type { QuizQuestion } from './types';

export const section37Questions: QuizQuestion[] = [
  {
    id: 1,
    type: 'multiple-choice',
    question: 'An ideal $P$ of a commutative ring $R$ is prime if and only if:',
    options: [
      '$P = R
    correctIndex: 1,
    difficulty: 'medium',
    explanation: 'An ideal $P$ is prime if and only if $R/P$ is an integral domain. Equivalently, $P \\neq R$ and whenever $ab \\in P$, either $a \\in P$ or $b \\in P$.',
  },
      '$R/P$ is an integral domain',
      '$R/P$ is a field',
      '$P$ contains all zero divisors',
    ],
    correctIndex: 2,
    difficulty: 'medium',
    explanation: 'An ideal $P$ is prime if and only if $R/P$ is an integral domain. Equivalently, $P \\neq R$ and whenever $ab \\in P$, either $a \\in P$ or $b \\in P$.',
  },
  {
    id: 2,
    type: 'multiple-choice',
    question: 'An ideal $M$ of a commutative ring $R$ is maximal if and only if:',
    options: [
      '$R/M$ is a field',
      '$M = \\{0\\}
    correctIndex: 0,
    difficulty: 'medium',
    explanation: 'An ideal $M$ is maximal if and only if $R/M$ is a field. This is because $R/M$ has no proper non-zero ideals, which characterizes fields among commutative rings with unity.',
  },
      '$R/M$ is an integral domain',
      '$M$ is finitely generated',
    ],
    correctIndex: 3,
    difficulty: 'medium',
    explanation: 'An ideal $M$ is maximal if and only if $R/M$ is a field. This is because $R/M$ has no proper non-zero ideals, which characterizes fields among commutative rings with unity.',
  },
  {
    id: 3,
    type: 'multiple-choice',
    question: 'In $\\mathbb{Z}$, which of the following is a maximal ideal?',
    options: [
      '$(6)
    correctIndex: 2,
    difficulty: 'easy',
    explanation: 'In $\\mathbb{Z}$, the maximal ideals are exactly $(p)$ where $p$ is prime. So $(5)$ is maximal since $\\mathbb{Z}/(5) = \\mathbb{Z}_5$ is a field. $(4)$ and $(6)$ are not maximal.',
  },
      '$(4)
    correctIndex: 0,
    difficulty: 'easy',
    explanation: 'In $\\mathbb{Z}$, the maximal ideals are exactly $(p)$ where $p$ is prime. So $(5)$ is maximal since $\\mathbb{Z}/(5) = \\mathbb{Z}_5$ is a field. $(4)$ and $(6)$ are not maximal.',
  },
      '$(5)
    correctIndex: 0,
    difficulty: 'easy',
    explanation: 'In $\\mathbb{Z}$, the maximal ideals are exactly $(p)$ where $p$ is prime. So $(5)$ is maximal since $\\mathbb{Z}/(5) = \\mathbb{Z}_5$ is a field. $(4)$ and $(6)$ are not maximal.',
  },
      '$(0)
    correctIndex: 0,
    difficulty: 'easy',
    explanation: 'In $\\mathbb{Z}$, the maximal ideals are exactly $(p)$ where $p$ is prime. So $(5)$ is maximal since $\\mathbb{Z}/(5) = \\mathbb{Z}_5$ is a field. $(4)$ and $(6)$ are not maximal.',
  },
    ],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: 'In $\\mathbb{Z}$, the maximal ideals are exactly $(p)$ where $p$ is prime. So $(5)$ is maximal since $\\mathbb{Z}/(5) = \\mathbb{Z}_5$ is a field. $(4)$ and $(6)$ are not maximal.',
  },
  {
    id: 4,
    type: 'multiple-choice',
    question: 'Every maximal ideal is:',
    options: [
      'Prime',
      'Principal',
      'Generated by a single element',
      'Equal to the whole ring',
    ],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: 'Every maximal ideal is prime. If $M$ is maximal, then $R/M$ is a field, which is in particular an integral domain, so $M$ is prime. The converse is false in general.',
  },
  {
    id: 5,
    type: 'multiple-choice',
    question: 'In $\\mathbb{Z}[x]$, the ideal $(x, 2)$ is:',
    options: [
      'Prime but not maximal',
      'Neither prime nor maximal',
      'Maximal',
      'The zero ideal',
    ],
    correctIndex: 2,
    difficulty: 'hard',
    explanation: '$\\mathbb{Z}[x]/(x, 2) \\cong \\mathbb{Z}_2$ (by first modding out by $x$, then by $2$). Since $\\mathbb{Z}_2$ is a field, $(x, 2)$ is a maximal ideal.',
  },
];
