import type { QuizQuestion } from './types';

export const section82Questions: QuizQuestion[] = [
  {
    id: 1,
    type: 'multiple-choice',
    question: 'A ring $R$ is Artinian if and only if:',
    options: [
      'Every ascending chain of ideals stabilizes (ACC)',
      'Every descending chain of ideals stabilizes (DCC)',
      '$R$ is a field',
      'Every ideal is finitely generated',
    ],
    correctIndex: 1,
    difficulty: 'easy',
    explanation: 'A ring is Artinian if it satisfies the descending chain condition (DCC) on ideals: every descending chain $I_1 \\supseteq I_2 \\supseteq I_3 \\supseteq \\cdots$ eventually stabilizes.',
  },
  {
    id: 2,
    type: 'multiple-choice',
    question: 'Which of the following is Artinian but NOT Noetherian?',
    options: [
      'There is no such ring',
      'A finite field',
      '$\\mathbb{Z}$',
      '$\\mathbb{Q}[x]$'
    ],
    correctIndex: 0,
    difficulty: 'medium',
    explanation: 'Every Artinian ring is Noetherian. The Hopkins-Levitzki theorem shows that Artinian rings have finite length as modules over themselves, which implies the Noetherian condition.',
  },
  {
    id: 3,
    type: 'multiple-choice',
    question: 'The structure theorem for Artinian rings states that every Artinian ring is:',
    options: [
      'A finite product of Artinian local rings',
      'A field',
      'A product of fields',
      'A polynomial ring',
    ],
    correctIndex: 0,
    difficulty: 'medium',
    explanation: 'Every Artinian ring is a finite product of Artinian local rings. An Artinian local ring has a unique prime ideal (its maximal ideal), which is nilpotent.',
  },
  {
    id: 4,
    type: 'multiple-choice',
    question: 'In an Artinian ring, every prime ideal is:',
    options: [
      'Principal',
      'Nilpotent',
      'Maximal',
      'Generated by two elements'
    ],
    correctIndex: 2,
    difficulty: 'medium',
    explanation: 'In an Artinian ring, every prime ideal is maximal. This means the Krull dimension of an Artinian ring is $0$.',
  },
  {
    id: 5,
    type: 'multiple-choice',
    question: 'The ring $\\mathbb{Z}/n\\mathbb{Z}$ is Artinian because:',
    options: [
      'It is a field',
      'It has no zero divisors',
      'It is a PID',
      'It is finite, hence has DCC on ideals'
    ],
    correctIndex: 3,
    difficulty: 'easy',
    explanation: '$\\mathbb{Z}/n\\mathbb{Z}$ is a finite ring, so it has only finitely many ideals. Any descending chain must stabilize, making it Artinian (and also Noetherian).',
  },
];
