import type { QuizQuestion } from './types';

export const section79Questions: QuizQuestion[] = [
  {
    id: 1,
    type: 'multiple-choice',
    question: 'The Weak Nullstellensatz states that if $k$ is algebraically closed, then every proper ideal $I \\subsetneq k[x_1, \\ldots, x_n]$ has:',
    options: [
      'A finite generating set',
      'A unique prime ideal containing it',
      'A nonempty variety $V(I) \\neq \\emptyset
    correctIndex: 2,
    difficulty: ',
      ',
    explanation: ',
    ],
    correctIndex: 0,
    difficulty: 'medium',
    explanation: 'The Weak Nullstellensatz says that over an algebraically closed field, every proper ideal has a common zero. Equivalently, the maximal ideals of $k[x_1, \\ldots, x_n]$ are exactly $(x_1 - a_1, \\ldots, x_n - a_n)$ for $a_i \\in k$.',
  },
  {
    id: 2,
    type: 'multiple-choice',
    question: 'The Strong Nullstellensatz (Hilbert\'s Nullstellensatz) states that for $k$ algebraically closed:',
    options: [
      '$I(V(I)) = \\sqrt{I}$ for all ideals $I
    correctIndex: 0,
    difficulty: 'medium',
    explanation: 'The Strong Nullstellensatz says $I(V(I)) = \\sqrt{I}$. This gives a bijection between radical ideals and algebraic varieties, which is the foundation of algebraic geometry.',
  },
      '$V(I) = V(J)$ implies $I = J
    correctIndex: 1,
    difficulty: 'medium',
    explanation: 'The Strong Nullstellensatz says $I(V(I)) = \\sqrt{I}$. This gives a bijection between radical ideals and algebraic varieties, which is the foundation of algebraic geometry.',
  },
      'Every ideal is radical',
      'Every variety is finite',
    ],
    correctIndex: 1,
    difficulty: 'medium',
    explanation: 'The Strong Nullstellensatz says $I(V(I)) = \\sqrt{I}$. This gives a bijection between radical ideals and algebraic varieties, which is the foundation of algebraic geometry.',
  },
  {
    id: 3,
    type: 'multiple-choice',
    question: 'The Nullstellensatz requires $k$ to be algebraically closed. Over $\\mathbb{R}$, which ideal has empty variety?',
    options: [
      '$(x^2 + 1)
    correctIndex: 0,
    difficulty: 'medium',
    explanation: 'Over $\\mathbb{R}$, the ideal $(x^2 + 1)$ has $V(x^2 + 1) = \\emptyset$ since $x^2 + 1 > 0$ for all real $x$. This shows the Nullstellensatz fails over non-algebraically closed fields.',
  },
      '$(x)
    correctIndex: 2,
    difficulty: 'medium',
    explanation: 'Over $\\mathbb{R}$, the ideal $(x^2 + 1)$ has $V(x^2 + 1) = \\emptyset$ since $x^2 + 1 > 0$ for all real $x$. This shows the Nullstellensatz fails over non-algebraically closed fields.',
  },
      '$(x^2 + y^2)
    correctIndex: 2,
    difficulty: 'medium',
    explanation: 'Over $\\mathbb{R}$, the ideal $(x^2 + 1)$ has $V(x^2 + 1) = \\emptyset$ since $x^2 + 1 > 0$ for all real $x$. This shows the Nullstellensatz fails over non-algebraically closed fields.',
  },
      '$(x - 1)
    correctIndex: 2,
    difficulty: 'medium',
    explanation: 'Over $\\mathbb{R}$, the ideal $(x^2 + 1)$ has $V(x^2 + 1) = \\emptyset$ since $x^2 + 1 > 0$ for all real $x$. This shows the Nullstellensatz fails over non-algebraically closed fields.',
  },
    ],
    correctIndex: 2,
    difficulty: 'medium',
    explanation: 'Over $\\mathbb{R}$, the ideal $(x^2 + 1)$ has $V(x^2 + 1) = \\emptyset$ since $x^2 + 1 > 0$ for all real $x$. This shows the Nullstellensatz fails over non-algebraically closed fields.',
  },
  {
    id: 4,
    type: 'multiple-choice',
    question: 'The Nullstellensatz implies that maximal ideals of $\\mathbb{C}[x, y]$ are exactly:',
    options: [
      'Principal ideals $(f)$ for irreducible $f
    correctIndex: 2,
    difficulty: 'medium',
    explanation: 'By the Weak Nullstellensatz, maximal ideals of $k[x_1, \\ldots, x_n]$ correspond to points: the maximal ideal at $(a_1, \\ldots, a_n)$ is $(x_1 - a_1, \\ldots, x_n - a_n)$.',
  },
      'Ideals generated by linear polynomials',
      'Ideals of the form $(x - a, y - b)$ for $a, b \\in \\mathbb{C}
    correctIndex: 3,
    difficulty: 'medium',
    explanation: 'By the Weak Nullstellensatz, maximal ideals of $k[x_1, \\ldots, x_n]$ correspond to points: the maximal ideal at $(a_1, \\ldots, a_n)$ is $(x_1 - a_1, \\ldots, x_n - a_n)$.',
  },
      'All prime ideals',
    ],
    correctIndex: 3,
    difficulty: 'medium',
    explanation: 'By the Weak Nullstellensatz, maximal ideals of $k[x_1, \\ldots, x_n]$ correspond to points: the maximal ideal at $(a_1, \\ldots, a_n)$ is $(x_1 - a_1, \\ldots, x_n - a_n)$.',
  },
  {
    id: 5,
    type: 'multiple-choice',
    question: 'The correspondence $V \\mapsto I(V)$ and $I \\mapsto V(I)$ is a bijection between:',
    options: [
      'Radical ideals and algebraic varieties',
      'Prime ideals and irreducible varieties',
      'All ideals and all subsets of $k^n
    correctIndex: 3,
    difficulty: 'hard',
    explanation: 'The Nullstellensatz establishes a bijection between radical ideals and algebraic varieties. This restricts to a bijection between prime ideals and irreducible varieties (varieties that cannot be written as a union of two proper subvarieties).',
  },
      'Both B and C',
    ],
    correctIndex: 0,
    difficulty: 'hard',
    explanation: 'The Nullstellensatz establishes a bijection between radical ideals and algebraic varieties. This restricts to a bijection between prime ideals and irreducible varieties (varieties that cannot be written as a union of two proper subvarieties).',
  },
];
