import type { QuizQuestion } from './types';

export const section41Questions: QuizQuestion[] = [
  {
    id: 1,
    type: 'multiple-choice',
    question: 'A principal ideal domain (PID) is an integral domain in which:',
    options: [
      'Every element is prime',
      'Every element is a unit',
      'Every ideal is generated by a single element',
      'There are only finitely many ideals'
    ],
    correctIndex: 2,
    difficulty: 'easy',
    explanation: 'A PID is an integral domain where every ideal is principal, meaning it can be generated by a single element: $I = (a)$ for some $a \\in R$.',
  },
  {
    id: 2,
    type: 'multiple-choice',
    question: 'Which of the following is a PID but NOT a Euclidean domain?',
    options: [
      '$\\mathbb{Z}$',
      '$\\mathbb{Z}[x]$',
      '$\\mathbb{Q}[x]$',
      '$\\mathbb{Z}\\left[\\frac{1+\\sqrt{-19}}{2}\\right]$'
    ],
    correctIndex: 3,
    difficulty: 'hard',
    explanation: 'The ring $\\mathbb{Z}\\left[\\frac{1+\\sqrt{-19}}{2}\\right]$ is a PID but not Euclidean. $\\mathbb{Z}$ and $\\mathbb{Q}[x]$ are Euclidean, and $\\mathbb{Z}[x]$ is not even a PID.',
  },
  {
    id: 3,
    type: 'multiple-choice',
    question: 'In a PID, every nonzero prime ideal is:',
    options: [
      'Maximal',
      'Equal to the whole ring',
      'Principal but not maximal',
      'Generated by two elements'
    ],
    correctIndex: 0,
    difficulty: 'medium',
    explanation: 'In a PID, every nonzero prime ideal is maximal. If $(p)$ is a nonzero prime ideal and $(p) \\subseteq (a)$, then $p = ab$ for some $b$. Since $(p)$ is prime, $a \\in (p)$ or $b \\in (p)$, leading to $(a) = (p)$ or $(a) = R$.',
  },
  {
    id: 4,
    type: 'multiple-choice',
    question: 'In $\\mathbb{Z}$, the ideal $(6)$ is:',
    options: [
      'Prime',
      'Maximal',
      'Neither prime nor maximal',
      'Both prime and maximal',
    ],
    correctIndex: 2,
    difficulty: 'easy',
    explanation: '$(6)$ is not prime because $2 \\cdot 3 = 6 \\in (6)$ but $2 \\notin (6)$ and $3 \\notin (6)$. It is not maximal because $(6) \\subsetneq (2) \\subsetneq \\mathbb{Z}$.',
  },
  {
    id: 5,
    type: 'multiple-choice',
    question: 'If $R$ is a PID and $a, b \\in R$ are nonzero, then $\\gcd(a, b)$:',
    options: [
      'May not exist',
      'Exists and can be written as $ra + sb$ for some $r, s \\in R
    correctIndex: 1,
    difficulty: 'medium',
    explanation: 'In a PID, the ideal $(a, b) = (d)$ for some $d$, and this $d$ is a gcd of $a$ and $b$. Since $d \\in (a, b)$, we have $d = ra + sb$ for some $r, s \\in R$ (Bezout\'s identity).',
  },
      'Always equals $ab
    correctIndex: 2,
    difficulty: 'medium',
    explanation: 'In a PID, the ideal $(a, b) = (d)$ for some $d$, and this $d$ is a gcd of $a$ and $b$. Since $d \\in (a, b)$, we have $d = ra + sb$ for some $r, s \\in R$ (Bezout\'s identity).',
  },
      'Is always a unit',
    ],
    correctIndex: 2,
    difficulty: 'medium',
    explanation: 'In a PID, the ideal $(a, b) = (d)$ for some $d$, and this $d$ is a gcd of $a$ and $b$. Since $d \\in (a, b)$, we have $d = ra + sb$ for some $r, s \\in R$ (Bezout\'s identity).',
  },
];
