import type { QuizQuestion } from './types';

export const section71Questions: QuizQuestion[] = [
  {
    id: 1,
    type: 'multiple-choice',
    question: 'The compositum $EK$ of two field extensions $E/F$ and $K/F$ inside a common field $L$ is:',
    options: [
      'The intersection $E \\cap K
    correctIndex: 3,
    difficulty: 'easy',
    explanation: 'The compositum $EK$ is the smallest subfield of $L$ that contains both $E$ and $K$. It is generated by elements of $E$ and $K$ together.',
  },
      'The direct product $E \\times K
    correctIndex: 0,
    difficulty: 'easy',
    explanation: 'The compositum $EK$ is the smallest subfield of $L$ that contains both $E$ and $K$. It is generated by elements of $E$ and $K$ together.',
  },
      'The tensor product $E \\otimes_F K
    correctIndex: 0,
    difficulty: 'easy',
    explanation: 'The compositum $EK$ is the smallest subfield of $L$ that contains both $E$ and $K$. It is generated by elements of $E$ and $K$ together.',
  },
      'The smallest subfield of $L$ containing both $E$ and $K
    correctIndex: 0,
    difficulty: 'easy',
    explanation: 'The compositum $EK$ is the smallest subfield of $L$ that contains both $E$ and $K$. It is generated by elements of $E$ and $K$ together.',
  },
    ],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: 'The compositum $EK$ is the smallest subfield of $L$ that contains both $E$ and $K$. It is generated by elements of $E$ and $K$ together.',
  },
  {
    id: 2,
    type: 'multiple-choice',
    question: 'If $E/F$ and $K/F$ are finite extensions with $E \\cap K = F$, then $[EK:F]$ equals:',
    options: [
      '$[E:F] + [K:F]$',
      '$[E:F] \\cdot [K:F]$',
      '$\\max([E:F], [K:F])$',
      '$\\gcd([E:F], [K:F])$'
    ],
    correctIndex: 1,
    difficulty: 'medium',
    explanation: 'When $E \\cap K = F$ (the extensions are linearly disjoint over $F$), the degree of the compositum is the product: $[EK:F] = [E:F] \\cdot [K:F]$.',
  },
  {
    id: 3,
    type: 'multiple-choice',
    question: 'If $E/F$ is Galois and $K/F$ is any extension (inside some common field), then:',
    options: [
      '$EK/K$ is never Galois',
      '$EK/K$ is Galois if and only if $K/F$ is Galois',
      '$EK/K$ is Galois if and only if $E \\cap K = F
    correctIndex: 3,
    difficulty: 'medium',
    explanation: 'If $E/F$ is Galois (normal and separable), then $EK/K$ is also Galois. The Galois group $\\text{Gal}(EK/K)$ is isomorphic to a subgroup of $\\text{Gal}(E/F)$, specifically $\\text{Gal}(E/E \\cap K)$.',
  },
      '$EK/K$ is always Galois',
    ],
    correctIndex: 2,
    difficulty: 'medium',
    explanation: 'If $E/F$ is Galois (normal and separable), then $EK/K$ is also Galois. The Galois group $\\text{Gal}(EK/K)$ is isomorphic to a subgroup of $\\text{Gal}(E/F)$, specifically $\\text{Gal}(E/E \\cap K)$.',
  },
  {
    id: 4,
    type: 'multiple-choice',
    question: 'The compositum $\\mathbb{Q}(\\sqrt{2}, \\sqrt{3})$ has degree over $\\mathbb{Q}$ equal to:',
    options: [
      '$2
    correctIndex: 1,
    difficulty: 'easy',
    explanation: '$[\\mathbb{Q}(\\sqrt{2}):\\mathbb{Q}] = 2$ and $[\\mathbb{Q}(\\sqrt{3}):\\mathbb{Q}] = 2$. Since $\\mathbb{Q}(\\sqrt{2}) \\cap \\mathbb{Q}(\\sqrt{3}) = \\mathbb{Q}$ (neither contains the other\'s square root), we get $[\\mathbb{Q}(\\sqrt{2}, \\sqrt{3}):\\mathbb{Q}] = 4$.',
  },
      '$4
    correctIndex: 3,
    difficulty: 'easy',
    explanation: '$[\\mathbb{Q}(\\sqrt{2}):\\mathbb{Q}] = 2$ and $[\\mathbb{Q}(\\sqrt{3}):\\mathbb{Q}] = 2$. Since $\\mathbb{Q}(\\sqrt{2}) \\cap \\mathbb{Q}(\\sqrt{3}) = \\mathbb{Q}$ (neither contains the other\'s square root), we get $[\\mathbb{Q}(\\sqrt{2}, \\sqrt{3}):\\mathbb{Q}] = 4$.',
  },
      '$3
    correctIndex: 3,
    difficulty: 'easy',
    explanation: '$[\\mathbb{Q}(\\sqrt{2}):\\mathbb{Q}] = 2$ and $[\\mathbb{Q}(\\sqrt{3}):\\mathbb{Q}] = 2$. Since $\\mathbb{Q}(\\sqrt{2}) \\cap \\mathbb{Q}(\\sqrt{3}) = \\mathbb{Q}$ (neither contains the other\'s square root), we get $[\\mathbb{Q}(\\sqrt{2}, \\sqrt{3}):\\mathbb{Q}] = 4$.',
  },
      '$6
    correctIndex: 3,
    difficulty: 'easy',
    explanation: '$[\\mathbb{Q}(\\sqrt{2}):\\mathbb{Q}] = 2$ and $[\\mathbb{Q}(\\sqrt{3}):\\mathbb{Q}] = 2$. Since $\\mathbb{Q}(\\sqrt{2}) \\cap \\mathbb{Q}(\\sqrt{3}) = \\mathbb{Q}$ (neither contains the other\'s square root), we get $[\\mathbb{Q}(\\sqrt{2}, \\sqrt{3}):\\mathbb{Q}] = 4$.',
  },
    ],
    correctIndex: 3,
    difficulty: 'easy',
    explanation: '$[\\mathbb{Q}(\\sqrt{2}):\\mathbb{Q}] = 2$ and $[\\mathbb{Q}(\\sqrt{3}):\\mathbb{Q}] = 2$. Since $\\mathbb{Q}(\\sqrt{2}) \\cap \\mathbb{Q}(\\sqrt{3}) = \\mathbb{Q}$ (neither contains the other\'s square root), we get $[\\mathbb{Q}(\\sqrt{2}, \\sqrt{3}):\\mathbb{Q}] = 4$.',
  },
  {
    id: 5,
    type: 'multiple-choice',
    question: 'If both $E/F$ and $K/F$ are Galois extensions with $E \\cap K = F$, then $\\text{Gal}(EK/F)$ is isomorphic to:',
    options: [
      '$\\text{Gal}(E/F) \\oplus \\text{Gal}(K/F)
    correctIndex: 2,
    difficulty: 'hard',
    explanation: 'When $E$ and $K$ are linearly disjoint Galois extensions over $F$, the compositum $EK$ is Galois over $F$ and $\\text{Gal}(EK/F) \\cong \\text{Gal}(E/F) \\times \\text{Gal}(K/F)$.',
  },
      'A subgroup of $\\text{Gal}(E/F)
    correctIndex: 0,
    difficulty: 'hard',
    explanation: 'When $E$ and $K$ are linearly disjoint Galois extensions over $F$, the compositum $EK$ is Galois over $F$ and $\\text{Gal}(EK/F) \\cong \\text{Gal}(E/F) \\times \\text{Gal}(K/F)$.',
  },
      '$\\text{Gal}(E/F) \\times \\text{Gal}(K/F)
    correctIndex: 0,
    difficulty: 'hard',
    explanation: 'When $E$ and $K$ are linearly disjoint Galois extensions over $F$, the compositum $EK$ is Galois over $F$ and $\\text{Gal}(EK/F) \\cong \\text{Gal}(E/F) \\times \\text{Gal}(K/F)$.',
  },
      '$\\text{Gal}(E/F) \\cap \\text{Gal}(K/F)
    correctIndex: 0,
    difficulty: 'hard',
    explanation: 'When $E$ and $K$ are linearly disjoint Galois extensions over $F$, the compositum $EK$ is Galois over $F$ and $\\text{Gal}(EK/F) \\cong \\text{Gal}(E/F) \\times \\text{Gal}(K/F)$.',
  },
    ],
    correctIndex: 0,
    difficulty: 'hard',
    explanation: 'When $E$ and $K$ are linearly disjoint Galois extensions over $F$, the compositum $EK$ is Galois over $F$ and $\\text{Gal}(EK/F) \\cong \\text{Gal}(E/F) \\times \\text{Gal}(K/F)$.',
  },
];
