import type { QuizQuestion } from './types';

export const section83Questions: QuizQuestion[] = [
  {
    id: 1,
    type: 'multiple-choice',
    question: 'A discrete valuation ring (DVR) is:',
    options: [
      'Any ring with a valuation function',
      'A local PID that is not a field',
      'A ring with finitely many ideals',
      'A ring where every element has finite order'
    ],
    correctIndex: 1,
    difficulty: 'easy',
    explanation: 'A DVR is a local principal ideal domain that is not a field. Equivalently, it is a Noetherian local ring with a principal maximal ideal generated by a uniformizer.',
  },
  {
    id: 2,
    type: 'multiple-choice',
    question: 'In a DVR with uniformizer $\\pi$, the nonzero ideals are:',
    options: [
      'Only the maximal ideal $(\\pi)$',
      '$(\\pi^n)$ for $n \\geq 0$',
      'All principal ideals',
      'All finitely generated ideals'
    ],
    correctIndex: 1,
    difficulty: 'medium',
    explanation: 'Every nonzero ideal in a DVR is of the form $(\\pi^n)$ for some $n \\geq 0$. The ideals form a chain: $R \\supsetneq (\\pi) \\supsetneq (\\pi^2) \\supsetneq \\cdots$',
  },
  {
    id: 3,
    type: 'multiple-choice',
    question: 'The discrete valuation $v$ on a DVR satisfies $v(\\pi^n u) = $ where $u$ is a unit:',
    options: [
      '$0$',
      '$n$',
      '$1$',
      '$v(u)$'
    ],
    correctIndex: 1,
    difficulty: 'easy',
    explanation: 'The valuation of $\\pi^n u$ is $n$. The valuation measures the "divisibility by $\\pi$." Units have valuation $0$, and $v(ab) = v(a) + v(b)$.',
  },
  {
    id: 4,
    type: 'multiple-choice',
    question: 'Which of the following is a DVR?',
    options: [
      '$\\mathbb{Z}$',
      '$\\mathbb{Z}_{(p)}$ (localization of $\\mathbb{Z}$ at $(p)$)',
      '$\\mathbb{Q}$',
      '$\\mathbb{Z}[x]$'
    ],
    correctIndex: 1,
    difficulty: 'medium',
    explanation: '$\\mathbb{Z}_{(p)}$ is a DVR with uniformizer $p$. It consists of fractions $a/b$ with $\\gcd(b, p) = 1$. The unique maximal ideal is $(p)$.',
  },
  {
    id: 5,
    type: 'multiple-choice',
    question: 'The field of fractions of a DVR with uniformizer $\\pi$ consists of elements of the form:',
    options: [
      '$\\pi^n u$ for $n \\geq 0$ and $u$ a unit',
      '$\\pi^n u$ for $n \\in \\mathbb{Z}$ and $u$ a unit',
      'Polynomials in $\\pi$',
      'Only units'
    ],
    correctIndex: 1,
    difficulty: 'medium',
    explanation: 'Every nonzero element of the fraction field can be written as $\\pi^n u$ where $n \\in \\mathbb{Z}$ (negative $n$ allowed) and $u$ is a unit. The valuation extends to $v(\\pi^n u) = n$.',
  },
];
