import type { QuizQuestion } from './types';

export const section58Questions: QuizQuestion[] = [
  {
    id: 1,
    type: 'multiple-choice',
    question: 'The tensor algebra $T(V)$ on a vector space $V$ is:',
    options: [
      '$V$ itself',
      '$\\bigoplus_{n=0}^{\\infty} V^{\\otimes n}$ with multiplication by tensor product',
      'The dual space $V^*$',
      'A finite-dimensional space'
    ],
    correctIndex: 1,
    difficulty: 'medium',
    explanation: '$T(V) = \\bigoplus_{n=0}^{\\infty} V^{\\otimes n} = F \\oplus V \\oplus (V \\otimes V) \\oplus \\cdots$ with multiplication given by the tensor product.',
  },
  {
    id: 2,
    type: 'multiple-choice',
    question: 'The symmetric algebra $S(V)$ is the quotient of $T(V)$ by:',
    options: [
      'The ideal generated by $v \\otimes v$ for all $v \\in V$',
      'The ideal generated by $v \\otimes w - w \\otimes v$ for all $v, w \\in V$',
      'The ideal generated by $v \\otimes w + w \\otimes v$ for all $v, w \\in V$',
      'No quotient needed'
    ],
    correctIndex: 1,
    difficulty: 'hard',
    explanation: '$S(V) = T(V)/I$ where $I$ is generated by $v \\otimes w - w \\otimes v$. This makes multiplication commutative: $vw = wv$ in $S(V)$.',
  },
  {
    id: 3,
    type: 'multiple-choice',
    question: 'The exterior (alternating) algebra $\\Lambda(V)$ satisfies:',
    options: [
      '$v \\wedge v = v$ for all $v$',
      '$v \\wedge v = 0$ for all $v \\in V$',
      '$v \\wedge w = w \\wedge v$ for all $v, w$',
      '$v \\wedge w = 0$ for all $v, w$'
    ],
    correctIndex: 1,
    difficulty: 'medium',
    explanation: 'In $\\Lambda(V)$, we have $v \\wedge v = 0$ for all $v$. This implies $v \\wedge w = -w \\wedge v$ (anticommutativity).',
  },
  {
    id: 4,
    type: 'multiple-choice',
    question: 'If $\\dim(V) = n$, then $\\dim(\\Lambda^k(V)) = $',
    options: [
      '$n^k$',
      '$k^n$',
      '$\\binom{n}{k}$',
      '$n!$'
    ],
    correctIndex: 2,
    difficulty: 'medium',
    explanation: '$\\dim(\\Lambda^k(V)) = \\binom{n}{k}$, the number of ways to choose $k$ basis vectors from $n$. Note $\\Lambda^k(V) = 0$ for $k > n$.',
  },
  {
    id: 5,
    type: 'multiple-choice',
    question: 'The top exterior power $\\Lambda^n(V)$ where $\\dim(V) = n$ has dimension:',
    options: [
      '$0$',
      '$1$',
      '$n$',
      '$n!$'
    ],
    correctIndex: 1,
    difficulty: 'easy',
    explanation: '$\\dim(\\Lambda^n(V)) = \\binom{n}{n} = 1$. This one-dimensional space is spanned by $e_1 \\wedge e_2 \\wedge \\cdots \\wedge e_n$ for any basis $\\{e_i\\}$.',
  },
];
