import type { QuizQuestion } from './types';

export const section70Questions: QuizQuestion[] = [
  {
    id: 1,
    type: 'multiple-choice',
    question: 'For any prime $p$ and positive integer $n$, there exists a finite field of order:',
    options: [
      '$pn
    correctIndex: 2,
    difficulty: 'easy',
    explanation: 'A finite field has order $p^n$ for some prime $p$ and positive integer $n$. For each such pair $(p, n)$, there exists a unique (up to isomorphism) field $\\mathbb{F}_{p^n}$.',
  },
      '$p + n
    correctIndex: 3,
    difficulty: 'easy',
    explanation: 'A finite field has order $p^n$ for some prime $p$ and positive integer $n$. For each such pair $(p, n)$, there exists a unique (up to isomorphism) field $\\mathbb{F}_{p^n}$.',
  },
      '$p^n
    correctIndex: 3,
    difficulty: 'easy',
    explanation: 'A finite field has order $p^n$ for some prime $p$ and positive integer $n$. For each such pair $(p, n)$, there exists a unique (up to isomorphism) field $\\mathbb{F}_{p^n}$.',
  },
      'Any positive integer',
    ],
    correctIndex: 3,
    difficulty: 'easy',
    explanation: 'A finite field has order $p^n$ for some prime $p$ and positive integer $n$. For each such pair $(p, n)$, there exists a unique (up to isomorphism) field $\\mathbb{F}_{p^n}$.',
  },
  {
    id: 2,
    type: 'multiple-choice',
    question: 'The multiplicative group $\\mathbb{F}_q^*$ of a finite field with $q$ elements is:',
    options: [
      'Cyclic of order $q
    correctIndex: 1,
    difficulty: 'easy',
    explanation: 'A fundamental theorem states that the multiplicative group of any finite field is cyclic. Since $|\\mathbb{F}_q^*| = q - 1$, we have $\\mathbb{F}_q^* \\cong \\mathbb{Z}/(q-1)\\mathbb{Z}$.',
  },
      'Cyclic of order $q - 1
    correctIndex: 0,
    difficulty: 'easy',
    explanation: 'A fundamental theorem states that the multiplicative group of any finite field is cyclic. Since $|\\mathbb{F}_q^*| = q - 1$, we have $\\mathbb{F}_q^* \\cong \\mathbb{Z}/(q-1)\\mathbb{Z}$.',
  },
      'Trivial',
      'Isomorphic to $\\mathbb{Z}/p\\mathbb{Z}$ where $q = p^n
    correctIndex: 0,
    difficulty: 'easy',
    explanation: 'A fundamental theorem states that the multiplicative group of any finite field is cyclic. Since $|\\mathbb{F}_q^*| = q - 1$, we have $\\mathbb{F}_q^* \\cong \\mathbb{Z}/(q-1)\\mathbb{Z}$.',
  },
    ],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: 'A fundamental theorem states that the multiplicative group of any finite field is cyclic. Since $|\\mathbb{F}_q^*| = q - 1$, we have $\\mathbb{F}_q^* \\cong \\mathbb{Z}/(q-1)\\mathbb{Z}$.',
  },
  {
    id: 3,
    type: 'multiple-choice',
    question: 'The finite field $\\mathbb{F}_{p^n}$ is the splitting field over $\\mathbb{F}_p$ of the polynomial:',
    options: [
      '$x^n - 1
    correctIndex: 3,
    difficulty: 'medium',
    explanation: 'The elements of $\\mathbb{F}_{p^n}$ are exactly the roots of $x^{p^n} - x$ in $\\overline{\\mathbb{F}_p}$. This polynomial splits completely and has $p^n$ distinct roots, all lying in $\\mathbb{F}_{p^n}$.',
  },
      '$x^p - x
    correctIndex: 1,
    difficulty: 'medium',
    explanation: 'The elements of $\\mathbb{F}_{p^n}$ are exactly the roots of $x^{p^n} - x$ in $\\overline{\\mathbb{F}_p}$. This polynomial splits completely and has $p^n$ distinct roots, all lying in $\\mathbb{F}_{p^n}$.',
  },
      '$x^{p^n} - 1
    correctIndex: 1,
    difficulty: 'medium',
    explanation: 'The elements of $\\mathbb{F}_{p^n}$ are exactly the roots of $x^{p^n} - x$ in $\\overline{\\mathbb{F}_p}$. This polynomial splits completely and has $p^n$ distinct roots, all lying in $\\mathbb{F}_{p^n}$.',
  },
      '$x^{p^n} - x
    correctIndex: 1,
    difficulty: 'medium',
    explanation: 'The elements of $\\mathbb{F}_{p^n}$ are exactly the roots of $x^{p^n} - x$ in $\\overline{\\mathbb{F}_p}$. This polynomial splits completely and has $p^n$ distinct roots, all lying in $\\mathbb{F}_{p^n}$.',
  },
    ],
    correctIndex: 1,
    difficulty: 'medium',
    explanation: 'The elements of $\\mathbb{F}_{p^n}$ are exactly the roots of $x^{p^n} - x$ in $\\overline{\\mathbb{F}_p}$. This polynomial splits completely and has $p^n$ distinct roots, all lying in $\\mathbb{F}_{p^n}$.',
  },
  {
    id: 4,
    type: 'multiple-choice',
    question: 'The Galois group $\\text{Gal}(\\mathbb{F}_{p^n}/\\mathbb{F}_p)$ is:',
    options: [
      'Cyclic of order $n$, generated by the Frobenius $x \\mapsto x^p
    correctIndex: 0,
    difficulty: 'medium',
    explanation: 'The Frobenius automorphism $\\phi: x \\mapsto x^p$ generates $\\text{Gal}(\\mathbb{F}_{p^n}/\\mathbb{F}_p)$. Since $\\phi^n = \\text{id}$ and $\\phi^k \\neq \\text{id}$ for $0 < k < n$, the Galois group is cyclic of order $n$.',
  },
      'Trivial',
      'Symmetric group $S_n
    correctIndex: 2,
    difficulty: 'medium',
    explanation: 'The Frobenius automorphism $\\phi: x \\mapsto x^p$ generates $\\text{Gal}(\\mathbb{F}_{p^n}/\\mathbb{F}_p)$. Since $\\phi^n = \\text{id}$ and $\\phi^k \\neq \\text{id}$ for $0 < k < n$, the Galois group is cyclic of order $n$.',
  },
      'Cyclic of order $p^n
    correctIndex: 2,
    difficulty: 'medium',
    explanation: 'The Frobenius automorphism $\\phi: x \\mapsto x^p$ generates $\\text{Gal}(\\mathbb{F}_{p^n}/\\mathbb{F}_p)$. Since $\\phi^n = \\text{id}$ and $\\phi^k \\neq \\text{id}$ for $0 < k < n$, the Galois group is cyclic of order $n$.',
  },
    ],
    correctIndex: 2,
    difficulty: 'medium',
    explanation: 'The Frobenius automorphism $\\phi: x \\mapsto x^p$ generates $\\text{Gal}(\\mathbb{F}_{p^n}/\\mathbb{F}_p)$. Since $\\phi^n = \\text{id}$ and $\\phi^k \\neq \\text{id}$ for $0 < k < n$, the Galois group is cyclic of order $n$.',
  },
  {
    id: 5,
    type: 'multiple-choice',
    question: '$\\mathbb{F}_{p^m}$ is a subfield of $\\mathbb{F}_{p^n}$ if and only if:',
    options: [
      '$m < n
    correctIndex: 1,
    difficulty: 'medium',
    explanation: '$\\mathbb{F}_{p^m} \\subseteq \\mathbb{F}_{p^n}$ if and only if $m | n$. This is because $\\mathbb{F}_{p^m}$ consists of roots of $x^{p^m} - x$, and $x^{p^m} - x$ divides $x^{p^n} - x$ if and only if $m | n$.',
  },
      '$m$ divides $n
    correctIndex: 3,
    difficulty: 'medium',
    explanation: '$\\mathbb{F}_{p^m} \\subseteq \\mathbb{F}_{p^n}$ if and only if $m | n$. This is because $\\mathbb{F}_{p^m}$ consists of roots of $x^{p^m} - x$, and $x^{p^m} - x$ divides $x^{p^n} - x$ if and only if $m | n$.',
  },
      '$m = n
    correctIndex: 3,
    difficulty: 'medium',
    explanation: '$\\mathbb{F}_{p^m} \\subseteq \\mathbb{F}_{p^n}$ if and only if $m | n$. This is because $\\mathbb{F}_{p^m}$ consists of roots of $x^{p^m} - x$, and $x^{p^m} - x$ divides $x^{p^n} - x$ if and only if $m | n$.',
  },
      '$\\gcd(m, n) = 1
    correctIndex: 3,
    difficulty: 'medium',
    explanation: '$\\mathbb{F}_{p^m} \\subseteq \\mathbb{F}_{p^n}$ if and only if $m | n$. This is because $\\mathbb{F}_{p^m}$ consists of roots of $x^{p^m} - x$, and $x^{p^m} - x$ divides $x^{p^n} - x$ if and only if $m | n$.',
  },
    ],
    correctIndex: 3,
    difficulty: 'medium',
    explanation: '$\\mathbb{F}_{p^m} \\subseteq \\mathbb{F}_{p^n}$ if and only if $m | n$. This is because $\\mathbb{F}_{p^m}$ consists of roots of $x^{p^m} - x$, and $x^{p^m} - x$ divides $x^{p^n} - x$ if and only if $m | n$.',
  },
];
