import type { QuizQuestion } from './types';

export const section40Questions: QuizQuestion[] = [
  {
    id: 1,
    type: 'multiple-choice',
    question: 'A Euclidean domain is an integral domain $R$ with a function $N: R \\setminus \\{0\\} \\to \\mathbb{Z}_{\\geq 0}$ such that:',
    options: [
      'For all $a, b \\in R$ with $b \\neq 0$, there exist $q, r$ with $a = bq + r$ and either $r = 0$ or $N(r) < N(b)
    correctIndex: 0,
    difficulty: 'medium',
    explanation: 'The defining property of a Euclidean domain is the division algorithm: for any $a$ and non-zero $b$, we can write $a = bq + r$ with remainder $r$ satisfying $r = 0$ or $N(r) < N(b)$.',
  },
      '$N(ab) = N(a) + N(b)
    correctIndex: 1,
    difficulty: 'medium',
    explanation: 'The defining property of a Euclidean domain is the division algorithm: for any $a$ and non-zero $b$, we can write $a = bq + r$ with remainder $r$ satisfying $r = 0$ or $N(r) < N(b)$.',
  },
      '$N(a) = 0$ implies $a = 0
    correctIndex: 1,
    difficulty: 'medium',
    explanation: 'The defining property of a Euclidean domain is the division algorithm: for any $a$ and non-zero $b$, we can write $a = bq + r$ with remainder $r$ satisfying $r = 0$ or $N(r) < N(b)$.',
  },
      '$N$ is a ring homomorphism',
    ],
    correctIndex: 1,
    difficulty: 'medium',
    explanation: 'The defining property of a Euclidean domain is the division algorithm: for any $a$ and non-zero $b$, we can write $a = bq + r$ with remainder $r$ satisfying $r = 0$ or $N(r) < N(b)$.',
  },
  {
    id: 2,
    type: 'multiple-choice',
    question: 'Which of the following is NOT a Euclidean domain?',
    options: [
      '$\\mathbb{Z}[x]
    correctIndex: 0,
    difficulty: 'medium',
    explanation: '$\\mathbb{Z}[x]$ is not a Euclidean domain. For example, you cannot perform division algorithm with $2$ and $x$ in $\\mathbb{Z}[x]$ since $x = 2q + r$ would require $r = x$ or $r = x - 2$, neither works.',
  },
      '$\\mathbb{Z}
    correctIndex: 2,
    difficulty: 'medium',
    explanation: '$\\mathbb{Z}[x]$ is not a Euclidean domain. For example, you cannot perform division algorithm with $2$ and $x$ in $\\mathbb{Z}[x]$ since $x = 2q + r$ would require $r = x$ or $r = x - 2$, neither works.',
  },
      '$\\mathbb{Q}[x]
    correctIndex: 2,
    difficulty: 'medium',
    explanation: '$\\mathbb{Z}[x]$ is not a Euclidean domain. For example, you cannot perform division algorithm with $2$ and $x$ in $\\mathbb{Z}[x]$ since $x = 2q + r$ would require $r = x$ or $r = x - 2$, neither works.',
  },
      '$\\mathbb{Z}[i]$ (Gaussian integers)',
    ],
    correctIndex: 2,
    difficulty: 'medium',
    explanation: '$\\mathbb{Z}[x]$ is not a Euclidean domain. For example, you cannot perform division algorithm with $2$ and $x$ in $\\mathbb{Z}[x]$ since $x = 2q + r$ would require $r = x$ or $r = x - 2$, neither works.',
  },
  {
    id: 3,
    type: 'multiple-choice',
    question: 'The Euclidean function on $\\mathbb{Z}$ is typically:',
    options: [
      '$N(a) = a
    correctIndex: 2,
    difficulty: 'easy',
    explanation: 'The standard Euclidean function on $\\mathbb{Z}$ is $N(a) = |a|$, the absolute value. This allows the usual division algorithm with $|r| < |b|$.',
  },
      '$N(a) = \\log|a|
    correctIndex: 3,
    difficulty: 'easy',
    explanation: 'The standard Euclidean function on $\\mathbb{Z}$ is $N(a) = |a|$, the absolute value. This allows the usual division algorithm with $|r| < |b|$.',
  },
      '$N(a) = |a|
    correctIndex: 3,
    difficulty: 'easy',
    explanation: 'The standard Euclidean function on $\\mathbb{Z}$ is $N(a) = |a|$, the absolute value. This allows the usual division algorithm with $|r| < |b|$.',
  },
      '$N(a) = a^2
    correctIndex: 3,
    difficulty: 'easy',
    explanation: 'The standard Euclidean function on $\\mathbb{Z}$ is $N(a) = |a|$, the absolute value. This allows the usual division algorithm with $|r| < |b|$.',
  },
    ],
    correctIndex: 3,
    difficulty: 'easy',
    explanation: 'The standard Euclidean function on $\\mathbb{Z}$ is $N(a) = |a|$, the absolute value. This allows the usual division algorithm with $|r| < |b|$.',
  },
  {
    id: 4,
    type: 'multiple-choice',
    question: 'Every Euclidean domain is:',
    options: [
      'A principal ideal domain (PID)',
      'A field',
      'A unique factorization domain only',
      'Finite',
    ],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: 'Every Euclidean domain is a PID. The Euclidean algorithm can be used to show that every ideal is principal (generated by the element of smallest norm in the ideal).',
  },
  {
    id: 5,
    type: 'multiple-choice',
    question: 'Using the Euclidean algorithm, $\\gcd(48, 18)$ in $\\mathbb{Z}$ is:',
    options: [
      '$2
    correctIndex: 3,
    difficulty: 'easy',
    explanation: '$48 = 18 \\cdot 2 + 12$, $18 = 12 \\cdot 1 + 6$, $12 = 6 \\cdot 2 + 0$. The last non-zero remainder is $6$, so $\\gcd(48, 18) = 6$.',
  },
      '$3
    correctIndex: 1,
    difficulty: 'easy',
    explanation: '$48 = 18 \\cdot 2 + 12$, $18 = 12 \\cdot 1 + 6$, $12 = 6 \\cdot 2 + 0$. The last non-zero remainder is $6$, so $\\gcd(48, 18) = 6$.',
  },
      '$12
    correctIndex: 1,
    difficulty: 'easy',
    explanation: '$48 = 18 \\cdot 2 + 12$, $18 = 12 \\cdot 1 + 6$, $12 = 6 \\cdot 2 + 0$. The last non-zero remainder is $6$, so $\\gcd(48, 18) = 6$.',
  },
      '$6
    correctIndex: 1,
    difficulty: 'easy',
    explanation: '$48 = 18 \\cdot 2 + 12$, $18 = 12 \\cdot 1 + 6$, $12 = 6 \\cdot 2 + 0$. The last non-zero remainder is $6$, so $\\gcd(48, 18) = 6$.',
  },
    ],
    correctIndex: 1,
    difficulty: 'easy',
    explanation: '$48 = 18 \\cdot 2 + 12$, $18 = 12 \\cdot 1 + 6$, $12 = 6 \\cdot 2 + 0$. The last non-zero remainder is $6$, so $\\gcd(48, 18) = 6$.',
  },
];
