import type { QuizQuestion } from './types';

export const section13Questions: QuizQuestion[] = [
  {
    id: 1,
    type: 'multiple-choice',
    question: 'The subgroup $\\langle S \\rangle$ generated by a subset $S$ of $G$ is:',
    options: [
      'The set $S$ itself',
      'The center of $G$',
      'The set of all products of elements in $S$',
      'The smallest subgroup containing $S$'
    ],
    correctIndex: 3,
    difficulty: 'easy',
    explanation: '$\\langle S \\rangle$ is the intersection of all subgroups containing $S$, which is the smallest such subgroup.',
  },
  {
    id: 2,
    type: 'multiple-choice',
    question: 'If $G = \\langle a, b \\rangle$, then every element of $G$ can be written as:',
    options: [
      'A product $a^m b^n$ for some integers $m, n
    correctIndex: 2,
    difficulty: 'medium',
    explanation: 'Elements of $\\langle a, b \\rangle$ are all finite products of $a, a^{-1}, b, b^{-1}$ (words in $a$ and $b$).',
  },
      'Either $a^m$ or $b^n$ for some integers $m, n
    correctIndex: 0,
    difficulty: 'medium',
    explanation: 'Elements of $\\langle a, b \\rangle$ are all finite products of $a, a^{-1}, b, b^{-1}$ (words in $a$ and $b$).',
  },
      'A product of $a$, $a^{-1}$, $b$, $b^{-1}$ in some order',
      '$ab$ or $ba$ only',
    ],
    correctIndex: 0,
    difficulty: 'medium',
    explanation: 'Elements of $\\langle a, b \\rangle$ are all finite products of $a, a^{-1}, b, b^{-1}$ (words in $a$ and $b$).',
  },
  {
    id: 3,
    type: 'multiple-choice',
    question: 'If $H = \\langle a \\rangle$ and $K = \\langle b \\rangle$ are subgroups of an abelian group $G$, then $\\langle a, b \\rangle$ equals:',
    options: [
      '$H \\cap K
    correctIndex: 3,
    difficulty: 'medium',
    explanation: 'In an abelian group, $\\langle a, b \\rangle = HK$ since products of powers of $a$ and $b$ can be rearranged.',
  },
      '$H \\cup K
    correctIndex: 1,
    difficulty: 'medium',
    explanation: 'In an abelian group, $\\langle a, b \\rangle = HK$ since products of powers of $a$ and $b$ can be rearranged.',
  },
      'Cannot be determined',
      '$HK = \\{hk : h \\in H, k \\in K\\}
    correctIndex: 1,
    difficulty: 'medium',
    explanation: 'In an abelian group, $\\langle a, b \\rangle = HK$ since products of powers of $a$ and $b$ can be rearranged.',
  },
    ],
    correctIndex: 1,
    difficulty: 'medium',
    explanation: 'In an abelian group, $\\langle a, b \\rangle = HK$ since products of powers of $a$ and $b$ can be rearranged.',
  },
  {
    id: 4,
    type: 'multiple-choice',
    question: 'If $G$ is a finite group and $g \\in G$ has order $n$, then $\\langle g \\rangle$ has:',
    options: [
      '$n$ elements',
      '$n - 1$ elements',
      '$n + 1$ elements',
      'Infinitely many elements',
    ],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: '$\\langle g \\rangle = \\{e, g, g^2, \\ldots, g^{n-1}\\}$ has exactly $n$ elements when $|g| = n$.',
  },
  {
    id: 5,
    type: 'multiple-choice',
    question: 'The subgroup generated by the empty set $\\langle \\emptyset \\rangle$ is:',
    options: [
      'The whole group $G
    correctIndex: 1,
    difficulty: 'medium',
    explanation: '$\\langle \\emptyset \\rangle = \\{e\\}$, the trivial subgroup, since it is the smallest subgroup (intersection of all subgroups).',
  },
      'The trivial subgroup $\\{e\\}
    correctIndex: 3,
    difficulty: 'medium',
    explanation: '$\\langle \\emptyset \\rangle = \\{e\\}$, the trivial subgroup, since it is the smallest subgroup (intersection of all subgroups).',
  },
      'The empty set',
      'Not defined',
    ],
    correctIndex: 3,
    difficulty: 'medium',
    explanation: '$\\langle \\emptyset \\rangle = \\{e\\}$, the trivial subgroup, since it is the smallest subgroup (intersection of all subgroups).',
  },
];
