import { useState, useMemo } from 'react';
import { motion, AnimatePresence } from 'framer-motion';

type IdealExample = {
  ringName: string;
  idealName: string;
  generator: string | string[];
  elements: string[];
  isPrincipal: boolean;
  isPrime: boolean;
  isMaximal: boolean;
  quotient: string;
  description: string;
};

const examples: IdealExample[] = [
  {
    ringName: 'Z',
    idealName: '(6)',
    generator: '6',
    elements: ['0', '±6', '±12', '±18', '...'],
    isPrincipal: true,
    isPrime: false,
    isMaximal: false,
    quotient: 'Z/6Z ≅ {0,1,2,3,4,5}',
    description: 'All multiples of 6. Not prime since 2·3 ∈ (6) but 2,3 ∉ (6).',
  },
  {
    ringName: 'Z',
    idealName: '(5)',
    generator: '5',
    elements: ['0', '±5', '±10', '±15', '...'],
    isPrincipal: true,
    isPrime: true,
    isMaximal: true,
    quotient: 'Z/5Z ≅ F_5 (field)',
    description: 'Prime ideal since Z/(5) is an integral domain. Maximal since Z/(5) is a field.',
  },
  {
    ringName: 'Z',
    idealName: '(0)',
    generator: '0',
    elements: ['0'],
    isPrincipal: true,
    isPrime: true,
    isMaximal: false,
    quotient: 'Z/(0) ≅ Z',
    description: 'Zero ideal. Prime (Z is integral domain) but not maximal.',
  },
  {
    ringName: 'Z[x]',
    idealName: '(x)',
    generator: 'x',
    elements: ['0', 'x', '2x', 'x²', 'x+x²', '...'],
    isPrincipal: true,
    isPrime: true,
    isMaximal: false,
    quotient: 'Z[x]/(x) ≅ Z',
    description: 'Polynomials with zero constant term. Prime but not maximal.',
  },
  {
    ringName: 'Z[x]',
    idealName: '(2, x)',
    generator: ['2', 'x'],
    elements: ['0', '2', '4', 'x', '2x', '2+x', '...'],
    isPrincipal: false,
    isPrime: true,
    isMaximal: true,
    quotient: 'Z[x]/(2,x) ≅ Z/2Z',
    description: 'NOT principal! Generated by 2 and x. Maximal since quotient is F_2.',
  },
  {
    ringName: 'Z[x]',
    idealName: '(x², x)',
    generator: ['x²', 'x'],
    elements: ['0', 'x', '2x', 'x²', 'x³', '...'],
    isPrincipal: true,
    isPrime: true,
    isMaximal: false,
    quotient: 'Z[x]/(x) ≅ Z',
    description: 'Actually equals (x)! Since x² ∈ (x).',
  },
];

export function IdealExplorer() {
  const [selectedExample, setSelectedExample] = useState(0);
  const [showContainment, setShowContainment] = useState(false);

  const example = examples[selectedExample];

  return (
    <div className="p-6 bg-dark-800 rounded-xl">
      <h4 className="text-lg font-semibold text-dark-100 mb-4">Ideal Explorer</h4>

      {/* Example Selector */}
      <div className="flex flex-wrap gap-2 mb-6">
        {examples.map((ex, idx) => (
          <button
            key={idx}
            onClick={() => setSelectedExample(idx)}
            className={`px-4 py-2 rounded transition-all ${
              selectedExample === idx
                ? ex.isMaximal ? 'bg-purple-600 text-white' :
                  ex.isPrime ? 'bg-blue-600 text-white' : 'bg-dark-600 text-white'
                : 'bg-dark-700 text-dark-300 hover:bg-dark-600'
            }`}
          >
            {ex.idealName} ⊂ {ex.ringName}
          </button>
        ))}
      </div>

      {/* Ideal Info */}
      <div className="bg-dark-700 p-4 rounded-lg mb-6">
        <div className="flex items-center gap-4 mb-3">
          <span className="text-dark-200 font-medium text-lg">{example.idealName}</span>
          <span className="text-dark-500">⊂</span>
          <span className="text-dark-200">{example.ringName}</span>
        </div>

        <div className="flex flex-wrap gap-2 mb-3">
          <span className={`px-3 py-1 rounded text-sm ${
            example.isPrincipal ? 'bg-green-900/50 text-green-400' : 'bg-red-900/50 text-red-400'
          }`}>
            {example.isPrincipal ? 'Principal' : 'Not Principal'}
          </span>
          <span className={`px-3 py-1 rounded text-sm ${
            example.isPrime ? 'bg-blue-900/50 text-blue-400' : 'bg-gray-900/50 text-gray-400'
          }`}>
            {example.isPrime ? 'Prime' : 'Not Prime'}
          </span>
          <span className={`px-3 py-1 rounded text-sm ${
            example.isMaximal ? 'bg-purple-900/50 text-purple-400' : 'bg-gray-900/50 text-gray-400'
          }`}>
            {example.isMaximal ? 'Maximal' : 'Not Maximal'}
          </span>
        </div>

        <div className="text-dark-400 text-sm">{example.description}</div>
      </div>

      {/* Generator Info */}
      <div className="bg-dark-700 p-4 rounded-lg mb-6">
        <h5 className="text-dark-200 font-medium mb-2">Generator(s)</h5>
        <div className="flex flex-wrap gap-2 mb-3">
          {Array.isArray(example.generator) ? (
            example.generator.map((g, idx) => (
              <span key={idx} className="bg-blue-900/50 text-blue-300 px-3 py-1 rounded font-mono">
                {g}
              </span>
            ))
          ) : (
            <span className="bg-blue-900/50 text-blue-300 px-3 py-1 rounded font-mono">
              {example.generator}
            </span>
          )}
        </div>

        <div className="text-dark-400 text-sm mb-2">Elements:</div>
        <div className="flex flex-wrap gap-2">
          {example.elements.map((el, idx) => (
            <span key={idx} className="bg-dark-600 text-dark-300 px-2 py-1 rounded text-sm font-mono">
              {el}
            </span>
          ))}
        </div>
      </div>

      {/* Quotient Ring */}
      <div className="bg-dark-700 p-4 rounded-lg mb-6">
        <h5 className="text-dark-200 font-medium mb-2">Quotient Ring</h5>
        <div className="font-mono text-lg text-center mb-2">
          <span className="text-blue-400">{example.ringName}</span>
          <span className="text-dark-500">/</span>
          <span className="text-purple-400">{example.idealName}</span>
          <span className="text-dark-500 mx-2">≅</span>
          <span className="text-green-400">{example.quotient}</span>
        </div>
        <div className="text-dark-500 text-sm text-center">
          {example.isPrime && 'Quotient is an integral domain (I is prime)'}
          {example.isMaximal && !example.isPrime && 'Quotient is a field (I is maximal)'}
          {example.isMaximal && example.isPrime && 'Quotient is a field (I is maximal ⟹ prime)'}
          {!example.isPrime && !example.isMaximal && 'Quotient has zero divisors'}
        </div>
      </div>

      {/* Ideal Containment Diagram */}
      <button
        onClick={() => setShowContainment(!showContainment)}
        className="mb-4 text-sm text-blue-400 hover:text-blue-300"
      >
        {showContainment ? '▼' : '▶'} Ideal Containments in Z[x]
      </button>

      <AnimatePresence>
        {showContainment && (
          <motion.div
            initial={{ opacity: 0, height: 0 }}
            animate={{ opacity: 1, height: 'auto' }}
            exit={{ opacity: 0, height: 0 }}
            className="bg-dark-700 p-4 rounded-lg overflow-hidden"
          >
            <div className="text-center">
              <div className="text-purple-400 mb-2">(2, x) - maximal</div>
              <div className="text-dark-500 text-2xl">↑</div>
              <div className="flex justify-center gap-8 mb-2">
                <span className="text-blue-400">(2)</span>
                <span className="text-blue-400">(x)</span>
              </div>
              <div className="text-dark-500 text-2xl">↑</div>
              <div className="text-dark-400">(0)</div>
            </div>
            <div className="mt-4 text-dark-500 text-xs text-center">
              (2) and (x) are prime. (2,x) is their sum, hence maximal.
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Prime vs Maximal Reference */}
      <div className="mt-6 p-4 bg-dark-700/50 rounded-lg">
        <h5 className="text-dark-200 font-medium mb-2">Key Facts</h5>
        <ul className="text-dark-400 text-sm space-y-1">
          <li>• <span className="text-purple-400">Maximal</span> ⟹ <span className="text-blue-400">Prime</span> (always)</li>
          <li>• In a PID: <span className="text-blue-400">nonzero Prime</span> ⟺ <span className="text-purple-400">Maximal</span></li>
          <li>• I is prime ⟺ R/I is an integral domain</li>
          <li>• I is maximal ⟺ R/I is a field</li>
        </ul>
      </div>
    </div>
  );
}
