import { LessonLayout } from '@/components/layout/LessonLayout';
import { Definition, Theorem, Example } from '@/components/common';
import { MathBlock, InlineMath } from '@/components/common/MathBlock';
import { Callout } from '@/components/common/Callout';

export default function Section08() {
  return (
    <LessonLayout sectionId={8}>
      <h2>Finite Fields</h2>

      <p>
        For the construction of BCH codes, we need to study the construction of finite fields.
        The construction of finite fields depends heavily on some results on commutative rings.
        We first recall these results on rings, although briefly.
      </p>

      <h3>Quotient Rings and Principal Ideals</h3>

      <Definition title="Quotient Ring">
        Let <InlineMath math="R" /> be a ring and <InlineMath math="I" /> be an ideal of <InlineMath math="R" />.
        Consider the set <InlineMath math="R/I = \\{x + I \\mid x \\in R\\}" />, where <InlineMath math="x + I = \\{x + a : a \\in R\\}" /> are
        cosets of the ideal <InlineMath math="I" /> in <InlineMath math="R" />. Using the ideal properties of <InlineMath math="I" />, we have:
        <MathBlock math="(x + I) + (y + I) = (x + y) + I" />
        <MathBlock math="(x + I)(y + I) = xy + I" />
        With these compositions, <InlineMath math="R/I" /> is a ring called the <strong>ring of quotients</strong> or
        the <strong>difference ring</strong> of <InlineMath math="R" /> relative to the ideal <InlineMath math="I" />.
      </Definition>

      <Definition title="Principal Ideal">
        Let <InlineMath math="R" /> be a commutative ring with identity and <InlineMath math="a \\in R" />. Then
        <InlineMath math="\\langle a \\rangle = aR = \\{ar : r \\in R\\}" /> is an ideal of <InlineMath math="R" /> called
        a <strong>principal ideal</strong> generated by <InlineMath math="a" />. If every ideal of <InlineMath math="R" /> is
        of this form, <InlineMath math="R" /> is called a <strong>principal ideal ring</strong>.
      </Definition>

      <Theorem
        title="F[X] is a Principal Ideal Ring"
        proof={
          <>
            <p>
              The ring <InlineMath math="F[X]" /> is already a commutative ring with identity. Let <InlineMath math="I" /> be an
              ideal of <InlineMath math="F[X]" />. If <InlineMath math="I = 0" />, then <InlineMath math="I" /> is a principal ideal
              generated by 0.
            </p>
            <p className="mt-2">
              Suppose <InlineMath math="I \\neq 0" />. Choose a <InlineMath math="0 \\neq f(X) \\in I" /> such that:
            </p>
            <MathBlock math="\\deg f(X) \\leq \\deg g(X) \\quad \\forall 0 \\neq g(X) \\in I" />
            <p className="mt-2">
              For any <InlineMath math="g(X) \\in F[X]" />, we claim that <InlineMath math="g(X) = q(X)f(X) + r(X)" /> for some
              <InlineMath math="q(X), r(X) \\in F[X]" /> where either <InlineMath math="r(X) = 0" /> or
              <InlineMath math="\\deg r(X) < \\deg f(X)" />.
            </p>
            <p className="mt-2">
              If <InlineMath math="r(X) \\neq 0" />, then <InlineMath math="r(X) = g(X) - q(X)f(X) \\in I" /> and
              <InlineMath math="\\deg r(X) < \\deg f(X)" />. This contradicts the choice of <InlineMath math="f(X)" />.
              Hence <InlineMath math="g(X) = q(X)f(X)" /> and <InlineMath math="I" /> is a principal ideal generated
              by <InlineMath math="f(X)" />.
            </p>
          </>
        }
      >
        The polynomial ring <InlineMath math="F[X]" />, where <InlineMath math="F" /> is a field, is a principal ideal ring.
      </Theorem>

      <h3>Irreducible Polynomials</h3>

      <Definition title="Irreducible Polynomial">
        A non-constant polynomial <InlineMath math="f(X) \\in R[X]" />, where <InlineMath math="R" /> is a commutative ring with
        identity, is called <strong>irreducible</strong> if:
        <MathBlock math="f(X) = g(X)h(X) \\text{ for } g(X), h(X) \\in R[X] \\Rightarrow \\deg g(X) = 0 \\text{ or } \\deg h(X) = 0" />
        Otherwise, we say that <InlineMath math="f(X)" /> is <strong>reducible</strong>.
      </Definition>

      <Theorem
        title="Irreducible Polynomials Generate Fields"
        proof={
          <>
            <p>
              Let <InlineMath math="I" /> denote the ideal <InlineMath math="\\langle f(X) \\rangle" /> of <InlineMath math="F[X]" /> generated
              by <InlineMath math="f(X)" />. If <InlineMath math="I = F[X]" />, then <InlineMath math="1 = f(X)g(X)" /> for
              some <InlineMath math="g(X) \\in F[X]" />. Comparing degrees implies <InlineMath math="f(X)" /> is constant, a contradiction.
              Hence <InlineMath math="F[X]/I" /> has at least two elements.
            </p>
            <p className="mt-2">
              Let <InlineMath math="g(X) \\in F[X]" />, <InlineMath math="g(X) \\notin I" />. Then:
            </p>
            <MathBlock math="J = \\{a(X)f(X) + b(X)g(X) : a(X), b(X) \\in F[X]\\}" />
            <p className="mt-2">
              is an ideal of <InlineMath math="F[X]" /> and there exists <InlineMath math="h(X) \\in F[X]" /> such
              that <InlineMath math="J = \\langle h(X) \\rangle" />. Irreducibility of <InlineMath math="f(X)" /> shows
              that <InlineMath math="h(X)" /> is a unit in <InlineMath math="F[X]" /> and <InlineMath math="J = F[X]" />.
            </p>
            <p className="mt-2">
              Therefore <InlineMath math="1 = a(X)f(X) + b(X)g(X)" /> for some <InlineMath math="a(X), b(X) \\in F[X]" /> and:
            </p>
            <MathBlock math="1 + I = (b(X) + I)(g(X) + I)" />
            <p className="mt-2">
              Thus <InlineMath math="g(X) + I" /> is invertible and <InlineMath math="F[X]/I" /> is a field.
            </p>
          </>
        }
      >
        Let <InlineMath math="F" /> be a field and <InlineMath math="f(X) \\in F[X]" /> be an irreducible polynomial.
        Then <InlineMath math="F[X]/\\langle f(X) \\rangle" /> is a field.
      </Theorem>

      <h3>Field Extensions</h3>

      <Definition title="Field Extension">
        Let <InlineMath math="K" /> be a field and <InlineMath math="F" /> be a subfield of <InlineMath math="K" />. Then <InlineMath math="K" /> is
        called an <strong>extension</strong> of the field <InlineMath math="F" />. This is expressed by writing:
        <MathBlock math="K|_F" />
        <InlineMath math="K" /> can be regarded as a vector space over <InlineMath math="F" />. The dimension of this
        vector space is called the <strong>degree</strong> of the extension and is denoted
        by <InlineMath math="[K:F]" />. The extension is called <strong>finite</strong> if <InlineMath math="[K:F]" /> is finite.
      </Definition>

      <Definition title="Algebraic Elements">
        Let <InlineMath math="K|_F" /> be an extension of a field <InlineMath math="F" />. An element <InlineMath math="\\alpha \\in K" /> is
        said to be <strong>algebraic</strong> over <InlineMath math="F" /> if there exists a
        polynomial <InlineMath math="f(X) \\in F[X]" /> which has <InlineMath math="\\alpha" /> as a root.
      </Definition>

      <Definition title="Minimal Polynomial">
        Let <InlineMath math="\\alpha \\in K" /> be algebraic over <InlineMath math="F" />. The <strong>minimal polynomial</strong>
        of <InlineMath math="\\alpha" /> over <InlineMath math="F" /> is the unique monic, irreducible polynomial <InlineMath math="m(X)" /> of
        the least possible degree which has <InlineMath math="\\alpha" /> as a root.
      </Definition>

      <h3>Order of Finite Fields</h3>

      <Theorem
        title="Order of a Finite Field"
        proof={
          <>
            <p>
              Let <InlineMath math="F" /> be a finite field. Since <InlineMath math="F" /> is a finite group w.r.t. addition,
              it follows from Lagrange's theorem that <InlineMath math="O(F) \\cdot a = 0 \\, \\forall a \\in F" />.
            </p>
            <p className="mt-2">
              Choose <InlineMath math="m" /> to be the smallest positive integer with <InlineMath math="ma = 0" /> for
              every <InlineMath math="a \\in F" />. If <InlineMath math="m = rs" /> where <InlineMath math="r > 1, s > 1" />, then:
            </p>
            <MathBlock math="0 = me = (rs)e = (re)(se)" />
            <p className="mt-2">
              Therefore either <InlineMath math="re = 0" /> or <InlineMath math="se = 0" />, contradicting the choice
              of <InlineMath math="m" />. Hence <InlineMath math="m" /> must be a prime <InlineMath math="p" />.
            </p>
            <p className="mt-2">
              The set <InlineMath math="K = \\{re : 0 \\leq r < p\\}" /> is a subfield of <InlineMath math="F" />. Since <InlineMath math="F" /> is
              finite, <InlineMath math="F" /> is a finite dimensional vector space over <InlineMath math="K" />.
              If <InlineMath math="\\dim_K F = n" />, and <InlineMath math="x_1, x_2, \\ldots, x_n" /> is a basis of <InlineMath math="F" /> over <InlineMath math="K" />,
              then every element of <InlineMath math="F" /> can be uniquely written as:
            </p>
            <MathBlock math="a_1 x_1 + a_2 x_2 + \\cdots + a_n x_n, \\quad a_i \\in K" />
            <p className="mt-2">
              Since each <InlineMath math="a_i" /> has exactly <InlineMath math="p" /> choices and choices are independent,
              there are exactly <InlineMath math="p^n" /> elements in <InlineMath math="F" />.
            </p>
          </>
        }
      >
        The order of a finite field is <InlineMath math="p^n" /> for some prime <InlineMath math="p" /> and some positive
        integer <InlineMath math="n" />.
      </Theorem>

      <Callout type="info">
        <strong>Notation:</strong> A finite field is called a <strong>Galois field</strong>. If <InlineMath math="F" /> is a field
        of order <InlineMath math="p^n" />, we write <InlineMath math="F = GF(p^n)" />.
      </Callout>

      <p>
        Let <InlineMath math="F" /> be a finite field of order <InlineMath math="p^n" />. Then <InlineMath math="F^* = F \\setminus \\{0\\}" /> is
        a multiplicative group of order <InlineMath math="p^n - 1" />. By Lagrange's theorem:
      </p>
      <MathBlock math="a^{p^n - 1} = 1 \\quad \\forall a \\in F^*" />
      <p>or equivalently:</p>
      <MathBlock math="a^{p^n} = a \\quad \\forall a \\in F" />

      <Theorem
        title="Multiplicative Group is Cyclic"
        proof={
          <>
            <p>
              The multiplicative group <InlineMath math="F^*" /> of <InlineMath math="F" /> is an Abelian group of
              order <InlineMath math="q - 1" />, where <InlineMath math="q = p^n" />.
            </p>
            <p className="mt-2">
              If <InlineMath math="F^*" /> is not cyclic, there exists an integer <InlineMath math="r" />,
              <InlineMath math="1 < r < q - 1" /> such that <InlineMath math="a^r = 1 \\, \\forall a \\in F^*" />.
            </p>
            <p className="mt-2">
              Thus every <InlineMath math="a \\in F" /> is a root of the polynomial <InlineMath math="X^{r+1} - X" />. Hence:
            </p>
            <MathBlock math="\\prod_{a \\in F}(X - a) \\mid X^{r+1} - X" />
            <p className="mt-2">
              But <InlineMath math="\\deg \\prod_{a \\in F}(X - a) = O(F) = q" /> and <InlineMath math="r + 1 < q - 1 + 1 = q" />.
              This is a contradiction. Hence <InlineMath math="F^*" /> is cyclic.
            </p>
          </>
        }
      >
        In any finite field <InlineMath math="F = GF(p^n)" />, the multiplicative group <InlineMath math="F^*" /> of all
        non-zero elements is cyclic.
      </Theorem>

      <Definition title="Primitive Element">
        A generator of the cyclic group <InlineMath math="F^*" /> of the finite field <InlineMath math="F" /> is called
        a <strong>primitive element</strong> of <InlineMath math="F" />.
      </Definition>

      <Callout type="success">
        <strong>Counting Primitive Elements:</strong> In a field of order <InlineMath math="p^n" />, there are
        exactly <InlineMath math="\\phi(p^n - 1)" /> primitive elements, where <InlineMath math="\\phi" /> is Euler's phi-function.
      </Callout>

      <h3>Constructing Finite Fields</h3>

      <p>
        To construct a field <InlineMath math="K" /> of order <InlineMath math="p^n" />, we need to find an irreducible
        polynomial <InlineMath math="f(X)" /> of degree <InlineMath math="n" /> over the field of <InlineMath math="p" /> elements.
        Then <InlineMath math="K = F_p[X]/\\langle f(X) \\rangle" /> is a field of order <InlineMath math="p^n" />.
      </p>

      <Theorem
        title="Irreducibility Test for Degree 2 or 3"
        proof={
          <>
            <p>
              Suppose <InlineMath math="f(X)" /> is reducible. Then <InlineMath math="f(X)" /> has a linear
              factor <InlineMath math="aX + b" />, where <InlineMath math="a, b \\in F" />, <InlineMath math="a \\neq 0" />.
              Then <InlineMath math="-b/a \\in F" /> is a root of <InlineMath math="f(X)" />.
            </p>
            <p className="mt-2">
              Conversely, suppose <InlineMath math="\\alpha \\in F" /> is a root of <InlineMath math="f(X)" />.
              Then <InlineMath math="(X - \\alpha) \\mid f(X)" />, so <InlineMath math="f(X)" /> is reducible.
            </p>
          </>
        }
      >
        Let <InlineMath math="f(X)" /> be a polynomial of degree 2 or 3 over a field <InlineMath math="F" />.
        Then <InlineMath math="f(X)" /> is irreducible if and only if none of the elements of <InlineMath math="F" /> is
        a root of <InlineMath math="f(X)" />.
      </Theorem>

      <Example title="Constructing GF(25)">
        <p>
          Let <InlineMath math="F" /> be the field of 5 elements. None of the elements of <InlineMath math="F" /> is a root of
          the polynomial <InlineMath math="f(X) = X^2 + 2" /> and so <InlineMath math="f(X)" /> is irreducible
          in <InlineMath math="F[X]" />. Hence:
        </p>
        <MathBlock math="K = F[X]/\\langle f(X) \\rangle" />
        <p className="mt-2">
          is a field of order 25. An arbitrary element of <InlineMath math="K" /> is of the
          form <InlineMath math="aX + b + \\langle f(X) \\rangle" /> for <InlineMath math="a, b \\in F" />.
        </p>
        <p className="mt-2">
          Write <InlineMath math="\\alpha = X + \\langle f(X) \\rangle" />. Then the powers of <InlineMath math="\\alpha" /> are:
        </p>
        <MathBlock math="\\alpha^2 = 3, \\quad \\alpha^3 = 3\\alpha, \\quad \\alpha^4 = 4, \\quad \\alpha^5 = 4\\alpha, \\quad \\alpha^6 = 2, \\quad \\alpha^7 = 2\\alpha, \\quad \\alpha^8 = 1" />
        <p className="mt-2">
          Thus <InlineMath math="\\alpha" /> is not a primitive element of <InlineMath math="K" /> (since its order is 8, not 24).
        </p>
      </Example>

      <Example title="Constructing GF(8)">
        <p>
          Let <InlineMath math="\\mathbb{B}" /> be the field of 2 elements. Neither 0 nor 1 is a root of
          <InlineMath math="X^3 + X + 1" />, so this polynomial is irreducible over <InlineMath math="\\mathbb{B}" />.
        </p>
        <MathBlock math="K = \\mathbb{B}[X]/\\langle X^3 + X + 1 \\rangle" />
        <p className="mt-2">
          is a field of order 8. Let <InlineMath math="\\alpha = X + \\langle X^3 + X + 1 \\rangle" />.
        </p>
        <p className="mt-2">
          The multiplicative group of <InlineMath math="K" /> is of order 7 (a prime), so any non-zero,
          non-identity element of <InlineMath math="K" /> is primitive. In particular, <InlineMath math="\\alpha" /> is primitive.
        </p>
      </Example>

      <Example title="Constructing GF(16)">
        <p>
          Consider the polynomial <InlineMath math="X^4 + X + 1 \\in \\mathbb{B}[X]" />. Neither 0 nor 1 is a root.
          For <InlineMath math="f(X)" /> to be reducible, it must be a product of quadratics. But:
        </p>
        <MathBlock math="(X^2 + X + 1)^2 = X^4 + X^2 + 1 \\neq X^4 + X + 1" />
        <p className="mt-2">
          Thus <InlineMath math="f(X) = X^4 + X + 1" /> is irreducible and:
        </p>
        <MathBlock math="K = \\mathbb{B}[X]/\\langle f(X) \\rangle" />
        <p className="mt-2">
          is a field of order 16. Let <InlineMath math="\\alpha = X + \\langle f(X) \\rangle" />. Then:
        </p>
        <MathBlock math="\\alpha^4 = \\alpha + 1 \\neq 1, \\quad \\alpha^5 = \\alpha^2 + \\alpha \\neq 1" />
        <p className="mt-2">
          Since <InlineMath math="O(\\alpha)" /> divides 15, and <InlineMath math="\\alpha^3 \\neq 1" />, <InlineMath math="\\alpha^5 \\neq 1" />,
          we have <InlineMath math="\\alpha" /> is a primitive element of <InlineMath math="K" />.
        </p>
      </Example>

      <Callout type="warning">
        <strong>Note:</strong> The minimal polynomial of an element depends on the subfield. For
        example, the minimal polynomial of <InlineMath math="\\alpha = \\sqrt{2}" /> over <InlineMath math="\\mathbb{Q}" /> is <InlineMath math="X^2 - 2" />,
        while over <InlineMath math="\\mathbb{R}" /> it is <InlineMath math="X - \\sqrt{2}" />.
      </Callout>

      <Theorem
        title="Same Minimal Polynomial"
        proof={
          <>
            <p>
              Define a map <InlineMath math="\\theta: F \\to F" /> by <InlineMath math="\\theta(a) = a^p" />,
              <InlineMath math="a \\in F" />. Since <InlineMath math="pa = 0 \\, \\forall a \\in F" />,
              <InlineMath math="ab = ba \\, \\forall a, b \\in F" />, and <InlineMath math="p" /> divides
              <InlineMath math="\\binom{p}{i}" /> for <InlineMath math="1 \\leq i \\leq p-1" />, it follows
              that <InlineMath math="\\theta" /> is a homomorphism of fields.
            </p>
            <p className="mt-2">
              Since <InlineMath math="a^p \\neq 0" /> for <InlineMath math="a \\neq 0" />, <InlineMath math="\\theta" /> is
              a monomorphism. For any <InlineMath math="a \\in k" />, <InlineMath math="a^p = a" /> so <InlineMath math="\\theta" /> keeps
              the elements of the prime subfield <InlineMath math="k" /> fixed.
            </p>
            <p className="mt-2">
              Let <InlineMath math="a \\in F" /> and <InlineMath math="m(X)" /> be the minimal polynomial of <InlineMath math="\\alpha" />.
              Then <InlineMath math="m(\\alpha) = 0" /> and <InlineMath math="\\theta" /> being a field homomorphism,
              <InlineMath math="m(\\alpha^p) = 0" />. Thus <InlineMath math="\\alpha^p" /> is also a root of <InlineMath math="m(X)" />.
            </p>
            <p className="mt-2">
              If <InlineMath math="m_1(X)" /> is the minimal polynomial of <InlineMath math="\\alpha^p" />,
              then <InlineMath math="m_1(X) \\mid m(X)" />. But <InlineMath math="m(X)" /> is irreducible and monic.
              Therefore <InlineMath math="m_1(X) = m(X)" />.
            </p>
          </>
        }
      >
        Let <InlineMath math="F" /> be a finite field of order <InlineMath math="p^n" /> with <InlineMath math="k" /> as its prime subfield.
        Then <InlineMath math="\\alpha" /> and <InlineMath math="\\alpha^p" /> have the same minimal polynomial
        over <InlineMath math="k" /> for every <InlineMath math="\\alpha \\in F" />.
      </Theorem>

      <Theorem
        title="Degree Relation for Extensions"
        proof={
          <>
            <p>
              Let <InlineMath math="[L:K] = m" /> and <InlineMath math="[K:F] = n" />. Let <InlineMath math="\\alpha_1, \\ldots, \\alpha_n" /> be
              a basis of <InlineMath math="K" /> over <InlineMath math="F" /> and <InlineMath math="\\beta_1, \\ldots, \\beta_m" /> be a basis
              of <InlineMath math="L" /> over <InlineMath math="K" />.
            </p>
            <p className="mt-2">
              Let <InlineMath math="x \\in L" />. Then there exist <InlineMath math="y_1, \\ldots, y_m \\in K" /> such that:
            </p>
            <MathBlock math="x = \\sum_{i=1}^{m} y_i \\beta_i" />
            <p className="mt-2">
              For every <InlineMath math="y_i" />, there exist <InlineMath math="a_{ij} \\in F" /> such
              that <InlineMath math="y_i = \\sum_{j=1}^{n} a_{ij} \\alpha_j" />.
            </p>
            <p className="mt-2">
              Substituting, <InlineMath math="x" /> can be expressed as a linear combination of the
              elements <InlineMath math="\\{\\alpha_j \\beta_i\\}" /> with coefficients in <InlineMath math="F" />.
            </p>
            <p className="mt-2">
              To show these are linearly independent: suppose <InlineMath math="\\sum_{i,j} a_{ij} \\alpha_j \\beta_i = 0" />.
              Then <InlineMath math="\\sum_i (\\sum_j a_{ij} \\alpha_j) \\beta_i = 0" />.
              Since <InlineMath math="\\{\\beta_i\\}" /> is a basis of <InlineMath math="L" /> over <InlineMath math="K" />:
            </p>
            <MathBlock math="\\sum_j a_{ij} \\alpha_j = 0 \\quad \\forall i" />
            <p className="mt-2">
              Since <InlineMath math="\\{\\alpha_j\\}" /> is a basis of <InlineMath math="K" /> over <InlineMath math="F" />:
              <InlineMath math="a_{ij} = 0 \\, \\forall i, j" />.
            </p>
            <p className="mt-2">
              Thus <InlineMath math="\\{\\alpha_j \\beta_i\\}" /> is a basis of <InlineMath math="L" /> over <InlineMath math="F" /> and
              <InlineMath math="[L:F] = mn = [L:K][K:F]" />.
            </p>
          </>
        }
      >
        Let <InlineMath math="K" /> be a finite extension of <InlineMath math="F" /> and <InlineMath math="L" /> be a finite extension
        of <InlineMath math="K" />. Then <InlineMath math="L" /> is a finite extension of <InlineMath math="F" /> and:
        <MathBlock math="[L:F] = [L:K][K:F]" />
      </Theorem>
    </LessonLayout>
  );
}
