import { LessonLayout } from '@/components/layout/LessonLayout';
import { Definition, Theorem, Example } from '@/components/common';
import { MathBlock, InlineMath } from '@/components/common/MathBlock';
import { Callout } from '@/components/common/Callout';

export default function Section21() {
  return (
    <LessonLayout sectionId={21}>
      <p>
        In this section, we explore the deep connection between cyclic codes and group
        algebras. This perspective provides elegant theoretical insights and connects
        coding theory to representation theory.
      </p>

      <h2 className="text-2xl font-bold mt-8 mb-4 text-gradient">Group Algebras</h2>

      <Definition title="Group Algebra">
        <p>
          Let <InlineMath>{`G`}</InlineMath> be a finite group and <InlineMath>{`F`}</InlineMath> be a field.
          The <strong>group algebra</strong> <InlineMath>{`F[G]`}</InlineMath> is the set of all formal
          linear combinations:
        </p>
        <MathBlock>{`F[G] = \\left\\{ \\sum_{g \\in G} a_g g \\mid a_g \\in F \\right\\}`}</MathBlock>
        <p className="mt-2">
          with addition defined componentwise and multiplication extending the group
          operation linearly:
        </p>
        <MathBlock>{`\\left( \\sum_{g \\in G} a_g g \\right) \\cdot \\left( \\sum_{h \\in G} b_h h \\right) = \\sum_{g, h \\in G} a_g b_h (gh)`}</MathBlock>
      </Definition>

      <p className="mt-4">
        The group algebra <InlineMath>{`F[G]`}</InlineMath> is a ring with identity <InlineMath>{`1 \\cdot e`}</InlineMath>,
        where <InlineMath>{`e`}</InlineMath> is the identity element of <InlineMath>{`G`}</InlineMath>. It is also
        a vector space over <InlineMath>{`F`}</InlineMath> of dimension <InlineMath>{`|G|`}</InlineMath>.
      </p>

      <Definition title="Cyclic Group Algebra">
        <p>
          Let <InlineMath>{`C_n = \\langle \\sigma \\rangle`}</InlineMath> be the cyclic group of
          order <InlineMath>{`n`}</InlineMath> generated by <InlineMath>{`\\sigma`}</InlineMath>. The group
          algebra <InlineMath>{`F[C_n]`}</InlineMath> consists of elements:
        </p>
        <MathBlock>{`\\sum_{i=0}^{n-1} a_i \\sigma^i \\quad \\text{where } a_i \\in F`}</MathBlock>
        <p className="mt-2">
          The multiplication rule uses <InlineMath>{`\\sigma^n = 1`}</InlineMath> (the identity).
        </p>
      </Definition>

      <Theorem
        title="Isomorphism to Quotient Ring"
        proof={
          <>
            <p>
              Define <InlineMath>{`\\phi: F[C_n] \\to F[X]/\\langle X^n - 1 \\rangle`}</InlineMath> by:
            </p>
            <MathBlock>{`\\phi\\left( \\sum_{i=0}^{n-1} a_i \\sigma^i \\right) = \\sum_{i=0}^{n-1} a_i X^i + \\langle X^n - 1 \\rangle`}</MathBlock>
            <p className="mt-2">
              This map is clearly a bijection since both spaces have the same dimension <InlineMath>{`n`}</InlineMath> over <InlineMath>{`F`}</InlineMath>.
            </p>
            <p className="mt-2">
              To verify it preserves multiplication, observe that <InlineMath>{`\sigma^i \cdot \sigma^j = \sigma^{i+j}`}</InlineMath> in <InlineMath>{`F[C_n]`}</InlineMath>,
              with the exponent taken modulo <InlineMath>{`n`}</InlineMath> when <InlineMath>{`i + j \\geq n`}</InlineMath>.
            </p>
            <p className="mt-2">
              Similarly, <InlineMath>{`X^i \cdot X^j = X^{i+j}`}</InlineMath> in <InlineMath>{`F[X]/\\langle X^n - 1 \\rangle`}</InlineMath>,
              with <InlineMath>{`X^n \\equiv 1`}</InlineMath>.
            </p>
            <p className="mt-2">
              Thus <InlineMath>{`\\phi(\\sigma^i \\cdot \\sigma^j) = \\phi(\\sigma^i) \\cdot \\phi(\\sigma^j)`}</InlineMath>,
              and <InlineMath>{`\\phi`}</InlineMath> is a ring isomorphism.
            </p>
          </>
        }
      >
        <p>
          The group algebra <InlineMath>{`F[C_n]`}</InlineMath> is isomorphic to the quotient
          ring <InlineMath>{`F[X]/\\langle X^n - 1 \\rangle`}</InlineMath>:
        </p>
        <MathBlock>{`F[C_n] \\cong F[X]/\\langle X^n - 1 \\rangle`}</MathBlock>
        <p className="mt-2">
          The isomorphism is given by <InlineMath>{`\\sigma \\mapsto X + \\langle X^n - 1 \\rangle`}</InlineMath>.
        </p>
      </Theorem>

      <Callout type="info" title="Connecting the Two Viewpoints">
        <p>
          This isomorphism shows that the ambient ring for cyclic codes is precisely
          the group algebra of the cyclic group. Under this correspondence:
        </p>
        <ul className="list-disc list-inside mt-2 space-y-1">
          <li>Elements of <InlineMath>{`F[C_n]`}</InlineMath> correspond to polynomials modulo <InlineMath>{`X^n - 1`}</InlineMath></li>
          <li>Multiplication by <InlineMath>{`\\sigma`}</InlineMath> corresponds to cyclic shift</li>
          <li>Ideals in <InlineMath>{`F[C_n]`}</InlineMath> correspond to cyclic codes</li>
        </ul>
      </Callout>

      <h2 className="text-2xl font-bold mt-8 mb-4 text-gradient">Cyclic Codes as Ideals in Group Algebras</h2>

      <Definition title="Cyclic Code via Group Algebra">
        <p>
          A <strong>cyclic code</strong> of length <InlineMath>{`n`}</InlineMath> over <InlineMath>{`F`}</InlineMath> is
          an ideal in the group algebra <InlineMath>{`F[C_n]`}</InlineMath>.
        </p>
        <p className="mt-2">
          Equivalently, a subset <InlineMath>{`\mathscr{C} \subseteq F[C_n]`}</InlineMath> is a cyclic
          code if:
        </p>
        <ol className="list-decimal list-inside mt-2 space-y-1">
          <li><InlineMath>{`\mathscr{C}`}</InlineMath> is a linear subspace of <InlineMath>{`F[C_n]`}</InlineMath></li>
          <li>For all <InlineMath>{`c \in \mathscr{C}`}</InlineMath> and <InlineMath>{`r \\in F[C_n]`}</InlineMath>, we have <InlineMath>{`rc \in \mathscr{C}`}</InlineMath></li>
        </ol>
      </Definition>

      <Theorem
        title="Semisimplicity and Code Decomposition"
        proof={
          <>
            <p>
              Since <InlineMath>{`\\gcd(n, q) = 1`}</InlineMath>, the characteristic of <InlineMath>{`F`}</InlineMath> does
              not divide <InlineMath>{`n = |C_n|`}</InlineMath>. By Maschke's theorem, <InlineMath>{`F[C_n]`}</InlineMath> is
              semisimple.
            </p>
            <p className="mt-2">
              The polynomial <InlineMath>{`X^n - 1`}</InlineMath> has no repeated roots
              (since <InlineMath>{`\gcd(X^n - 1, nX^{n-1}) = \gcd(X^n - 1, n) = 1`}</InlineMath> when <InlineMath>{`\\gcd(n, q) = 1`}</InlineMath>).
            </p>
            <p className="mt-2">
              By the Chinese Remainder Theorem, if <InlineMath>{`X^n - 1 = f_1(X) \\cdots f_t(X)`}</InlineMath> with
              irreducible factors <InlineMath>{`f_i(X)`}</InlineMath>, then:
            </p>
            <MathBlock>{`F[C_n] \\cong F[X]/\\langle f_1(X) \\rangle \\times \\cdots \\times F[X]/\\langle f_t(X) \\rangle`}</MathBlock>
            <p className="mt-2">
              Each factor <InlineMath>{`F[X]/\\langle f_i(X) \\rangle`}</InlineMath> is a field extension of <InlineMath>{`F`}</InlineMath>.
              These are the minimal ideals of <InlineMath>{`F[C_n]`}</InlineMath>, corresponding to
              minimal cyclic codes.
            </p>
          </>
        }
      >
        <p>
          Let <InlineMath>{`F = \text{GF}(q)`}</InlineMath> with <InlineMath>{`\\gcd(n, q) = 1`}</InlineMath>. Then
          the group algebra <InlineMath>{`F[C_n]`}</InlineMath> is semisimple and decomposes as a direct
          product of fields:
        </p>
        <MathBlock>{`F[C_n] \\cong K_1 \\times K_2 \\times \\cdots \\times K_t`}</MathBlock>
        <p className="mt-2">
          where each <InlineMath>{`K_i`}</InlineMath> is a field extension of <InlineMath>{`F`}</InlineMath>.
          The number <InlineMath>{`t`}</InlineMath> equals the number of irreducible factors
          of <InlineMath>{`X^n - 1`}</InlineMath> over <InlineMath>{`F`}</InlineMath>.
        </p>
      </Theorem>

      <Example title="Decomposition of Binary Group Algebra">
        <p>
          Consider <InlineMath>{`F = \mathbb{B}`}</InlineMath> (binary field) and <InlineMath>{`n = 7`}</InlineMath>.
          We have:
        </p>
        <MathBlock>
          {`X^7 - 1 = (X + 1)(X^3 + X + 1)(X^3 + X^2 + 1)`}
        </MathBlock>
        <p className="mt-2">
          The group algebra decomposes as:
        </p>
        <MathBlock>{`\\mathbb{B}[C_7] \\cong \\mathbb{B} \\times \\text{GF}(8) \\times \\text{GF}(8)`}</MathBlock>
        <p className="mt-2">
          The factor <InlineMath>{`\mathbb{B}`}</InlineMath> corresponds to <InlineMath>{`X + 1`}</InlineMath>,
          and each <InlineMath>{`\text{GF}(8)`}</InlineMath> corresponds to one of the degree-3 factors.
        </p>
        <p className="mt-2">
          The three minimal cyclic codes of length 7 correspond to these three factors.
        </p>
      </Example>

      <h2 className="text-2xl font-bold mt-8 mb-4 text-gradient">Primitive Idempotents and Minimal Codes</h2>

      <Definition title="Primitive Idempotent in Group Algebra">
        <p>
          In the semisimple decomposition <InlineMath>{`F[C_n] \\cong K_1 \\times \\cdots \\times K_t`}</InlineMath>,
          the <strong>primitive idempotent</strong> <InlineMath>{`e_i`}</InlineMath> is the element
          corresponding to <InlineMath>{`(0, \\ldots, 0, 1, 0, \\ldots, 0)`}</InlineMath> with the 1 in
          the <InlineMath>{`i`}</InlineMath>-th position.
        </p>
        <p className="mt-2">
          These idempotents satisfy:
        </p>
        <MathBlock>{`e_i^2 = e_i, \\quad e_i e_j = 0 \\text{ for } i \\neq j, \\quad \\sum_{i=1}^t e_i = 1`}</MathBlock>
      </Definition>

      <Theorem
        title="Classification of Cyclic Codes via Group Algebra"
        proof={
          <>
            <p>
              In a semisimple ring <InlineMath>{`R = K_1 \\times \\cdots \\times K_t`}</InlineMath> (product of fields),
              every ideal has the form <InlineMath>{`I_1 \\times \\cdots \\times I_t`}</InlineMath> where
              each <InlineMath>{`I_j`}</InlineMath> is an ideal of <InlineMath>{`K_j`}</InlineMath>.
            </p>
            <p className="mt-2">
              Since each <InlineMath>{`K_j`}</InlineMath> is a field, its only ideals
              are <InlineMath>{`\\{0\\}`}</InlineMath> and <InlineMath>{`K_j`}</InlineMath> itself.
            </p>
            <p className="mt-2">
              Therefore, each ideal in <InlineMath>{`R`}</InlineMath> is determined by a
              subset <InlineMath>{`S \\subseteq \\{1, \\ldots, t\\}`}</InlineMath>, consisting of factors
              where we take <InlineMath>{`K_j`}</InlineMath> rather than <InlineMath>{`\\{0\\}`}</InlineMath>.
            </p>
            <p className="mt-2">
              There are <InlineMath>{`2^t`}</InlineMath> such subsets, hence <InlineMath>{`2^t`}</InlineMath> ideals
              (cyclic codes), including the zero ideal and the full ring.
            </p>
          </>
        }
      >
        <p>
          Let <InlineMath>{`\\gcd(n, q) = 1`}</InlineMath> and let <InlineMath>{`t`}</InlineMath> be the number of
          irreducible factors of <InlineMath>{`X^n - 1`}</InlineMath> over <InlineMath>{`\text{GF}(q)`}</InlineMath>.
          Then:
        </p>
        <ol className="list-decimal list-inside mt-2 space-y-2">
          <li>There are exactly <InlineMath>{`2^t`}</InlineMath> cyclic codes of length <InlineMath>{`n`}</InlineMath></li>
          <li>
            Each cyclic code <InlineMath>{`\mathscr{C}`}</InlineMath> corresponds to a unique
            idempotent <InlineMath>{`e = \\sum_{i \\in S} e_i`}</InlineMath> for some <InlineMath>{`S \\subseteq \\{1, \\ldots, t\\}`}</InlineMath>
          </li>
          <li>The minimal cyclic codes are generated by single primitive idempotents</li>
        </ol>
      </Theorem>

      <h2 className="text-2xl font-bold mt-8 mb-4 text-gradient">Group Algebra Perspective on Duality</h2>

      <Definition title="Involution on Group Algebra">
        <p>
          Define the <strong>involution</strong> <InlineMath>{`*: F[C_n] \\to F[C_n]`}</InlineMath> by:
        </p>
        <MathBlock>{`\\left( \\sum_{i=0}^{n-1} a_i \\sigma^i \\right)^* = \\sum_{i=0}^{n-1} a_i \\sigma^{-i} = \\sum_{i=0}^{n-1} a_i \\sigma^{n-i}`}</MathBlock>
        <p className="mt-2">
          This is an anti-automorphism satisfying <InlineMath>{`(ab)^* = b^* a^*`}</InlineMath>.
        </p>
      </Definition>

      <Theorem
        title="Dual Code via Involution"
        proof={
          <>
            <p>
              The inner product <InlineMath>{`\langle a, b \rangle = \sum_{i=0}^{n-1} a_i b_i`}</InlineMath> on <InlineMath>{`F^n`}</InlineMath> corresponds
              to evaluating the product <InlineMath>{`a \\cdot b^*`}</InlineMath> at <InlineMath>{`\\sigma = 1`}</InlineMath>
              in the group algebra.
            </p>
            <p className="mt-2">
              Specifically, if <InlineMath>{`a = \\sum a_i \\sigma^i`}</InlineMath> and <InlineMath>{`b = \\sum b_i \\sigma^i`}</InlineMath>, then:
            </p>
            <MathBlock>{`a \\cdot b^* = \\sum_{i,j} a_i b_j \\sigma^{i-j}`}</MathBlock>
            <p className="mt-2">
              The coefficient of <InlineMath>{`\\sigma^0 = 1`}</InlineMath> is <InlineMath>{`\\sum_i a_i b_i = \\langle a, b \\rangle`}</InlineMath>.
            </p>
            <p className="mt-2">
              Now, <InlineMath>{`a \perp \mathscr{C}`}</InlineMath> means <InlineMath>{`\\langle a, c \\rangle = 0`}</InlineMath> for all <InlineMath>{`c \in \mathscr{C}`}</InlineMath>.
              This is equivalent to the coefficient of <InlineMath>{`\\sigma^0`}</InlineMath> in <InlineMath>{`a \\cdot c^*`}</InlineMath> being
              zero for all <InlineMath>{`c \in \mathscr{C}`}</InlineMath>.
            </p>
            <p className="mt-2">
              The annihilator of <InlineMath>{`\mathscr{C}^*`}</InlineMath> in a suitable sense gives <InlineMath>{`\mathscr{C}^\perp`}</InlineMath>.
            </p>
          </>
        }
      >
        <p>
          Let <InlineMath>{`\mathscr{C}`}</InlineMath> be a cyclic code viewed as an ideal
          in <InlineMath>{`F[C_n]`}</InlineMath>. The dual code <InlineMath>{`\mathscr{C}^\perp`}</InlineMath> is
          related to <InlineMath>{`\mathscr{C}`}</InlineMath> by:
        </p>
        <MathBlock>{`\\mathscr{C}^\\perp = \\{ a \\in F[C_n] : \\langle a, c \\rangle = 0 \\text{ for all } c \\in \\mathscr{C} \\}`}</MathBlock>
        <p className="mt-2">
          where <InlineMath>{`\\langle a, c \\rangle`}</InlineMath> is the inner product of the
          coefficient vectors.
        </p>
      </Theorem>

      <Example title="Computing with Group Algebra Structure">
        <p>
          Let <InlineMath>{`\mathscr{C}`}</InlineMath> be the binary cyclic code of length 7 with
          generator <InlineMath>{`g(X) = X^3 + X + 1`}</InlineMath>.
        </p>
        <p className="mt-2">
          In the group algebra <InlineMath>{`\mathbb{B}[C_7]`}</InlineMath>, this corresponds to the
          element <InlineMath>{`g = 1 + \\sigma + \\sigma^3`}</InlineMath>.
        </p>
        <p className="mt-2">
          The code <InlineMath>{`\mathscr{C}`}</InlineMath> consists of all elements <InlineMath>{`a \\cdot g`}</InlineMath> where <InlineMath>{`a \in \mathbb{B}[C_7]`}</InlineMath>,
          reduced modulo the relation <InlineMath>{`\\sigma^7 = 1`}</InlineMath>.
        </p>
        <p className="mt-2">
          Under the decomposition <InlineMath>{`\mathbb{B}[C_7] \cong \mathbb{B} \times \text{GF}(8) \times \text{GF}(8)`}</InlineMath>,
          the code <InlineMath>{`\mathscr{C}`}</InlineMath> projects to <InlineMath>{`\mathbb{B} \times \{0\} \times \text{GF}(8)`}</InlineMath>.
        </p>
      </Example>

      <Callout type="success" title="Advantages of the Group Algebra Viewpoint">
        <ol className="list-decimal list-inside mt-2 space-y-2">
          <li>
            <strong>Unified framework:</strong> All cyclic codes of a given length arise
            as ideals in a single ring structure.
          </li>
          <li>
            <strong>Idempotent decomposition:</strong> The semisimple decomposition gives
            a complete classification of cyclic codes via primitive idempotents.
          </li>
          <li>
            <strong>Generalization:</strong> The group algebra approach extends naturally
            to non-abelian groups (group codes) and other algebraic structures.
          </li>
          <li>
            <strong>Representation theory:</strong> Characters and representations of <InlineMath>{`C_n`}</InlineMath> give
            additional tools for analyzing cyclic codes.
          </li>
        </ol>
      </Callout>

      <h2 className="text-2xl font-bold mt-8 mb-4 text-gradient">Characters and Cyclotomic Fields</h2>

      <Definition title="Character of Cyclic Group">
        <p>
          A <strong>character</strong> of <InlineMath>{`C_n`}</InlineMath> is a group
          homomorphism <InlineMath>{`\\chi: C_n \\to F^*`}</InlineMath> (where <InlineMath>{`F`}</InlineMath> is an
          extension of the base field containing <InlineMath>{`n`}</InlineMath>-th roots of unity).
        </p>
        <p className="mt-2">
          If <InlineMath>{`\\omega`}</InlineMath> is a primitive <InlineMath>{`n`}</InlineMath>-th root of unity,
          then the characters are <InlineMath>{`\\chi_j(\\sigma) = \\omega^j`}</InlineMath> for <InlineMath>{`j = 0, 1, \\ldots, n-1`}</InlineMath>.
        </p>
      </Definition>

      <Theorem title="Fourier Transform Interpretation">
        <p>
          Let <InlineMath>{`\\omega`}</InlineMath> be a primitive <InlineMath>{`n`}</InlineMath>-th root of unity
          in an extension of <InlineMath>{`F`}</InlineMath>. For <InlineMath>{`a = \sum_{i=0}^{n-1} a_i \sigma^i \in F[C_n]`}</InlineMath>,
          the <strong>discrete Fourier transform</strong> is:
        </p>
        <MathBlock>{`\\hat{a}_j = \\sum_{i=0}^{n-1} a_i \\omega^{ij}`}</MathBlock>
        <p className="mt-2">
          A vector <InlineMath>{`a`}</InlineMath> is in a cyclic code <InlineMath>{`\mathscr{C}`}</InlineMath> if and
          only if <InlineMath>{`\hat{a}_j = 0`}</InlineMath> for all <InlineMath>{`j`}</InlineMath> in the defining set
          of <InlineMath>{`\mathscr{C}`}</InlineMath>.
        </p>
      </Theorem>

      <Example title="DFT and Cyclic Codes">
        <p>
          For the binary [7, 4] Hamming code with generator <InlineMath>{`g(X) = X^3 + X + 1`}</InlineMath>,
          let <InlineMath>{`\\alpha`}</InlineMath> be a root of <InlineMath>{`g(X)`}</InlineMath> in <InlineMath>{`\text{GF}(8)`}</InlineMath>.
        </p>
        <p className="mt-2">
          The defining set is <InlineMath>{`T = \{1, 2, 4\}`}</InlineMath> (the cyclotomic coset of 1 mod 7).
        </p>
        <p className="mt-2">
          A codeword <InlineMath>{`c = (c_0, \\ldots, c_6)`}</InlineMath> satisfies <InlineMath>{`\hat{c}_1 = \hat{c}_2 = \hat{c}_4 = 0`}</InlineMath>,
          i.e., <InlineMath>{`c(\\alpha) = c(\\alpha^2) = c(\\alpha^4) = 0`}</InlineMath>.
        </p>
        <p className="mt-2">
          This is precisely the condition that <InlineMath>{`g(X)`}</InlineMath> divides <InlineMath>{`c(X)`}</InlineMath>,
          showing the equivalence of the group algebra and polynomial viewpoints.
        </p>
      </Example>
    </LessonLayout>
  );
}
