import { LessonLayout } from '@/components/layout/LessonLayout';
import { Definition, Theorem, Example } from '@/components/common';
import { MathBlock, InlineMath } from '@/components/common/MathBlock';
import { Callout } from '@/components/common/Callout';

export default function Section10() {
  return (
    <LessonLayout sectionId={10}>
      <h2>BCH Codes</h2>

      <p>
        Hocquenghem (1959) and Bose and Ray-Chaudhuri (1960) independently proved a remarkable theorem
        which enables us to systematically construct one of the most powerful multiple error-correcting
        codes for random independent errors. These are polynomial codes called <strong>Bose-Chaudhuri-Hocquenghem codes</strong>
        (BCH codes for short).
      </p>

      <h3>Construction of BCH Codes</h3>

      <p>
        A polynomial code is determined as soon as the generator polynomial is determined. The procedure
        for constructing a BCH code is as follows:
      </p>

      <div className="bg-dark-800/50 rounded-xl p-4 border border-dark-700 my-4">
        <h4 className="text-lg font-semibold text-primary-400 mb-3">BCH Code Construction Procedure</h4>
        <p>
          Suppose a BCH code with code word length <InlineMath math="n" />, minimum distance <InlineMath math="d" />,
          and symbols in <InlineMath math="F = GF(q)" /> is required.
        </p>
        <ol className="list-decimal list-inside mt-2 space-y-2">
          <li>Choose the least positive integer <InlineMath math="r" /> satisfying <InlineMath math="q^r \\geq n + 1" /></li>
          <li>Let <InlineMath math="K" /> be an extension of <InlineMath math="F" /> of degree <InlineMath math="r" /></li>
          <li>Let <InlineMath math="\\alpha" /> be a primitive element of <InlineMath math="K" /></li>
          <li>Let <InlineMath math="m_i(X)" /> be the minimal polynomial of <InlineMath math="\\alpha^i" />, <InlineMath math="1 \\leq i \\leq d-1" /></li>
          <li>Set <InlineMath math="g(X) = \\text{LCM}(m_1(X), \\ldots, m_{d-1}(X))" /></li>
        </ol>
      </div>

      <Theorem
        title="BCH Bound"
        proof={
          <>
            <p>
              Let <InlineMath math="h(X)" /> be any polynomial over <InlineMath math="F" /> which has
              <InlineMath math="\\alpha, \\alpha^2, \\ldots, \\alpha^{d-1}" /> among its roots. Then:
            </p>
            <MathBlock math="m_i(X) \\mid h(X) \\quad \\forall i, \\, 1 \\leq i \\leq d-1" />
            <p className="mt-2">
              and hence <InlineMath math="g(X) \\mid h(X)" />. Thus <InlineMath math="g(X)" /> is the polynomial of least
              possible degree (up to a constant factor) with roots <InlineMath math="\\alpha, \\alpha^2, \\ldots, \\alpha^{d-1}" />.
            </p>
            <p className="mt-2">
              If <InlineMath math="c(X)" /> is a code polynomial in the polynomial code generated by <InlineMath math="g(X)" />, then
              <InlineMath math="c(X) = a(X)g(X)" /> for some <InlineMath math="a(X) \\in F[X]" />, so <InlineMath math="\\alpha, \\alpha^2, \\ldots, \\alpha^{d-1}" /> are
              roots of <InlineMath math="c(X)" />.
            </p>
            <p className="mt-2">
              Suppose a code word has less than <InlineMath math="d" /> non-zero entries. Then the corresponding code
              polynomial is of the form:
            </p>
            <MathBlock math="c(X) = b_1 X^{n_1} + b_2 X^{n_2} + \\cdots + b_{d-1} X^{n_{d-1}}" />
            <p className="mt-2">
              where <InlineMath math="b_1, \\ldots, b_{d-1} \\in F" /> and <InlineMath math="n_1 > n_2 > \\cdots > n_{d-1} \\geq 0" />.
              Since <InlineMath math="\\alpha, \\alpha^2, \\ldots, \\alpha^{d-1}" /> are roots of <InlineMath math="c(X)" />:
            </p>
            <MathBlock math="\\mathbf{A} \\begin{pmatrix} b_1 \\\\ b_2 \\\\ \\vdots \\\\ b_{d-1} \\end{pmatrix} = 0" />
            <p className="mt-2">where:</p>
            <MathBlock math="\\mathbf{A} = \\begin{pmatrix} \\alpha^{n_1} & \\alpha^{n_2} & \\cdots & \\alpha^{n_{d-1}} \\\\ \\alpha^{2n_1} & \\alpha^{2n_2} & \\cdots & \\alpha^{2n_{d-1}} \\\\ \\vdots & \\vdots & \\ddots & \\vdots \\\\ \\alpha^{(d-1)n_1} & \\alpha^{(d-1)n_2} & \\cdots & \\alpha^{(d-1)n_{d-1}} \\end{pmatrix}" />
            <p className="mt-2">
              The determinant of <InlineMath math="\\mathbf{A}" /> is a Vandermonde determinant:
            </p>
            <MathBlock math="\\det \\mathbf{A} = \\prod_{i > j} (\\alpha^{n_i} - \\alpha^{n_j})" />
            <p className="mt-2">
              Since <InlineMath math="\\alpha" /> is primitive and <InlineMath math="q^r - 1 > n_1 > \\cdots > n_{d-1} \\geq 0" />,
              we have <InlineMath math="\\alpha^{n_i} - \\alpha^{n_j} \\neq 0" /> for <InlineMath math="i \\neq j" />.
              Therefore <InlineMath math="\\det \\mathbf{A} \\neq 0" />.
            </p>
            <p className="mt-2">
              The system admits only the zero solution, so <InlineMath math="c(X) = 0" />. Hence there is no
              non-zero code word with less than <InlineMath math="d" /> non-zero entries.
            </p>
          </>
        }
      >
        The polynomial code with symbols in <InlineMath math="F" /> and encoding polynomial <InlineMath math="g(X)" /> has
        minimum distance at least <InlineMath math="d" />.
      </Theorem>

      <h3>Examples of BCH Code Construction</h3>

      <Example title="Binary BCH Code of Length 7, Distance 3">
        <p>
          Here <InlineMath math="n = 7" /> so we need an extension of <InlineMath math="\\mathbb{B}" /> of degree <InlineMath math="r" /> where
          <InlineMath math="2^r \\geq 8" />. Thus <InlineMath math="r = 3" />.
        </p>
        <p className="mt-2">
          <InlineMath math="X^3 + X + 1" /> is a primitive polynomial of degree 3 over <InlineMath math="\\mathbb{B}" />.
          Therefore <InlineMath math="K = \\mathbb{B}[X]/\\langle X^3 + X + 1 \\rangle" /> is a field of order 8 and
          <InlineMath math="\\alpha = X + \\langle X^3 + X + 1 \\rangle" /> is a primitive element.
        </p>
        <p className="mt-2">
          Then <InlineMath math="\\alpha^3 + \\alpha + 1 = 0" /> and <InlineMath math="\\alpha^7 = 1" />. The minimal polynomial
          of <InlineMath math="\\alpha" /> is <InlineMath math="X^3 + X + 1" />.
        </p>
        <p className="mt-2">
          Since <InlineMath math="\\alpha" /> and <InlineMath math="\\alpha^2" /> have the same minimal polynomial,
          the generator polynomial of the required BCH code is:
        </p>
        <MathBlock math="g(X) = X^3 + X + 1" />
        <p className="mt-2">
          The encoding polynomial has 3 non-zero terms, so the minimum distance is exactly 3.
        </p>
      </Example>

      <Example title="Binary BCH Code of Length 15, Distance 5">
        <p>
          Here <InlineMath math="n = 15 \\leq 2^4 - 1" /> so we need an extension <InlineMath math="K" /> of
          <InlineMath math="\\mathbb{B}" /> of degree 4.
        </p>
        <p className="mt-2">
          <InlineMath math="X^4 + X + 1" /> is a primitive polynomial, so <InlineMath math="\\alpha = X + \\langle X^4 + X + 1 \\rangle" /> is
          a primitive element of <InlineMath math="K = \\mathbb{B}[X]/\\langle X^4 + X + 1 \\rangle" />.
        </p>
        <p className="mt-2">
          The minimal polynomial of <InlineMath math="\\alpha" /> is <InlineMath math="m_1(X) = X^4 + X + 1" />. Also
          <InlineMath math="m_2(X) = m_4(X) = m_1(X)" />.
        </p>
        <p className="mt-2">
          For <InlineMath math="m_3(X)" />: the elements <InlineMath math="\\alpha^3, \\alpha^6, \\alpha^{12}, \\alpha^9" /> have the same
          minimal polynomial:
        </p>
        <MathBlock math="m_3(X) = (X - \\alpha^3)(X - \\alpha^6)(X - \\alpha^9)(X - \\alpha^{12})" />
        <p className="mt-2">Computing:</p>
        <MathBlock math="m_3(X) = X^4 + X^3 + X^2 + X + 1" />
        <p className="mt-2">Therefore, the encoding polynomial is:</p>
        <MathBlock math="g(X) = (X^4 + X + 1)(X^4 + X^3 + X^2 + X + 1) = X^8 + X^7 + X^6 + X^4 + 1" />
        <p className="mt-2">
          Since the encoding polynomial has 5 non-zero terms, the minimum distance is exactly 5.
        </p>
      </Example>

      <Example title="Binary BCH Code of Length 31, Distance 5">
        <p>Given that <InlineMath math="X^5 + X^2 + 1" /> is irreducible over <InlineMath math="\\mathbb{B}" />:</p>
        <MathBlock math="F = \\mathbb{B}[X]/\\langle X^5 + X^2 + 1 \\rangle" />
        <p className="mt-2">
          is a field of order 32. Since <InlineMath math="F^*" /> is cyclic of order 31 (prime), every non-identity
          element is primitive. Let <InlineMath math="\\alpha = X + \\langle X^5 + X^2 + 1 \\rangle" />.
        </p>
        <p className="mt-2">
          The minimal polynomial of <InlineMath math="\\alpha" /> is <InlineMath math="m_1(X) = X^5 + X^2 + 1" />.
          Note that <InlineMath math="m_1(X) = m_2(X) = m_4(X)" />.
        </p>
        <p className="mt-2">
          For <InlineMath math="m_3(X)" />: the elements <InlineMath math="\\alpha^3, \\alpha^6, \\alpha^{12}, \\alpha^{24}, \\alpha^{17}" /> share
          the same minimal polynomial (since <InlineMath math="\\{3, 6, 12, 24, 17\\}" /> is a cyclotomic class mod 31).
        </p>
        <p className="mt-2">Computing coefficients:</p>
        <MathBlock math="m_3(X) = X^5 + X^4 + X^3 + X^2 + 1" />
        <p className="mt-2">Therefore:</p>
        <MathBlock math="g(X) = m_1(X) \\cdot m_3(X) = (X^5 + X^2 + 1)(X^5 + X^4 + X^3 + X^2 + 1)" />
        <MathBlock math="= X^{10} + X^9 + X^8 + X^6 + X^5 + X^3 + 1" />
      </Example>

      <Example title="5-Error-Correcting BCH Code of Length 63">
        <p>
          Given <InlineMath math="X^6 + X + 1" /> is primitive over <InlineMath math="\\mathbb{B}" />:
        </p>
        <MathBlock math="K = \\mathbb{B}[X]/\\langle X^6 + X + 1 \\rangle" />
        <p className="mt-2">
          is a field of order 64, and <InlineMath math="\\alpha = X + \\langle X^6 + X + 1 \\rangle" /> is primitive.
        </p>
        <p className="mt-2">
          For a 5-error-correcting code, minimum distance is at least <InlineMath math="2 \\times 5 + 1 = 11" />.
          We need minimal polynomials <InlineMath math="m_i(X)" /> of <InlineMath math="\\alpha^i" /> for <InlineMath math="1 \\leq i \\leq 10" />.
        </p>
        <p className="mt-2">Using cyclotomic classes:</p>
        <ul className="list-disc list-inside mt-2 space-y-1">
          <li><InlineMath math="m_1(X) = m_2(X) = m_4(X) = m_8(X) = m_{16}(X) = m_{32}(X) = X^6 + X + 1" /></li>
          <li><InlineMath math="m_3(X) = m_6(X) = m_{12}(X) = m_{24}(X) = m_{48}(X) = m_{33}(X)" /></li>
          <li><InlineMath math="m_5(X) = m_{10}(X) = m_{20}(X) = m_{40}(X) = m_{17}(X) = m_{34}(X)" /></li>
          <li><InlineMath math="m_7(X) = m_{14}(X) = m_{28}(X) = m_{56}(X) = m_{49}(X) = m_{35}(X)" /></li>
          <li><InlineMath math="m_9(X) = m_{18}(X) = m_{36}(X)" /></li>
        </ul>
        <p className="mt-2">
          Computing these minimal polynomials (degree 6 for the first four, degree 3 for the last):
        </p>
        <MathBlock math="m_3(X) = X^6 + X^4 + X^3 + X^2 + X + 1" />
        <MathBlock math="m_5(X) = X^6 + X^5 + X^2 + X + 1" />
        <MathBlock math="m_7(X) = X^6 + X^3 + 1" />
        <MathBlock math="m_9(X) = X^3 + X^2 + 1" />
        <p className="mt-2">The generator polynomial is:</p>
        <MathBlock math="g(X) = m_1(X) \\cdot m_3(X) \\cdot m_5(X) \\cdot m_7(X) \\cdot m_9(X)" />
        <p className="mt-2">which has degree 27.</p>
      </Example>

      <h3>Bound on Check Digits</h3>

      <Theorem
        title="Check Digit Bound for Binary BCH Codes"
        proof={
          <>
            <p>
              The code is of length <InlineMath math="n = 2^m - 1" />. We construct an extension <InlineMath math="K" /> of
              <InlineMath math="\\mathbb{B}" /> of degree <InlineMath math="m" /> and let <InlineMath math="\\alpha" /> be a primitive element.
            </p>
            <p className="mt-2">
              Since <InlineMath math="[K:\\mathbb{B}] = m" /> is finite, every element of <InlineMath math="K" /> is algebraic over
              <InlineMath math="\\mathbb{B}" />. If <InlineMath math="\\beta \\in K" />, then <InlineMath math="\\mathbb{B}(\\beta)" /> is a subfield of <InlineMath math="K" /> and:
            </p>
            <MathBlock math="[K:\\mathbb{B}] = [K:\\mathbb{B}(\\beta)][\\mathbb{B}(\\beta):\\mathbb{B}]" />
            <p className="mt-2">
              shows that <InlineMath math="[\\mathbb{B}(\\beta):\\mathbb{B}] \\leq m" />. Thus the degree of the minimal
              polynomial of <InlineMath math="\\beta" /> is at most <InlineMath math="m" />.
            </p>
            <p className="mt-2">
              We prove by induction on <InlineMath math="t" /> that <InlineMath math="\\deg g(X) \\leq mt" />.
              For <InlineMath math="t = 1" />: <InlineMath math="g(X) = \\text{LCM}\\{m_1(X), m_2(X)\\} = m_1(X)" />
              since <InlineMath math="\\alpha" /> and <InlineMath math="\\alpha^2" /> have the same minimal polynomial.
            </p>
            <p className="mt-2">
              Suppose the claim holds for <InlineMath math="t" />. Let:
            </p>
            <MathBlock math="g_1(X) = \\text{LCM}\\{m_1(X), \\ldots, m_{2t}(X), m_{2t+1}(X), m_{2t+2}(X)\\}" />
            <p className="mt-2">
              Since <InlineMath math="m_{2t+2}(X) = m_{t+1}(X)" />:
            </p>
            <MathBlock math="g_1(X) = \\text{LCM}\\{g(X), m_{2t+1}(X)\\}" />
            <p className="mt-2">Then:</p>
            <MathBlock math="\\deg g_1(X) \\leq \\deg g(X) + \\deg m_{2t+1}(X) \\leq mt + m = m(t+1)" />
          </>
        }
      >
        A binary BCH code with code word length <InlineMath math="n = 2^m - 1" /> and minimum distance at
        least <InlineMath math="d = 2t + 1" /> can always be constructed with check digits at most <InlineMath math="mt" />.
      </Theorem>

      <Callout type="info">
        <strong>Remark:</strong> If <InlineMath math="g(X)" /> is the generating polynomial of the binary BCH code with
        minimum distance at least <InlineMath math="2t" />, then:
        <MathBlock math="g(X) = \\text{LCM}\\{m_1(X), \\ldots, m_{2t-1}(X)\\} = \\text{LCM}\\{m_1(X), \\ldots, m_{2t}(X)\\}" />
        Therefore, <InlineMath math="g(X)" /> is also the generating polynomial of a BCH code with minimum distance
        at least <InlineMath math="2t + 1" />.
      </Callout>

      <Theorem
        title="General Check Digit Bound"
        proof={
          <>
            <p>
              The proof follows exactly the same lines as the binary case, with <InlineMath math="p" /> replacing 2.
              The key observation is that <InlineMath math="\\alpha" /> and <InlineMath math="\\alpha^p" /> share the same minimal
              polynomial over the prime subfield.
            </p>
          </>
        }
      >
        A BCH code over <InlineMath math="GF(p)" /> with code word length <InlineMath math="n = p^m - 1" /> and minimum distance
        at least <InlineMath math="pt + 1" /> can always be constructed with at most <InlineMath math="(p-1)mt" /> check digits.
      </Theorem>

      <h3>Non-Binary BCH Codes</h3>

      <Example title="2-Error-Correcting BCH Code over GF(3)">
        <p>
          For a code of length <InlineMath math="8 = 3^2 - 1" /> over <InlineMath math="GF(3)" />, we construct an extension
          of degree 2.
        </p>
        <p className="mt-2">
          <InlineMath math="X^2 + X + 2" /> is primitive over <InlineMath math="F_3" />. Let
          <InlineMath math="K = F_3[X]/\\langle X^2 + X + 2 \\rangle" /> and
          <InlineMath math="\\alpha = X + \\langle X^2 + X + 2 \\rangle" />.
        </p>
        <p className="mt-2">
          Minimum distance is at least <InlineMath math="2 \\times 2 + 1 = 5" />. We need
          <InlineMath math="m_i(X)" /> for <InlineMath math="1 \\leq i \\leq 4" />.
        </p>
        <p className="mt-2">
          By the theory, <InlineMath math="m_1(X) = m_3(X)" /> and <InlineMath math="m_2(X) = m_6(X)" />.
        </p>
        <MathBlock math="m_2(X) = (X - \\alpha^2)(X - \\alpha^6) = X^2 + 1" />
        <MathBlock math="m_4(X) = X - \\alpha^4 = X + 1" />
        <p className="mt-2">The generator polynomial is:</p>
        <MathBlock math="g(X) = m_1(X) \\cdot m_2(X) \\cdot m_4(X) = (X^2 + X + 2)(X^2 + 1)(X + 1)" />
        <MathBlock math="= X^5 + 2X^4 + X^3 + X^2 + 2" />
        <p className="mt-2">
          Since the generator polynomial has 5 non-zero terms, the minimum distance is exactly 5.
        </p>
      </Example>

      <Callout type="success">
        <strong>Summary:</strong> BCH codes provide a powerful systematic method for constructing codes
        with guaranteed minimum distance. The key ingredients are:
        <ul className="list-disc list-inside mt-2 space-y-1">
          <li>Finite field extensions and primitive elements</li>
          <li>Minimal polynomials and cyclotomic classes</li>
          <li>The Vandermonde determinant argument for the BCH bound</li>
        </ul>
      </Callout>
    </LessonLayout>
  );
}
