import { LessonLayout } from '@/components/layout/LessonLayout';
import { Definition, Theorem, Example } from '@/components/common';
import { MathBlock, InlineMath } from '@/components/common/MathBlock';
import { Callout } from '@/components/common/Callout';

export default function Section04() {
  return (
    <LessonLayout sectionId={4}>
      <h2>2.2 Polynomial Codes</h2>

      <p>
        We now introduce polynomial codes, where encoding is performed through polynomial
        multiplication. This elegant technique produces many important codes including
        BCH codes and cyclic codes.
      </p>

      <h3>Definition of Polynomial Codes</h3>

      <Definition title="Polynomial Code">
        <p>
          Let <InlineMath>{`g(X) = g_0 + g_1X + \\cdots + g_kX^k \\in F[X]`}</InlineMath> be a polynomial
          of degree at most <InlineMath>k</InlineMath>.
        </p>
        <p className="mt-2">
          The <strong>polynomial code</strong> with encoding (generator) polynomial <InlineMath>{`g(X)`}</InlineMath> encodes
          each message word <InlineMath>{`a = (a_0, a_1, \\ldots, a_{m-1})`}</InlineMath> of length <InlineMath>m</InlineMath> into
          the code word <InlineMath>{`b = (b_0, b_1, \\ldots, b_{m+k-1})`}</InlineMath> of length <InlineMath>{`n = m + k`}</InlineMath>,
          where:
        </p>
        <MathBlock>{`b(X) = a(X) \\cdot g(X)`}</MathBlock>
        <p className="mt-2">
          The code polynomial <InlineMath>{`b(X) = b_0 + b_1X + \\cdots + b_{m+k-1}X^{m+k-1}`}</InlineMath> corresponds
          to the code word <InlineMath>b</InlineMath>.
        </p>
      </Definition>

      <Callout type="warning">
        <strong>Convention:</strong> If <InlineMath>{`g_0 = 0`}</InlineMath> in the encoding polynomial,
        then the first entry of every code word is 0, wasting information. Similarly, if <InlineMath>{`g_k = 0`}</InlineMath>,
        the last entry is always 0.
        <p className="mt-2">
          To avoid this waste, we assume <InlineMath>{`g_0 \\neq 0`}</InlineMath> and <InlineMath>{`g_k \\neq 0`}</InlineMath> throughout.
        </p>
      </Callout>

      <Theorem
        title="Polynomial Codes are Subspaces"
        proof={
          <>
            <p>
              Let <InlineMath>{`a = (a_0, \\ldots, a_{m-1})`}</InlineMath> and <InlineMath>{`b = (b_0, \\ldots, b_{m-1})`}</InlineMath> be
              message words with corresponding polynomials <InlineMath>{`a(X)`}</InlineMath> and <InlineMath>{`b(X)`}</InlineMath>.
            </p>
            <p className="mt-2">
              For <InlineMath>{`\\alpha, \\beta \\in F`}</InlineMath>, the code polynomial corresponding to
              message polynomial <InlineMath>{`\\alpha a(X) + \\beta b(X)`}</InlineMath> is:
            </p>
            <MathBlock>{`[\\alpha a(X) + \\beta b(X)]g(X) = \\alpha a(X)g(X) + \\beta b(X)g(X)`}</MathBlock>
            <p className="mt-2">
              This is a linear combination of the code polynomials for <InlineMath>a</InlineMath> and <InlineMath>b</InlineMath>.
            </p>
          </>
        }
      >
        <p>
          The polynomial code of length <InlineMath>{`n = m + k`}</InlineMath> generated by the
          polynomial <InlineMath>{`g(X) = g_0 + g_1X + \\cdots + g_kX^k`}</InlineMath> is a
          subspace of <InlineMath>{`F^{(n)}`}</InlineMath>.
        </p>
      </Theorem>

      <Callout type="info">
        <strong>Group Code Property:</strong> Since a vector space is first a group under addition,
        a polynomial code is always a <strong>group code</strong>. Therefore, the minimum distance
        equals the minimum weight of the non-zero code words.
      </Callout>

      <h3>Weight of Polynomials</h3>

      <Definition title="Weight of a Polynomial">
        <p>
          The <strong>weight</strong> of a code polynomial <InlineMath>{`a(X)g(X)`}</InlineMath> is the
          number of non-zero terms (coefficients) in the polynomial.
        </p>
        <p className="mt-2">For example:</p>
        <MathBlock>{`\\text{wt}(X + X^2 + X^3 + X^6) = 4`}</MathBlock>
        <MathBlock>{`\\text{wt}(1 + X + X^3) = 3`}</MathBlock>
      </Definition>

      <h3>Divisibility by <InlineMath>{`1 + X`}</InlineMath></h3>

      <Theorem
        title="Divisibility by 1 + X"
        proof={
          <>
            <p>
              <strong>(⇒)</strong> Suppose <InlineMath>{`f(X)`}</InlineMath> is divisible
              by <InlineMath>{`1 + X`}</InlineMath>. Then <InlineMath>{`f(X) = (1 + X)b(X)`}</InlineMath> for
              some <InlineMath>{`b(X) \\in \\mathbb{B}[X]`}</InlineMath>.
            </p>
            <p className="mt-2">
              Taking <InlineMath>{`X = 1`}</InlineMath>:
            </p>
            <MathBlock>{`a_0 + a_1 + \\cdots + a_n = (1 + 1)b(1) = 0 \\cdot b(1) = 0`}</MathBlock>
            <p className="mt-2">
              In <InlineMath>{`\\mathbb{B}`}</InlineMath>, this sum is 0 only if the number of non-zero <InlineMath>{`a_i`}</InlineMath>'s
              is even.
            </p>
            <p className="mt-2">
              <strong>(⇐)</strong> Suppose <InlineMath>{`f(X)`}</InlineMath> has an even number of non-zero
              terms. Write:
            </p>
            <MathBlock>{`f(X) = X^{i_1} + X^{i_2} + \\cdots + X^{i_{2k}}`}</MathBlock>
            <p className="mt-2">
              Grouping in pairs:
            </p>
            <MathBlock>{`f(X) = (X^{i_1} + X^{i_2}) + \\cdots + (X^{i_{2k-1}} + X^{i_{2k}})`}</MathBlock>
            <p className="mt-2">
              For <InlineMath>{`i < j`}</InlineMath>:
            </p>
            <MathBlock>{`X^i + X^j = X^i(1 + X^{j-i}) = X^i(1 + X)(1 + X + \\cdots + X^{j-i-1})`}</MathBlock>
            <p className="mt-2">
              Thus each pair is divisible by <InlineMath>{`1 + X`}</InlineMath>, so <InlineMath>{`f(X)`}</InlineMath> is
              divisible by <InlineMath>{`1 + X`}</InlineMath>.
            </p>
          </>
        }
      >
        <p>
          A polynomial with coefficients in <InlineMath>{`\\mathbb{B}`}</InlineMath> is divisible
          by <InlineMath>{`1 + X`}</InlineMath> if and only if it has an even number of terms.
        </p>
      </Theorem>

      <h3>Minimum Distance of Polynomial Codes</h3>

      <Definition title="Exponent of a Polynomial">
        <p>
          The <strong>exponent</strong> of a polynomial <InlineMath>{`g(X) \\in \\mathbb{B}[X]`}</InlineMath> is
          the least positive integer <InlineMath>e</InlineMath> such that <InlineMath>{`g(X) | X^e - 1`}</InlineMath>.
        </p>
      </Definition>

      <Theorem
        title="Minimum Distance at Least 3"
        proof={
          <>
            <p>
              Let <InlineMath>{`g(X) = g_0 + g_1X + \\cdots + g_rX^r`}</InlineMath> with <InlineMath>{`g_0 \\neq 0`}</InlineMath> and <InlineMath>{`g_r \\neq 0`}</InlineMath>.
              Let <InlineMath>{`m = n - r`}</InlineMath>.
            </p>
            <p className="mt-2">
              Every code polynomial is divisible by <InlineMath>{`g(X)`}</InlineMath>. Since the code is
              a group code, we need to show there is no non-zero code word of weight at most 2.
            </p>
            <p className="mt-2">
              The condition <InlineMath>{`g(X) \\nmid X^k - 1`}</InlineMath> for <InlineMath>{`k < n`}</InlineMath> implies <InlineMath>{`g(X)`}</InlineMath> is
              not a constant polynomial.
            </p>
            <p className="mt-2">
              <strong>Case 1:</strong> <InlineMath>{`b(X) = X^i + X^j`}</InlineMath> with <InlineMath>{`i < j < n`}</InlineMath>.
            </p>
            <p className="mt-2">
              Then <InlineMath>{`b(X) = X^i(1 + X^{j-i})`}</InlineMath> where <InlineMath>{`0 < j - i < n`}</InlineMath>.
              Since <InlineMath>{`g_0 \\neq 0`}</InlineMath>, we have <InlineMath>{`X \\nmid g(X)`}</InlineMath>,
              so <InlineMath>{`g(X) | b(X)`}</InlineMath> implies <InlineMath>{`g(X) | 1 + X^{j-i}`}</InlineMath>.
              But this contradicts our hypothesis.
            </p>
            <p className="mt-2">
              <strong>Case 2:</strong> <InlineMath>{`b(X) = X^i`}</InlineMath> with <InlineMath>{`i < n`}</InlineMath>.
            </p>
            <p className="mt-2">
              Since <InlineMath>{`g(X) \\nmid X^i`}</InlineMath> (as <InlineMath>{`g_0 \\neq 0`}</InlineMath>), this is a contradiction.
            </p>
          </>
        }
      >
        <p>
          If <InlineMath>{`g(X) \\in \\mathbb{B}[X]`}</InlineMath> divides no polynomial of the
          form <InlineMath>{`X^k - 1`}</InlineMath> for <InlineMath>{`k < n`}</InlineMath>, then the binary
          polynomial code of length <InlineMath>n</InlineMath> generated by <InlineMath>{`g(X)`}</InlineMath> has
          minimum distance at least 3.
        </p>
      </Theorem>

      <Example title="Binary Polynomial Code of Length 6">
        <p>Consider the binary polynomial code of length 6 generated by:</p>
        <MathBlock>{`g(X) = 1 + X + X^3`}</MathBlock>
        <p className="mt-2">
          Message polynomials have degree at most 2. For message word <InlineMath>{`(a_0, a_1, a_2)`}</InlineMath>:
        </p>
        <MathBlock>{`a(X) = a_0 + a_1X + a_2X^2`}</MathBlock>
        <p className="mt-2">The code polynomial is:</p>
        <MathBlock>{`b(X) = (a_0 + a_1X + a_2X^2)(1 + X + X^3)`}</MathBlock>
        <MathBlock>{`= a_0 + (a_0 + a_1)X + (a_1 + a_2)X^2 + (a_0 + a_2)X^3 + a_1X^4 + a_2X^5`}</MathBlock>
        <p className="mt-2">All code words:</p>
        <div className="grid grid-cols-2 gap-4 mt-2">
          <div className="bg-dark-800/50 p-3 rounded-lg font-mono text-sm">
            <p>000 → 000000</p>
            <p>001 → 001101</p>
            <p>010 → 011010</p>
            <p>100 → 110100</p>
          </div>
          <div className="bg-dark-800/50 p-3 rounded-lg font-mono text-sm">
            <p>011 → 010111</p>
            <p>101 → 111001</p>
            <p>110 → 101110</p>
            <p>111 → 100011</p>
          </div>
        </div>
        <p className="mt-4 text-emerald-400">
          The minimum distance of this code is 3. Note that <InlineMath>{`1 + X + X^3`}</InlineMath> does
          not divide <InlineMath>{`X^4 + 1`}</InlineMath> or <InlineMath>{`X^5 + 1`}</InlineMath>.
        </p>
      </Example>

      <Example title="Binary Polynomial Code of Length 7">
        <p>Consider the code of length 7 generated by <InlineMath>{`g(X) = 1 + X^2 + X^3`}</InlineMath>:</p>
        <p className="mt-2">Message words have length 4. Sample code words:</p>
        <div className="bg-dark-800/50 p-3 rounded-lg font-mono text-sm mt-2">
          <p>0000 → 0000000</p>
          <p>0001 → 0001011</p>
          <p>0010 → 0010110</p>
          <p>1000 → 1011000</p>
          <p>1101 → 1111111</p>
        </div>
        <p className="mt-2 text-emerald-400">The minimum distance is 3.</p>
      </Example>

      <h3>Error Detection in Polynomial Codes</h3>

      <Theorem
        title="Undetected Errors"
        proof={
          <>
            <p>
              In a group code, an error vector <InlineMath>{`\\mathbf{e}`}</InlineMath> goes undetected
              if and only if <InlineMath>{`\\mathbf{b} + \\mathbf{e}`}</InlineMath> is a code word for some
              code word <InlineMath>{`\\mathbf{b}`}</InlineMath>.
            </p>
            <p className="mt-2">
              This is equivalent to <InlineMath>{`\\mathbf{e}`}</InlineMath> being a code word.
            </p>
            <p className="mt-2">
              For polynomial codes, this means the error polynomial <InlineMath>{`e(X)`}</InlineMath> is
              a multiple of <InlineMath>{`g(X)`}</InlineMath>.
            </p>
          </>
        }
      >
        <p>
          An error vector <InlineMath>{`\\mathbf{e} = (e_0, e_1, \\ldots, e_{n-1})`}</InlineMath> of a
          polynomial <InlineMath>(m, n)</InlineMath>-code with generator <InlineMath>{`g(X)`}</InlineMath> is
          undetected if and only if the error polynomial <InlineMath>{`e(X) = e_0 + e_1X + \\cdots + e_{n-1}X^{n-1}`}</InlineMath> is
          a multiple of <InlineMath>{`g(X)`}</InlineMath>.
        </p>
      </Theorem>

      <h3>Double Error Detection</h3>

      <Definition title="Double Error">
        <p>
          Two errors occurring at adjacent positions are called a <strong>double error</strong>.
        </p>
        <p className="mt-2">
          For example, <InlineMath>{`e(X) = X^2 + X^3`}</InlineMath> is a double error,
          but <InlineMath>{`e(X) = X + X^3`}</InlineMath> is not.
        </p>
      </Definition>

      <Theorem
        title="Detection of Single and Double Errors"
        proof={
          <>
            <p>
              Since <InlineMath>h(X)</InlineMath> has exponent <InlineMath>{`e > n`}</InlineMath>,
              it is neither constant nor a multiple of <InlineMath>X</InlineMath>.
            </p>
            <p className="mt-2">
              <strong>Case 1:</strong> Error <InlineMath>{`e(X) = X^i + X^j`}</InlineMath> with <InlineMath>{`i + 1 \\leq j \\leq n - 1`}</InlineMath>.
            </p>
            <p className="mt-2">
              Then <InlineMath>{`e(X) = X^i(1 + X^{j-i})`}</InlineMath> with <InlineMath>{`j - i < n`}</InlineMath>.
              Since <InlineMath>h(X)</InlineMath> has exponent <InlineMath>{`e > n`}</InlineMath>,
              it doesn't divide <InlineMath>{`1 + X^{j-i}`}</InlineMath>. Thus <InlineMath>{`g(X) \\nmid e(X)`}</InlineMath>.
            </p>
            <p className="mt-2">
              <strong>Case 2:</strong> Error <InlineMath>{`e(X) = X^i + X^{i+1} + X^j`}</InlineMath> or similar patterns.
            </p>
            <p className="mt-2">
              Since <InlineMath>{`1 + X \\nmid e(X)`}</InlineMath> (odd number of terms), <InlineMath>{`g(X) \\nmid e(X)`}</InlineMath>.
            </p>
            <p className="mt-2">
              <strong>Case 3:</strong> Error <InlineMath>{`e(X) = X^i + X^{i+1} + X^j + X^{j+1}`}</InlineMath>.
            </p>
            <p className="mt-2">
              Then <InlineMath>{`e(X) = (1 + X)(X^i + X^j)`}</InlineMath>. Since <InlineMath>{`h(X) \\nmid X^i + X^j`}</InlineMath>,
              we have <InlineMath>{`g(X) \\nmid e(X)`}</InlineMath>.
            </p>
          </>
        }
      >
        <p>
          In a binary polynomial <InlineMath>(m, n)</InlineMath>-code with encoding
          polynomial <InlineMath>{`g(X) = (1 + X)h(X)`}</InlineMath> where <InlineMath>h(X)</InlineMath> has
          exponent <InlineMath>{`e > n`}</InlineMath>, any combination of two single or double errors will be detected.
        </p>
      </Theorem>

      <h3>Even Weight Code Words</h3>

      <Theorem
        title="Even Weight Condition"
        proof={
          <>
            <p>
              <strong>(⇒)</strong> If <InlineMath>{`g(X) = (1 + X)h(X)`}</InlineMath>, then every code
              polynomial <InlineMath>{`b(X) = a(X)g(X)`}</InlineMath> is divisible by <InlineMath>{`1 + X`}</InlineMath>.
              By the divisibility theorem, <InlineMath>{`b(X)`}</InlineMath> has an even number of terms,
              so the code word has even weight.
            </p>
            <p className="mt-2">
              <strong>(⇐)</strong> Suppose every code word has even weight. Consider the code
              polynomial <InlineMath>{`Xg(X)`}</InlineMath> corresponding to message polynomial <InlineMath>{`a(X) = X`}</InlineMath>.
            </p>
            <p className="mt-2">
              Since this code word has even weight, <InlineMath>{`Xg(X)`}</InlineMath> has an even number
              of terms, so <InlineMath>{`1 + X | Xg(X)`}</InlineMath>.
            </p>
            <p className="mt-2">
              Since <InlineMath>{`\\gcd(X, 1 + X) = 1`}</InlineMath>, we have <InlineMath>{`1 + X | g(X)`}</InlineMath>.
            </p>
          </>
        }
      >
        <p>
          In a binary polynomial <InlineMath>(m, n)</InlineMath>-code with encoding
          polynomial <InlineMath>{`g(X)`}</InlineMath>, every code word has even weight if and only
          if <InlineMath>{`(1 + X) | g(X)`}</InlineMath>.
        </p>
      </Theorem>

      <Callout type="success">
        <strong>Section Summary:</strong> Polynomial codes encode messages by multiplying the
        message polynomial by a generator polynomial. They form a subspace of the word space
        and are therefore group codes. The minimum distance depends on the divisibility properties
        of the generator polynomial. A code generated by <InlineMath>{`g(X)`}</InlineMath> that doesn't
        divide <InlineMath>{`X^k - 1`}</InlineMath> for <InlineMath>{`k < n`}</InlineMath> has minimum distance
        at least 3. When <InlineMath>{`(1 + X) | g(X)`}</InlineMath>, all code words have even weight.
      </Callout>
    </LessonLayout>
  );
}
