import { LessonLayout } from '@/components/layout/LessonLayout';
import { Definition, Theorem, Example } from '@/components/common';
import { MathBlock, InlineMath } from '@/components/common/MathBlock';
import { Callout } from '@/components/common/Callout';

export default function Section19() {
  return (
    <LessonLayout sectionId={19}>
      <p>
        In this section, we study idempotent generators for cyclic codes. An idempotent
        is an element that equals its own square, and such elements provide an elegant
        alternative characterization of cyclic codes.
      </p>

      <Definition title="Idempotent Element">
        <p>
          An element <InlineMath>{`e`}</InlineMath> in a ring <InlineMath>{`R`}</InlineMath> is
          called an <strong>idempotent</strong> if <InlineMath>{`e^2 = e`}</InlineMath>.
        </p>
        <p className="mt-2">
          In the context of the ring <InlineMath>{`R_n = F[X]/\\langle X^n - 1 \\rangle`}</InlineMath>,
          an element <InlineMath>{`e(X) + I`}</InlineMath> is idempotent if:
        </p>
        <MathBlock>{`e(X)^2 \\equiv e(X) \\pmod{X^n - 1}`}</MathBlock>
      </Definition>

      <Callout type="info" title="Motivation">
        <p>
          Every ideal in a principal ideal ring can be generated by a single element.
          For cyclic codes, we use the generator polynomial <InlineMath>{`g(X)`}</InlineMath>.
          However, in certain cases, an idempotent generator provides additional insight
          and computational advantages.
        </p>
      </Callout>

      <h2 className="text-2xl font-bold mt-8 mb-4 text-gradient">Properties of Idempotents</h2>

      <Theorem
        title="Unique Idempotent Generator"
        proof={
          <>
            <p>
              Let <InlineMath>{`\mathscr{C}`}</InlineMath> be a cyclic code
              in <InlineMath>{`R_n = F[X]/\\langle X^n - 1 \\rangle`}</InlineMath> with <InlineMath>{`\\gcd(n, q) = 1`}</InlineMath>.
            </p>
            <p className="mt-2">
              Since <InlineMath>{`R_n`}</InlineMath> is a principal ideal ring, <InlineMath>{`\mathscr{C}`}</InlineMath> is
              generated by a unique monic polynomial <InlineMath>{`g(X)`}</InlineMath> that
              divides <InlineMath>{`X^n - 1`}</InlineMath>.
            </p>
            <p className="mt-2">
              Because <InlineMath>{`\\gcd(n, q) = 1`}</InlineMath>, the
              polynomial <InlineMath>{`X^n - 1`}</InlineMath> has no repeated roots in any extension
              of <InlineMath>{`F`}</InlineMath>. By the Chinese Remainder Theorem for polynomial rings,
              we can decompose <InlineMath>{`R_n`}</InlineMath> into a direct product of fields.
            </p>
            <p className="mt-2">
              In each component field, an ideal is either <InlineMath>{`\\{0\\}`}</InlineMath> or
              the entire field. The idempotent corresponding to <InlineMath>{`\mathscr{C}`}</InlineMath> is
              the element that is 1 in the components corresponding to factors of <InlineMath>{`g(X)`}</InlineMath> in
              the factorization of <InlineMath>{`X^n - 1`}</InlineMath>, and 0 in other components.
            </p>
            <p className="mt-2">
              This idempotent is unique and generates <InlineMath>{`\mathscr{C}`}</InlineMath>.
            </p>
          </>
        }
      >
        <p>
          Let <InlineMath>{`\mathscr{C}`}</InlineMath> be a cyclic code of
          length <InlineMath>{`n`}</InlineMath> over <InlineMath>{`F = \text{GF}(q)`}</InlineMath> with <InlineMath>{`\\gcd(n, q) = 1`}</InlineMath>.
          Then <InlineMath>{`\mathscr{C}`}</InlineMath> contains a unique idempotent <InlineMath>{`e(X)`}</InlineMath> such
          that <InlineMath>{`\mathscr{C} = \langle e(X) \rangle`}</InlineMath>.
        </p>
      </Theorem>

      <Definition title="Primitive Idempotent">
        <p>
          An idempotent <InlineMath>{`e`}</InlineMath> in <InlineMath>{`R_n`}</InlineMath> is
          called <strong>primitive</strong> if it cannot be written as a sum of two
          non-zero orthogonal idempotents (i.e., idempotents <InlineMath>{`e_1, e_2`}</InlineMath> with <InlineMath>{`e_1 e_2 = 0`}</InlineMath>).
        </p>
        <p className="mt-2">
          Primitive idempotents correspond to minimal cyclic codes (cyclic codes that
          contain no proper non-zero cyclic subcodes).
        </p>
      </Definition>

      <h2 className="text-2xl font-bold mt-8 mb-4 text-gradient">Construction of Idempotents</h2>

      <p>
        Let <InlineMath>{`X^n - 1 = f_1(X)f_2(X) \\cdots f_t(X)`}</InlineMath> be the factorization
        of <InlineMath>{`X^n - 1`}</InlineMath> into irreducible factors over <InlineMath>{`F`}</InlineMath>.
        For each <InlineMath>{`i`}</InlineMath>, define:
      </p>
      <MathBlock>{`F_i(X) = \\frac{X^n - 1}{f_i(X)}`}</MathBlock>

      <p className="mt-4">
        Since the <InlineMath>{`f_i(X)`}</InlineMath> are pairwise coprime, there exist
        polynomials <InlineMath>{`u_i(X)`}</InlineMath> such that:
      </p>
      <MathBlock>{`\\sum_{i=1}^{t} u_i(X) F_i(X) \\equiv 1 \\pmod{X^n - 1}`}</MathBlock>

      <Definition title="Primitive Idempotent Formula">
        <p>
          The <strong>primitive idempotent</strong> corresponding to the irreducible
          factor <InlineMath>{`f_i(X)`}</InlineMath> is:
        </p>
        <MathBlock>{`e_i(X) = u_i(X) F_i(X) \\mod (X^n - 1)`}</MathBlock>
        <p className="mt-2">
          These primitive idempotents satisfy:
        </p>
        <ul className="list-disc list-inside mt-2 space-y-1">
          <li><InlineMath>{`e_i(X)^2 \\equiv e_i(X) \\pmod{X^n - 1}`}</InlineMath></li>
          <li><InlineMath>{`e_i(X) e_j(X) \\equiv 0 \\pmod{X^n - 1}`}</InlineMath> for <InlineMath>{`i \\neq j`}</InlineMath></li>
          <li><InlineMath>{`\\sum_{i=1}^t e_i(X) \\equiv 1 \\pmod{X^n - 1}`}</InlineMath></li>
        </ul>
      </Definition>

      <Theorem
        title="Idempotent from Generator Polynomial"
        proof={
          <>
            <p>
              Let <InlineMath>{`g(X) = \\prod_{j \\in S} f_j(X)`}</InlineMath> for some
              subset <InlineMath>{`S \\subseteq \\{1, 2, \\ldots, t\\}`}</InlineMath>.
            </p>
            <p className="mt-2">
              The idempotent generator of <InlineMath>{`\mathscr{C}`}</InlineMath> is:
            </p>
            <MathBlock>{`e(X) = \\sum_{j \\notin S} e_j(X)`}</MathBlock>
            <p className="mt-2">
              This is because <InlineMath>{`e(X)`}</InlineMath> is 1 modulo each <InlineMath>{`f_j(X)`}</InlineMath> for <InlineMath>{`j \\notin S`}</InlineMath>,
              and 0 modulo each <InlineMath>{`f_j(X)`}</InlineMath> for <InlineMath>{`j \\in S`}</InlineMath>.
            </p>
            <p className="mt-2">
              Since <InlineMath>{`c(X) \in \mathscr{C}`}</InlineMath> if and only if <InlineMath>{`g(X) | c(X)`}</InlineMath>,
              which happens if and only if <InlineMath>{`c(X) \\equiv 0 \\pmod{f_j(X)}`}</InlineMath> for
              all <InlineMath>{`j \\in S`}</InlineMath>, we see that <InlineMath>{`e(X)`}</InlineMath> generates
              exactly <InlineMath>{`\mathscr{C}`}</InlineMath>.
            </p>
          </>
        }
      >
        <p>
          Let <InlineMath>{`\mathscr{C}`}</InlineMath> be a cyclic code with generator
          polynomial <InlineMath>{`g(X)`}</InlineMath>. If <InlineMath>{`g(X) = \\prod_{j \\in S} f_j(X)`}</InlineMath> where
          the <InlineMath>{`f_j(X)`}</InlineMath> are distinct irreducible factors of <InlineMath>{`X^n - 1`}</InlineMath>,
          then the idempotent generator of <InlineMath>{`\mathscr{C}`}</InlineMath> is:
        </p>
        <MathBlock>{`e(X) = \\sum_{j \\notin S} e_j(X)`}</MathBlock>
        <p className="mt-2">
          where the sum is over all indices <InlineMath>{`j`}</InlineMath> such
          that <InlineMath>{`f_j(X) \\nmid g(X)`}</InlineMath>.
        </p>
      </Theorem>

      <Example title="Idempotent for Binary Cyclic Code of Length 7">
        <p>
          Over <InlineMath>{`\mathbb{B}`}</InlineMath>, we have:
        </p>
        <MathBlock>
          {`X^7 - 1 = (X + 1)(X^3 + X + 1)(X^3 + X^2 + 1)`}
        </MathBlock>
        <p className="mt-2">
          Let <InlineMath>{`f_1(X) = X + 1`}</InlineMath>, <InlineMath>{`f_2(X) = X^3 + X + 1`}</InlineMath>,
          and <InlineMath>{`f_3(X) = X^3 + X^2 + 1`}</InlineMath>.
        </p>
        <p className="mt-2">
          For the cyclic code <InlineMath>{`\mathscr{C}`}</InlineMath> generated
          by <InlineMath>{`g(X) = X^3 + X + 1`}</InlineMath>, we have <InlineMath>{`S = \\{2\\}`}</InlineMath>.
        </p>
        <p className="mt-2">
          The idempotent generator is <InlineMath>{`e(X) = e_1(X) + e_3(X)`}</InlineMath>, where <InlineMath>{`e_1(X)`}</InlineMath> and <InlineMath>{`e_3(X)`}</InlineMath> are
          the primitive idempotents corresponding to <InlineMath>{`f_1(X)`}</InlineMath> and <InlineMath>{`f_3(X)`}</InlineMath>.
        </p>
        <p className="mt-2">
          Computing these using the extended Euclidean algorithm gives a specific polynomial
          representation for <InlineMath>{`e(X)`}</InlineMath>.
        </p>
      </Example>

      <h2 className="text-2xl font-bold mt-8 mb-4 text-gradient">Applications of Idempotents</h2>

      <Callout type="success" title="Advantages of Idempotent Generators">
        <ol className="list-decimal list-inside mt-2 space-y-2">
          <li>
            <strong>Projection property:</strong> For any <InlineMath>{`a(X) \\in R_n`}</InlineMath>,
            the product <InlineMath>{`a(X)e(X)`}</InlineMath> gives the projection
            of <InlineMath>{`a(X)`}</InlineMath> onto the code <InlineMath>{`\mathscr{C}`}</InlineMath>.
          </li>
          <li>
            <strong>Direct computation:</strong> The idempotent can be computed directly
            from the factorization of <InlineMath>{`X^n - 1`}</InlineMath> without needing
            to find a generator polynomial explicitly.
          </li>
          <li>
            <strong>Dual code:</strong> If <InlineMath>{`e(X)`}</InlineMath> is the idempotent
            of <InlineMath>{`\mathscr{C}`}</InlineMath>, then <InlineMath>{`1 - e(X)`}</InlineMath> is
            related to the idempotent of <InlineMath>{`\mathscr{C}^\perp`}</InlineMath>.
          </li>
        </ol>
      </Callout>

      <Theorem
        title="Idempotent of Dual Code"
        proof={
          <>
            <p>
              If <InlineMath>{`e(X) = \\sum_{j \\notin S} e_j(X)`}</InlineMath> is the idempotent
              of <InlineMath>{`\mathscr{C}`}</InlineMath>, then:
            </p>
            <MathBlock>{`1 - e(X) = \\sum_{j \\in S} e_j(X)`}</MathBlock>
            <p className="mt-2">
              The dual code <InlineMath>{`\mathscr{C}^\perp`}</InlineMath> has generator
              polynomial <InlineMath>{`h^*(X) = X^{n-r}h(X^{-1})`}</InlineMath>, where <InlineMath>{`h(X) = (X^n - 1)/g(X)`}</InlineMath>.
            </p>
            <p className="mt-2">
              The idempotent of <InlineMath>{`\mathscr{C}^\perp`}</InlineMath> is obtained by taking
              the reciprocal polynomial of <InlineMath>{`1 - e(X)`}</InlineMath>, giving the stated formula.
            </p>
          </>
        }
      >
        <p>
          Let <InlineMath>{`e(X)`}</InlineMath> be the idempotent of a cyclic
          code <InlineMath>{`\mathscr{C}`}</InlineMath>. Then the idempotent of the dual
          code <InlineMath>{`\mathscr{C}^\perp`}</InlineMath> is:
        </p>
        <MathBlock>{`e^\\perp(X) = X^{n-1}(1 - e(X^{-1})) \\mod (X^n - 1)`}</MathBlock>
        <p className="mt-2">
          In particular, if <InlineMath>{`e(X) = e(X^{-1})`}</InlineMath> (i.e., <InlineMath>{`e(X)`}</InlineMath> is
          self-reciprocal), then <InlineMath>{`e^\\perp(X) = 1 - e(X)`}</InlineMath>.
        </p>
      </Theorem>

      <Example title="Self-Orthogonal Idempotent">
        <p>
          A cyclic code <InlineMath>{`\mathscr{C}`}</InlineMath> is self-orthogonal
          (<InlineMath>{`\mathscr{C} \subseteq \mathscr{C}^\perp`}</InlineMath>) if and only if its
          idempotent <InlineMath>{`e(X)`}</InlineMath> satisfies:
        </p>
        <MathBlock>{`e(X) \\cdot e^\\perp(X) = e(X)`}</MathBlock>
        <p className="mt-2">
          This provides a useful criterion for constructing self-orthogonal cyclic codes.
        </p>
      </Example>
    </LessonLayout>
  );
}
