import { LessonLayout } from '@/components/layout/LessonLayout';
import { Definition, Theorem, Example } from '@/components/common';
import { MathBlock, InlineMath } from '@/components/common/MathBlock';
import { Callout } from '@/components/common/Callout';

export default function Section05() {
  return (
    <LessonLayout sectionId={5}>
      <h2>2.3 Generator and Parity Check Matrices - General Case</h2>

      <p>
        We have seen that polynomial codes can be studied using polynomial multiplication.
        However, we can also represent polynomial codes using matrix techniques. In this section,
        we develop the general theory of generator and parity check matrices, connecting
        polynomial codes to matrix codes.
      </p>

      <h3>General Definition of Generator Matrix</h3>

      <p>
        Previously, we defined generator matrices in standard form where the first <InlineMath>m</InlineMath> columns
        form the identity matrix. We now generalize this definition.
      </p>

      <Definition title="Generator Matrix (General)">
        <p>
          Let <InlineMath>{`\\mathcal{C}`}</InlineMath> be an <InlineMath>(m, n)</InlineMath>-code.
          If there exists an <InlineMath>{`m \\times n`}</InlineMath> matrix <InlineMath>{`\\mathbf{G}`}</InlineMath> of
          rank <InlineMath>m</InlineMath> such that:
        </p>
        <MathBlock>{`\\mathcal{C} = \\{\\mathbf{aG} : \\mathbf{a} \\in \\mathbb{B}^m\\}`}</MathBlock>
        <p className="mt-2">
          then <InlineMath>{`\\mathbf{G}`}</InlineMath> is called a <strong>generator matrix</strong> of
          the code <InlineMath>{`\\mathcal{C}`}</InlineMath>, and <InlineMath>{`\\mathcal{C}`}</InlineMath> is
          called a <strong>matrix code</strong> generated by <InlineMath>{`\\mathbf{G}`}</InlineMath>.
        </p>
      </Definition>

      <Definition title="Parity Check Matrix (General)">
        <p>
          Let <InlineMath>{`\\mathcal{C}`}</InlineMath> be an <InlineMath>(m, n)</InlineMath>-code.
          If there exists an <InlineMath>{`(n - m) \\times n`}</InlineMath> matrix <InlineMath>{`\\mathbf{H}`}</InlineMath> of
          rank <InlineMath>{`n - m`}</InlineMath> such that <InlineMath>{`\\mathbf{Hb}^t = \\mathbf{0}`}</InlineMath> for
          all <InlineMath>{`\\mathbf{b} \\in \\mathcal{C}`}</InlineMath>, then <InlineMath>{`\\mathbf{H}`}</InlineMath> is
          called a <strong>parity check matrix</strong> of <InlineMath>{`\\mathcal{C}`}</InlineMath>.
        </p>
      </Definition>

      <Callout type="info">
        <strong>Rank Requirement:</strong> We insist that the generator matrix has rank <InlineMath>m</InlineMath> to
        ensure the encoding map <InlineMath>{`\\mathbf{a} \\mapsto \\mathbf{aG}`}</InlineMath> is one-to-one.
        If the rank is less than <InlineMath>m</InlineMath>, different message words could produce the
        same code word.
      </Callout>

      <h3>Polynomial Codes as Matrix Codes</h3>

      <Theorem
        title="Polynomial Codes are Matrix Codes"
        proof={
          <>
            <p>
              Let <InlineMath>{`\\mathcal{C}`}</InlineMath> be a polynomial <InlineMath>(m, n)</InlineMath>-code
              with encoding polynomial <InlineMath>{`g(X) = g_0 + g_1X + \\cdots + g_kX^k`}</InlineMath> where <InlineMath>{`n = m + k`}</InlineMath>.
            </p>
            <p className="mt-2">
              Construct the <InlineMath>{`m \\times n`}</InlineMath> matrix <InlineMath>{`\\mathbf{G}`}</InlineMath> whose
              rows are the coefficients of <InlineMath>{`g(X), Xg(X), \\ldots, X^{m-1}g(X)`}</InlineMath>:
            </p>
            <MathBlock>{`\\mathbf{G} = \\begin{pmatrix} g_0 & g_1 & \\cdots & g_k & 0 & \\cdots & 0 \\\\ 0 & g_0 & g_1 & \\cdots & g_k & \\cdots & 0 \\\\ \\vdots & & \\ddots & & \\ddots & \\ddots & \\vdots \\\\ 0 & 0 & \\cdots & 0 & g_0 & g_1 & \\cdots & g_k \\end{pmatrix}`}</MathBlock>
            <p className="mt-2">
              The determinant of the submatrix formed by the first <InlineMath>m</InlineMath> columns
              is <InlineMath>{`g_0^m \\neq 0`}</InlineMath> since <InlineMath>{`g_0 \\neq 0`}</InlineMath>.
              Thus rank<InlineMath>{`(\\mathbf{G}) = m`}</InlineMath>.
            </p>
            <p className="mt-2">
              For message word <InlineMath>{`\\mathbf{a} = (a_0, a_1, \\ldots, a_{m-1})`}</InlineMath>,
              the product <InlineMath>{`\\mathbf{aG}`}</InlineMath> gives the coefficients of:
            </p>
            <MathBlock>{`a_0g(X) + a_1Xg(X) + \\cdots + a_{m-1}X^{m-1}g(X) = a(X)g(X)`}</MathBlock>
            <p className="mt-2">
              which is exactly the code polynomial in the polynomial code.
            </p>
          </>
        }
      >
        <p>A polynomial code is a matrix code.</p>
      </Theorem>

      <Example title="Generator Matrix of a Polynomial Code">
        <p>
          Consider the <InlineMath>(3, 6)</InlineMath> polynomial code with encoding
          polynomial <InlineMath>{`g(X) = 1 + X + X^3`}</InlineMath>.
        </p>
        <p className="mt-2">The generator matrix is:</p>
        <MathBlock>{`\\mathbf{G} = \\begin{pmatrix} 1 & 1 & 0 & 1 & 0 & 0 \\\\ 0 & 1 & 1 & 0 & 1 & 0 \\\\ 0 & 0 & 1 & 1 & 0 & 1 \\end{pmatrix}`}</MathBlock>
        <p className="mt-2">
          Row 1 corresponds to <InlineMath>{`g(X) = 1 + X + X^3`}</InlineMath>, Row 2 to <InlineMath>{`Xg(X)`}</InlineMath>,
          and Row 3 to <InlineMath>{`X^2g(X)`}</InlineMath>.
        </p>
      </Example>

      <Example title="Generator Matrices for (4, 7) Polynomial Codes">
        <div className="space-y-4">
          <div>
            <p><strong>(i)</strong> For <InlineMath>{`g(X) = 1 + X^2 + X^3`}</InlineMath>:</p>
            <MathBlock>{`\\mathbf{G} = \\begin{pmatrix} 1 & 0 & 1 & 1 & 0 & 0 & 0 \\\\ 0 & 1 & 0 & 1 & 1 & 0 & 0 \\\\ 0 & 0 & 1 & 0 & 1 & 1 & 0 \\\\ 0 & 0 & 0 & 1 & 0 & 1 & 1 \\end{pmatrix}`}</MathBlock>
          </div>
          <div>
            <p><strong>(ii)</strong> For <InlineMath>{`g(X) = 1 + X + X^3`}</InlineMath>:</p>
            <MathBlock>{`\\mathbf{G} = \\begin{pmatrix} 1 & 1 & 0 & 1 & 0 & 0 & 0 \\\\ 0 & 1 & 1 & 0 & 1 & 0 & 0 \\\\ 0 & 0 & 1 & 1 & 0 & 1 & 0 \\\\ 0 & 0 & 0 & 1 & 1 & 0 & 1 \\end{pmatrix}`}</MathBlock>
          </div>
        </div>
      </Example>

      <h3>Finding Parity Check Matrices</h3>

      <p>
        For polynomial codes, finding the parity check matrix requires solving a system of
        linear equations. Unlike the standard form case, the relationship is more complex.
      </p>

      <Example title="Finding a Parity Check Matrix">
        <p>
          Consider the <InlineMath>(4, 7)</InlineMath> polynomial code with <InlineMath>{`g(X) = 1 + X + X^3`}</InlineMath>.
          The code word for message <InlineMath>{`(a_0, a_1, a_2, a_3)`}</InlineMath> is:
        </p>
        <MathBlock>{`(a_0, a_0 + a_1, a_1 + a_2, a_0 + a_2 + a_3, a_1 + a_3, a_2, a_3)`}</MathBlock>
        <p className="mt-2">
          Let <InlineMath>{`\\alpha_i`}</InlineMath> be elements from <InlineMath>{`\\mathbb{B}`}</InlineMath> such
          that <InlineMath>{`\\sum_{i=0}^{6} \\alpha_i b_i = 0`}</InlineMath> for all code words <InlineMath>{`(b_0, \\ldots, b_6)`}</InlineMath>.
        </p>
        <p className="mt-2">Substituting and collecting coefficients:</p>
        <MathBlock>{`\\begin{aligned}
a_0(\\alpha_0 + \\alpha_1 + \\alpha_3) + a_1(\\alpha_1 + \\alpha_2 + \\alpha_4) \\\\
+ a_2(\\alpha_2 + \\alpha_3 + \\alpha_5) + a_3(\\alpha_3 + \\alpha_4 + \\alpha_6) = 0
\\end{aligned}`}</MathBlock>
        <p className="mt-2">This must hold for all <InlineMath>{`\\mathbf{a} \\in \\mathbb{B}^4`}</InlineMath>, giving:</p>
        <MathBlock>{`\\alpha_0 + \\alpha_1 + \\alpha_3 = 0, \\quad \\alpha_1 + \\alpha_2 + \\alpha_4 = 0`}</MathBlock>
        <MathBlock>{`\\alpha_2 + \\alpha_3 + \\alpha_5 = 0, \\quad \\alpha_3 + \\alpha_4 + \\alpha_6 = 0`}</MathBlock>
        <p className="mt-2">One solution gives the parity check matrix:</p>
        <MathBlock>{`\\mathbf{H} = \\begin{pmatrix} 0 & 1 & 1 & 1 & 0 & 0 & 1 \\\\ 0 & 1 & 0 & 1 & 1 & 1 & 0 \\\\ 1 & 1 & 0 & 0 & 1 & 0 & 1 \\end{pmatrix}`}</MathBlock>
      </Example>

      <Callout type="warning">
        <strong>Non-Uniqueness:</strong> Unlike the standard form case, for general polynomial codes
        there may be multiple valid parity check matrices. Different choices of free variables in
        the system of equations lead to different parity check matrices.
      </Callout>

      <h3>Importance of Full Rank</h3>

      <Example title="Why Rank Matters">
        <p>Consider the <InlineMath>{`3 \\times 6`}</InlineMath> matrix:</p>
        <MathBlock>{`\\mathbf{G} = \\begin{pmatrix} 1 & 1 & 0 & 1 & 0 & 0 \\\\ 0 & 1 & 1 & 0 & 1 & 1 \\\\ 1 & 0 & 1 & 1 & 1 & 1 \\end{pmatrix}`}</MathBlock>
        <p className="mt-2">Computing:</p>
        <MathBlock>{`(0, 0, 0)\\mathbf{G} = (0, 0, 0, 0, 0, 0) = (1, 1, 1)\\mathbf{G}`}</MathBlock>
        <MathBlock>{`(0, 0, 1)\\mathbf{G} = (1, 0, 1, 1, 1, 1) = (1, 1, 0)\\mathbf{G}`}</MathBlock>
        <MathBlock>{`(1, 0, 0)\\mathbf{G} = (1, 1, 0, 1, 0, 0) = (0, 1, 1)\\mathbf{G}`}</MathBlock>
        <p className="mt-2 text-rose-400">
          The map <InlineMath>{`\\mathbf{a} \\mapsto \\mathbf{aG}`}</InlineMath> is not one-to-one because
          the rows of <InlineMath>{`\\mathbf{G}`}</InlineMath> are linearly dependent
          (rank<InlineMath>{`(\\mathbf{G}) < 3`}</InlineMath>).
        </p>
        <p className="mt-2">
          This means different message words produce the same code word, making the code unusable
          for reliable communication.
        </p>
      </Example>

      <h3>Structure of Polynomial Code Generator Matrices</h3>

      <Callout type="info">
        <strong>Key Observation:</strong> For a polynomial code with generator <InlineMath>{`g(X)`}</InlineMath>,
        the generator matrix has a special <strong>shift structure</strong>: each row is a cyclic
        shift of the coefficients of <InlineMath>{`g(X)`}</InlineMath> to the right.
        <p className="mt-2">
          This structure is fundamental to <strong>cyclic codes</strong>, which we will study later.
        </p>
      </Callout>

      <h3>Connection Between Generator and Parity Check Matrices</h3>

      <p>
        For a polynomial code, if we can convert the generator matrix to standard form through
        row operations, we can then easily find the parity check matrix using the formula
        from Section 2.
      </p>

      <Theorem
        title="Fundamental Property"
        proof={
          <>
            <p>
              Let <InlineMath>{`\\mathbf{b}`}</InlineMath> be any code word. Then <InlineMath>{`\\mathbf{b} = \\mathbf{aG}`}</InlineMath> for
              some message word <InlineMath>{`\\mathbf{a}`}</InlineMath>.
            </p>
            <p className="mt-2">
              By definition of <InlineMath>{`\\mathbf{H}`}</InlineMath>, we have <InlineMath>{`\\mathbf{Hb}^t = \\mathbf{0}`}</InlineMath>.
            </p>
            <p className="mt-2">
              Substituting:
            </p>
            <MathBlock>{`\\mathbf{H}(\\mathbf{aG})^t = \\mathbf{HG}^t\\mathbf{a}^t = \\mathbf{0}`}</MathBlock>
            <p className="mt-2">
              Since this holds for all <InlineMath>{`\\mathbf{a} \\in \\mathbb{B}^m`}</InlineMath>,
              we must have <InlineMath>{`\\mathbf{HG}^t = \\mathbf{0}`}</InlineMath>,
              equivalently <InlineMath>{`\\mathbf{GH}^t = \\mathbf{0}`}</InlineMath>.
            </p>
          </>
        }
      >
        <p>
          If <InlineMath>{`\\mathbf{G}`}</InlineMath> is a generator matrix and <InlineMath>{`\\mathbf{H}`}</InlineMath> is
          a parity check matrix for the same code, then:
        </p>
        <MathBlock>{`\\mathbf{GH}^t = \\mathbf{0}`}</MathBlock>
      </Theorem>

      <Example title="Verifying the Fundamental Property">
        <p>
          For the <InlineMath>(4, 7)</InlineMath> code with <InlineMath>{`g(X) = 1 + X + X^3`}</InlineMath>:
        </p>
        <MathBlock>{`\\mathbf{G} = \\begin{pmatrix} 1 & 1 & 0 & 1 & 0 & 0 & 0 \\\\ 0 & 1 & 1 & 0 & 1 & 0 & 0 \\\\ 0 & 0 & 1 & 1 & 0 & 1 & 0 \\\\ 0 & 0 & 0 & 1 & 1 & 0 & 1 \\end{pmatrix}`}</MathBlock>
        <MathBlock>{`\\mathbf{H} = \\begin{pmatrix} 0 & 1 & 1 & 1 & 0 & 0 & 1 \\\\ 0 & 1 & 0 & 1 & 1 & 1 & 0 \\\\ 1 & 1 & 0 & 0 & 1 & 0 & 1 \\end{pmatrix}`}</MathBlock>
        <p className="mt-2">
          Computing <InlineMath>{`\\mathbf{GH}^t`}</InlineMath> (over <InlineMath>{`\\mathbb{B}`}</InlineMath>)
          gives the <InlineMath>{`4 \\times 3`}</InlineMath> zero matrix.
        </p>
      </Example>

      <Callout type="success">
        <strong>Section Summary:</strong> Polynomial codes can be represented as matrix codes with
        generator matrices having a specific shift structure. The generator matrix has rank <InlineMath>m</InlineMath> to
        ensure one-to-one encoding. The parity check matrix satisfies <InlineMath>{`\\mathbf{GH}^t = \\mathbf{0}`}</InlineMath>.
        For polynomial codes not in standard form, finding the parity check matrix requires solving
        a system of linear equations.
      </Callout>
    </LessonLayout>
  );
}
