import { LessonLayout } from '@/components/layout/LessonLayout';
import { Callout } from '@/components/common/Callout';
import { MathBlock, InlineMath } from '@/components/common/MathBlock';

export default function Section21() {
  return (
    <LessonLayout sectionId={21}>
      <h2>Chapter XXII: On Surfaces</h2>
      <p className="text-lg text-dark-300 italic mb-6">
        Appendix: De Superficiebus
      </p>

      <p>
        In this appendix, Euler extends the theory of curves to three dimensions,
        introducing the study of <strong>surfaces</strong>. Just as curves are
        one-dimensional objects in the plane, surfaces are two-dimensional objects
        in space, defined by equations in three variables.
      </p>

      <Callout type="info">
        <strong>Generalization:</strong> Everything we learned about curves—coordinates,
        equations, classification by degree, asymptotic behavior—has a three-dimensional
        analogue for surfaces.
      </Callout>

      <h2>Coordinates in Space</h2>

      <p>
        A point in three-dimensional space is specified by three coordinates:
      </p>

      <MathBlock>{`P = (x, y, z)`}</MathBlock>

      <p>
        The three coordinate axes are mutually perpendicular, meeting at the origin
        <InlineMath>O = (0, 0, 0)</InlineMath>. Each pair of axes determines a
        <strong> coordinate plane</strong>:
      </p>

      <ul className="list-disc list-inside space-y-2 my-4 text-dark-300">
        <li><InlineMath>xy</InlineMath>-plane: <InlineMath>z = 0</InlineMath></li>
        <li><InlineMath>xz</InlineMath>-plane: <InlineMath>y = 0</InlineMath></li>
        <li><InlineMath>yz</InlineMath>-plane: <InlineMath>x = 0</InlineMath></li>
      </ul>

      <h2>Equations of Surfaces</h2>

      <p>
        A surface is the locus of points satisfying an equation:
      </p>

      <MathBlock>{`F(x, y, z) = 0`}</MathBlock>

      <p>
        Alternatively, if we can solve for <InlineMath>z</InlineMath>:
      </p>

      <MathBlock>{`z = f(x, y)`}</MathBlock>

      <p>
        This explicit form shows <InlineMath>z</InlineMath> as a function of
        <InlineMath>x</InlineMath> and <InlineMath>y</InlineMath>—the height of
        the surface above the <InlineMath>xy</InlineMath>-plane.
      </p>

      <h2>Planes</h2>

      <p>
        The simplest surfaces are planes, given by first-degree equations:
      </p>

      <MathBlock>{`ax + by + cz + d = 0`}</MathBlock>

      <div className="bg-dark-800/50 rounded-xl p-6 border border-dark-700 my-6">
        <h3 className="text-primary-400 mb-4">Special Planes</h3>
        <ul className="space-y-2 text-dark-300">
          <li><InlineMath>z = c</InlineMath>: horizontal plane at height <InlineMath>c</InlineMath></li>
          <li><InlineMath>x = c</InlineMath>: plane parallel to <InlineMath>yz</InlineMath>-plane</li>
          <li><InlineMath>x + y + z = 1</InlineMath>: plane cutting all three axes at 1</li>
        </ul>
      </div>

      <h2>Quadric Surfaces</h2>

      <p>
        Second-degree equations define <strong>quadric surfaces</strong>—the
        three-dimensional analogues of conics:
      </p>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 my-6">
        <div className="bg-dark-800/50 rounded-xl p-4 border border-dark-700">
          <h4 className="text-emerald-400 font-semibold mb-2">Sphere</h4>
          <MathBlock>{`x^2 + y^2 + z^2 = r^2`}</MathBlock>
          <p className="text-dark-400 text-sm mt-2">
            All points at distance <InlineMath>r</InlineMath> from the origin
          </p>
        </div>
        <div className="bg-dark-800/50 rounded-xl p-4 border border-dark-700">
          <h4 className="text-blue-400 font-semibold mb-2">Ellipsoid</h4>
          <MathBlock>{`\\frac{x^2}{a^2} + \\frac{y^2}{b^2} + \\frac{z^2}{c^2} = 1`}</MathBlock>
          <p className="text-dark-400 text-sm mt-2">
            Stretched sphere with three different semi-axes
          </p>
        </div>
        <div className="bg-dark-800/50 rounded-xl p-4 border border-dark-700">
          <h4 className="text-purple-400 font-semibold mb-2">Paraboloid</h4>
          <MathBlock>{`z = x^2 + y^2`}</MathBlock>
          <p className="text-dark-400 text-sm mt-2">
            Bowl-shaped surface (satellite dish shape)
          </p>
        </div>
        <div className="bg-dark-800/50 rounded-xl p-4 border border-dark-700">
          <h4 className="text-amber-400 font-semibold mb-2">Hyperboloid</h4>
          <MathBlock>{`\\frac{x^2}{a^2} + \\frac{y^2}{b^2} - \\frac{z^2}{c^2} = 1`}</MathBlock>
          <p className="text-dark-400 text-sm mt-2">
            One sheet: cooling tower shape
          </p>
        </div>
      </div>

      <h2>Ruled Surfaces</h2>

      <p>
        A <strong>ruled surface</strong> is generated by moving a straight line:
      </p>

      <div className="bg-dark-800 p-4 rounded-lg my-4 border-l-4 border-amber-500">
        <p className="font-semibold text-amber-400">Examples of Ruled Surfaces</p>
        <ul className="mt-2 space-y-2 text-dark-300">
          <li>
            <strong>Cone:</strong> Lines through a fixed point (the vertex)
          </li>
          <li>
            <strong>Cylinder:</strong> Lines parallel to a fixed direction
          </li>
          <li>
            <strong>Hyperboloid of one sheet:</strong> Contains two families of lines!
          </li>
          <li>
            <strong>Hyperbolic paraboloid:</strong> The "saddle" surface, also doubly ruled
          </li>
        </ul>
      </div>

      <Callout type="success">
        <strong>Remarkable Fact:</strong> The hyperboloid of one sheet and the hyperbolic
        paraboloid are <em>doubly ruled</em>—through every point pass two different lines
        lying entirely on the surface. This is why hyperboloids are used in architecture
        (easy to construct from straight beams).
      </Callout>

      <h2>Surfaces of Revolution</h2>

      <p>
        Rotating a plane curve around an axis creates a <strong>surface of revolution</strong>:
      </p>

      <ul className="list-disc list-inside space-y-2 my-4 text-dark-300">
        <li>Circle rotated around diameter → Sphere</li>
        <li>Ellipse rotated around axis → Ellipsoid of revolution (spheroid)</li>
        <li>Parabola rotated around axis → Paraboloid of revolution</li>
        <li>Catenary rotated → Catenoid (minimal surface)</li>
      </ul>

      <MathBlock>{`\\text{Curve } y = f(x) \\text{ rotated around } x\\text{-axis: } y^2 + z^2 = [f(x)]^2`}</MathBlock>

      <h2>Tangent Planes and Normals</h2>

      <p>
        At a smooth point of a surface <InlineMath>F(x, y, z) = 0</InlineMath>,
        the <strong>tangent plane</strong> is:
      </p>

      <MathBlock>{`F_x(P)(X - x_0) + F_y(P)(Y - y_0) + F_z(P)(Z - z_0) = 0`}</MathBlock>

      <p>
        The <strong>normal line</strong> is perpendicular to the tangent plane,
        with direction vector <InlineMath>(F_x, F_y, F_z)</InlineMath>.
      </p>

      <h2>Classification by Degree</h2>

      <p>
        Surfaces are classified by the degree of their defining equation:
      </p>

      <div className="bg-dark-800/50 rounded-xl p-6 border border-dark-700 my-6">
        <table className="w-full text-left">
          <thead>
            <tr className="border-b border-dark-600">
              <th className="pb-2">Degree</th>
              <th className="pb-2">Name</th>
              <th className="pb-2">Examples</th>
            </tr>
          </thead>
          <tbody className="text-dark-300">
            <tr className="border-b border-dark-700">
              <td className="py-2">1</td>
              <td>Planes</td>
              <td><InlineMath>ax + by + cz = d</InlineMath></td>
            </tr>
            <tr className="border-b border-dark-700">
              <td className="py-2">2</td>
              <td>Quadrics</td>
              <td>Sphere, ellipsoid, paraboloid, hyperboloid</td>
            </tr>
            <tr className="border-b border-dark-700">
              <td className="py-2">3</td>
              <td>Cubic surfaces</td>
              <td>27 lines on a smooth cubic!</td>
            </tr>
            <tr>
              <td className="py-2">n</td>
              <td>Degree-n surfaces</td>
              <td>Increasingly complex</td>
            </tr>
          </tbody>
        </table>
      </div>

      <h2>Looking Forward</h2>

      <p>
        Euler's treatment of surfaces in this appendix laid groundwork for:
      </p>

      <ul className="list-disc list-inside space-y-2 my-4 text-dark-300">
        <li><strong>Differential geometry:</strong> Curvature of surfaces (Gauss)</li>
        <li><strong>Algebraic geometry:</strong> Higher-dimensional varieties</li>
        <li><strong>Topology:</strong> Classification of surfaces by genus</li>
        <li><strong>Computer graphics:</strong> Surface modeling and rendering</li>
      </ul>

      <Callout type="success">
        <strong>Chapter Summary:</strong> The theory of curves extends naturally to
        surfaces in three dimensions. Quadric surfaces (degree 2) include spheres,
        ellipsoids, paraboloids, and hyperboloids—each with distinctive properties.
        Ruled surfaces and surfaces of revolution provide important special cases.
        The classification of surfaces by degree, tangent planes, and normal lines
        generalize the corresponding notions for curves. This appendix opens the door
        to higher-dimensional geometry and the modern field of algebraic geometry.
      </Callout>

      <div className="mt-8 p-6 bg-gradient-to-r from-amber-900/30 to-amber-700/30 rounded-xl border border-amber-600/50">
        <h3 className="text-xl font-bold text-amber-400 mb-4">Conclusion of the Course</h3>
        <p className="text-dark-200">
          You have completed Euler's <em>Introductio in Analysin Infinitorum</em>,
          Volume II—a foundational text in the theory of curves. From the basic
          correspondence between equations and geometry, through the classification
          of conics and cubics, to transcendental curves and surfaces, you have
          traced the development of ideas that remain central to mathematics today.
        </p>
        <p className="text-dark-200 mt-4">
          Euler's analytical approach—using algebra and calculus to study geometry—
          transformed mathematics and continues to influence how we think about
          curves, surfaces, and their generalizations.
        </p>
      </div>
    </LessonLayout>
  );
}
