import { LessonLayout } from '@/components/layout/LessonLayout';
import { Definition, Theorem, Example } from '@/components/common/ContentBlocks';
import { Callout } from '@/components/common/Callout';
import { MathBlock, InlineMath } from '@/components/common/MathBlock';
import { SectionQuiz } from '@/components/quiz/SectionQuiz';
import { quizMap } from '@/data/quizzes';

export default function Section02() {
  return (
    <LessonLayout sectionId={2}>
      <h2>Pythagorean Triples</h2>

      <p>
        A <strong>Pythagorean triple</strong> is a set of three positive integers
        <InlineMath>(a, b, c)</InlineMath> that satisfy the Pythagorean equation
        <InlineMath>a^2 + b^2 = c^2</InlineMath>. These triples have fascinated
        mathematicians for millennia, from ancient Babylon to modern number theory.
      </p>

      <h3>The First Pythagorean Triples</h3>

      <p>
        The most famous Pythagorean triple is <InlineMath>(3, 4, 5)</InlineMath>:
      </p>

      <MathBlock>
        {`3^2 + 4^2 = 9 + 16 = 25 = 5^2`}
      </MathBlock>

      <p>
        This triple was known in ancient Egypt, where it was used to construct
        right angles. A rope with 12 equally-spaced knots, when formed into a
        triangle with sides 3, 4, and 5 units, produces a perfect right angle.
      </p>

      <Example title="More Pythagorean Triples">
        <p>Here are the first few Pythagorean triples:</p>
        <div className="grid grid-cols-2 gap-4 mt-4">
          <div>
            <MathBlock>{`(3, 4, 5): \\quad 9 + 16 = 25`}</MathBlock>
          </div>
          <div>
            <MathBlock>{`(5, 12, 13): \\quad 25 + 144 = 169`}</MathBlock>
          </div>
          <div>
            <MathBlock>{`(8, 15, 17): \\quad 64 + 225 = 289`}</MathBlock>
          </div>
          <div>
            <MathBlock>{`(7, 24, 25): \\quad 49 + 576 = 625`}</MathBlock>
          </div>
        </div>
      </Example>

      <h3>Primitive vs. Non-Primitive Triples</h3>

      <Definition title="Primitive Pythagorean Triple">
        <p>
          A Pythagorean triple <InlineMath>(a, b, c)</InlineMath> is called
          <strong> primitive</strong> if <InlineMath>\\gcd(a, b, c) = 1</InlineMath>,
          meaning the three numbers share no common factor greater than 1.
        </p>
      </Definition>

      <p>
        If <InlineMath>(a, b, c)</InlineMath> is a Pythagorean triple, then so is
        <InlineMath>(ka, kb, kc)</InlineMath> for any positive integer <InlineMath>k</InlineMath>.
        For example, <InlineMath>(6, 8, 10)</InlineMath> is a non-primitive triple
        (it's just <InlineMath>(3, 4, 5)</InlineMath> multiplied by 2).
      </p>

      <h3>Generating All Pythagorean Triples</h3>

      <p>
        The ancient Greeks discovered a remarkable formula that generates all
        primitive Pythagorean triples. This formula was known to Euclid around 300 BCE.
      </p>

      <Theorem title="Euclid's Formula for Pythagorean Triples">
        <p>
          Every primitive Pythagorean triple <InlineMath>(a, b, c)</InlineMath> can be
          generated by choosing positive integers <InlineMath>m {'>'} n</InlineMath> with
          <InlineMath>\\gcd(m, n) = 1</InlineMath> and <InlineMath>m - n</InlineMath> odd, then setting:
        </p>
        <MathBlock>
          {`a = m^2 - n^2, \\quad b = 2mn, \\quad c = m^2 + n^2`}
        </MathBlock>
      </Theorem>

      <Example title="Generating (3, 4, 5)">
        <p>
          Let <InlineMath>m = 2</InlineMath> and <InlineMath>n = 1</InlineMath>:
        </p>
        <MathBlock>
          {`\\begin{aligned}
a &= m^2 - n^2 = 4 - 1 = 3 \\\\
b &= 2mn = 2 \\cdot 2 \\cdot 1 = 4 \\\\
c &= m^2 + n^2 = 4 + 1 = 5
\\end{aligned}`}
        </MathBlock>
      </Example>

      <Example title="Generating (5, 12, 13)">
        <p>
          Let <InlineMath>m = 3</InlineMath> and <InlineMath>n = 2</InlineMath>:
        </p>
        <MathBlock>
          {`\\begin{aligned}
a &= m^2 - n^2 = 9 - 4 = 5 \\\\
b &= 2mn = 2 \\cdot 3 \\cdot 2 = 12 \\\\
c &= m^2 + n^2 = 9 + 4 = 13
\\end{aligned}`}
        </MathBlock>
      </Example>

      <h3>Why Does the Formula Work?</h3>

      <p>
        Let's verify algebraically that Euclid's formula always produces a
        Pythagorean triple:
      </p>

      <MathBlock>
        {`\\begin{aligned}
a^2 + b^2 &= (m^2 - n^2)^2 + (2mn)^2 \\\\
&= m^4 - 2m^2n^2 + n^4 + 4m^2n^2 \\\\
&= m^4 + 2m^2n^2 + n^4 \\\\
&= (m^2 + n^2)^2 = c^2
\\end{aligned}`}
      </MathBlock>

      <h3>Babylonian Knowledge</h3>

      <Callout type="note">
        <strong>Historical Discovery:</strong> The clay tablet Plimpton 322, dating
        from around 1800 BCE, contains a list of Pythagorean triples. The Babylonians
        knew these triples over 1000 years before Pythagoras!
      </Callout>

      <p>
        The Plimpton 322 tablet shows that Babylonian mathematicians could generate
        Pythagorean triples systematically. Some scholars believe they used a method
        equivalent to Euclid's formula. The tablet includes triples like
        <InlineMath>(119, 120, 169)</InlineMath>—far beyond anything that could be
        found by trial and error.
      </p>

      <h3>Infinitely Many Triples</h3>

      <Theorem title="Infinitude of Pythagorean Triples">
        <p>
          There are infinitely many primitive Pythagorean triples.
        </p>
      </Theorem>

      <p>
        This follows immediately from Euclid's formula: we can choose <InlineMath>m</InlineMath> to
        be any integer greater than 1, and <InlineMath>n = 1</InlineMath>, giving us:
      </p>

      <MathBlock>
        {`(m^2 - 1, 2m, m^2 + 1)`}
      </MathBlock>

      <p>For example:</p>
      <ul className="list-disc list-inside space-y-1 ml-4">
        <li><InlineMath>m = 2</InlineMath>: <InlineMath>(3, 4, 5)</InlineMath></li>
        <li><InlineMath>m = 3</InlineMath>: <InlineMath>(8, 6, 10)</InlineMath> → primitive form: <InlineMath>(3, 4, 5)</InlineMath></li>
        <li><InlineMath>m = 4</InlineMath>: <InlineMath>(15, 8, 17)</InlineMath></li>
        <li><InlineMath>m = 5</InlineMath>: <InlineMath>(24, 10, 26)</InlineMath> → primitive form: <InlineMath>(5, 12, 13)</InlineMath></li>
      </ul>

      <Callout type="info">
        <strong>Connection to Fermat:</strong> Pythagorean triples are solutions to
        <InlineMath>x^2 + y^2 = z^2</InlineMath>. Fermat's Last Theorem states that
        the similar equation <InlineMath>x^n + y^n = z^n</InlineMath> has no positive
        integer solutions when <InlineMath>n {'>'} 2</InlineMath>. This seemingly simple
        statement took 358 years to prove!
      </Callout>

      <SectionQuiz
        sectionId={2}
        questions={quizMap[2] || []}
        title="Pythagorean Triples Quiz"
      />
    </LessonLayout>
  );
}
