import { LessonLayout } from '@/components/layout/LessonLayout';
import { Definition, Theorem, Example } from '@/components/common/ContentBlocks';
import { Callout } from '@/components/common/Callout';
import { MathBlock, InlineMath } from '@/components/common/MathBlock';
import { SectionQuiz } from '@/components/quiz/SectionQuiz';
import { quizMap } from '@/data/quizzes';

export default function Section62() {
  return (
    <LessonLayout sectionId={62}>
      <h2>Groups of Symmetries</h2>

      <p>
        Beyond permutations of roots, groups naturally arise as symmetries of
        geometric objects. The rotations and reflections that leave a shape
        unchanged form a group, revealing deep connections between algebra
        and geometry. This geometric perspective, developed by Felix Klein
        and others, shows that groups are everywhere we find structure and
        pattern.
      </p>

      <Callout type="info">
        <strong>Klein's Erlangen Program:</strong> In 1872, Felix Klein proposed
        that geometry should be defined by its symmetry group. Different
        geometries (Euclidean, projective, hyperbolic) are distinguished by
        which transformations preserve their structure.
      </Callout>

      <h3>Symmetries of Geometric Objects</h3>

      <Definition title="Symmetry Group">
        <p>
          The <strong>symmetry group</strong> of a geometric object is the
          set of all transformations (rotations, reflections, translations, etc.)
          that map the object to itself, together with composition of
          transformations.
        </p>
      </Definition>

      <Example title="Symmetries of a Square">
        <p>
          A square has 8 symmetries:
        </p>
        <ul className="list-disc list-inside mt-2 space-y-1">
          <li>The identity (do nothing)</li>
          <li>Rotations by 90°, 180°, and 270°</li>
          <li>Reflections across 2 diagonals</li>
          <li>Reflections across 2 lines through midpoints of opposite edges</li>
        </ul>
        <p className="mt-2">
          This group is called <InlineMath>D_4</InlineMath>, the dihedral group
          of order 8.
        </p>
      </Example>

      <Example title="Symmetries of an Equilateral Triangle">
        <p>
          An equilateral triangle has 6 symmetries:
        </p>
        <ul className="list-disc list-inside mt-2 space-y-1">
          <li>The identity</li>
          <li>Rotations by 120° and 240°</li>
          <li>Reflections across 3 lines through vertices and opposite midpoints</li>
        </ul>
        <p className="mt-2">
          This is <InlineMath>D_3</InlineMath>, which is isomorphic to{' '}
          <InlineMath>S_3</InlineMath>.
        </p>
      </Example>

      <h3>Dihedral Groups</h3>

      <Definition title="Dihedral Group">
        <p>
          The <strong>dihedral group</strong> <InlineMath>D_n</InlineMath> is
          the symmetry group of a regular <InlineMath>n</InlineMath>-gon. It
          has <InlineMath>2n</InlineMath> elements:
        </p>
        <ul className="list-disc list-inside mt-2 space-y-1">
          <li><InlineMath>n</InlineMath> rotations (including identity)</li>
          <li><InlineMath>n</InlineMath> reflections</li>
        </ul>
      </Definition>

      <Example title="Structure of D_n">
        <p>
          Let <InlineMath>r</InlineMath> be rotation by <InlineMath>360°/n</InlineMath>{' '}
          and <InlineMath>s</InlineMath> be any reflection. Then:
        </p>
        <MathBlock>
          {`D_n = \\langle r, s \\mid r^n = s^2 = e, \\, srs = r^{-1} \\rangle`}
        </MathBlock>
        <p className="mt-2 text-dark-400">
          The relation <InlineMath>srs = r^{-1}</InlineMath> says that conjugating
          a rotation by a reflection reverses it.
        </p>
      </Example>

      <h3>Cyclic Groups</h3>

      <Definition title="Cyclic Group">
        <p>
          A <strong>cyclic group</strong> <InlineMath>C_n</InlineMath> (or{' '}
          <InlineMath>\mathbb{Z}/n\mathbb{Z}</InlineMath>) is generated by a
          single element:
        </p>
        <MathBlock>
          {`C_n = \\{e, g, g^2, \\ldots, g^{n-1}\\}, \\quad g^n = e`}
        </MathBlock>
      </Definition>

      <Example title="Rotational Symmetry">
        <p>
          If we consider only rotations (no reflections), the symmetries of
          a regular <InlineMath>n</InlineMath>-gon form the cyclic group{' '}
          <InlineMath>C_n</InlineMath>.
        </p>
        <p className="mt-2">
          The rotations of a circle form an infinite cyclic group (or the
          circle group <InlineMath>SO(2)</InlineMath>).
        </p>
      </Example>

      <h3>Symmetries in Three Dimensions</h3>

      <p>
        Three-dimensional objects have richer symmetry groups:
      </p>

      <Example title="Symmetries of Regular Polyhedra">
        <p>
          The Platonic solids have symmetry groups:
        </p>
        <ul className="list-disc list-inside mt-2 space-y-1">
          <li><strong>Tetrahedron:</strong> 24 symmetries, isomorphic to <InlineMath>S_4</InlineMath></li>
          <li><strong>Cube/Octahedron:</strong> 48 symmetries, isomorphic to <InlineMath>S_4 \times C_2</InlineMath></li>
          <li><strong>Dodecahedron/Icosahedron:</strong> 120 symmetries, isomorphic to <InlineMath>A_5 \times C_2</InlineMath></li>
        </ul>
        <p className="mt-2 text-dark-400">
          Dual polyhedra (cube/octahedron, dodecahedron/icosahedron) share
          the same symmetry group.
        </p>
      </Example>

      <Callout type="note">
        <strong>A₅ Again!</strong> The rotation group of the icosahedron is{' '}
        <InlineMath>A_5</InlineMath>, the same group that prevents quintic
        solvability. This is not a coincidence—it reflects deep connections
        between symmetry, algebra, and geometry.
      </Callout>

      <h3>Continuous Symmetry Groups</h3>

      <p>
        Some objects have infinitely many symmetries:
      </p>

      <Definition title="Lie Groups">
        <p>
          A <strong>Lie group</strong> is a continuous group—a group that is
          also a smooth manifold, where group operations are smooth.
        </p>
      </Definition>

      <Example title="Important Lie Groups">
        <p>
          Key examples include:
        </p>
        <ul className="list-disc list-inside mt-2 space-y-1">
          <li><InlineMath>SO(n)</InlineMath>: rotations in <InlineMath>n</InlineMath> dimensions</li>
          <li><InlineMath>O(n)</InlineMath>: rotations and reflections in <InlineMath>n</InlineMath> dimensions</li>
          <li><InlineMath>SU(n)</InlineMath>: special unitary group (quantum mechanics)</li>
          <li><InlineMath>GL(n)</InlineMath>: invertible <InlineMath>n \times n</InlineMath> matrices</li>
        </ul>
      </Example>

      <Example title="Symmetries of the Sphere">
        <p>
          A sphere has infinitely many rotational symmetries, forming the
          group <InlineMath>SO(3)</InlineMath>. Including reflections gives{' '}
          <InlineMath>O(3)</InlineMath>.
        </p>
        <p className="mt-2 text-dark-400">
          These groups are 3-dimensional manifolds themselves (the rotation
          group is topologically like a 3-sphere, sort of).
        </p>
      </Example>

      <h3>Crystallographic Groups</h3>

      <p>
        The symmetries of crystals form discrete groups with special properties:
      </p>

      <Theorem title="Crystallographic Restriction">
        <p>
          In 2 dimensions, a lattice can only have rotational symmetries of
          order 1, 2, 3, 4, or 6. (No 5-fold or 7-fold crystallographic symmetry
          exists.)
        </p>
      </Theorem>

      <Example title="Wallpaper Groups">
        <p>
          There are exactly 17 distinct symmetry groups for 2D repeating
          patterns (wallpaper groups). These classify all possible ways to
          tile the plane with a repeating motif.
        </p>
        <p className="mt-2 text-dark-400">
          In 3D, there are 230 crystallographic space groups, classifying
          all possible crystal structures.
        </p>
      </Example>

      <h3>Klein's Erlangen Program</h3>

      <p>
        Felix Klein revolutionized geometry by defining it through symmetry:
      </p>

      <Theorem title="Klein's Principle">
        <p>
          A <strong>geometry</strong> is characterized by a group of
          transformations. The "geometric properties" are those invariant
          under the group.
        </p>
      </Theorem>

      <Example title="Different Geometries">
        <p>
          Different transformation groups give different geometries:
        </p>
        <ul className="list-disc list-inside mt-2 space-y-1">
          <li><strong>Euclidean geometry:</strong> Isometries (preserve distance)</li>
          <li><strong>Affine geometry:</strong> Affine transformations (preserve parallelism)</li>
          <li><strong>Projective geometry:</strong> Projective transformations (preserve collinearity)</li>
          <li><strong>Topology:</strong> Homeomorphisms (preserve continuity)</li>
        </ul>
        <p className="mt-2 text-dark-400">
          Each successive geometry has a larger symmetry group and fewer
          invariants.
        </p>
      </Example>

      <Callout type="info">
        <strong>Symmetry as Organization:</strong> Klein's insight was that
        symmetry groups organize mathematical knowledge. Rather than studying
        individual properties, we study what remains unchanged under
        transformations—a perspective that pervades modern mathematics
        and physics.
      </Callout>

      <h3>Physical Applications</h3>

      <p>
        Symmetry groups are fundamental in physics:
      </p>

      <ul className="list-disc list-inside space-y-2 mt-4">
        <li>
          <strong>Conservation laws:</strong> Noether's theorem connects
          symmetries to conserved quantities (time translation → energy,
          space translation → momentum, rotation → angular momentum).
        </li>
        <li>
          <strong>Particle physics:</strong> The Standard Model is built on
          the gauge group <InlineMath>SU(3) \times SU(2) \times U(1)</InlineMath>.
        </li>
        <li>
          <strong>Crystallography:</strong> Crystal properties are determined
          by their symmetry groups.
        </li>
      </ul>

      <SectionQuiz sectionId={62} questions={quizMap[62] || []} title="Check Your Understanding" />
    </LessonLayout>
  );
}
