// =============================================================================
// CURRICULUM STRUCTURE - Dummit & Foote Abstract Algebra (3rd Edition)
// =============================================================================

/**
 * Individual section within a part
 */
export interface Section {
  id: number;
  title: string;
  slug: string;
  description: string;
}

/**
 * Part containing multiple sections
 */
export interface Part {
  id: number;
  title: string;
  slug: string;
  sections: Section[];
}

/**
 * Complete curriculum structure
 */
export const curriculum: Part[] = [
  // ==========================================================================
  // PRELIMINARIES
  // ==========================================================================
  {
    id: 0,
    title: 'Preliminaries',
    slug: 'preliminaries',
    sections: [
      {
        id: 0,
        title: 'Basics',
        slug: 'basics',
        description: 'Sets, functions, relations, and basic logical concepts.',
      },
      {
        id: 1,
        title: 'Properties of the Integers',
        slug: 'properties-integers',
        description: 'Division algorithm, GCD, primes, and the Well-Ordering Property.',
      },
      {
        id: 2,
        title: 'The Integers Modulo n',
        slug: 'integers-modulo-n',
        description: 'Congruences, residue classes, and the ring Z/nZ.',
      },
    ],
  },

  // ==========================================================================
  // PART I - GROUP THEORY
  // ==========================================================================
  {
    id: 1,
    title: 'Introduction to Groups',
    slug: 'intro-groups',
    sections: [
      {
        id: 3,
        title: 'Basic Axioms and Examples',
        slug: 'basic-axioms',
        description: 'Definition of a group, basic properties, and important examples.',
      },
      {
        id: 4,
        title: 'Dihedral Groups',
        slug: 'dihedral-groups',
        description: 'Symmetries of regular n-gons and the dihedral group D_2n.',
      },
      {
        id: 5,
        title: 'Symmetric Groups',
        slug: 'symmetric-groups',
        description: 'Permutation groups, cycle notation, and the symmetric group S_n.',
      },
      {
        id: 6,
        title: 'Matrix Groups',
        slug: 'matrix-groups',
        description: 'General linear groups GL_n(F), special linear groups SL_n(F).',
      },
      {
        id: 7,
        title: 'The Quaternion Group',
        slug: 'quaternion-group',
        description: 'The quaternion group Q_8 and its properties.',
      },
      {
        id: 8,
        title: 'Homomorphisms and Isomorphisms',
        slug: 'homomorphisms-isomorphisms',
        description: 'Group homomorphisms, isomorphisms, and structural equivalence.',
      },
      {
        id: 9,
        title: 'Group Actions',
        slug: 'group-actions-intro',
        description: 'Introduction to group actions on sets.',
      },
    ],
  },
  {
    id: 2,
    title: 'Subgroups',
    slug: 'subgroups',
    sections: [
      {
        id: 10,
        title: 'Definition and Examples',
        slug: 'subgroup-definition',
        description: 'Subgroup criteria and important examples.',
      },
      {
        id: 11,
        title: 'Centralizers and Normalizers',
        slug: 'centralizers-normalizers',
        description: 'Centralizers, normalizers, stabilizers, and kernels.',
      },
      {
        id: 12,
        title: 'Cyclic Groups',
        slug: 'cyclic-groups',
        description: 'Cyclic groups, generators, and their subgroup structure.',
      },
      {
        id: 13,
        title: 'Subgroups Generated by Subsets',
        slug: 'generated-subgroups',
        description: 'Generating subgroups from arbitrary subsets.',
      },
      {
        id: 14,
        title: 'Lattice of Subgroups',
        slug: 'lattice-subgroups',
        description: 'The lattice structure of subgroups of a group.',
      },
    ],
  },
  {
    id: 3,
    title: 'Quotient Groups and Homomorphisms',
    slug: 'quotient-groups',
    sections: [
      {
        id: 15,
        title: 'Definitions and Examples',
        slug: 'quotient-definitions',
        description: 'Cosets, normal subgroups, and quotient groups.',
      },
      {
        id: 16,
        title: 'Cosets and Lagrange\'s Theorem',
        slug: 'lagrange-theorem',
        description: 'Coset properties and Lagrange\'s fundamental theorem.',
      },
      {
        id: 17,
        title: 'The Isomorphism Theorems',
        slug: 'isomorphism-theorems',
        description: 'The First, Second, and Third Isomorphism Theorems.',
      },
      {
        id: 18,
        title: 'Composition Series',
        slug: 'composition-series',
        description: 'Composition series and the Holder program.',
      },
      {
        id: 19,
        title: 'The Alternating Group',
        slug: 'alternating-group',
        description: 'Transpositions, sign of permutation, and the alternating group A_n.',
      },
    ],
  },
  {
    id: 4,
    title: 'Group Actions',
    slug: 'group-actions',
    sections: [
      {
        id: 20,
        title: 'Group Actions and Permutation Representations',
        slug: 'permutation-representations',
        description: 'Orbits, stabilizers, and the orbit-stabilizer theorem.',
      },
      {
        id: 21,
        title: 'Cayley\'s Theorem',
        slug: 'cayleys-theorem',
        description: 'Groups acting on themselves by left multiplication.',
      },
      {
        id: 22,
        title: 'The Class Equation',
        slug: 'class-equation',
        description: 'Conjugation action and the class equation.',
      },
      {
        id: 23,
        title: 'Automorphisms',
        slug: 'automorphisms',
        description: 'Inner and outer automorphisms of groups.',
      },
      {
        id: 24,
        title: 'The Sylow Theorems',
        slug: 'sylow-theorems',
        description: 'Existence, conjugacy, and counting Sylow p-subgroups.',
      },
      {
        id: 25,
        title: 'Simplicity of A_n',
        slug: 'simplicity-an',
        description: 'Proof that A_n is simple for n >= 5.',
      },
    ],
  },
  {
    id: 5,
    title: 'Direct and Semidirect Products',
    slug: 'direct-semidirect',
    sections: [
      {
        id: 26,
        title: 'Direct Products',
        slug: 'direct-products',
        description: 'External and internal direct products of groups.',
      },
      {
        id: 27,
        title: 'Finitely Generated Abelian Groups',
        slug: 'finitely-generated-abelian',
        description: 'The Fundamental Theorem of Finitely Generated Abelian Groups.',
      },
      {
        id: 28,
        title: 'Groups of Small Order',
        slug: 'small-order-groups',
        description: 'Classification of groups of small order.',
      },
      {
        id: 29,
        title: 'Recognizing Direct Products',
        slug: 'recognizing-direct-products',
        description: 'Criteria for recognizing internal direct products.',
      },
      {
        id: 30,
        title: 'Semidirect Products',
        slug: 'semidirect-products',
        description: 'Construction and examples of semidirect products.',
      },
    ],
  },
  {
    id: 6,
    title: 'Further Topics in Group Theory',
    slug: 'further-group-theory',
    sections: [
      {
        id: 31,
        title: 'p-groups and Nilpotent Groups',
        slug: 'p-groups-nilpotent',
        description: 'p-groups, nilpotent groups, and solvable groups.',
      },
      {
        id: 32,
        title: 'Groups of Medium Order',
        slug: 'medium-order-groups',
        description: 'Applications and classification techniques.',
      },
      {
        id: 33,
        title: 'Free Groups',
        slug: 'free-groups',
        description: 'Free groups and presentations.',
      },
    ],
  },

  // ==========================================================================
  // PART II - RING THEORY
  // ==========================================================================
  {
    id: 7,
    title: 'Introduction to Rings',
    slug: 'intro-rings',
    sections: [
      {
        id: 34,
        title: 'Basic Definitions and Examples',
        slug: 'ring-definitions',
        description: 'Rings, subrings, units, and zero divisors.',
      },
      {
        id: 35,
        title: 'Polynomial and Matrix Rings',
        slug: 'polynomial-matrix-rings',
        description: 'Polynomial rings R[x], matrix rings, and group rings.',
      },
      {
        id: 36,
        title: 'Ring Homomorphisms and Quotient Rings',
        slug: 'ring-homomorphisms',
        description: 'Ring homomorphisms, ideals, and quotient rings.',
      },
      {
        id: 37,
        title: 'Properties of Ideals',
        slug: 'ideal-properties',
        description: 'Prime ideals, maximal ideals, and ideal operations.',
      },
      {
        id: 38,
        title: 'Rings of Fractions',
        slug: 'rings-fractions',
        description: 'Localization and fields of fractions.',
      },
      {
        id: 39,
        title: 'Chinese Remainder Theorem',
        slug: 'crt-rings',
        description: 'The Chinese Remainder Theorem for rings.',
      },
    ],
  },
  {
    id: 8,
    title: 'Euclidean Domains, PIDs, and UFDs',
    slug: 'ed-pid-ufd',
    sections: [
      {
        id: 40,
        title: 'Euclidean Domains',
        slug: 'euclidean-domains',
        description: 'Euclidean domains and the division algorithm.',
      },
      {
        id: 41,
        title: 'Principal Ideal Domains',
        slug: 'pids',
        description: 'PIDs and their properties.',
      },
      {
        id: 42,
        title: 'Unique Factorization Domains',
        slug: 'ufds',
        description: 'UFDs, irreducibles, and primes.',
      },
    ],
  },
  {
    id: 9,
    title: 'Polynomial Rings',
    slug: 'polynomial-rings',
    sections: [
      {
        id: 43,
        title: 'Definitions and Basic Properties',
        slug: 'polynomial-basics',
        description: 'Polynomial rings and basic operations.',
      },
      {
        id: 44,
        title: 'Polynomial Rings over Fields I',
        slug: 'poly-fields-1',
        description: 'Division algorithm and factorization.',
      },
      {
        id: 45,
        title: 'Polynomial UFDs',
        slug: 'poly-ufds',
        description: 'Polynomial rings that are UFDs.',
      },
      {
        id: 46,
        title: 'Irreducibility Criteria',
        slug: 'irreducibility',
        description: 'Eisenstein criterion and reduction methods.',
      },
      {
        id: 47,
        title: 'Polynomial Rings over Fields II',
        slug: 'poly-fields-2',
        description: 'Advanced properties of polynomial rings.',
      },
      {
        id: 48,
        title: 'Grobner Bases',
        slug: 'grobner-bases',
        description: 'Polynomials in several variables and Grobner bases.',
      },
    ],
  },

  // ==========================================================================
  // PART III - MODULES AND VECTOR SPACES
  // ==========================================================================
  {
    id: 10,
    title: 'Introduction to Module Theory',
    slug: 'intro-modules',
    sections: [
      {
        id: 49,
        title: 'Basic Definitions and Examples',
        slug: 'module-definitions',
        description: 'Modules over rings and basic examples.',
      },
      {
        id: 50,
        title: 'Quotient Modules and Homomorphisms',
        slug: 'module-homomorphisms',
        description: 'Submodules, quotient modules, and module homomorphisms.',
      },
      {
        id: 51,
        title: 'Direct Sums and Free Modules',
        slug: 'free-modules',
        description: 'Generation, direct sums, and free modules.',
      },
      {
        id: 52,
        title: 'Tensor Products',
        slug: 'tensor-products',
        description: 'Tensor products of modules.',
      },
      {
        id: 53,
        title: 'Exact Sequences',
        slug: 'exact-sequences',
        description: 'Projective, injective, and flat modules.',
      },
    ],
  },
  {
    id: 11,
    title: 'Vector Spaces',
    slug: 'vector-spaces',
    sections: [
      {
        id: 54,
        title: 'Definitions and Basic Theory',
        slug: 'vector-space-basics',
        description: 'Vector spaces, bases, and dimension.',
      },
      {
        id: 55,
        title: 'Linear Transformations',
        slug: 'linear-transformations',
        description: 'The matrix of a linear transformation.',
      },
      {
        id: 56,
        title: 'Dual Vector Spaces',
        slug: 'dual-spaces',
        description: 'Dual spaces and dual bases.',
      },
      {
        id: 57,
        title: 'Determinants',
        slug: 'determinants',
        description: 'Determinants and their properties.',
      },
      {
        id: 58,
        title: 'Tensor Algebras',
        slug: 'tensor-algebras',
        description: 'Tensor, symmetric, and exterior algebras.',
      },
    ],
  },
  {
    id: 12,
    title: 'Modules over PIDs',
    slug: 'modules-pids',
    sections: [
      {
        id: 59,
        title: 'Basic Theory',
        slug: 'modules-pid-basic',
        description: 'Structure theorem for modules over PIDs.',
      },
      {
        id: 60,
        title: 'Rational Canonical Form',
        slug: 'rational-canonical',
        description: 'The rational canonical form of a matrix.',
      },
      {
        id: 61,
        title: 'Jordan Canonical Form',
        slug: 'jordan-canonical',
        description: 'The Jordan canonical form.',
      },
    ],
  },

  // ==========================================================================
  // PART IV - FIELD THEORY AND GALOIS THEORY
  // ==========================================================================
  {
    id: 13,
    title: 'Field Theory',
    slug: 'field-theory',
    sections: [
      {
        id: 62,
        title: 'Field Extensions',
        slug: 'field-extensions',
        description: 'Basic theory of field extensions.',
      },
      {
        id: 63,
        title: 'Algebraic Extensions',
        slug: 'algebraic-extensions',
        description: 'Algebraic elements and algebraic extensions.',
      },
      {
        id: 64,
        title: 'Straightedge and Compass',
        slug: 'straightedge-compass',
        description: 'Classical geometric constructions.',
      },
      {
        id: 65,
        title: 'Splitting Fields',
        slug: 'splitting-fields',
        description: 'Splitting fields and algebraic closures.',
      },
      {
        id: 66,
        title: 'Separable Extensions',
        slug: 'separable-extensions',
        description: 'Separable and inseparable extensions.',
      },
      {
        id: 67,
        title: 'Cyclotomic Polynomials',
        slug: 'cyclotomic-polynomials',
        description: 'Cyclotomic polynomials and extensions.',
      },
    ],
  },
  {
    id: 14,
    title: 'Galois Theory',
    slug: 'galois-theory',
    sections: [
      {
        id: 68,
        title: 'Basic Definitions',
        slug: 'galois-definitions',
        description: 'Fixed fields and Galois groups.',
      },
      {
        id: 69,
        title: 'Fundamental Theorem',
        slug: 'fundamental-theorem-galois',
        description: 'The Fundamental Theorem of Galois Theory.',
      },
      {
        id: 70,
        title: 'Finite Fields',
        slug: 'finite-fields',
        description: 'Structure and classification of finite fields.',
      },
      {
        id: 71,
        title: 'Composite and Simple Extensions',
        slug: 'composite-extensions',
        description: 'Composite extensions and simple extensions.',
      },
      {
        id: 72,
        title: 'Cyclotomic Extensions',
        slug: 'cyclotomic-extensions',
        description: 'Cyclotomic extensions and abelian extensions over Q.',
      },
      {
        id: 73,
        title: 'Galois Groups of Polynomials',
        slug: 'galois-groups-polynomials',
        description: 'Computing Galois groups of polynomials.',
      },
      {
        id: 74,
        title: 'Solvable Extensions',
        slug: 'solvable-extensions',
        description: 'Solvable and radical extensions; insolvability of the quintic.',
      },
      {
        id: 75,
        title: 'Computing Galois Groups',
        slug: 'computing-galois',
        description: 'Computation of Galois groups over Q.',
      },
      {
        id: 76,
        title: 'Transcendental Extensions',
        slug: 'transcendental-extensions',
        description: 'Transcendental extensions and infinite Galois groups.',
      },
    ],
  },

  // ==========================================================================
  // PART V - COMMUTATIVE RINGS, ALGEBRAIC GEOMETRY, HOMOLOGICAL ALGEBRA
  // ==========================================================================
  {
    id: 15,
    title: 'Commutative Rings and Algebraic Geometry',
    slug: 'commutative-algebraic-geometry',
    sections: [
      {
        id: 77,
        title: 'Noetherian Rings',
        slug: 'noetherian-rings',
        description: 'Noetherian rings and affine algebraic sets.',
      },
      {
        id: 78,
        title: 'Radicals and Varieties',
        slug: 'radicals-varieties',
        description: 'Radicals and affine varieties.',
      },
      {
        id: 79,
        title: 'Hilbert\'s Nullstellensatz',
        slug: 'nullstellensatz',
        description: 'Integral extensions and Hilbert\'s Nullstellensatz.',
      },
      {
        id: 80,
        title: 'Localization',
        slug: 'localization',
        description: 'Localization of rings and modules.',
      },
      {
        id: 81,
        title: 'Prime Spectrum',
        slug: 'prime-spectrum',
        description: 'The prime spectrum of a ring.',
      },
    ],
  },
  {
    id: 16,
    title: 'Artinian Rings and Dedekind Domains',
    slug: 'artinian-dedekind',
    sections: [
      {
        id: 82,
        title: 'Artinian Rings',
        slug: 'artinian-rings',
        description: 'Artinian rings and their structure.',
      },
      {
        id: 83,
        title: 'Discrete Valuation Rings',
        slug: 'dvrs',
        description: 'Discrete valuation rings.',
      },
      {
        id: 84,
        title: 'Dedekind Domains',
        slug: 'dedekind-domains',
        description: 'Dedekind domains and ideal factorization.',
      },
    ],
  },
  {
    id: 17,
    title: 'Homological Algebra',
    slug: 'homological-algebra',
    sections: [
      {
        id: 85,
        title: 'Ext and Tor',
        slug: 'ext-tor',
        description: 'Introduction to homological algebra: Ext and Tor.',
      },
      {
        id: 86,
        title: 'Cohomology of Groups',
        slug: 'group-cohomology',
        description: 'The cohomology of groups.',
      },
      {
        id: 87,
        title: 'Crossed Homomorphisms',
        slug: 'crossed-homomorphisms',
        description: 'Crossed homomorphisms and H^1(G, A).',
      },
      {
        id: 88,
        title: 'Group Extensions',
        slug: 'group-extensions',
        description: 'Group extensions, factor sets, and H^2(G, A).',
      },
    ],
  },

  // ==========================================================================
  // PART VI - REPRESENTATION THEORY
  // ==========================================================================
  {
    id: 18,
    title: 'Representation Theory',
    slug: 'representation-theory',
    sections: [
      {
        id: 89,
        title: 'Linear Actions and Group Rings',
        slug: 'linear-actions',
        description: 'Linear actions and modules over group rings.',
      },
      {
        id: 90,
        title: 'Wedderburn\'s Theorem',
        slug: 'wedderburn-theorem',
        description: 'Wedderburn\'s theorem and consequences.',
      },
      {
        id: 91,
        title: 'Character Theory',
        slug: 'character-theory',
        description: 'Character theory and orthogonality relations.',
      },
    ],
  },
  {
    id: 19,
    title: 'Applications of Character Theory',
    slug: 'character-applications',
    sections: [
      {
        id: 92,
        title: 'Characters of Small Groups',
        slug: 'characters-small-groups',
        description: 'Characters of groups of small order.',
      },
      {
        id: 93,
        title: 'Burnside and Hall',
        slug: 'burnside-hall',
        description: 'Theorems of Burnside and Hall.',
      },
      {
        id: 94,
        title: 'Induced Characters',
        slug: 'induced-characters',
        description: 'Introduction to the theory of induced characters.',
      },
    ],
  },
];

// =============================================================================
// HELPER FUNCTIONS
// =============================================================================

/**
 * Get section by ID
 */
export function getSectionById(id: number): Section | undefined {
  for (const part of curriculum) {
    const section = part.sections.find((s) => s.id === id);
    if (section) return section;
  }
  return undefined;
}

/**
 * Get part containing a section
 */
export function getPartBySectionId(sectionId: number): Part | undefined {
  return curriculum.find((part) =>
    part.sections.some((section) => section.id === sectionId)
  );
}

/**
 * Get adjacent sections (previous and next)
 */
export function getAdjacentSections(sectionId: number): {
  prev: Section | null;
  next: Section | null;
} {
  const allSections = curriculum.flatMap((part) => part.sections);
  const index = allSections.findIndex((s) => s.id === sectionId);

  return {
    prev: index > 0 ? allSections[index - 1] : null,
    next: index < allSections.length - 1 ? allSections[index + 1] : null,
  };
}

/**
 * Get total number of sections
 */
export function getTotalSections(): number {
  return curriculum.reduce((total, part) => total + part.sections.length, 0);
}

/**
 * Get all sections as a flat array
 */
export function getAllSections(): Section[] {
  return curriculum.flatMap((part) => part.sections);
}

/**
 * Get section index (position in course)
 */
export function getSectionIndex(sectionId: number): number {
  const allSections = getAllSections();
  return allSections.findIndex((s) => s.id === sectionId);
}
