import type { QuizQuestion } from './types';

export const section21Questions: QuizQuestion[] = [
  {
    id: 1,
    type: 'multiple-choice',
    question: 'How many coordinates are needed to specify a point in 3D space?',
    options: [
      '3',
      '1',
      '2',
      '4',
    ],
    correctIndex: 0,
    difficulty: 'easy',
    explanation: 'A point in three-dimensional space requires three coordinates $(x, y, z)$ to specify its position.',
  },
  {
    id: 2,
    type: 'multiple-choice',
    question: 'What is the equation of a sphere with radius $r$ centered at the origin?',
    options: [
      '$x^2 + y^2 + z^2 = r^2
    correctIndex: 0,
    difficulty: 'easy',
    explanation: 'The sphere consists of all points at distance $r$ from the origin, giving $x^2 + y^2 + z^2 = r^2$ by the 3D distance formula.',
  },
      '$x + y + z = r
    correctIndex: 3,
    difficulty: 'easy',
    explanation: 'The sphere consists of all points at distance $r$ from the origin, giving $x^2 + y^2 + z^2 = r^2$ by the 3D distance formula.',
  },
      '$x^2 + y^2 = r^2
    correctIndex: 3,
    difficulty: 'easy',
    explanation: 'The sphere consists of all points at distance $r$ from the origin, giving $x^2 + y^2 + z^2 = r^2$ by the 3D distance formula.',
  },
      '$xyz = r^3
    correctIndex: 3,
    difficulty: 'easy',
    explanation: 'The sphere consists of all points at distance $r$ from the origin, giving $x^2 + y^2 + z^2 = r^2$ by the 3D distance formula.',
  },
    ],
    correctIndex: 3,
    difficulty: 'easy',
    explanation: 'The sphere consists of all points at distance $r$ from the origin, giving $x^2 + y^2 + z^2 = r^2$ by the 3D distance formula.',
  },
  {
    id: 3,
    type: 'multiple-choice',
    question: 'What are quadric surfaces?',
    options: [
      'Surfaces with four sides',
      'Surfaces that are always flat',
      'Second-degree surfaces (3D analogues of conics)',
      'Surfaces defined by fourth-degree equations',
    ],
    correctIndex: 2,
    difficulty: 'medium',
    explanation: 'Quadric surfaces are defined by second-degree equations in three variables—they include spheres, ellipsoids, paraboloids, and hyperboloids.',
  },
  {
    id: 4,
    type: 'multiple-choice',
    question: 'What is a ruled surface?',
    options: [
      'A surface with straight lines drawn on it',
      'A surface generated by moving a straight line',
      'A surface that follows rules',
      'A flat surface',
    ],
    correctIndex: 1,
    difficulty: 'medium',
    explanation: 'A ruled surface is one that can be generated by moving a straight line through space. Examples include cones, cylinders, and hyperboloids of one sheet.',
  },
  {
    id: 5,
    type: 'multiple-choice',
    question: 'What is remarkable about the hyperboloid of one sheet?',
    options: [
      'It is the only quadric with a hole',
      'It has no real points',
      'It is the same as a sphere',
      'It is doubly ruled—through every point pass two different lines on the surface',
    ],
    correctIndex: 3,
    difficulty: 'hard',
    explanation: 'The hyperboloid of one sheet is doubly ruled: through every point on the surface pass two different straight lines that lie entirely on the surface. This is why it\'s used in architecture.',
  },
];
