// Chapter 7: The Rational and Jordan Forms (Sections 40-44)
// Based on Hoffman & Kunze Chapter 7
import type { DifficultyQuizData } from './types';

// Section 40: Cyclic Subspaces and Annihilators
export const section40Quiz: DifficultyQuizData = {
  easy: [
    {
      id: 's40-e01',
      question: 'The cyclic subspace generated by v under T is:',
      options: [
      'span{v, Tv, T²v, ...}',
      '{v}',
      'V',
      'ker(T)',
    ],
      correctIndex: 0,
      difficulty: 'easy',
      explanation: 'The T-cyclic subspace generated by v is Z(v;T) = span{v, Tv, T²v, ...}.'
    },
    {
      id: 's40-e02',
      question: 'A cyclic vector for T generates:',
      options: [
      'Only itself',
      'All of V under T',
      'The zero space',
      'The kernel of T',
    ],
      correctIndex: 1,
      difficulty: 'easy',
      explanation: 'A cyclic vector v satisfies Z(v;T) = V.'
    },
    {
      id: 's40-e03',
      question: 'If v is a cyclic vector for T on V, then:',
      options: [
      'V = span{v}',
      'v = 0',
      'V = Z(v;T)',
      'T = I',
    ],
      correctIndex: 2,
      difficulty: 'easy',
      explanation: 'A cyclic vector generates all of V under repeated application of T.'
    },
    {
      id: 's40-e04',
      question: 'The dimension of Z(v;T) equals:',
      options: [
      '1',
      'dim(V)',
      'deg of the T-annihilator of v',
      'The rank of T',
    ],
      correctIndex: 2,
      difficulty: 'easy',
      explanation: 'dim(Z(v;T)) = deg(annihilator of v), as v, Tv, ..., T^{k-1}v form a basis.'
    },
    {
      id: 's40-e05',
      question: 'Z(v;T) is always:',
      options: [
      'Equal to V',
      'One-dimensional',
      'Empty',
      'T-invariant',
    ],
      correctIndex: 3,
      difficulty: 'easy',
      explanation: 'Z(v;T) is invariant since T(T^k v) = T^{k+1}v ∈ Z(v;T).'
    },
    {
      id: 's40-e06',
      question: 'For the zero vector, Z(0;T) equals:',
      options: [
      'V',
      'ker(T)',
      '{0}',
      'The whole space',
    ],
      correctIndex: 2,
      difficulty: 'easy',
      explanation: 'The cyclic subspace of the zero vector is just {0}.'
    }
  ],
  medium: [
    {
      id: 's40-m01',
      question: 'The T-annihilator of v is:',
      options: [
      'The monic polynomial of least degree with p(T)v = 0',
      'A vector',
      'The characteristic polynomial',
      'Zero',
    ],
      correctIndex: 0,
      difficulty: 'medium',
      explanation: 'The T-annihilator is the minimal monic polynomial annihilating v under T.'
    },
    {
      id: 's40-m02',
      question: 'The T-annihilator of v divides:',
      options: [
      'The characteristic polynomial',
      'Both characteristic and minimal polynomials',
      'Nothing',
      'The minimal polynomial of T',
    ],
      correctIndex: 3,
      difficulty: 'medium',
      explanation: 'The annihilator of any vector divides the minimal polynomial of T.'
    },
    {
      id: 's40-m03',
      question: 'T has a cyclic vector iff:',
      options: [
      'The minimal polynomial equals the characteristic polynomial',
      'T = 0',
      'T is diagonalizable',
      'T is nilpotent',
    ],
      correctIndex: 0,
      difficulty: 'medium',
      explanation: 'A cyclic vector exists iff minimal polynomial = characteristic polynomial.'
    },
    {
      id: 's40-m04',
      question: 'The companion matrix has:',
      options: [
      'Only diagonal entries',
      'No eigenvalues',
      'A standard cyclic vector',
      'All entries equal',
    ],
      correctIndex: 2,
      difficulty: 'medium',
      explanation: 'The companion matrix has e₁ as a cyclic vector.'
    },
    {
      id: 's40-m05',
      question: 'If v has T-annihilator equal to the minimal polynomial of T, then:',
      options: [
      'v = 0',
      'v is a cyclic vector',
      'T = I',
      'The minimal polynomial is 1',
    ],
      correctIndex: 1,
      difficulty: 'medium',
      explanation: 'Maximum annihilator degree means v generates all of V.'
    },
    {
      id: 's40-m06',
      question: 'Every nonzero v has a T-annihilator of degree:',
      options: [
      '0',
      'Exactly n',
      'Infinite',
      'At most dim(V)',
    ],
      correctIndex: 3,
      difficulty: 'medium',
      explanation: 'The annihilator has degree at most dim(V), achieved when v is cyclic.'
    }
  ],
  hard: [
    {
      id: 's40-h01',
      question: 'The T-annihilator of v is irreducible iff:',
      options: [
      'v = 0',
      'T is diagonalizable',
      'Z(v;T) has no proper T-invariant subspace',
      'v is an eigenvector',
    ],
      correctIndex: 2,
      difficulty: 'hard',
      explanation: 'Irreducible annihilator corresponds to an irreducible T-module (no proper invariant subspaces).'
    },
    {
      id: 's40-h02',
      question: 'The cyclic decomposition theorem states that V is a direct sum of:',
      options: [
      'Eigenspaces',
      'Kernels',
      'Cyclic subspaces with divisibility of annihilators',
      'Images',
    ],
      correctIndex: 2,
      difficulty: 'hard',
      explanation: 'V = Z(v₁;T) ⊕ ... ⊕ Z(vₖ;T) where the annihilators satisfy divisibility conditions.'
    },
    {
      id: 's40-h03',
      question: 'If f₁ | f₂ | ... | fₖ are the invariant factors, then the minimal polynomial is:',
      options: [
      'f₁',
      'fₖ',
      'f₁f₂...fₖ',
      'gcd of all fᵢ',
    ],
      correctIndex: 1,
      difficulty: 'hard',
      explanation: 'The largest invariant factor equals the minimal polynomial.'
    },
    {
      id: 's40-h04',
      question: 'The product of invariant factors equals:',
      options: [
      'The minimal polynomial',
      '1',
      'The characteristic polynomial',
      'The trace',
    ],
      correctIndex: 2,
      difficulty: 'hard',
      explanation: 'The product of invariant factors = characteristic polynomial.'
    },
    {
      id: 's40-h05',
      question: 'Two operators have the same rational canonical form iff:',
      options: [
      'They have the same trace',
      'They have the same invariant factors',
      'They have the same eigenvalues',
      'They are equal',
    ],
      correctIndex: 1,
      difficulty: 'hard',
      explanation: 'Invariant factors completely determine the rational canonical form.'
    },
    {
      id: 's40-h06',
      question: 'The number of cyclic summands in the rational decomposition equals:',
      options: [
      'The dimension',
      'The number of eigenvalues',
      'One',
      'The number of invariant factors',
    ],
      correctIndex: 3,
      difficulty: 'hard',
      explanation: 'Each invariant factor corresponds to one cyclic subspace.'
    }
  ]
};

// Section 41: Cyclic Decompositions and the Rational Form
export const section41Quiz: DifficultyQuizData = {
  easy: [
    {
      id: 's41-e01',
      question: 'The rational canonical form exists for:',
      options: [
      'Only diagonalizable operators',
      'Only nilpotent operators',
      'All linear operators',
      'Only invertible operators',
    ],
      correctIndex: 2,
      difficulty: 'easy',
      explanation: 'Every linear operator has a rational canonical form over any field.'
    },
    {
      id: 's41-e02',
      question: 'The rational form is block diagonal with:',
      options: [
      'Identity blocks',
      'Diagonal matrices',
      'Zero blocks',
      'Companion matrices',
    ],
      correctIndex: 3,
      difficulty: 'easy',
      explanation: 'Rational form consists of companion matrices for the invariant factors.'
    },
    {
      id: 's41-e03',
      question: 'The rational form depends on:',
      options: [
      'The choice of basis',
      'Only the operator',
      'The field extension',
      'Random choices',
    ],
      correctIndex: 1,
      difficulty: 'easy',
      explanation: 'The rational canonical form is uniquely determined by the operator.'
    },
    {
      id: 's41-e04',
      question: 'Companion matrices are always:',
      options: ['Diagonal', 'Symmetric', 'Cyclic (have a cyclic vector)', 'Nilpotent'],
      correctIndex: 2,
      difficulty: 'easy',
      explanation: 'A companion matrix has the standard basis vector e₁ as a cyclic vector.'
    },
    {
      id: 's41-e05',
      question: 'The companion matrix of x² - 1 is:',
      options: ['[[0,1],[1,0]]', '[[0,1],[0,0]]', '[[1,0],[0,1]]', '[[0,1],[1,0]]'],
      correctIndex: 0,
      difficulty: 'easy',
      explanation: 'The companion matrix has 1 on the subdiagonal and coefficients in the last row.'
    },
    {
      id: 's41-e06',
      question: 'If T has one invariant factor, the rational form is:',
      options: [
      'A single companion matrix',
      'Diagonal',
      'Block diagonal',
      'The identity',
    ],
      correctIndex: 0,
      difficulty: 'easy',
      explanation: 'One invariant factor means one companion block (T has a cyclic vector).'
    }
  ],
  medium: [
    {
      id: 's41-m01',
      question: 'The companion matrix of polynomial p(x) = xⁿ + aₙ₋₁xⁿ⁻¹ + ... + a₀ has:',
      options: [
      'All zeros',
      'Diagonal entries only',
      'Random entries',
      'Ones on superdiagonal and -aᵢ in last column',
    ],
      correctIndex: 3,
      difficulty: 'medium',
      explanation: 'The companion matrix has 1s on the subdiagonal (or superdiagonal) and coefficients in one row/column.'
    },
    {
      id: 's41-m02',
      question: 'Two matrices are similar iff they have:',
      options: [
      'The same trace',
      'The same determinant',
      'The same size',
      'The same invariant factors',
    ],
      correctIndex: 3,
      difficulty: 'medium',
      explanation: 'Matrices are similar iff they have the same invariant factors (equivalently, same rational form).'
    },
    {
      id: 's41-m03',
      question: 'The characteristic polynomial of a companion matrix for p(x) is:',
      options: [
      'x',
      'p(x)',
      '1',
      'p(x)²',
    ],
      correctIndex: 1,
      difficulty: 'medium',
      explanation: 'The characteristic polynomial of the companion matrix of p(x) is p(x).'
    },
    {
      id: 's41-m04',
      question: 'The minimal polynomial of a companion matrix for p(x) is:',
      options: ['x', '1', 'p(x)', 'Different from p(x)'],
      correctIndex: 2,
      difficulty: 'medium',
      explanation: 'For companion matrices, minimal = characteristic = p(x).'
    },
    {
      id: 's41-m05',
      question: 'The rational form is defined over:',
      options: [
      'Only ℂ',
      'Any field',
      'Only algebraically closed fields',
      'Only ℝ',
    ],
      correctIndex: 1,
      difficulty: 'medium',
      explanation: 'Rational canonical form exists over any field (no splitting required).'
    },
    {
      id: 's41-m06',
      question: 'The invariant factors f₁, f₂, ..., fₖ satisfy:',
      options: [
      'f₁ | f₂ | ... | fₖ',
      'f₁ = f₂ = ... = fₖ',
      'No relation',
      'f₁ + f₂ + ... + fₖ = 0',
    ],
      correctIndex: 0,
      difficulty: 'medium',
      explanation: 'Invariant factors form a divisibility chain: each divides the next.'
    }
  ],
  hard: [
    {
      id: 's41-h01',
      question: 'The Smith normal form is used to:',
      options: [
      'Diagonalize matrices',
      'Find eigenvalues',
      'Compute determinants',
      'Compute invariant factors of xI - A',
    ],
      correctIndex: 3,
      difficulty: 'hard',
      explanation: 'Smith normal form of xI - A gives the invariant factors.'
    },
    {
      id: 's41-h02',
      question: 'The number of invariant factors equal to 1 is:',
      options: [
      'Zero',
      'dim(V) - rank(similarity invariants)',
      'Always n',
      'Undefined',
    ],
      correctIndex: 0,
      difficulty: 'hard',
      explanation: 'We typically exclude trivial factors of 1 from the list.'
    },
    {
      id: 's41-h03',
      question: 'Elementary divisors are obtained by:',
      options: [
      'Adding invariant factors',
      'Factoring invariant factors into prime powers',
      'Multiplying eigenvalues',
      'Computing determinant',
    ],
      correctIndex: 1,
      difficulty: 'hard',
      explanation: 'Elementary divisors are the prime power factors of the invariant factors.'
    },
    {
      id: 's41-h04',
      question: 'Two matrices over F have the same Jordan form (over algebraic closure) iff:',
      options: [
      'They are equal',
      'They have the same size',
      'They have the same elementary divisors',
      'They commute',
    ],
      correctIndex: 2,
      difficulty: 'hard',
      explanation: 'Elementary divisors determine the Jordan form (once eigenvalues are in the field).'
    },
    {
      id: 's41-h05',
      question: 'Frobenius blocks in rational form correspond to:',
      options: [
      'Eigenvalues',
      'Invariant factors',
      'Elementary divisors',
      'Jordan blocks',
    ],
      correctIndex: 1,
      difficulty: 'hard',
      explanation: 'Each Frobenius (companion) block corresponds to one invariant factor.'
    },
    {
      id: 's41-h06',
      question: 'The rational form reveals similarity without:',
      options: [
      'Computing anything',
      'Using any field',
      'The characteristic polynomial',
      'Finding eigenvalues',
    ],
      correctIndex: 3,
      difficulty: 'hard',
      explanation: 'Rational form can be computed over any field, without finding eigenvalues.'
    }
  ]
};

// Section 42: The Jordan Form
export const section42Quiz: DifficultyQuizData = {
  easy: [
    {
      id: 's42-e01',
      question: 'Jordan canonical form exists when:',
      options: [
      'Always',
      'T is diagonalizable',
      'F = ℝ',
      'The characteristic polynomial splits over F',
    ],
      correctIndex: 3,
      difficulty: 'easy',
      explanation: 'Jordan form exists iff all eigenvalues are in F (characteristic polynomial splits).'
    },
    {
      id: 's42-e02',
      question: 'A Jordan block Jₖ(λ) is a k × k matrix with:',
      options: [
      'All entries equal to λ',
      'λ everywhere',
      'Only diagonal λ',
      'λ on diagonal, 1s on superdiagonal',
    ],
      correctIndex: 3,
      difficulty: 'easy',
      explanation: 'Jordan block: λ on diagonal, 1s just above diagonal, zeros elsewhere.'
    },
    {
      id: 's42-e03',
      question: 'A is diagonalizable iff all Jordan blocks have size:',
      options: [
      'n',
      '2',
      '0',
      '1',
    ],
      correctIndex: 3,
      difficulty: 'easy',
      explanation: 'Diagonalizable means all Jordan blocks are 1 × 1 (just eigenvalues on diagonal).'
    },
    {
      id: 's42-e04',
      question: 'The Jordan form is unique up to:',
      options: [
      'Similarity',
      'Nothing (completely unique)',
      'Permutation of blocks',
      'Scalar multiplication',
    ],
      correctIndex: 2,
      difficulty: 'easy',
      explanation: 'Jordan form is unique up to ordering of the Jordan blocks.'
    },
    {
      id: 's42-e05',
      question: 'J₂(0) represents a:',
      options: [
      'Diagonal matrix',
      'Identity matrix',
      'Scalar matrix',
      'Nilpotent matrix',
    ],
      correctIndex: 3,
      difficulty: 'easy',
      explanation: 'J₂(0) = [[0,1],[0,0]] is nilpotent (J₂(0)² = 0).'
    },
    {
      id: 's42-e06',
      question: 'For an n × n matrix, the sum of sizes of all Jordan blocks equals:',
      options: [
      'n',
      'The rank',
      'The trace',
      'The determinant',
    ],
      correctIndex: 0,
      difficulty: 'easy',
      explanation: 'Total size of Jordan blocks = dimension of the space = n.'
    }
  ],
  medium: [
    {
      id: 's42-m01',
      question: 'If A has Jordan form with blocks of sizes 3, 2, 1 for eigenvalue λ, the geometric multiplicity of λ is:',
      options: [
      '6',
      '1',
      '3',
      'Undefined',
    ],
      correctIndex: 2,
      difficulty: 'medium',
      explanation: 'Geometric multiplicity = number of Jordan blocks for that eigenvalue.'
    },
    {
      id: 's42-m02',
      question: 'The number of 1s above the diagonal in Jordan form equals:',
      options: [
      'n - (number of Jordan blocks)',
      'n',
      'The trace',
      '0',
    ],
      correctIndex: 0,
      difficulty: 'medium',
      explanation: '1s above diagonal = n - (number of Jordan blocks).'
    },
    {
      id: 's42-m03',
      question: 'An n × n nilpotent matrix can have Jordan blocks of size at most:',
      options: [
      '1',
      'n/2',
      '2',
      'n',
    ],
      correctIndex: 3,
      difficulty: 'medium',
      explanation: 'A nilpotent has only eigenvalue 0; blocks can be as large as n (for a cyclic nilpotent).'
    },
    {
      id: 's42-m04',
      question: 'If A has a single Jordan block Jₙ(λ), then:',
      options: [
      'A has a cyclic vector',
      'A is diagonalizable',
      'A = λI',
      'A is nilpotent',
    ],
      correctIndex: 0,
      difficulty: 'medium',
      explanation: 'Single block means minimal polynomial = characteristic polynomial, so there\'s a cyclic vector.'
    },
    {
      id: 's42-m05',
      question: 'The algebraic multiplicity of λ in Jordan form is:',
      options: [
      'The sum of sizes of blocks for λ',
      'The number of blocks',
      'Always 1',
      'The trace',
    ],
      correctIndex: 0,
      difficulty: 'medium',
      explanation: 'Algebraic multiplicity = total size of all Jordan blocks for eigenvalue λ.'
    },
    {
      id: 's42-m06',
      question: 'If T has Jordan form diag(J₂(λ), J₁(λ)), then dim(ker(T - λI)) equals:',
      options: [
      '2',
      '1',
      '3',
      '0',
    ],
      correctIndex: 0,
      difficulty: 'medium',
      explanation: 'Geometric multiplicity = number of blocks = 2.'
    }
  ],
  hard: [
    {
      id: 's42-h01',
      question: 'The sizes of Jordan blocks for λ are determined by:',
      options: ['The trace', 'dims of ker((T-λI)^k) for k = 1, 2, ...', 'The determinant', 'Random'],
      correctIndex: 1,
      difficulty: 'hard',
      explanation: 'The sequence dim(ker(T-λI)^k) determines the Jordan block structure.'
    },
    {
      id: 's42-h02',
      question: 'dim(ker(T-λI)²) - dim(ker(T-λI)) equals:',
      options: [
      '0',
      'The algebraic multiplicity',
      'Number of Jordan blocks of size ≥ 2',
      'n',
    ],
      correctIndex: 2,
      difficulty: 'hard',
      explanation: 'This difference counts blocks of size at least 2.'
    },
    {
      id: 's42-h03',
      question: 'The Jordan form of J₂(λ)² is:',
      options: [
      'J₂(λ)²',
      'Diagonal',
      'J₂(λ²)',
      'Not a Jordan form',
    ],
      correctIndex: 2,
      difficulty: 'hard',
      explanation: 'Powers of Jordan blocks give Jordan blocks with eigenvalue λᵏ but same size.'
    },
    {
      id: 's42-h04',
      question: 'A generalized eigenvector of rank k satisfies:',
      options: [
      'Tv = λv',
      'T^k v = 0',
      '(T-λI)^k v = 0 but (T-λI)^{k-1}v ≠ 0',
      'v = 0',
    ],
      correctIndex: 2,
      difficulty: 'hard',
      explanation: 'Rank k means (T-λI)^k kills v but (T-λI)^{k-1} doesn\'t.'
    },
    {
      id: 's42-h05',
      question: 'A Jordan chain is:',
      options: [
      'A sequence of eigenvalues',
      'Vectors v, (T-λI)v, ..., (T-λI)^{k-1}v',
      'The blocks',
      'The invariant factors',
    ],
      correctIndex: 1,
      difficulty: 'hard',
      explanation: 'A Jordan chain consists of a generalized eigenvector and its images under (T-λI).'
    },
    {
      id: 's42-h06',
      question: 'The exponent of (x-λ) in the minimal polynomial equals:',
      options: ['The algebraic multiplicity', 'The size of the largest Jordan block for λ', 'The geometric multiplicity', 'n'],
      correctIndex: 1,
      difficulty: 'hard',
      explanation: 'The largest block size determines the exponent in the minimal polynomial.'
    }
  ]
};

// Section 43-44: Computation and Summary
export const section43Quiz: DifficultyQuizData = {
  easy: [
    {
      id: 's43-e01',
      question: 'To find Jordan form, we first need:',
      options: [
      'The trace',
      'The dimension',
      'The inverse',
      'The eigenvalues',
    ],
      correctIndex: 3,
      difficulty: 'easy',
      explanation: 'Jordan form requires finding eigenvalues first.'
    },
    {
      id: 's43-e02',
      question: 'The Smith normal form of a matrix over F[x] has:',
      options: [
      'Diagonal polynomial entries',
      'All entries in F',
      'Random polynomials',
      'Only constants',
    ],
      correctIndex: 0,
      difficulty: 'easy',
      explanation: 'Smith form has diagonal polynomial entries dividing each other.'
    },
    {
      id: 's43-e03',
      question: 'A semi-simple operator is:',
      options: [
      'Diagonalizable',
      'Nilpotent',
      'The identity',
      'Zero',
    ],
      correctIndex: 0,
      difficulty: 'easy',
      explanation: 'Semi-simple = diagonalizable (over an algebraically closed field).'
    },
    {
      id: 's43-e04',
      question: 'Every operator T can be written as T = S + N where:',
      options: [
      'S is symmetric',
      'S = N',
      'S is semi-simple, N is nilpotent, SN = NS',
      'S + N = I',
    ],
      correctIndex: 2,
      difficulty: 'easy',
      explanation: 'Jordan decomposition: T = S + N with S semi-simple, N nilpotent, and they commute.'
    },
    {
      id: 's43-e05',
      question: 'The largest invariant factor equals:',
      options: [
      'The characteristic polynomial',
      'The determinant',
      'The trace',
      'The minimal polynomial',
    ],
      correctIndex: 3,
      difficulty: 'easy',
      explanation: 'The last (largest) invariant factor is the minimal polynomial.'
    },
    {
      id: 's43-e06',
      question: 'The product of all invariant factors equals:',
      options: [
      'The characteristic polynomial',
      'The minimal polynomial',
      '1',
      'The trace',
    ],
      correctIndex: 0,
      difficulty: 'easy',
      explanation: 'The product of invariant factors equals the characteristic polynomial.'
    }
  ],
  medium: [
    {
      id: 's43-m01',
      question: 'The Smith normal form of xI - A gives:',
      options: [
      'The invariant factors',
      'Eigenvalues directly',
      'The Jordan form',
      'The determinant',
    ],
      correctIndex: 0,
      difficulty: 'medium',
      explanation: 'Smith normal form of xI - A has invariant factors on the diagonal.'
    },
    {
      id: 's43-m02',
      question: 'Elementary divisors are:',
      options: [
      'Prime power factors of invariant factors',
      'The eigenvalues',
      'Always linear',
      'The trace',
    ],
      correctIndex: 0,
      difficulty: 'medium',
      explanation: 'Elementary divisors = prime power factors of the invariant factors.'
    },
    {
      id: 's43-m03',
      question: 'Jordan blocks correspond to:',
      options: [
      'Elementary divisors',
      'Invariant factors',
      'The trace',
      'Eigenvalues only',
    ],
      correctIndex: 0,
      difficulty: 'medium',
      explanation: 'Each elementary divisor (x-λ)^k gives a Jordan block Jₖ(λ).'
    },
    {
      id: 's43-m04',
      question: 'The semi-simple and nilpotent parts of T are:',
      options: [
      'Always zero',
      'Not related to T',
      'Inverses of each other',
      'Polynomials in T',
    ],
      correctIndex: 3,
      difficulty: 'medium',
      explanation: 'S and N can both be expressed as polynomials in T.'
    },
    {
      id: 's43-m05',
      question: 'Matrices with the same characteristic polynomial:',
      options: [
      'May not be similar',
      'Are always similar',
      'Have the same Jordan form',
      'Commute',
    ],
      correctIndex: 0,
      difficulty: 'medium',
      explanation: 'Same characteristic polynomial doesn\'t imply similarity (need same invariant factors).'
    },
    {
      id: 's43-m06',
      question: 'The uniqueness of Jordan decomposition T = S + N means:',
      options: [
      'Only S is unique',
      'Only N is unique',
      'Neither is unique',
      'S and N are unique',
    ],
      correctIndex: 3,
      difficulty: 'medium',
      explanation: 'The decomposition T = S + N with SN = NS, S semi-simple, N nilpotent is unique.'
    }
  ],
  hard: [
    {
      id: 's43-h01',
      question: 'The Smith normal form has diagonal entries d₁, ..., dₙ with:',
      options: [
      'd₁ = d₂ = ... = dₙ',
      'No relation',
      'd₁ | d₂ | ... | dₙ',
      'dᵢ = xⁱ',
    ],
      correctIndex: 2,
      difficulty: 'hard',
      explanation: 'Smith form diagonal entries form a divisibility chain.'
    },
    {
      id: 's43-h02',
      question: 'Row and column operations on xI - A over F[x] preserve:',
      options: [
      'The similarity class of A',
      'The matrix itself',
      'Nothing',
      'Only the determinant',
    ],
      correctIndex: 0,
      difficulty: 'hard',
      explanation: 'These operations give equivalent matrices, revealing similarity invariants.'
    },
    {
      id: 's43-h03',
      question: 'The number of non-unit invariant factors equals:',
      options: [
      'n',
      'The number of non-trivial cyclic summands',
      'Zero',
      'One',
    ],
      correctIndex: 1,
      difficulty: 'hard',
      explanation: 'Each non-unit invariant factor corresponds to a non-trivial cyclic summand.'
    },
    {
      id: 's43-h04',
      question: 'The determinantal divisors dₖ(xI - A) are:',
      options: [
      'The eigenvalues',
      'gcds of k × k minors',
      'The invariant factors',
      'The trace',
    ],
      correctIndex: 1,
      difficulty: 'hard',
      explanation: 'dₖ = gcd of all k × k minors of xI - A.'
    },
    {
      id: 's43-h05',
      question: 'Invariant factors are recovered from determinantal divisors by:',
      options: [
      'Addition',
      'fₖ = dₖ/dₖ₋₁',
      'Multiplication',
      'fₖ = dₖ + dₖ₋₁',
    ],
      correctIndex: 1,
      difficulty: 'hard',
      explanation: 'The k-th invariant factor is fₖ = dₖ/dₖ₋₁.'
    },
    {
      id: 's43-h06',
      question: 'For T = S + N (Jordan decomposition), S and N can be computed from:',
      options: [
      'Guessing',
      'Fitting polynomials in T to interpolation conditions',
      'The eigenvectors',
      'Taking limits',
    ],
      correctIndex: 1,
      difficulty: 'hard',
      explanation: 'S and N are polynomials in T, found by interpolation from eigenvalues and eigenspaces.'
    }
  ]
};

// Chapter 7 Comprehensive Quiz
export const chapter07Quiz: DifficultyQuizData = {
  easy: [],
  medium: [],
  hard: [
    {
      id: 'ch07-h01',
      question: 'The Jordan form is unique up to:',
      options: [
      'Similarity',
      'Nothing (completely unique)',
      'Permutation of blocks',
      'Scalar multiplication',
    ],
      correctIndex: 2,
      difficulty: 'hard',
      explanation: 'Jordan form is unique up to ordering of the Jordan blocks.'
    },
    {
      id: 'ch07-h02',
      question: 'The largest invariant factor equals:',
      options: ['The characteristic polynomial', 'The minimal polynomial', 'The determinant', 'The trace'],
      correctIndex: 1,
      difficulty: 'hard',
      explanation: 'The last (largest) invariant factor is the minimal polynomial.'
    },
    {
      id: 'ch07-h03',
      question: 'The product of all invariant factors equals:',
      options: ['The minimal polynomial', 'The characteristic polynomial', '1', 'The trace'],
      correctIndex: 1,
      difficulty: 'hard',
      explanation: 'The product of invariant factors equals the characteristic polynomial.'
    },
    {
      id: 'ch07-h04',
      question: 'An n × n nilpotent matrix can have Jordan blocks of size at most:',
      options: [
      '1',
      'n/2',
      '2',
      'n',
    ],
      correctIndex: 3,
      difficulty: 'hard',
      explanation: 'A nilpotent has only eigenvalue 0; blocks can be as large as n (for a cyclic nilpotent).'
    },
    {
      id: 'ch07-h05',
      question: 'The number of 1s above the diagonal in Jordan form equals:',
      options: [
      'n',
      'The trace',
      'n - (geometric multiplicity summed over eigenvalues)',
      '0',
    ],
      correctIndex: 2,
      difficulty: 'hard',
      explanation: '1s above diagonal = n - (number of Jordan blocks) = n - Σ(geometric multiplicities).'
    },
    {
      id: 'ch07-h06',
      question: 'Companion matrices are always:',
      options: [
      'Cyclic (have a cyclic vector)',
      'Diagonal',
      'Symmetric',
      'Nilpotent',
    ],
      correctIndex: 0,
      difficulty: 'hard',
      explanation: 'A companion matrix has the standard basis vector e₁ as a cyclic vector.'
    },
    {
      id: 'ch07-h07',
      question: 'If T has Jordan form diag(J₂(λ), J₁(λ)), then dim(ker(T - λI)) equals:',
      options: [
      '1',
      '3',
      '0',
      '2',
    ],
      correctIndex: 3,
      difficulty: 'hard',
      explanation: 'Geometric multiplicity = number of blocks = 2.'
    },
    {
      id: 'ch07-h08',
      question: 'The rational form is defined over:',
      options: [
      'Only ℂ',
      'Any field',
      'Only algebraically closed fields',
      'Only ℝ',
    ],
      correctIndex: 1,
      difficulty: 'hard',
      explanation: 'Rational canonical form exists over any field (no splitting required).'
    },
    {
      id: 'ch07-h09',
      question: 'Matrices with the same characteristic polynomial:',
      options: [
      'Are always similar',
      'May not be similar',
      'Have the same Jordan form',
      'Commute',
    ],
      correctIndex: 1,
      difficulty: 'hard',
      explanation: 'Same characteristic polynomial doesn\'t imply similarity (need same invariant factors).'
    },
    {
      id: 'ch07-h10',
      question: 'For an n × n matrix, the sum of sizes of all Jordan blocks equals:',
      options: [
      'The rank',
      'The trace',
      'n',
      'The determinant',
    ],
      correctIndex: 2,
      difficulty: 'hard',
      explanation: 'Total size of Jordan blocks = dimension of the space = n.'
    }
  ]
};
