import { LessonLayout } from '@/components/layout/LessonLayout';
import { Definition, Theorem, Example } from '@/components/common/ContentBlocks';
import { InlineMath, MathBlock } from '@/components/common/MathBlock';

export default function Section25() {
  return (
    <LessonLayout sectionId={25}>
      {/* Introduction */}
      <p>
        Cyclic codes are a special class of linear codes with additional algebraic structure that
        makes encoding and decoding efficient. They are described using polynomials and have wide
        applications in digital communication and storage.
      </p>

      <h2>Polynomial Representation of Codewords</h2>

      <Definition title="Polynomial Representation" className="my-6">
        <p>
          A binary codeword <InlineMath>(c_0, c_1, \ldots, c_{'{n-1}'}) \in \mathbb{'{Z}'}_2^n</InlineMath>{' '}
          is represented by the polynomial:
        </p>
        <MathBlock>{`c(x) = c_0 + c_1 x + c_2 x^2 + \\cdots + c_{n-1} x^{n-1} \\in \\mathbb{Z}_2[x]`}</MathBlock>
      </Definition>

      <Example title="Polynomial Representation" className="my-6">
        <p>
          The codeword <InlineMath>(1, 0, 1, 1, 0, 0, 1)</InlineMath> corresponds to:
        </p>
        <MathBlock>{`c(x) = 1 + x^2 + x^3 + x^6`}</MathBlock>
      </Example>

      <h2>Cyclic Codes</h2>

      <Definition title="Cyclic Shift" className="my-6">
        <p>
          A <strong>cyclic shift</strong> of <InlineMath>(c_0, c_1, \ldots, c_{'{n-1}'})</InlineMath> is:
        </p>
        <MathBlock>{`(c_{n-1}, c_0, c_1, \\ldots, c_{n-2})`}</MathBlock>
        <p className="mt-2">
          In polynomial form, this corresponds to <InlineMath>x \cdot c(x) \mod (x^n - 1)</InlineMath>.
        </p>
      </Definition>

      <Definition title="Cyclic Code" className="my-6">
        <p>
          A linear code <InlineMath>C</InlineMath> of length <InlineMath>n</InlineMath> is{' '}
          <strong>cyclic</strong> if every cyclic shift of a codeword is also a codeword.
        </p>
        <p className="mt-2">
          Equivalently, <InlineMath>C</InlineMath> is an ideal in the quotient ring{' '}
          <InlineMath>\mathbb{'{Z}'}_2[x]/(x^n - 1)</InlineMath>.
        </p>
      </Definition>

      <Theorem title="Cyclic Codes are Principal Ideals" className="my-6">
        <p>
          Every cyclic code <InlineMath>C</InlineMath> of length <InlineMath>n</InlineMath> is
          generated by a unique monic polynomial <InlineMath>g(x)</InlineMath> that divides{' '}
          <InlineMath>x^n - 1</InlineMath>:
        </p>
        <MathBlock>{`C = \\{m(x) \\cdot g(x) \\mod (x^n - 1) : \\deg m < n - \\deg g\\}`}</MathBlock>
        <p className="mt-2">
          <InlineMath>g(x)</InlineMath> is called the <strong>generator polynomial</strong>.
        </p>
      </Theorem>

      <h2>Properties of Generator Polynomials</h2>

      <Theorem title="Dimension and Generator" className="my-6">
        <p>
          If <InlineMath>g(x)</InlineMath> is the generator polynomial of a cyclic code of length{' '}
          <InlineMath>n</InlineMath> with <InlineMath>\deg g = r</InlineMath>, then:
        </p>
        <ul className="list-disc list-inside mt-2 space-y-1">
          <li>
            The code has dimension <InlineMath>k = n - r</InlineMath>
          </li>
          <li>
            The code has <InlineMath>2^k</InlineMath> codewords
          </li>
          <li>
            <InlineMath>g(x)</InlineMath> divides <InlineMath>x^n - 1</InlineMath>
          </li>
        </ul>
      </Theorem>

      <Example title="Factoring x^7 - 1 over Z_2" className="my-6">
        <p>
          Over <InlineMath>\mathbb{'{Z}'}_2</InlineMath>:
        </p>
        <MathBlock>{`x^7 - 1 = x^7 + 1 = (x + 1)(x^3 + x + 1)(x^3 + x^2 + 1)`}</MathBlock>
        <p className="mt-2">
          Each divisor of <InlineMath>x^7 - 1</InlineMath> generates a cyclic code of length 7:
        </p>
        <ul className="list-disc list-inside mt-2 space-y-1">
          <li>
            <InlineMath>g(x) = x + 1</InlineMath>: dimension <InlineMath>k = 7 - 1 = 6</InlineMath>
          </li>
          <li>
            <InlineMath>g(x) = x^3 + x + 1</InlineMath>: dimension <InlineMath>k = 7 - 3 = 4</InlineMath>
          </li>
          <li>
            <InlineMath>g(x) = x^3 + x^2 + 1</InlineMath>: dimension <InlineMath>k = 4</InlineMath>
          </li>
          <li>
            <InlineMath>g(x) = (x + 1)(x^3 + x + 1)</InlineMath>: dimension <InlineMath>k = 3</InlineMath>
          </li>
        </ul>
      </Example>

      <h2>The [7, 4] Hamming Code as Cyclic</h2>

      <Example title="Hamming Code Generator" className="my-6">
        <p>
          The <InlineMath>[7, 4]</InlineMath> Hamming code is cyclic with generator:
        </p>
        <MathBlock>{`g(x) = x^3 + x + 1`}</MathBlock>
        <p className="mt-3"><strong>Encoding:</strong> To encode message <InlineMath>m(x)</InlineMath> (degree ≤ 3):</p>
        <MathBlock>{`c(x) = m(x) \\cdot g(x)`}</MathBlock>
        <p className="mt-3">
          Example: Encode <InlineMath>m(x) = x^2 + 1</InlineMath> (message <InlineMath>(1, 0, 1, 0)</InlineMath>):
        </p>
        <MathBlock>{`c(x) = (x^2 + 1)(x^3 + x + 1) = x^5 + x^3 + x^2 + x^3 + x + 1 = x^5 + x^2 + x + 1`}</MathBlock>
        <p className="mt-2">
          Codeword: <InlineMath>(1, 1, 1, 0, 0, 1, 0)</InlineMath>.
        </p>
      </Example>

      <h2>Check Polynomial and Parity Check</h2>

      <Definition title="Check Polynomial" className="my-6">
        <p>
          If <InlineMath>g(x)</InlineMath> is the generator polynomial and{' '}
          <InlineMath>g(x) h(x) = x^n - 1</InlineMath>, then <InlineMath>h(x)</InlineMath> is the{' '}
          <strong>check polynomial</strong>.
        </p>
        <p className="mt-2">
          A polynomial <InlineMath>c(x)</InlineMath> is a codeword iff{' '}
          <InlineMath>c(x) \cdot h(x) \equiv 0 \pmod{'{x^n - 1}'}</InlineMath>.
        </p>
      </Definition>

      <Example title="Check Polynomial for Hamming" className="my-6">
        <p>
          For the <InlineMath>[7, 4]</InlineMath> Hamming code with <InlineMath>g(x) = x^3 + x + 1</InlineMath>:
        </p>
        <MathBlock>{`h(x) = \\frac{x^7 + 1}{x^3 + x + 1} = x^4 + x^2 + x + 1`}</MathBlock>
        <p className="mt-2">
          Verify: <InlineMath>(x^3 + x + 1)(x^4 + x^2 + x + 1) = x^7 + 1</InlineMath>.
        </p>
      </Example>

      <h2>Error Detection and Correction</h2>

      <Definition title="Syndrome Polynomial" className="my-6">
        <p>
          For a received polynomial <InlineMath>r(x)</InlineMath>, the <strong>syndrome</strong> is:
        </p>
        <MathBlock>{`s(x) = r(x) \\mod g(x)`}</MathBlock>
        <p className="mt-2">
          If <InlineMath>s(x) = 0</InlineMath>, then <InlineMath>r(x)</InlineMath> is a codeword.
        </p>
      </Definition>

      <Example title="Syndrome Calculation" className="my-6">
        <p>
          Suppose <InlineMath>c(x) = x^5 + x^2 + x + 1</InlineMath> is sent but{' '}
          <InlineMath>r(x) = x^5 + x^3 + x^2 + x + 1</InlineMath> is received (error in position 3).
        </p>
        <p className="mt-3"><strong>Compute syndrome:</strong></p>
        <MathBlock>{`s(x) = r(x) \\mod g(x) = (x^5 + x^3 + x^2 + x + 1) \\mod (x^3 + x + 1) = x`}</MathBlock>
        <p className="mt-2">
          The syndrome <InlineMath>x</InlineMath> corresponds to an error pattern, allowing correction.
        </p>
      </Example>

      <h2>BCH and Reed-Solomon Codes</h2>

      <div className="bg-dark-800/50 rounded-xl p-6 my-6 border border-dark-700">
        <h4 className="text-lg font-semibold text-dark-100 mb-4">Advanced Cyclic Codes</h4>
        <ul className="space-y-3 text-dark-200">
          <li>
            <strong>BCH codes:</strong> A class of cyclic codes with prescribed minimum distance.
            Can correct multiple errors.
          </li>
          <li>
            <strong>Reed-Solomon codes:</strong> BCH codes over larger finite fields. Widely used
            in CDs, DVDs, QR codes, and space communication.
          </li>
          <li>
            <strong>Fire codes:</strong> Used for burst error correction (consecutive errors).
          </li>
          <li>
            <strong>CRC (Cyclic Redundancy Check):</strong> Uses cyclic codes for error detection
            in networking and storage.
          </li>
        </ul>
      </div>

      <h2>Applications</h2>

      <Example title="CRC in Practice" className="my-6">
        <p>
          CRC-32 uses the generator polynomial:
        </p>
        <MathBlock>{`g(x) = x^{32} + x^{26} + x^{23} + x^{22} + x^{16} + x^{12} + x^{11} + x^{10}`}</MathBlock>
        <MathBlock>{`+ x^8 + x^7 + x^5 + x^4 + x^2 + x + 1`}</MathBlock>
        <p className="mt-2">
          Used in Ethernet, ZIP files, PNG images, and many other applications for error detection.
        </p>
      </Example>

      <h2>Key Ideas</h2>

      <div className="bg-gradient-to-br from-primary-500/10 to-dark-800/50 rounded-xl p-6 my-6 border border-primary-500/20">
        <ul className="space-y-3 text-dark-200">
          <li className="flex items-start gap-3">
            <span className="text-primary-400 font-bold">1.</span>
            <span>
              <strong>Cyclic codes</strong> are closed under cyclic shifts. They correspond to ideals
              in <InlineMath>\mathbb{'{Z}'}_2[x]/(x^n - 1)</InlineMath>.
            </span>
          </li>
          <li className="flex items-start gap-3">
            <span className="text-primary-400 font-bold">2.</span>
            <span>
              Every cyclic code has a <strong>generator polynomial</strong> <InlineMath>g(x)</InlineMath>{' '}
              that divides <InlineMath>x^n - 1</InlineMath>.
            </span>
          </li>
          <li className="flex items-start gap-3">
            <span className="text-primary-400 font-bold">3.</span>
            <span>
              <strong>Encoding:</strong> <InlineMath>c(x) = m(x) \cdot g(x)</InlineMath>.{' '}
              <strong>Dimension:</strong> <InlineMath>k = n - \deg g</InlineMath>.
            </span>
          </li>
          <li className="flex items-start gap-3">
            <span className="text-primary-400 font-bold">4.</span>
            <span>
              <strong>Check polynomial:</strong> <InlineMath>h(x) = (x^n - 1)/g(x)</InlineMath>.
              Codewords satisfy <InlineMath>c(x) h(x) \equiv 0</InlineMath>.
            </span>
          </li>
          <li className="flex items-start gap-3">
            <span className="text-primary-400 font-bold">5.</span>
            <span>
              <strong>Syndrome:</strong> <InlineMath>s(x) = r(x) \mod g(x)</InlineMath> detects errors.
            </span>
          </li>
          <li className="flex items-start gap-3">
            <span className="text-primary-400 font-bold">6.</span>
            <span>
              <strong>Applications:</strong> CRC, BCH codes, Reed-Solomon codes—used throughout
              digital communication.
            </span>
          </li>
        </ul>
      </div>
    </LessonLayout>
  );
}
