import { LessonLayout } from '@/components/layout/LessonLayout';
import { Definition, Theorem, Example } from '@/components/common/ContentBlocks';
import { InlineMath, MathBlock } from '@/components/common/MathBlock';

export default function Section17() {
  return (
    <LessonLayout sectionId={17}>
      {/* Introduction */}
      <p>
        A subgroup is a subset of a group that is itself a group under the same operation. Subgroups
        help us understand the structure of groups by breaking them into smaller, more manageable
        pieces. This section develops the theory of subgroups and introduces cyclic groups.
      </p>

      <h2>Subgroups</h2>

      <Definition title="Subgroup" className="my-6">
        <p>
          A nonempty subset <InlineMath>H</InlineMath> of a group <InlineMath>G</InlineMath> is a{' '}
          <strong>subgroup</strong> of <InlineMath>G</InlineMath>, written{' '}
          <InlineMath>H \leq G</InlineMath>, if <InlineMath>H</InlineMath> is a group under the same
          operation as <InlineMath>G</InlineMath>.
        </p>
        <p className="mt-2">
          If <InlineMath>H \leq G</InlineMath> and <InlineMath>H \neq G</InlineMath>, we write{' '}
          <InlineMath>H {'<'} G</InlineMath> and call <InlineMath>H</InlineMath> a <strong>proper
          subgroup</strong>.
        </p>
      </Definition>

      <Theorem title="Subgroup Test" className="my-6">
        <p>
          A nonempty subset <InlineMath>H</InlineMath> of <InlineMath>G</InlineMath> is a subgroup
          if and only if:
        </p>
        <ol className="list-decimal list-inside mt-2 space-y-1">
          <li>
            For all <InlineMath>a, b \in H</InlineMath>, <InlineMath>ab \in H</InlineMath> (closure)
          </li>
          <li>
            For all <InlineMath>a \in H</InlineMath>, <InlineMath>a^{'{-1}'} \in H</InlineMath> (inverses)
          </li>
        </ol>
        <p className="mt-2">
          (The identity follows: if <InlineMath>a \in H</InlineMath>, then{' '}
          <InlineMath>e = aa^{'{-1}'} \in H</InlineMath>.)
        </p>
      </Theorem>

      <Theorem title="One-Step Subgroup Test" className="my-6">
        <p>
          A nonempty subset <InlineMath>H</InlineMath> of <InlineMath>G</InlineMath> is a subgroup
          if and only if:
        </p>
        <MathBlock>{`\\text{For all } a, b \\in H, \\quad ab^{-1} \\in H`}</MathBlock>
      </Theorem>

      <Example title="Subgroup Examples" className="my-6">
        <ul className="space-y-3">
          <li>
            Every group <InlineMath>G</InlineMath> has the <strong>trivial subgroups</strong>:{' '}
            <InlineMath>\{'{e}'}\</InlineMath> and <InlineMath>G</InlineMath> itself.
          </li>
          <li>
            <InlineMath>(\mathbb{'{Z}'}, +)</InlineMath> has subgroups{' '}
            <InlineMath>n\mathbb{'{Z}'} = \{'{nk : k \\in \\mathbb{Z}}'}\</InlineMath> for each{' '}
            <InlineMath>n \geq 0</InlineMath>.
          </li>
          <li>
            <InlineMath>A_n \leq S_n</InlineMath> (the alternating group is a subgroup of the
            symmetric group).
          </li>
          <li>
            <InlineMath>SL_n(\mathbb{'{R}'}) = \{'{A \\in GL_n(\\mathbb{R}) : \\det(A) = 1}'}\</InlineMath>{' '}
            is a subgroup of <InlineMath>GL_n(\mathbb{'{R}'})</InlineMath>.
          </li>
        </ul>
      </Example>

      <Example title="Verifying a Subgroup" className="my-6">
        <p>
          Show <InlineMath>H = \{'{[0], [3], [6], [9]}'}\</InlineMath> is a subgroup of{' '}
          <InlineMath>(\mathbb{'{Z}'}_{'{12}'}, +)</InlineMath>.
        </p>
        <div className="bg-dark-800/50 rounded-xl p-4 mt-4 border border-dark-700">
          <p><strong>Using the subgroup test:</strong></p>
          <ul className="list-disc list-inside mt-2 space-y-1">
            <li><InlineMath>H \neq \emptyset</InlineMath> (clearly)</li>
            <li>
              Closure: Any two elements of <InlineMath>H</InlineMath> sum to a multiple of 3 mod 12, which
              is in <InlineMath>H</InlineMath>
            </li>
            <li>
              Inverses: <InlineMath>-[0] = [0]</InlineMath>, <InlineMath>-[3] = [9]</InlineMath>,{' '}
              <InlineMath>-[6] = [6]</InlineMath>, <InlineMath>-[9] = [3]</InlineMath>, all in{' '}
              <InlineMath>H</InlineMath>
            </li>
          </ul>
          <p className="mt-2">Therefore <InlineMath>H \leq \mathbb{'{Z}'}_{'{12}'}</InlineMath>.</p>
        </div>
      </Example>

      <h2>Cyclic Groups and Generators</h2>

      <Definition title="Group Generated by a Subset" className="my-6">
        <p>
          For a subset <InlineMath>S</InlineMath> of a group <InlineMath>G</InlineMath>, the{' '}
          <strong>subgroup generated by S</strong>, denoted <InlineMath>\langle S \rangle</InlineMath>,
          is the smallest subgroup of <InlineMath>G</InlineMath> containing <InlineMath>S</InlineMath>.
        </p>
        <p className="mt-2">
          It consists of all finite products of elements of <InlineMath>S</InlineMath> and their
          inverses.
        </p>
      </Definition>

      <Definition title="Cyclic Group" className="my-6">
        <p>
          A group <InlineMath>G</InlineMath> is <strong>cyclic</strong> if <InlineMath>G = \langle g \rangle</InlineMath>{' '}
          for some element <InlineMath>g</InlineMath>. The element <InlineMath>g</InlineMath> is
          called a <strong>generator</strong>.
        </p>
        <MathBlock>{`\\langle g \\rangle = \\{g^n : n \\in \\mathbb{Z}\\} = \\{\\ldots, g^{-2}, g^{-1}, e, g, g^2, g^3, \\ldots\\}`}</MathBlock>
      </Definition>

      <Theorem title="Order of a Cyclic Group" className="my-6">
        <p>
          If <InlineMath>g</InlineMath> has finite order <InlineMath>n</InlineMath>, then:
        </p>
        <MathBlock>{`\\langle g \\rangle = \\{e, g, g^2, \\ldots, g^{n-1}\\}`}</MathBlock>
        <p className="mt-2">
          So <InlineMath>|\langle g \rangle| = |g|</InlineMath> (the order of the group equals the
          order of the generator).
        </p>
      </Theorem>

      <Theorem title="Subgroups of Cyclic Groups" className="my-6">
        <p>
          Every subgroup of a cyclic group is cyclic.
        </p>
      </Theorem>

      <Theorem title="Subgroups of Z" className="my-6">
        <p>
          Every subgroup of <InlineMath>(\mathbb{'{Z}'}, +)</InlineMath> has the form{' '}
          <InlineMath>n\mathbb{'{Z}'} = \{'{nk : k \\in \\mathbb{Z}}'}\</InlineMath> for some{' '}
          <InlineMath>n \geq 0</InlineMath>.
        </p>
      </Theorem>

      <Example title="Subgroups of Z_12" className="my-6">
        <p>
          <InlineMath>\mathbb{'{Z}'}_{'{12}'}</InlineMath> is cyclic with generator <InlineMath>[1]</InlineMath>.
        </p>
        <p className="mt-2">Its subgroups are:</p>
        <ul className="list-disc list-inside mt-2 space-y-1">
          <li><InlineMath>\langle [1] \rangle = \mathbb{'{Z}'}_{'{12}'}</InlineMath> (order 12)</li>
          <li><InlineMath>\langle [2] \rangle = \{'{[0], [2], [4], [6], [8], [10]}'}\</InlineMath> (order 6)</li>
          <li><InlineMath>\langle [3] \rangle = \{'{[0], [3], [6], [9]}'}\</InlineMath> (order 4)</li>
          <li><InlineMath>\langle [4] \rangle = \{'{[0], [4], [8]}'}\</InlineMath> (order 3)</li>
          <li><InlineMath>\langle [6] \rangle = \{'{[0], [6]}'}\</InlineMath> (order 2)</li>
          <li><InlineMath>\langle [0] \rangle = \{'{[0]}'}\</InlineMath> (order 1)</li>
        </ul>
        <p className="mt-2">
          Notice: subgroup orders are <InlineMath>1, 2, 3, 4, 6, 12</InlineMath>—exactly the
          divisors of 12!
        </p>
      </Example>

      <h2>Generators of Cyclic Groups</h2>

      <Theorem title="Generators of Z_n" className="my-6">
        <p>
          The generators of <InlineMath>\mathbb{'{Z}'}_n</InlineMath> are exactly the elements{' '}
          <InlineMath>[a]</InlineMath> where <InlineMath>\gcd(a, n) = 1</InlineMath>.
        </p>
        <p className="mt-2">
          The number of generators is <InlineMath>\phi(n)</InlineMath>.
        </p>
      </Theorem>

      <Example title="Generators of Z_8" className="my-6">
        <p>
          <InlineMath>\mathbb{'{Z}'}_8</InlineMath> has <InlineMath>\phi(8) = 4</InlineMath> generators:
        </p>
        <ul className="list-disc list-inside mt-2">
          <li><InlineMath>[1], [3], [5], [7]</InlineMath> (those relatively prime to 8)</li>
        </ul>
        <p className="mt-2">
          <InlineMath>[2], [4], [6]</InlineMath> generate proper subgroups.
        </p>
      </Example>

      <Theorem title="Order of Powers" className="my-6">
        <p>
          Let <InlineMath>|g| = n</InlineMath>. Then for any integer <InlineMath>k</InlineMath>:
        </p>
        <MathBlock>{`|g^k| = \\frac{n}{\\gcd(k, n)}`}</MathBlock>
      </Theorem>

      <Example title="Computing Orders" className="my-6">
        <p>
          In <InlineMath>\mathbb{'{Z}'}_{'{12}'}</InlineMath>, <InlineMath>|[1]| = 12</InlineMath>. Then:
        </p>
        <ul className="list-disc list-inside mt-2 space-y-1">
          <li><InlineMath>|[3]| = |[1]^3| = 12/\gcd(3, 12) = 12/3 = 4</InlineMath></li>
          <li><InlineMath>|[4]| = |[1]^4| = 12/\gcd(4, 12) = 12/4 = 3</InlineMath></li>
          <li><InlineMath>|[5]| = |[1]^5| = 12/\gcd(5, 12) = 12/1 = 12</InlineMath></li>
        </ul>
      </Example>

      <h2>Key Ideas</h2>

      <div className="bg-gradient-to-br from-primary-500/10 to-dark-800/50 rounded-xl p-6 my-6 border border-primary-500/20">
        <ul className="space-y-3 text-dark-200">
          <li className="flex items-start gap-3">
            <span className="text-primary-400 font-bold">1.</span>
            <span>
              A <strong>subgroup</strong> <InlineMath>H \leq G</InlineMath> is a subset closed under
              the operation and inverses.
            </span>
          </li>
          <li className="flex items-start gap-3">
            <span className="text-primary-400 font-bold">2.</span>
            <span>
              <strong>Subgroup test:</strong> Check <InlineMath>ab^{'{-1}'} \in H</InlineMath> for
              all <InlineMath>a, b \in H</InlineMath>.
            </span>
          </li>
          <li className="flex items-start gap-3">
            <span className="text-primary-400 font-bold">3.</span>
            <span>
              <InlineMath>\langle g \rangle = \{'{g^n : n \\in \\mathbb{Z}}'}\</InlineMath> is the{' '}
              <strong>cyclic subgroup</strong> generated by <InlineMath>g</InlineMath>.
            </span>
          </li>
          <li className="flex items-start gap-3">
            <span className="text-primary-400 font-bold">4.</span>
            <span>
              Every subgroup of a cyclic group is cyclic. Subgroups of <InlineMath>\mathbb{'{Z}'}</InlineMath>{' '}
              have form <InlineMath>n\mathbb{'{Z}'}</InlineMath>.
            </span>
          </li>
          <li className="flex items-start gap-3">
            <span className="text-primary-400 font-bold">5.</span>
            <span>
              <InlineMath>[a]</InlineMath> generates <InlineMath>\mathbb{'{Z}'}_n</InlineMath> iff{' '}
              <InlineMath>\gcd(a, n) = 1</InlineMath>. Number of generators: <InlineMath>\phi(n)</InlineMath>.
            </span>
          </li>
          <li className="flex items-start gap-3">
            <span className="text-primary-400 font-bold">6.</span>
            <span>
              <InlineMath>|g^k| = n/\gcd(k, n)</InlineMath> where <InlineMath>|g| = n</InlineMath>.
            </span>
          </li>
        </ul>
      </div>
    </LessonLayout>
  );
}
