import { LessonLayout } from '@/components/layout';
import { Definition, Theorem, Example } from '@/components/common';
import { InlineMath, MathBlock } from '@/components/common/MathBlock';
import { Callout } from '@/components/common/Callout';

export default function Section08() {
  return (
    <LessonLayout sectionId={8}>
      <h2 className="text-2xl font-bold text-dark-100 mb-6">Canonical Transformations</h2>

      <p className="mb-4">
        A canonical transformation is a change of phase space coordinates that preserves the form
        of Hamilton's equations. Such transformations are the symmetries of Hamiltonian mechanics,
        and they include time evolution itself. The theory of canonical transformations provides
        powerful techniques for solving mechanical problems by finding coordinates in which the
        problem simplifies.
      </p>

      <h3 className="text-xl font-semibold text-dark-100 mt-8 mb-4">Definition of Canonical Transformation</h3>

      <Definition title="Canonical Transformation">
        <p>
          A transformation of phase space coordinates:
        </p>
        <MathBlock>{`(q, p) \\to (Q, P) = (Q(q, p, t), P(q, p, t))`}</MathBlock>
        <p className="mt-2">
          is <strong>canonical</strong> if it preserves the symplectic form:
        </p>
        <MathBlock>{`\\sum_i dP_i \\wedge dQ^i = \\sum_i dp_i \\wedge dq^i`}</MathBlock>
        <p className="mt-2">
          Equivalently, Hamilton's equations in the new coordinates have the same form as in the old.
        </p>
      </Definition>

      <Theorem title="Preservation of Poisson Brackets">
        <p className="mb-2">
          A transformation is canonical if and only if it preserves all Poisson brackets:
        </p>
        <MathBlock>{`\\{Q^i, Q^j\\}_{q,p} = 0, \\quad \\{P_i, P_j\\}_{q,p} = 0, \\quad \\{Q^i, P_j\\}_{q,p} = \\delta^i_j`}</MathBlock>
        <p className="mt-2">
          where the brackets are computed using the original coordinates <InlineMath>{`(q, p)`}</InlineMath>.
        </p>
      </Theorem>

      <Example title="Point Transformation">
        <p className="mb-3">
          A change of configuration coordinates <InlineMath>{`Q^i = Q^i(q)`}</InlineMath> (independent
          of momenta) extends to a canonical transformation via:
        </p>
        <MathBlock>{`P_i = \\sum_j \\frac{\\partial q^j}{\\partial Q^i} p_j`}</MathBlock>
        <p className="mt-2">
          For example, the transformation from Cartesian to polar coordinates <InlineMath>{`(x, y) \\to (r, \\theta)`}</InlineMath>
          gives <InlineMath>{`p_r = (xp_x + yp_y)/r`}</InlineMath> and <InlineMath>{`p_\\theta = xp_y - yp_x`}</InlineMath>.
        </p>
      </Example>

      <h3 className="text-xl font-semibold text-dark-100 mt-8 mb-4">Generating Functions</h3>

      <p className="mb-4">
        Canonical transformations can be systematically constructed using generating functions.
        There are four types, depending on which variables are treated as independent.
      </p>

      <Definition title="Type 1 Generating Function">
        <p>
          A generating function <InlineMath>{`F_1(q, Q, t)`}</InlineMath> determines a canonical
          transformation via:
        </p>
        <MathBlock>{`p_i = \\frac{\\partial F_1}{\\partial q^i}, \\quad P_i = -\\frac{\\partial F_1}{\\partial Q^i}`}</MathBlock>
        <p className="mt-2">
          The new Hamiltonian is <InlineMath>{`K = H + \\partial F_1/\\partial t`}</InlineMath>.
        </p>
      </Definition>

      <Definition title="Type 2 Generating Function">
        <p>
          A generating function <InlineMath>{`F_2(q, P, t)`}</InlineMath> gives:
        </p>
        <MathBlock>{`p_i = \\frac{\\partial F_2}{\\partial q^i}, \\quad Q^i = \\frac{\\partial F_2}{\\partial P_i}`}</MathBlock>
        <p className="mt-2">
          The identity transformation corresponds to <InlineMath>{`F_2 = \\sum_i q^i P_i`}</InlineMath>.
        </p>
      </Definition>

      <Example title="Exchange Transformation">
        <p className="mb-3">
          The generating function <InlineMath>{`F_1 = \\sum_i q^i Q^i`}</InlineMath> gives:
        </p>
        <MathBlock>{`p_i = Q^i, \\quad P_i = -q^i`}</MathBlock>
        <p className="mt-2">
          This exchanges coordinates and momenta (with a sign), demonstrating the democratic treatment
          of <InlineMath>{`q`}</InlineMath> and <InlineMath>{`p`}</InlineMath> in Hamiltonian mechanics.
        </p>
      </Example>

      <h3 className="text-xl font-semibold text-dark-100 mt-8 mb-4">Time Evolution as Canonical Transformation</h3>

      <Theorem title="Hamiltonian Flow is Canonical">
        <p className="mb-2">
          The time evolution map <InlineMath>{`\\phi_t: (q_0, p_0) \\to (q(t), p(t))`}</InlineMath>
          generated by Hamilton's equations is a canonical transformation for each <InlineMath>{`t`}</InlineMath>.
        </p>
        <p className="mt-2">
          The infinitesimal generator of this transformation is the Hamiltonian itself. For small <InlineMath>{`\\epsilon`}</InlineMath>:
        </p>
        <MathBlock>{`q(\\epsilon) \\approx q_0 + \\epsilon\\{q_0, H\\}, \\quad p(\\epsilon) \\approx p_0 + \\epsilon\\{p_0, H\\}`}</MathBlock>
      </Theorem>

      <h3 className="text-xl font-semibold text-dark-100 mt-8 mb-4">Hamilton-Jacobi Theory</h3>

      <p className="mb-4">
        The ultimate goal of canonical transformation theory is to find coordinates in which the
        Hamiltonian vanishes, making the solution trivial.
      </p>

      <Definition title="Hamilton-Jacobi Equation">
        <p>
          The <strong>Hamilton-Jacobi equation</strong> is a partial differential equation for a
          generating function <InlineMath>{`S(q, P, t)`}</InlineMath> (called <strong>Hamilton's principal
          function</strong>) such that the new Hamiltonian vanishes:
        </p>
        <MathBlock>{`H\\left(q, \\frac{\\partial S}{\\partial q}, t\\right) + \\frac{\\partial S}{\\partial t} = 0`}</MathBlock>
        <p className="mt-2">
          If solved, the new momenta <InlineMath>{`P_i`}</InlineMath> are constants, and the new
          coordinates <InlineMath>{`Q^i = \\partial S/\\partial P_i`}</InlineMath> are also constant
          (up to linear time dependence).
        </p>
      </Definition>

      <Example title="Free Particle Hamilton-Jacobi">
        <p className="mb-3">
          For a free particle in one dimension, <InlineMath>{`H = p^2/2m`}</InlineMath>. The
          Hamilton-Jacobi equation is:
        </p>
        <MathBlock>{`\\frac{1}{2m}\\left(\\frac{\\partial S}{\\partial q}\\right)^2 + \\frac{\\partial S}{\\partial t} = 0`}</MathBlock>
        <p className="mb-2">
          Trying <InlineMath>{`S = W(q) - Et`}</InlineMath> (separation of variables):
        </p>
        <MathBlock>{`\\frac{1}{2m}\\left(\\frac{dW}{dq}\\right)^2 = E \\implies W = \\sqrt{2mE} \\cdot q`}</MathBlock>
        <p className="mt-2">
          So <InlineMath>{`S = \\sqrt{2mE} \\cdot q - Et`}</InlineMath>, and <InlineMath>{`Q = \\partial S/\\partial E = \\sqrt{m/2E} \\cdot q - t`}</InlineMath>
          is constant, giving <InlineMath>{`q = vt + q_0`}</InlineMath>.
        </p>
      </Example>

      <h3 className="text-xl font-semibold text-dark-100 mt-8 mb-4">Symplectic Group</h3>

      <Definition title="Symplectic Group">
        <p>
          The <strong>symplectic group</strong> <InlineMath>{`Sp(2n, \\mathbb{R})`}</InlineMath> consists
          of <InlineMath>{`2n \\times 2n`}</InlineMath> matrices <InlineMath>{`M`}</InlineMath> satisfying:
        </p>
        <MathBlock>{`M^T J M = J`}</MathBlock>
        <p className="mt-2">
          where <InlineMath>{`J`}</InlineMath> is the symplectic matrix. Linear canonical transformations
          are elements of this group.
        </p>
      </Definition>

      <Theorem title="Properties of Symplectic Matrices">
        <p className="mb-2">
          Symplectic matrices satisfy:
        </p>
        <ol className="list-decimal list-inside mb-2 text-dark-300 space-y-1">
          <li><InlineMath>{`\\det(M) = 1`}</InlineMath> (volume preserving)</li>
          <li>If <InlineMath>{`\\lambda`}</InlineMath> is an eigenvalue, so is <InlineMath>{`1/\\lambda`}</InlineMath></li>
          <li><InlineMath>{`M^{-1} = J^{-1} M^T J = -J M^T J`}</InlineMath></li>
        </ol>
      </Theorem>

      <Callout type="info" title="Action-Angle Variables">
        <p>
          For integrable systems, there exist special canonical coordinates called action-angle
          variables <InlineMath>{`(\\theta, I)`}</InlineMath> where the Hamiltonian depends only
          on the actions: <InlineMath>{`H = H(I)`}</InlineMath>. The actions are constants of
          motion, and the angles evolve linearly: <InlineMath>{`\\dot{\\theta} = \\partial H/\\partial I = \\omega(I)`}</InlineMath>.
          Finding these variables via canonical transformation solves the integrable system completely.
        </p>
      </Callout>

      <Callout type="success" title="Key Insight">
        <p>
          Canonical transformations preserve the Hamiltonian structure of mechanics. They form a
          rich family of symmetries that includes time evolution, coordinate changes, and more
          exotic transformations. The theory of generating functions and Hamilton-Jacobi equation
          provides systematic methods to find coordinates that simplify problems, potentially
          reducing integration to algebraic operations.
        </p>
      </Callout>
    </LessonLayout>
  );
}
