name: MagicInternetMath
options:
  bundleIdPrefix: com.magicinternetmath
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1,2"

targets:
  MagicInternetMath:
    type: application
    platform: iOS
    sources:
      - MagicInternetMath
    resources:
      - MagicInternetMath/Resources
    settings:
      base:
        INFOPLIST_FILE: MagicInternetMath/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.magicinternetmath.app
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    info:
      path: MagicInternetMath/Resources/Info.plist
      properties:
        CFBundleDisplayName: Magic Math
        CFBundleName: MagicInternetMath
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        UILaunchStoryboardName: LaunchScreen
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
        NSAppTransportSecurity:
          NSAllowsArbitraryLoadsInWebContent: true
        ITSAppUsesNonExemptEncryption: false
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
