import { LessonLayout } from '@/components/layout';
import { Definition, Example } from '@/components/common';
import { InlineMath, MathBlock } from '@/components/common/MathBlock';
import { Callout } from '@/components/common/Callout';

export default function Section01() {
  return (
    <LessonLayout sectionId={1}>
      <h2 className="text-2xl font-bold text-dark-100 mb-6">Binding Commitments</h2>

      <p className="mb-4">
        A commitment scheme allows one party to commit to a value while keeping it hidden,
        with the ability to reveal the value later. The <strong>binding</strong> property
        ensures that once committed, the party cannot change the value.
      </p>

      <Definition title="Binding Commitment">
        <p>
          A commitment scheme is said to be <strong>binding</strong> if for all PPT adversaries{' '}
          <InlineMath>\mathcal{'{A}'}</InlineMath> there exists a negligible function{' '}
          <InlineMath>\mu</InlineMath> such that:
        </p>
        <MathBlock>
          {`\\Pr\\left[\\text{Com}(x_0; r_0) = \\text{Com}(x_1; r_1) \\land x_0 \\neq x_1 \\;\\middle|\\; \\begin{array}{l} pp \\leftarrow\\!\\!\\$ \\text{Setup}(1^\\lambda) \\\\ (x_0, x_1, r_0, r_1) \\leftarrow \\mathcal{A}(pp) \\end{array}\\right] \\leq \\mu(\\lambda)`}
        </MathBlock>
      </Definition>

      <h3 className="text-xl font-semibold text-dark-100 mt-8 mb-4">Understanding the Definition</h3>

      <p className="mb-4">
        Let's break down this definition:
      </p>

      <ul className="list-disc list-inside space-y-2 mb-6">
        <li>
          <InlineMath>\text{'{Com}'}(x; r)</InlineMath> is the commitment to value <InlineMath>x</InlineMath> using
          randomness <InlineMath>r</InlineMath>
        </li>
        <li>
          <InlineMath>pp</InlineMath> are public parameters generated by <InlineMath>\text{'{Setup}'}</InlineMath>
        </li>
        <li>
          The adversary <InlineMath>\mathcal{'{A}'}</InlineMath> tries to find two different values that
          produce the same commitment
        </li>
        <li>
          The probability of success must be negligible in the security parameter
        </li>
      </ul>

      <Callout type="info" title="Computational vs. Information-Theoretic Binding">
        <p>
          The definition above describes <strong>computational binding</strong>: breaking it requires
          solving a computationally hard problem. Some schemes offer <strong>information-theoretic
          binding</strong>, which is secure even against unbounded adversaries.
        </p>
      </Callout>

      <Example title="Hash-Based Commitment">
        <p>
          A simple binding commitment can be constructed using a hash function{' '}
          <InlineMath>H</InlineMath>:
        </p>
        <MathBlock>
          {`\\text{Com}(x; r) = H(x \\| r)`}
        </MathBlock>
        <p className="mt-2">
          where <InlineMath>\|</InlineMath> denotes concatenation. If <InlineMath>H</InlineMath> is
          collision-resistant, finding <InlineMath>(x_0, r_0) \neq (x_1, r_1)</InlineMath> with the
          same hash would contradict collision resistance.
        </p>
      </Example>

      <h3 className="text-xl font-semibold text-dark-100 mt-8 mb-4">The Hiding Property</h3>

      <p className="mb-4">
        Commitment schemes also require a <strong>hiding</strong> property: the commitment should
        not reveal any information about the committed value. Together, binding and hiding ensure:
      </p>

      <ul className="list-disc list-inside space-y-2">
        <li><strong>Hiding:</strong> The receiver learns nothing about <InlineMath>x</InlineMath> from the commitment</li>
        <li><strong>Binding:</strong> The sender cannot change <InlineMath>x</InlineMath> after committing</li>
      </ul>

      <p className="mt-4">
        These properties create a "locked box" metaphor: you can lock a value in a box (commit),
        and later open it (reveal), but you cannot change what's inside after locking.
      </p>
    </LessonLayout>
  );
}
