import { LessonLayout } from '@/components/layout';
import { Definition } from '@/components/common';
import { InlineMath, MathBlock } from '@/components/common/MathBlock';
import { Callout } from '@/components/common/Callout';
import { PSHVZKVariantTool } from '@/components/visualizations';

export default function Section04() {
  return (
    <LessonLayout sectionId={4}>
      <h2 className="text-2xl font-bold text-dark-100 mb-6">Perfect Special Honest Verifier Zero Knowledge</h2>

      <p className="mb-4">
        Perfect Special Honest Verifier Zero Knowledge (PSHVZK) is a specific and important
        variant of zero-knowledge. Understanding this definition precisely is crucial for
        proving the security of cryptographic protocols.
      </p>

      <Definition title="Perfect Special Honest Verifier Zero-Knowledge (PSHVZK)">
        <p>
          The protocol <InlineMath>(\text{'{Setup}'}, \mathsf{'{P}'}, \mathsf{'{V}'})</InlineMath> has{' '}
          <strong>perfect Special Honest Verifier Zero-Knowledge (PSHVZK)</strong> if there exists
          a probabilistic polynomial time (PPT) simulator <InlineMath>\mathcal{'{S}'}</InlineMath> such
          that for all pairs of adversaries <InlineMath>(\mathcal{'{A}'}_1, \mathcal{'{A}'}_2)</InlineMath>:
        </p>
        <MathBlock>
          {`\\Pr\\left[\\begin{array}{c} (\\sigma, x, w) \\in \\mathcal{R} \\\\ \\land\\; \\mathcal{A}_2(\\sigma, \\pi) = 1 \\end{array} \\;\\middle|\\; \\begin{array}{l} \\sigma \\leftarrow \\text{Setup}(1^\\lambda) \\\\ (x, w, \\rho) \\leftarrow \\mathcal{A}_1(\\sigma) \\\\ \\pi \\leftarrow \\langle \\mathsf{P}(\\sigma, x, w), \\mathsf{V}(\\sigma, x; \\rho) \\rangle \\end{array}\\right]`}
        </MathBlock>
        <MathBlock>
          {`= \\Pr\\left[\\begin{array}{c} (\\sigma, x, w) \\in \\mathcal{R} \\\\ \\land\\; \\mathcal{A}_2(\\sigma, \\pi) = 1 \\end{array} \\;\\middle|\\; \\begin{array}{l} \\sigma \\leftarrow \\text{Setup}(1^\\lambda) \\\\ (x, w, \\rho) \\leftarrow \\mathcal{A}_1(\\sigma) \\\\ \\pi \\leftarrow \\mathcal{S}(x, \\rho) \\end{array}\\right]`}
        </MathBlock>
      </Definition>

      <h3 className="text-xl font-semibold text-dark-100 mt-8 mb-4">Understanding the Definition</h3>

      <p className="mb-4">
        Let's unpack the key aspects of this definition:
      </p>

      <Callout type="info" title="The Randomness Parameter">
        <p>
          Note that <InlineMath>\mathsf{'{V}'}(\sigma, x; \rho)</InlineMath> means that{' '}
          <InlineMath>\mathsf{'{V}'}</InlineMath> is run on randomness <InlineMath>\rho</InlineMath>.
          The word <strong>"special"</strong> in PSHVZK refers to the fact that the simulator
          gets access to the <em>same randomness</em> <InlineMath>\rho</InlineMath> as the verifier.
        </p>
      </Callout>

      <h4 className="text-lg font-semibold text-dark-100 mt-6 mb-3">Why "Honest Verifier"?</h4>

      <p className="mb-4">
        The definition assumes the verifier follows the protocol honestly (uses truly random{' '}
        <InlineMath>\rho</InlineMath>). This is a weaker guarantee than full zero-knowledge,
        which must hold against arbitrary verifier strategies.
      </p>

      <h4 className="text-lg font-semibold text-dark-100 mt-6 mb-3">Why "Perfect"?</h4>

      <p className="mb-4">
        The equality of probabilities is <em>exact</em>, not just computationally
        indistinguishable. The simulated transcripts are distributed identically to real
        transcripts, providing <strong>information-theoretic</strong> (not just computational)
        zero-knowledge.
      </p>

      <h3 className="text-xl font-semibold text-dark-100 mt-8 mb-4">When is a Protocol NOT PSHVZK?</h3>

      <p className="mb-4">
        It follows that a protocol is <strong>not SHVZK</strong> if there exist adversaries{' '}
        <InlineMath>(\mathcal{'{A}'}_1, \mathcal{'{A}'}_2)</InlineMath> which can distinguish
        between:
      </p>

      <ul className="list-disc list-inside space-y-2 mb-6">
        <li>
          A transcript <InlineMath>\pi</InlineMath> generated by real interaction between
          prover and verifier
        </li>
        <li>
          A simulated transcript produced by a simulator <em>without access to the witness{' '}
          <InlineMath>w</InlineMath></em>
        </li>
      </ul>

      <Callout type="warning" title="Adversary Power">
        <p>
          Importantly, in the PSHVZK definition, the adversary is <strong>not restricted to
          polynomial time</strong> and comes up with the statement and the witness. This means
          the distinguisher <InlineMath>\mathcal{'{A}'}_2</InlineMath> can solve the discrete
          logarithm problem and knows witnesses like <InlineMath>a</InlineMath> and{' '}
          <InlineMath>s_C</InlineMath>.
        </p>
      </Callout>

      <h3 className="text-xl font-semibold text-dark-100 mt-8 mb-4">The Simulator's Challenge</h3>

      <p className="mb-4">
        The simulator must produce transcripts that look real without knowing the witness.
        It has access to:
      </p>

      <ul className="list-disc list-inside space-y-2">
        <li>The statement <InlineMath>x</InlineMath></li>
        <li>The verifier's randomness <InlineMath>\rho</InlineMath></li>
        <li><strong>NOT</strong> the witness <InlineMath>w</InlineMath></li>
      </ul>

      <p className="mt-4">
        The next sections will demonstrate how to construct such simulators for specific
        protocols.
      </p>

      <PSHVZKVariantTool className="my-8" />
    </LessonLayout>
  );
}
